const WORDS_ZK_GO = {
  "第1组": [
    { word: "glad", syllables: ["glad"], phonetic: "/ɡlæd/", meaning: "adj. 高兴的；乐意的", example: "I'm glad to see you." },
    { word: "glass", syllables: ["glass"], phonetic: "/ɡlæs/", meaning: "n. 玻璃杯；玻璃；(复)眼镜", example: "Give me a glass of water." },
    { word: "go (went, gone)", syllables: ["go (went, gone)"], phonetic: "", meaning: "v. 去；走；驶；通到；到达", example: "The word 'go (went, gone)' means v. 去." },
    { word: "goal", syllables: ["goal"], phonetic: "", meaning: "n. 目标", example: "The word 'goal' means n. 目标." },
    { word: "gold", syllables: ["gold"], phonetic: "/ɡoʊld/", meaning: "n. 黄金", example: "She won a gold medal." },
    { word: "golden", syllables: ["gold","en"], phonetic: "/ˈɡoʊldən/", meaning: "adj. 金色的", example: "She has golden hair." },
    { word: "good (比较级 better，最高级 best)", syllables: ["good (比较级 better，最高级 best)"], phonetic: "", meaning: "adj. 好；良好", example: "The word 'good (比较级 better，最高级 best)' means adj. 好." },
    { word: "government", syllables: ["gov","ern","ment"], phonetic: "/ˈɡʌvərnmənt/", meaning: "n. 政府", example: "The government made a new law." },
    { word: "grade", syllables: ["grade"], phonetic: "/ɡreɪd/", meaning: "n. 等级；(中小学的)学年；成绩，分数", example: "She is in Grade 8." },
    { word: "graduate", syllables: ["graduate"], phonetic: "", meaning: "v. 毕业; n. 大学毕业生", example: "The word 'graduate' means v. 毕业; n. 大学毕业生." },
    { word: "grandma=grandmother", syllables: ["grandma=grandmother"], phonetic: "", meaning: "n. 奶奶；外婆", example: "The word 'grandma=grandmother' means n. 奶奶." },
    { word: "grandpa=grandfather", syllables: ["grandpa=grandfather"], phonetic: "", meaning: "n. 爷爷；外公", example: "The word 'grandpa=grandfather' means n. 爷爷." },
    { word: "grape", syllables: ["grape"], phonetic: "/ɡreɪp/", meaning: "n. 葡萄", example: "I like eating grapes." },
    { word: "grass", syllables: ["grass"], phonetic: "/ɡræs/", meaning: "n. 草；草场；牧草", example: "Don't walk on the grass." },
    { word: "great", syllables: ["great"], phonetic: "/ɡreɪt/", meaning: "adj. 伟大的；重要的；(口语)好极了，很好", example: "That's a great idea!" },
    { word: "green", syllables: ["green"], phonetic: "/ɡriːn/", meaning: "adj. 绿色的；青的; n. 绿色", example: "The tree is green." },
    { word: "greenhouse", syllables: ["greenhouse"], phonetic: "", meaning: "n. 温室，暖房", example: "The word 'greenhouse' means n. 温室." },
    { word: "greet", syllables: ["greet"], phonetic: "/ɡriːt/", meaning: "v. 问候； 向……致敬", example: "She greeted me with a smile." },
    { word: "ground", syllables: ["ground"], phonetic: "/ɡraʊnd/", meaning: "n. 地面", example: "The ball is on the ground." },
    { word: "group", syllables: ["group"], phonetic: "/ɡruːp/", meaning: "n. 组，群", example: "We work in groups." },
    { word: "grow (grew, grown)", syllables: ["grow (grew, grown)"], phonetic: "", meaning: "v. 生长；发育；种植；变成", example: "The word 'grow (grew, grown)' means v. 生长." },
    { word: "guess", syllables: ["guess"], phonetic: "/ɡes/", meaning: "v. 猜测；推测", example: "Can you guess the answer?" },
    { word: "guest", syllables: ["guest"], phonetic: "/ɡest/", meaning: "n. 客人，宾客", example: "We have a guest tonight." },
    { word: "guide", syllables: ["guide"], phonetic: "/ɡaɪd/", meaning: "n. 向导，导游；指南", example: "The guide showed us around." },
    { word: "guitar", syllables: ["gui","tar"], phonetic: "/ɡɪˈtɑːr/", meaning: "n. 吉他", example: "He plays the guitar well." },
    { word: "gun", syllables: ["gun"], phonetic: "/ɡʌn/", meaning: "n. 枪；炮", example: "The police carried guns." },
    { word: "habit", syllables: ["hab","it"], phonetic: "/ˈhæbɪt/", meaning: "n. 习惯", example: "Reading is a good habit." },
    { word: "hair", syllables: ["hair"], phonetic: "/her/", meaning: "n. 头发", example: "She has long hair." },
    { word: "half", syllables: ["half"], phonetic: "/hæf/", meaning: "adj. & n.            半，一半，半个", example: "Half of the students are girls." },
    { word: "hall", syllables: ["hall"], phonetic: "/hɔːl/", meaning: "n. 大厅，会堂，礼堂", example: "The concert is in the hall." },
    { word: "hamburger", syllables: ["ham","bur","ger"], phonetic: "/ˈhæmbɜːrɡər/", meaning: "n. 汉堡包", example: "I'd like a hamburger." },
    { word: "hand", syllables: ["hand"], phonetic: "/hænd/", meaning: "n. 手；指针; v. 递；给；交付；交进", example: "Raise your hand, please." },
    { word: "hang (hanged, hanged)", syllables: ["hang (hanged, hanged)"], phonetic: "", meaning: "v. 处绞刑；上吊; v. 悬挂；把……吊起", example: "The word 'hang (hanged, hanged)' means v. 处绞刑." },
    { word: "happen", syllables: ["hap","pen"], phonetic: "/ˈhæpən/", meaning: "v. (偶然)发生；碰巧", example: "What happened to him?" },
    { word: "happily", syllables: ["happily"], phonetic: "", meaning: "adv. 幸福地；快乐地，高兴地", example: "The word 'happily' means adv. 幸福地." },
    { word: "happiness", syllables: ["happiness"], phonetic: "", meaning: "n. 幸福，快乐", example: "The word 'happiness' means n. 幸福." },
    { word: "happy", syllables: ["hap","py"], phonetic: "/ˈhæpi/", meaning: "adj. 幸福的；快乐的，高兴的", example: "I feel very happy today." },
    { word: "hard", syllables: ["hard"], phonetic: "/hɑːrd/", meaning: "adv. 努力地；使劲；猛烈地; adj. 硬的；困难的；艰难的", example: "He studies hard every day." },
    { word: "hardly", syllables: ["hard","ly"], phonetic: "/ˈhɑːrdli/", meaning: "adv. 几乎不", example: "I hardly know her." },
    { word: "hardworking", syllables: ["hardworking"], phonetic: "", meaning: "adj. 努力工作的", example: "The word 'hardworking' means adj. 努力工作的." },
    { word: "harm", syllables: ["harm"], phonetic: "/hɑːrm/", meaning: "v. & n.                  伤害", example: "Smoking does harm to health." },
    { word: "harmful", syllables: ["harm","ful"], phonetic: "/ˈhɑːrmfl/", meaning: "adj. 有害的；导致损害的", example: "Junk food is harmful." },
    { word: "hat", syllables: ["hat"], phonetic: "/hæt/", meaning: "n. 帽子", example: "She is wearing a hat." },
    { word: "hate", syllables: ["hate"], phonetic: "/heɪt/", meaning: "v. & n.             不喜欢；恨；讨厌", example: "I hate rainy days." },
    { word: "have (had, had)", syllables: ["have (had, had)"], phonetic: "", meaning: "v. 有；吃；喝；进行", example: "The word 'have (had, had)' means v. 有." },
    { word: "head", syllables: ["head"], phonetic: "/hed/", meaning: "n. 头；头脑；首脑；", example: "She nodded her head." },
    { word: "headache", syllables: ["head","ache"], phonetic: "/ˈhedeɪk/", meaning: "n. 头疼", example: "I have a headache today." },
    { word: "headline", syllables: ["head","line"], phonetic: "/ˈhedlaɪn/", meaning: "n. (报刊的)大字标题", example: "Read the headline of the news." },
    { word: "headmaster", syllables: ["headmaster"], phonetic: "", meaning: "n. (英)中小学校长", example: "The word 'headmaster' means n. (英)中小学校长." },
    { word: "health", syllables: ["health"], phonetic: "/helθ/", meaning: "n. 健康", example: "Health is very important." }
  ],
  "第2组": [
    { word: "healthy", syllables: ["health","y"], phonetic: "/ˈhelθi/", meaning: "adj. 健康的", example: "We should eat healthy food." },
    { word: "hear (heard, heard)", syllables: ["hear (heard, heard)"], phonetic: "", meaning: "v. 听见；听说；得知", example: "The word 'hear (heard, heard)' means v. 听见." },
    { word: "heart", syllables: ["heart"], phonetic: "/hɑːrt/", meaning: "n. 心；心脏", example: "Thank you from the bottom of my heart." },
    { word: "heat", syllables: ["heat"], phonetic: "/hiːt/", meaning: "n. 热度；热量; v. 加热", example: "The heat of the sun is strong." },
    { word: "heavily", syllables: ["heavily"], phonetic: "", meaning: "adv. 沉重地；大量地", example: "The word 'heavily' means adv. 沉重地." },
    { word: "heavy", syllables: ["hea","vy"], phonetic: "/ˈhevi/", meaning: "adj. 重的", example: "This box is too heavy." },
    { word: "height", syllables: ["height"], phonetic: "/haɪt/", meaning: "n. 高度", example: "What is your height?" },
    { word: "hello", syllables: ["hel","lo"], phonetic: "/həˈloʊ/", meaning: "int. 喂；你好", example: "Hello, how are you?" },
    { word: "help", syllables: ["help"], phonetic: "/help/", meaning: "n. & v. 帮助，帮忙", example: "Can you help me?" },
    { word: "helpful", syllables: ["help","ful"], phonetic: "/ˈhelpfl/", meaning: "adj. 有帮助的，有益的", example: "The book is very helpful." },
    { word: "helpless", syllables: ["help","less"], phonetic: "/ˈhelpləs/", meaning: "adj. 无助的，没有帮助的", example: "The baby felt helpless." },
    { word: "here", syllables: ["here"], phonetic: "/hɪr/", meaning: "adv. 这里，在这里；向这里", example: "Please come here." },
    { word: "hero", syllables: ["he","ro"], phonetic: "/ˈhɪroʊ/", meaning: "n. 英雄，勇士；男主角", example: "He is a national hero." },
    { word: "hesitate", syllables: ["hesitate"], phonetic: "", meaning: "v. 犹豫，踌躇", example: "The word 'hesitate' means v. 犹豫." },
    { word: "hide (hid, hidden)", syllables: ["hide (hid, hidden)"], phonetic: "", meaning: "v. 把……藏起来；隐藏", example: "The word 'hide (hid, hidden)' means v. 把……藏起来." },
    { word: "high", syllables: ["high"], phonetic: "/haɪ/", meaning: "adj. 高的", example: "The mountain is very high." },
    { word: "hill", syllables: ["hill"], phonetic: "/hɪl/", meaning: "n. 小山", example: "We climbed the hill." },
    { word: "historical", syllables: ["historical"], phonetic: "", meaning: "adj. 历史的，历史上", example: "The word 'historical' means adj. 历史的." },
    { word: "history", syllables: ["his","to","ry"], phonetic: "/ˈhɪstri/", meaning: "n. 历史，历史学", example: "I like studying history." },
    { word: "hit (hit, hit)", syllables: ["hit (hit, hit)"], phonetic: "", meaning: "v. 打，撞，击中，碰撞", example: "The word 'hit (hit, hit)' means v. 打." },
    { word: "hobby", syllables: ["hob","by"], phonetic: "/ˈhɑːbi/", meaning: "n. 爱好，嗜好", example: "My hobby is reading." },
    { word: "hold (held, held)", syllables: ["hold (held, held)"], phonetic: "", meaning: "v. 拿；抱；握住；举行；进行；保持；容纳", example: "The word 'hold (held, held)' means v. 拿." },
    { word: "hole", syllables: ["hole"], phonetic: "/hoʊl/", meaning: "n. 洞，坑", example: "There is a hole in the wall." },
    { word: "holiday", syllables: ["hol","i","day"], phonetic: "/ˈhɑːlədeɪ/", meaning: "n. 假日；假期", example: "We went to the beach on holiday." },
    { word: "home", syllables: ["home"], phonetic: "/hoʊm/", meaning: "n. 家; adv. 在家；到家；回家", example: "I go home at five." },
    { word: "homeless", syllables: ["homeless"], phonetic: "", meaning: "adj. 无家可归的", example: "The word 'homeless' means adj. 无家可归的." },
    { word: "hometown", syllables: ["home","town"], phonetic: "/ˈhoʊmtaʊn/", meaning: "n. 家乡，故乡", example: "I love my hometown." },
    { word: "homework", syllables: ["home","work"], phonetic: "/ˈhoʊmwɜːrk/", meaning: "n. 家庭作业", example: "I finished my homework." },
    { word: "honest", syllables: ["hon","est"], phonetic: "/ˈɑːnɪst/", meaning: "adj. 诚实的；正直的", example: "He is an honest boy." },
    { word: "honesty", syllables: ["honesty"], phonetic: "", meaning: "n. 诚实", example: "The word 'honesty' means n. 诚实." },
    { word: "honey", syllables: ["honey"], phonetic: "", meaning: "n. 蜂蜜", example: "The word 'honey' means n. 蜂蜜." },
    { word: "honour (美 honor)", syllables: ["honour (美 honor)"], phonetic: "", meaning: "n. 荣誉，光荣", example: "The word 'honour (美 honor)' means n. 荣誉." },
    { word: "hope", syllables: ["hope"], phonetic: "/hoʊp/", meaning: "n. & v. 希望", example: "I hope you get well soon." },
    { word: "horrible", syllables: ["hor","ri","ble"], phonetic: "/ˈhɔːrəbl/", meaning: "adj. 令人恐惧的；恐怖的", example: "The weather was horrible." },
    { word: "horse", syllables: ["horse"], phonetic: "/hɔːrs/", meaning: "n. 马", example: "She rides a horse." },
    { word: "hospital", syllables: ["hos","pi","tal"], phonetic: "/ˈhɑːspɪtl/", meaning: "n. 医院", example: "He is in the hospital." },
    { word: "host", syllables: ["host"], phonetic: "/hoʊst/", meaning: "n. 主人；节目主持人", example: "She is the host of the show." },
    { word: "hot", syllables: ["hot"], phonetic: "/hɑːt/", meaning: "adj. 热的；辣的", example: "It is very hot today." },
    { word: "hot-dog", syllables: ["hot-dog"], phonetic: "", meaning: "n. 热狗", example: "The word 'hot-dog' means n. 热狗." },
    { word: "hotel", syllables: ["ho","tel"], phonetic: "/hoʊˈtel/", meaning: "n. 旅馆，宾馆", example: "We stayed at a hotel." },
    { word: "hour", syllables: ["hour"], phonetic: "/ˈaʊər/", meaning: "n. 小时", example: "I waited for two hours." },
    { word: "house", syllables: ["house"], phonetic: "/haʊs/", meaning: "n. 房子；住宅，家", example: "They have a big house." },
    { word: "housework", syllables: ["house","work"], phonetic: "/ˈhaʊswɜːrk/", meaning: "n. 家务活", example: "I help with the housework." },
    { word: "how", syllables: ["how"], phonetic: "/haʊ/", meaning: "adv. (方法、手段、状态)怎样；如何；(程度、数量、价钱)多少；", example: "How are you?" },
    { word: "however", syllables: ["how","ev","er"], phonetic: "/haʊˈevər/", meaning: "adv. 可是; conj. 然而，可是；尽管如此", example: "However, he didn't agree." },
    { word: "hug", syllables: ["hug"], phonetic: "/hʌɡ/", meaning: "n. & v. 拥抱", example: "She gave her mother a hug." },
    { word: "huge", syllables: ["huge"], phonetic: "/hjuːdʒ/", meaning: "adj. 巨大的，庞大的", example: "The elephant is huge." },
    { word: "human", syllables: ["hu","man"], phonetic: "/ˈhjuːmən/", meaning: "adj. 人的，人类的; n. (=human being) 人类", example: "Humans need water." },
    { word: "humorous", syllables: ["hu","mor","ous"], phonetic: "/ˈhjuːmərəs/", meaning: "adj. 幽默的，风趣的", example: "Our teacher is humorous." },
    { word: "hungry", syllables: ["hun","gry"], phonetic: "/ˈhʌŋɡri/", meaning: "adj. 饥饿的", example: "I am very hungry now." }
  ],
  "第3组": [
    { word: "hunt", syllables: ["hunt"], phonetic: "/hʌnt/", meaning: "v. 寻找；猎取", example: "They went hunting." },
    { word: "hurry", syllables: ["hur","ry"], phonetic: "/ˈhɜːri/", meaning: "v. 赶快；急忙; n. 赶紧；急忙", example: "Hurry up, or we'll be late!" },
    { word: "hurt (hurt, hurt)", syllables: ["hurt (hurt, hurt)"], phonetic: "", meaning: "v. 伤害；痛；使受伤痛", example: "The word 'hurt (hurt, hurt)' means v. 伤害." },
    { word: "husband", syllables: ["hus","band"], phonetic: "/ˈhʌzbənd/", meaning: "n. 丈夫", example: "Her husband is a teacher." },
    { word: "ice", syllables: ["ice"], phonetic: "/aɪs/", meaning: "n. 冰", example: "The lake is covered with ice." },
    { word: "ice-cream", syllables: ["ice-cream"], phonetic: "", meaning: "n. 冰淇淋", example: "The word 'ice-cream' means n. 冰淇淋." },
    { word: "idea", syllables: ["i","de","a"], phonetic: "/aɪˈdiːə/", meaning: "n. 主意，意见，打算，想法", example: "That's a good idea!" },
    { word: "if", syllables: ["if"], phonetic: "/ɪf/", meaning: "conj. (连接状语从句)如果，假使；(连接宾语从句)是否，是不是", example: "If it rains, I will stay home." },
    { word: "ignore", syllables: ["ignore"], phonetic: "", meaning: "v. 忽视；不理睬", example: "The word 'ignore' means v. 忽视." },
    { word: "ill", syllables: ["ill"], phonetic: "/ɪl/", meaning: "adj. 有病的；不健康的", example: "She is ill in bed." },
    { word: "illness", syllables: ["ill","ness"], phonetic: "/ˈɪlnəs/", meaning: "n. 疾病", example: "He recovered from his illness." },
    { word: "imagine", syllables: ["i","ma","gine"], phonetic: "/ɪˈmædʒɪn/", meaning: "v. 想象；设想", example: "Imagine you are on the moon." },
    { word: "immediately", syllables: ["immediately"], phonetic: "", meaning: "adv. 立即，马上", example: "The word 'immediately' means adv. 立即." },
    { word: "importance", syllables: ["importance"], phonetic: "", meaning: "n. 重要性", example: "The word 'importance' means n. 重要性." },
    { word: "important", syllables: ["im","por","tant"], phonetic: "/ɪmˈpɔːrtnt/", meaning: "adj. 重要的", example: "Health is very important." },
    { word: "impossible", syllables: ["im","pos","si","ble"], phonetic: "/ɪmˈpɑːsəbl/", meaning: "adj. 不可能的", example: "Nothing is impossible." },
    { word: "impression", syllables: ["im","pres","sion"], phonetic: "/ɪmˈpreʃn/", meaning: "n. 印象", example: "He made a good impression." },
    { word: "improve", syllables: ["im","prove"], phonetic: "/ɪmˈpruːv/", meaning: "v. 改进，更新", example: "I want to improve my English." },
    { word: "in", syllables: ["in"], phonetic: "/ɪn/", meaning: "prep. 在……(位置)里(内)；在……(时间)；在……(情况、状态)中；; adv. 在家，在内，向内", example: "The book is in the bag." },
    { word: "inch", syllables: ["inch"], phonetic: "/ɪntʃ/", meaning: "n. 英寸", example: "Give him an inch and he'll take a mile." },
    { word: "include", syllables: ["in","clude"], phonetic: "/ɪnˈkluːd/", meaning: "v. 包含，包括", example: "The price includes breakfast." },
    { word: "including", syllables: ["including"], phonetic: "", meaning: "prep. 包括；包含", example: "The word 'including' means prep. 包括." },
    { word: "income", syllables: ["income"], phonetic: "", meaning: "n. 收入，所得", example: "The word 'income' means n. 收入." },
    { word: "increase", syllables: ["in","crease"], phonetic: "/ɪnˈkriːs/", meaning: "v. & n.         增加", example: "The population is increasing." },
    { word: "independent", syllables: ["independent"], phonetic: "", meaning: "adj. 独立的；有主见的", example: "The word 'independent' means adj. 独立的." },
    { word: "indoor", syllables: ["indoor"], phonetic: "", meaning: "adj. 室内的", example: "The word 'indoor' means adj. 室内的." },
    { word: "industry", syllables: ["in","dus","try"], phonetic: "/ˈɪndəstri/", meaning: "n. 工业，产业", example: "The car industry is growing." },
    { word: "information", syllables: ["in","for","ma","tion"], phonetic: "/ˌɪnfərˈmeɪʃn/", meaning: "n. 信息；情报；资料", example: "Can you give me some information?" },
    { word: "ink", syllables: ["ink"], phonetic: "/ɪŋk/", meaning: "n. 墨水；油墨", example: "The pen has run out of ink." },
    { word: "inside", syllables: ["in","side"], phonetic: "/ˌɪnˈsaɪd/", meaning: "prep. 在……里面; adv. 在里面", example: "The cat is inside the box." },
    { word: "instead", syllables: ["in","stead"], phonetic: "/ɪnˈsted/", meaning: "adv. 代替；顶替", example: "Let's walk instead of driving." },
    { word: "instruction", syllables: ["in","struc","tion"], phonetic: "/ɪnˈstrʌkʃn/", meaning: "n. 用法说明；命令，指示；教导", example: "Read the instructions carefully." },
    { word: "interest", syllables: ["in","ter","est"], phonetic: "/ˈɪntrəst/", meaning: "n. 兴趣；趣味", example: "I have an interest in music." },
    { word: "interested", syllables: ["in","ter","est","ed"], phonetic: "/ˈɪntrəstɪd/", meaning: "adj. 感兴趣的", example: "I am interested in science." },
    { word: "interesting", syllables: ["in","ter","est","ing"], phonetic: "/ˈɪntrəstɪŋ/", meaning: "adj. 有趣的；有意思的", example: "The story is very interesting." },
    { word: "international", syllables: ["in","ter","na","tion","al"], phonetic: "/ˌɪntərˈnæʃnəl/", meaning: "adj. 国际的", example: "English is an international language." },
    { word: "internet", syllables: ["In","ter","net"], phonetic: "/ˈɪntərnet/", meaning: "n. 互联网，因特网", example: "I often use the Internet." },
    { word: "interview", syllables: ["in","ter","view"], phonetic: "/ˈɪntərvjuː/", meaning: "n. & v. 采访，会见，面试", example: "I have a job interview tomorrow." },
    { word: "into", syllables: ["in","to"], phonetic: "/ˈɪntuː/", meaning: "prep. 到……里；向内；变成", example: "Come into the room." },
    { word: "introduce", syllables: ["in","tro","duce"], phonetic: "/ˌɪntrəˈduːs/", meaning: "v. 介绍", example: "Let me introduce myself." },
    { word: "invent", syllables: ["in","vent"], phonetic: "/ɪnˈvent/", meaning: "v. 发明，创造", example: "Who invented the telephone?" },
    { word: "invention", syllables: ["in","ven","tion"], phonetic: "/ɪnˈvenʃn/", meaning: "n. 发明，创造", example: "The computer is a great invention." },
    { word: "inventor", syllables: ["inventor"], phonetic: "", meaning: "v. 发明家，创造者", example: "The word 'inventor' means v. 发明家." },
    { word: "investigate", syllables: ["investigate"], phonetic: "", meaning: "v. 调查", example: "The word 'investigate' means v. 调查." },
    { word: "invitation", syllables: ["in","vi","ta","tion"], phonetic: "/ˌɪnvɪˈteɪʃn/", meaning: "n. 邀请，请帖", example: "I received an invitation to the party." },
    { word: "invite", syllables: ["in","vite"], phonetic: "/ɪnˈvaɪt/", meaning: "v. 邀请", example: "I invited her to dinner." },
    { word: "iron", syllables: ["i","ron"], phonetic: "/ˈaɪərn/", meaning: "n. 铁", example: "The gate is made of iron." },
    { word: "island", syllables: ["is","land"], phonetic: "/ˈaɪlənd/", meaning: "n. 岛", example: "Taiwan is a beautiful island." },
    { word: "item", syllables: ["item"], phonetic: "", meaning: "n. 项目；节目；一件商品（物品）；一则", example: "The word 'item' means n. 项目." },
    { word: "jacket", syllables: ["jack","et"], phonetic: "/ˈdʒækɪt/", meaning: "n. 短上衣，夹克衫", example: "Put on your jacket." }
  ],
  "第4组": [
    { word: "jam", syllables: ["jam"], phonetic: "/dʒæm/", meaning: "n. 果酱；阻塞", example: "I like strawberry jam." },
    { word: "jeans", syllables: ["jeans"], phonetic: "/dʒiːnz/", meaning: "n. 牛仔裤", example: "She is wearing jeans." },
    { word: "job", syllables: ["job"], phonetic: "/dʒɑːb/", meaning: "n. 工作", example: "He has a new job." },
    { word: "join", syllables: ["join"], phonetic: "/dʒɔɪn/", meaning: "v. 参加，加入；连接", example: "Will you join us?" },
    { word: "joke", syllables: ["joke"], phonetic: "/dʒoʊk/", meaning: "n. 笑话; v. 开玩笑", example: "He told a funny joke." },
    { word: "journalist", syllables: ["journalist"], phonetic: "", meaning: "n. 记者，新闻工作者", example: "The word 'journalist' means n. 记者." },
    { word: "journey", syllables: ["jour","ney"], phonetic: "/ˈdʒɜːrni/", meaning: "n. 旅行；旅程", example: "Have a good journey!" },
    { word: "joy", syllables: ["joy"], phonetic: "/dʒɔɪ/", meaning: "n. 欢乐；高兴，乐趣", example: "Children are full of joy." },
    { word: "judge", syllables: ["judge"], phonetic: "/dʒʌdʒ/", meaning: "n. 裁判； 审判员； 法官; v. 审判；断定", example: "Don't judge a book by its cover." },
    { word: "juice", syllables: ["juice"], phonetic: "/dʒuːs/", meaning: "n. 果汁", example: "I'd like a glass of orange juice." },
    { word: "jump", syllables: ["jump"], phonetic: "/dʒʌmp/", meaning: "n. & v. 跳；跳跃", example: "The cat jumped over the wall." },
    { word: "junior", syllables: ["jun","ior"], phonetic: "/ˈdʒuːniər/", meaning: "adj. 初级的；年少的", example: "He is a junior high school student." },
    { word: "just", syllables: ["just"], phonetic: "/dʒʌst/", meaning: "adv. 刚才；恰好；不过；仅", example: "I just finished my homework." },
    { word: "keen", syllables: ["keen"], phonetic: "", meaning: "adj. 热心的", example: "The word 'keen' means adj. 热心的." },
    { word: "keep (kept, kept)", syllables: ["keep (kept, kept)"], phonetic: "", meaning: "v. 保持；保存；继续不断；培育，饲养", example: "The word 'keep (kept, kept)' means v. 保持." },
    { word: "key", syllables: ["key"], phonetic: "/kiː/", meaning: "n. 钥匙；答案；关键", example: "Where is the key?" },
    { word: "keyboard", syllables: ["key","board"], phonetic: "/ˈkiːbɔːrd/", meaning: "n. 键盘", example: "He typed on the keyboard." },
    { word: "kick", syllables: ["kick"], phonetic: "", meaning: "v. & n.             踢", example: "The word 'kick' means v. & n.             踢." },
    { word: "kid", syllables: ["kid"], phonetic: "/kɪd/", meaning: "v. 开玩笑; n. 小孩", example: "The kids are playing outside." },
    { word: "kill", syllables: ["kill"], phonetic: "/kɪl/", meaning: "v. 杀死，弄死", example: "The cold weather killed the flowers." },
    { word: "kilogram", syllables: ["kilogram"], phonetic: "", meaning: "n. 千克(公斤)", example: "The word 'kilogram' means n. 千克(公斤)." },
    { word: "kilometre", syllables: ["kilometre"], phonetic: "", meaning: "n. 千米(公里)", example: "The word 'kilometre' means n. 千米(公里)." },
    { word: "kind", syllables: ["kind"], phonetic: "/kaɪnd/", meaning: "n. 种；类; adj. 善良的；友好的", example: "She is a kind person." },
    { word: "kindergarten", syllables: ["kindergarten"], phonetic: "", meaning: "n. 幼儿园", example: "The word 'kindergarten' means n. 幼儿园." },
    { word: "kindness", syllables: ["kindness"], phonetic: "", meaning: "n. 仁慈；好意", example: "The word 'kindness' means n. 仁慈." },
    { word: "king", syllables: ["king"], phonetic: "/kɪŋ/", meaning: "n. 国王", example: "The king ruled the country." },
    { word: "kitchen", syllables: ["kitch","en"], phonetic: "/ˈkɪtʃɪn/", meaning: "n. 厨房", example: "Mom is cooking in the kitchen." },
    { word: "kite", syllables: ["kite"], phonetic: "/kaɪt/", meaning: "n. 风筝", example: "Let's fly a kite." },
    { word: "knife (复 knives)", syllables: ["knife (复 knives)"], phonetic: "", meaning: "n. 小刀", example: "The word 'knife (复 knives)' means n. 小刀." },
    { word: "knock", syllables: ["knock"], phonetic: "/nɑːk/", meaning: "n. & v. 敲(门)；打；击", example: "Someone is knocking at the door." },
    { word: "know (knew, known)", syllables: ["know (knew, known)"], phonetic: "", meaning: "v. 知道；了解；认识；懂得", example: "The word 'know (knew, known)' means v. 知道." },
    { word: "knowledge", syllables: ["knowl","edge"], phonetic: "/ˈnɑːlɪdʒ/", meaning: "n. 知识，学问", example: "Knowledge is power." },
    { word: "lab", syllables: ["lab"], phonetic: "/læb/", meaning: "n. 实验室", example: "We did experiments in the lab." },
    { word: "lady", syllables: ["la","dy"], phonetic: "/ˈleɪdi/", meaning: "n. 女士，夫人", example: "The lady is very kind." },
    { word: "lake", syllables: ["lake"], phonetic: "/leɪk/", meaning: "n. 湖", example: "We went swimming in the lake." },
    { word: "lamp", syllables: ["lamp"], phonetic: "/læmp/", meaning: "n. 灯", example: "Turn on the lamp, please." },
    { word: "land", syllables: ["land"], phonetic: "/lænd/", meaning: "n. 陆地；土地; v. 登陆；降落", example: "The plane landed safely." },
    { word: "language", syllables: ["lan","guage"], phonetic: "/ˈlæŋɡwɪdʒ/", meaning: "n. 语言", example: "English is a useful language." },
    { word: "lantern", syllables: ["lantern"], phonetic: "", meaning: "n. 灯笼", example: "The word 'lantern' means n. 灯笼." },
    { word: "large", syllables: ["large"], phonetic: "/lɑːrdʒ/", meaning: "adj. 大的；巨大的", example: "They live in a large house." },
    { word: "last", syllables: ["last"], phonetic: "/læst/", meaning: "adj. 最近刚过去的；最后的", example: "What did you do last weekend?" },
    { word: "late", syllables: ["late"], phonetic: "/leɪt/", meaning: "adj. 晚的；迟的; adv. 晚地；迟地", example: "Don't be late for school." },
    { word: "later", syllables: ["la","ter"], phonetic: "/ˈleɪtər/", meaning: "adj. 晚些的，迟些的; adv. 后来，以后", example: "See you later." },
    { word: "laugh", syllables: ["laugh"], phonetic: "/læf/", meaning: "v. & n.          笑，大笑；嘲笑", example: "We laughed at the joke." },
    { word: "law", syllables: ["law"], phonetic: "/lɔː/", meaning: "n. 法律", example: "Everyone must obey the law." },
    { word: "lawyer", syllables: ["lawyer"], phonetic: "", meaning: "n. 律师", example: "The word 'lawyer' means n. 律师." },
    { word: "lay (laid, laid)", syllables: ["lay (laid, laid)"], phonetic: "", meaning: "v. 放，搁；下(蛋)", example: "The word 'lay (laid, laid)' means v. 放." },
    { word: "lazy", syllables: ["la","zy"], phonetic: "/ˈleɪzi/", meaning: "adj. 懒惰的", example: "Don't be so lazy." },
    { word: "lead (led, led)", syllables: ["lead (led, led)"], phonetic: "", meaning: "v. 领导；带领", example: "The word 'lead (led, led)' means v. 领导." },
    { word: "learn (learnt，learnt；learned，learned)", syllables: ["learn (learnt，learnt；learned，learned)"], phonetic: "", meaning: "v. 学习，学会", example: "The word 'learn (learnt，learnt；learned，learned)' means v. 学习." }
  ],
  "第5组": [
    { word: "leave (left, left)", syllables: ["leave (left, left)"], phonetic: "", meaning: "v. 离开；把……留下；剩下; n. 准假", example: "The word 'leave (left, left)' means v. 离开." },
    { word: "lecture", syllables: ["lec","ture"], phonetic: "/ˈlektʃər/", meaning: "n. 讲座；演讲", example: "We attended a lecture." },
    { word: "left", syllables: ["left"], phonetic: "/left/", meaning: "adj. 左边的; adv. 向左; n. 左，左边", example: "Turn left at the corner." },
    { word: "leg", syllables: ["leg"], phonetic: "/leɡ/", meaning: "n. 腿", example: "He broke his leg." },
    { word: "lend (lent, lent)", syllables: ["lend (lent, lent)"], phonetic: "", meaning: "v. 借(出)；把……借给", example: "The word 'lend (lent, lent)' means v. 借(出)." },
    { word: "length", syllables: ["length"], phonetic: "", meaning: "n. 长度", example: "The word 'length' means n. 长度." },
    { word: "lesson", syllables: ["les","son"], phonetic: "/ˈlesn/", meaning: "n. 课；功课；教训", example: "We have six lessons today." },
    { word: "let (let, let)", syllables: ["let (let, let)"], phonetic: "", meaning: "v. 让", example: "The word 'let (let, let)' means v. 让." },
    { word: "letter", syllables: ["let","ter"], phonetic: "/ˈletər/", meaning: "n. 信；字母", example: "I received a letter from my friend." },
    { word: "level", syllables: ["lev","el"], phonetic: "/ˈlevl/", meaning: "n. 水平线；水平", example: "The water level is rising." },
    { word: "librarian", syllables: ["librarian"], phonetic: "", meaning: "n. 图书馆管理员", example: "The word 'librarian' means n. 图书馆管理员." },
    { word: "library", syllables: ["li","brar","y"], phonetic: "/ˈlaɪbreri/", meaning: "n. 图书馆，图书室", example: "I often go to the library." },
    { word: "lie", syllables: ["lie"], phonetic: "/laɪ/", meaning: "n. & v. 谎言； 说谎; v. (lay, lain) 躺；卧；位于", example: "Don't lie to me." },
    { word: "life (复 lives)", syllables: ["life (复 lives)"], phonetic: "", meaning: "n. 生命；生活；人生", example: "The word 'life (复 lives)' means n. 生命." },
    { word: "lift", syllables: ["lift"], phonetic: "/lɪft/", meaning: "v. 举起，抬起; n. (英)电梯", example: "Can you lift this box?" },
    { word: "light", syllables: ["light"], phonetic: "/laɪt/", meaning: "n. 光；灯光; adj. 明亮的；轻的；浅色的", example: "Turn off the light, please." },
    { word: "like", syllables: ["like"], phonetic: "/laɪk/", meaning: "prep. 像，跟……一样; v. 喜欢；喜爱；想要(should/would like)", example: "I like playing basketball." },
    { word: "likely", syllables: ["like","ly"], phonetic: "/ˈlaɪkli/", meaning: "adj. 很可能的; adv. 很可能地", example: "It is likely to rain." },
    { word: "limited", syllables: ["limited"], phonetic: "", meaning: "adj. 有限的，限制的", example: "The word 'limited' means adj. 有限的." },
    { word: "line", syllables: ["line"], phonetic: "/laɪn/", meaning: "n. 排，行；线路; v. 排队", example: "Please stand in line." },
    { word: "lion", syllables: ["li","on"], phonetic: "/ˈlaɪən/", meaning: "n. 狮子", example: "The lion is the king of animals." },
    { word: "liquid", syllables: ["liquid"], phonetic: "", meaning: "n. 液体", example: "The word 'liquid' means n. 液体." },
    { word: "list", syllables: ["list"], phonetic: "/lɪst/", meaning: "n. 目录，清单", example: "Make a list of things to buy." },
    { word: "listen", syllables: ["lis","ten"], phonetic: "/ˈlɪsn/", meaning: "v. 听；仔细听", example: "Please listen carefully." },
    { word: "litter", syllables: ["lit","ter"], phonetic: "/ˈlɪtər/", meaning: "n. 废物，垃圾; v. 乱丢杂物", example: "Don't litter in the park." },
    { word: "little (比较级 less，最高级 least)", syllables: ["little (比较级 less，最高级 least)"], phonetic: "", meaning: "adj. 小的，少的; adv. 很少地，稍许; n. 没有多少，一点", example: "The word 'little (比较级 less，最高级 least)' means adj. 小的." },
    { word: "live", syllables: ["live"], phonetic: "/lɪv/", meaning: "v. 生活；居住；活着", example: "I live in Beijing." },
    { word: "local", syllables: ["lo","cal"], phonetic: "/ˈloʊkl/", meaning: "adj. 当地的； 地方的; n. 本地人", example: "We eat at a local restaurant." },
    { word: "locate", syllables: ["locate"], phonetic: "", meaning: "v. 坐落于；确定……的地方", example: "The word 'locate' means v. 坐落于." },
    { word: "location", syllables: ["location"], phonetic: "", meaning: "n. 位置；场所", example: "The word 'location' means n. 位置." },
    { word: "lock", syllables: ["lock"], phonetic: "/lɑːk/", meaning: "n. & v. 锁", example: "Lock the door when you leave." },
    { word: "London", syllables: ["London"], phonetic: "", meaning: "n. 伦敦", example: "The word 'London' means n. 伦敦." },
    { word: "lonely", syllables: ["lone","ly"], phonetic: "/ˈloʊnli/", meaning: "adj. 孤独的，寂寞的", example: "She felt lonely in the new city." },
    { word: "long", syllables: ["long"], phonetic: "/lɔːŋ/", meaning: "adj. (时间)长的，(距离)远的", example: "The river is very long." },
    { word: "look", syllables: ["look"], phonetic: "/lʊk/", meaning: "n. 看，瞧; v. 看；观看；看起来", example: "Look at the blackboard." },
    { word: "lose (lost, lost)", syllables: ["lose (lost, lost)"], phonetic: "", meaning: "v. 失去；丢失", example: "The word 'lose (lost, lost)' means v. 失去." },
    { word: "lost", syllables: ["lost"], phonetic: "", meaning: "adj. 丢失的，迷路的", example: "The word 'lost' means adj. 丢失的." },
    { word: "lot", syllables: ["lot"], phonetic: "/lɑːt/", meaning: "n. 许多", example: "I have a lot of homework." },
    { word: "loud", syllables: ["loud"], phonetic: "/laʊd/", meaning: "adj. 大声的", example: "The music is too loud." },
    { word: "loudly", syllables: ["loudly"], phonetic: "", meaning: "adv. 大声地", example: "The word 'loudly' means adv. 大声地." },
    { word: "love", syllables: ["love"], phonetic: "/lʌv/", meaning: "n. & v. 爱；热爱；很喜欢", example: "I love my family." },
    { word: "lovely", syllables: ["love","ly"], phonetic: "/ˈlʌvli/", meaning: "adj. 美好的；可爱的", example: "What a lovely day!" },
    { word: "low", syllables: ["low"], phonetic: "/loʊ/", meaning: "adj. & adv.               低；矮", example: "The temperature is very low." },
    { word: "luck", syllables: ["luck"], phonetic: "/lʌk/", meaning: "n. 运气，好运", example: "Good luck to you!" },
    { word: "luckily", syllables: ["luckily"], phonetic: "", meaning: "adv. 幸运地；侥幸地", example: "The word 'luckily' means adv. 幸运地." },
    { word: "lucky", syllables: ["luck","y"], phonetic: "/ˈlʌki/", meaning: "adj. 幸运的", example: "You are a lucky boy." },
    { word: "luggage", syllables: ["luggage"], phonetic: "", meaning: "n. 行李", example: "The word 'luggage' means n. 行李." },
    { word: "lunch", syllables: ["lunch"], phonetic: "/lʌntʃ/", meaning: "n. 午餐；午饭", example: "Let's have lunch together." },
    { word: "machine", syllables: ["ma","chine"], phonetic: "/məˈʃiːn/", meaning: "n. 机器", example: "This machine is very useful." },
    { word: "mad", syllables: ["mad"], phonetic: "/mæd/", meaning: "adj. 发疯的；生气的", example: "She was mad at him." }
  ],
  "第6组": [
    { word: "magazine", syllables: ["mag","a","zine"], phonetic: "/ˌmæɡəˈziːn/", meaning: "n. 杂志", example: "I read a magazine every week." },
    { word: "magic", syllables: ["mag","ic"], phonetic: "/ˈmædʒɪk/", meaning: "n. 魔术；魔法", example: "The magic show was amazing." },
    { word: "mail", syllables: ["mail"], phonetic: "/meɪl/", meaning: "n. (美)邮件；邮递; v. 邮寄", example: "I sent the letter by mail." },
    { word: "main", syllables: ["main"], phonetic: "/meɪn/", meaning: "adj. 主要的", example: "What is the main idea?" },
    { word: "mainly", syllables: ["mainly"], phonetic: "", meaning: "adv. 主要地", example: "The word 'mainly' means adv. 主要地." },
    { word: "major", syllables: ["ma","jor"], phonetic: "/ˈmeɪdʒər/", meaning: "adj. 主要的", example: "This is a major problem." },
    { word: "make (made, made)", syllables: ["make (made, made)"], phonetic: "", meaning: "v. 制造；做；使得", example: "The word 'make (made, made)' means v. 制造." },
    { word: "male", syllables: ["male"], phonetic: "/meɪl/", meaning: "adj. 男(性)的；雄的; n. 男性", example: "A male deer stood there." },
    { word: "man (复 men)", syllables: ["man (复 men)"], phonetic: "", meaning: "n. 成年男人；人；人类", example: "The word 'man (复 men)' means n. 成年男人." },
    { word: "manage", syllables: ["man","age"], phonetic: "/ˈmænɪdʒ/", meaning: "v. 管理；经营；处理；设法对付", example: "She manages the company well." },
    { word: "manager", syllables: ["man","ag","er"], phonetic: "/ˈmænɪdʒər/", meaning: "n. 经理", example: "He is the manager of the hotel." },
    { word: "manner(s)", syllables: ["manner(s)"], phonetic: "", meaning: "n. 方式；态度，举止", example: "The word 'manner(s)' means n. 方式." },
    { word: "many (比较级 more，最高级 most)", syllables: ["many (比较级 more，最高级 most)"], phonetic: "", meaning: "adj. 许多的; pron. 许多人或物", example: "The word 'many (比较级 more，最高级 most)' means adj. 许多的; pron. 许多人或物." },
    { word: "map", syllables: ["map"], phonetic: "/mæp/", meaning: "n. 地图", example: "Look at the map of China." },
    { word: "mark", syllables: ["mark"], phonetic: "/mɑːrk/", meaning: "n. 标记，记号；符号；(考试等)分数; vt. 标明，作记号于；给……打分数", example: "He got good marks in the exam." },
    { word: "market", syllables: ["mar","ket"], phonetic: "/ˈmɑːrkɪt/", meaning: "n. 市场；集市", example: "We went to the market to buy fruit." },
    { word: "marry", syllables: ["mar","ry"], phonetic: "/ˈmæri/", meaning: "v. (使)成婚，结婚", example: "They got married last year." },
    { word: "match", syllables: ["match"], phonetic: "/mætʃ/", meaning: "n. 比赛，竞赛；火柴; v. 与……匹配", example: "We watched a football match." },
    { word: "material", syllables: ["ma","te","ri","al"], phonetic: "/məˈtɪriəl/", meaning: "n. 材料，原料", example: "What material is this made of?" },
    { word: "maths (=mathematics，美 math)", syllables: ["maths (=mathematics，美 math)"], phonetic: "", meaning: "n. (通常作单数用)数学", example: "The word 'maths (=mathematics，美 math)' means n. (通常作单数用)数学." },
    { word: "matter", syllables: ["mat","ter"], phonetic: "/ˈmætər/", meaning: "n. 要紧事，麻烦事，事情；问题；物质; v. (用于否定句和疑问句)要紧，有关系", example: "What's the matter with you?" },
    { word: "may (might)", syllables: ["may (might)"], phonetic: "", meaning: "aux.   v. 可以；也许，可能", example: "The word 'may (might)' means aux.   v. 可以." },
    { word: "maybe", syllables: ["may","be"], phonetic: "/ˈmeɪbi/", meaning: "adv. 可能，大概；也许", example: "Maybe it will rain tomorrow." },
    { word: "meal", syllables: ["meal"], phonetic: "/miːl/", meaning: "n. 一餐(饭)", example: "We have three meals a day." },
    { word: "mean", syllables: ["mean"], phonetic: "/miːn/", meaning: "v. (meant, meant)                意思是，意味着; adj. 刻薄的", example: "What does this word mean?" },
    { word: "meaning", syllables: ["mean","ing"], phonetic: "/ˈmiːnɪŋ/", meaning: "n. 意思，意义；含义", example: "I don't know the meaning of this word." },
    { word: "meat", syllables: ["meat"], phonetic: "/miːt/", meaning: "n. 肉", example: "I don't eat much meat." },
    { word: "medical", syllables: ["med","i","cal"], phonetic: "/ˈmedɪkl/", meaning: "adj. 医学的，医疗的", example: "He needs medical help." },
    { word: "medicine", syllables: ["med","i","cine"], phonetic: "/ˈmedɪsn/", meaning: "n. 药", example: "Take this medicine three times a day." },
    { word: "medium", syllables: ["me","di","um"], phonetic: "/ˈmiːdiəm/", meaning: "adj. 中间的，中等的", example: "I'd like a medium pizza." },
    { word: "meet (met, met)", syllables: ["meet (met, met)"], phonetic: "", meaning: "v. 遇见，见到；会见；迎接；满足; n. 会，集会", example: "The word 'meet (met, met)' means v. 遇见." },
    { word: "meeting", syllables: ["meet","ing"], phonetic: "/ˈmiːtɪŋ/", meaning: "n. 会；集会；会见", example: "We have a meeting at ten." },
    { word: "member", syllables: ["mem","ber"], phonetic: "/ˈmembər/", meaning: "n. 成员，会员", example: "She is a member of the club." },
    { word: "memory", syllables: ["mem","o","ry"], phonetic: "/ˈmeməri/", meaning: "n. 回忆，记忆", example: "She has a good memory." },
    { word: "mention", syllables: ["men","tion"], phonetic: "/ˈmenʃn/", meaning: "v. 提到，说起", example: "He didn't mention it to me." },
    { word: "menu", syllables: ["men","u"], phonetic: "/ˈmenjuː/", meaning: "n. 菜单", example: "May I see the menu, please?" },
    { word: "message", syllables: ["mes","sage"], phonetic: "/ˈmesɪdʒ/", meaning: "n. 消息；音信", example: "Can I leave a message?" },
    { word: "metal", syllables: ["met","al"], phonetic: "/ˈmetl/", meaning: "n. 金属", example: "Gold is a precious metal." },
    { word: "method", syllables: ["meth","od"], phonetic: "/ˈmeθəd/", meaning: "n. 方法，办法", example: "This is a good method." },
    { word: "metre (美 meter)", syllables: ["metre (美 meter)"], phonetic: "", meaning: "n. 米，公尺", example: "The word 'metre (美 meter)' means n. 米." },
    { word: "middle", syllables: ["mid","dle"], phonetic: "/ˈmɪdl/", meaning: "n. 中间；当中；中部", example: "She sat in the middle." },
    { word: "mile", syllables: ["mile"], phonetic: "/maɪl/", meaning: "n. 英里", example: "We walked for miles." },
    { word: "milk", syllables: ["milk"], phonetic: "/mɪlk/", meaning: "n. 牛奶", example: "I drink milk every morning." },
    { word: "mind", syllables: ["mind"], phonetic: "/maɪnd/", meaning: "n. 思想；想法; v. 介意；关心", example: "Do you mind opening the window?" },
    { word: "minus", syllables: ["minus"], phonetic: "", meaning: "prep. & adj.                 负的，减去的", example: "The word 'minus' means prep. & adj.                 负的." },
    { word: "minute", syllables: ["min","ute"], phonetic: "/ˈmɪnɪt/", meaning: "n. 分钟；一会儿，瞬间", example: "Wait a minute, please." },
    { word: "mirror", syllables: ["mir","ror"], phonetic: "/ˈmɪrər/", meaning: "n. 镜子", example: "She looked in the mirror." },
    { word: "miss", syllables: ["miss"], phonetic: "/mɪs/", meaning: "v. 失去，错过，缺；惦记", example: "I miss my old school." },
    { word: "miss", syllables: ["miss"], phonetic: "/mɪs/", meaning: "n. 小姐，女士(称呼未婚妇女)", example: "I miss my old school." },
    { word: "mistake", syllables: ["mis","take"], phonetic: "/mɪˈsteɪk/", meaning: "n. 错误; v. 弄错，误解", example: "Everyone makes mistakes." }
  ],
  "第7组": [
    { word: "mix", syllables: ["mix"], phonetic: "/mɪks/", meaning: "v. 混合，搅拌", example: "Mix the flour and water." },
    { word: "mixture", syllables: ["mixture"], phonetic: "", meaning: "n. 混合物", example: "The word 'mixture' means n. 混合物." },
    { word: "model", syllables: ["mod","el"], phonetic: "/ˈmɑːdl/", meaning: "n. 模型；范例；模范；模特", example: "She made a model plane." },
    { word: "modern", syllables: ["mod","ern"], phonetic: "/ˈmɑːdərn/", meaning: "adj. 现代的", example: "This is a modern city." },
    { word: "moment", syllables: ["mo","ment"], phonetic: "/ˈmoʊmənt/", meaning: "n. 片刻，瞬间", example: "Wait a moment, please." },
    { word: "money", syllables: ["mon","ey"], phonetic: "/ˈmʌni/", meaning: "n. 钱；货币", example: "I don't have enough money." },
    { word: "monitor", syllables: ["mon","i","tor"], phonetic: "/ˈmɑːnɪtər/", meaning: "n. 班长；监视器", example: "He is our class monitor." },
    { word: "monkey", syllables: ["mon","key"], phonetic: "/ˈmʌŋki/", meaning: "n. 猴子", example: "The monkey is eating a banana." },
    { word: "month", syllables: ["month"], phonetic: "/mʌnθ/", meaning: "n. 月，月份", example: "There are twelve months in a year." },
    { word: "mood", syllables: ["mood"], phonetic: "", meaning: "n. 心情，语气，气氛", example: "The word 'mood' means n. 心情." },
    { word: "moon", syllables: ["moon"], phonetic: "/muːn/", meaning: "n. 月球，月亮", example: "The moon is bright tonight." },
    { word: "more(much 或 many 的比较级)", syllables: ["more(much 或 many 的比较级)"], phonetic: "", meaning: "adj. 较多的；更大的；更多的; adv. 再；更; n. 更多的量", example: "The word 'more(much 或 many 的比较级)' means adj. 较多的." },
    { word: "morning", syllables: ["mor","ning"], phonetic: "/ˈmɔːrnɪŋ/", meaning: "n. 早晨，上午", example: "Good morning, everyone!" },
    { word: "most (much 或 many 的最高级)", syllables: ["most (much 或 many 的最高级)"], phonetic: "", meaning: "adj. 最大的；最多的；; adv. 最; n. 大部分，大多数", example: "The word 'most (much 或 many 的最高级)' means adj. 最大的." },
    { word: "mother", syllables: ["moth","er"], phonetic: "/ˈmʌðər/", meaning: "n. 母亲", example: "My mother is a teacher." },
    { word: "motorcycle", syllables: ["motorcycle"], phonetic: "", meaning: "n. 摩托车", example: "The word 'motorcycle' means n. 摩托车." },
    { word: "mountain", syllables: ["moun","tain"], phonetic: "/ˈmaʊntən/", meaning: "n. 山；山脉", example: "We climbed the mountain." },
    { word: "mouse (复 mice)", syllables: ["mouse (复 mice)"], phonetic: "", meaning: "n. 老鼠；(计算机)鼠标", example: "The word 'mouse (复 mice)' means n. 老鼠." },
    { word: "mouth", syllables: ["mouth"], phonetic: "/maʊθ/", meaning: "n. 嘴，口", example: "Open your mouth, please." },
    { word: "move", syllables: ["move"], phonetic: "/muːv/", meaning: "v. 移动；搬动；搬家；感动", example: "Please move your car." },
    { word: "movie", syllables: ["mov","ie"], phonetic: "/ˈmuːvi/", meaning: "n. 电影", example: "Let's go to the movies." },
    { word: "mr", syllables: ["Mr"], phonetic: "/ˈmɪstər/", meaning: "n. 先生", example: "Mr Smith is our teacher." },
    { word: "mrs", syllables: ["Mrs"], phonetic: "/ˈmɪsɪz/", meaning: "n. 夫人，太太", example: "Mrs Green is very kind." },
    { word: "much (more, most)", syllables: ["much (more, most)"], phonetic: "", meaning: "adj. (修饰不可数名词)许多的，大量的; adv. 非常；更加; n. (表示不可数名词)许多；大量", example: "The word 'much (more, most)' means adj. (修饰不可数名词)许多的." },
    { word: "mum", syllables: ["mum"], phonetic: "", meaning: "n. (口语)妈妈", example: "The word 'mum' means n. (口语)妈妈." },
    { word: "museum", syllables: ["mu","se","um"], phonetic: "/mjuˈziːəm/", meaning: "n. 博物馆", example: "We visited the museum yesterday." },
    { word: "mushroom", syllables: ["mushroom"], phonetic: "", meaning: "n. 蘑菇", example: "The word 'mushroom' means n. 蘑菇." },
    { word: "music", syllables: ["mu","sic"], phonetic: "/ˈmjuːzɪk/", meaning: "n. 音乐；乐曲", example: "I love listening to music." },
    { word: "must", syllables: ["must"], phonetic: "/mʌst/", meaning: "aux. v. 必须；需要；应当；必定是，一定", example: "You must finish your homework." },
    { word: "name", syllables: ["name"], phonetic: "/neɪm/", meaning: "n. 名字；姓名；名称; v. 命名，名叫", example: "My name is Li Ming." },
    { word: "narrow", syllables: ["narrow"], phonetic: "", meaning: "adj. 狭窄的", example: "The word 'narrow' means adj. 狭窄的." },
    { word: "nation", syllables: ["na","tion"], phonetic: "/ˈneɪʃn/", meaning: "n. 民族；国家", example: "The whole nation celebrated." },
    { word: "national", syllables: ["na","tion","al"], phonetic: "/ˈnæʃnəl/", meaning: "adj. 全国性的；国家的；民族的", example: "Today is National Day." },
    { word: "nationality", syllables: ["nationality"], phonetic: "", meaning: "n. 国籍", example: "The word 'nationality' means n. 国籍." },
    { word: "native", syllables: ["na","tive"], phonetic: "/ˈneɪtɪv/", meaning: "adj. 本地的；本国的；当地的; n. 本地人；本国人", example: "She is a native speaker." },
    { word: "natural", syllables: ["nat","ur","al"], phonetic: "/ˈnætʃərəl/", meaning: "adj. 自然的，天然的", example: "It is a natural phenomenon." },
    { word: "nature", syllables: ["na","ture"], phonetic: "/ˈneɪtʃər/", meaning: "n. 自然；本质", example: "I love the beauty of nature." },
    { word: "naughty", syllables: ["naughty"], phonetic: "", meaning: "adj. 顽皮的", example: "The word 'naughty' means adj. 顽皮的." },
    { word: "near", syllables: ["near"], phonetic: "/nɪr/", meaning: "prep. 在……附近; adj. 近的，附近的; adv. 附近，邻近", example: "The school is near my home." },
    { word: "nearby", syllables: ["nearby"], phonetic: "", meaning: "adj. 附近的; adv. 在附近", example: "The word 'nearby' means adj. 附近的; adv. 在附近." },
    { word: "nearly", syllables: ["near","ly"], phonetic: "/ˈnɪrli/", meaning: "adv. 将近；几乎；差不多", example: "It is nearly twelve o'clock." },
    { word: "necessary", syllables: ["nec","es","sar","y"], phonetic: "/ˈnesəseri/", meaning: "adj. 必需的，必要的", example: "Sleep is necessary for health." },
    { word: "need", syllables: ["need"], phonetic: "/niːd/", meaning: "aux. v. 必须; v. 需要；必须; n. 需要，需求；必要", example: "I need some help." },
    { word: "neighbour (美 neighbor)", syllables: ["neighbour (美 neighbor)"], phonetic: "", meaning: "n. 邻居", example: "The word 'neighbour (美 neighbor)' means n. 邻居." },
    { word: "neighbourhood (美 neighborhood)", syllables: ["neighbourhood (美 neighborhood)"], phonetic: "", meaning: "n. 邻近地区，街坊", example: "The word 'neighbourhood (美 neighborhood)' means n. 邻近地区." },
    { word: "neither", syllables: ["nei","ther"], phonetic: "/ˈniːðər/", meaning: "pron. (两者)都不; adj. (两者)都不", example: "Neither answer is correct." },
    { word: "nervous", syllables: ["nerv","ous"], phonetic: "/ˈnɜːrvəs/", meaning: "adj. 紧张的", example: "I felt nervous before the exam." },
    { word: "net", syllables: ["net"], phonetic: "", meaning: "n. 网", example: "The word 'net' means n. 网." },
    { word: "network", syllables: ["network"], phonetic: "", meaning: "n. 网络；网络系统", example: "The word 'network' means n. 网络." },
    { word: "never", syllables: ["nev","er"], phonetic: "/ˈnevər/", meaning: "adv. 决不；从来没有", example: "I never get up late." }
  ],
  "第8组": [
    { word: "new", syllables: ["new"], phonetic: "/njuː/", meaning: "adj. 新的；新鲜的", example: "I bought a new bike." },
    { word: "news", syllables: ["news"], phonetic: "/njuːz/", meaning: "n. 新闻；消息", example: "I heard the good news." },
    { word: "newspaper", syllables: ["news","pa","per"], phonetic: "/ˈnjuːzpeɪpər/", meaning: "n. 报纸", example: "He reads the newspaper every day." },
    { word: "next", syllables: ["next"], phonetic: "/nekst/", meaning: "adj. 最近的；紧挨着的；隔壁的；下一次的; adv. 最近地；然后；下一步", example: "What will you do next?" },
    { word: "nice", syllables: ["nice"], phonetic: "/naɪs/", meaning: "adj. 令人愉快的；好的；漂亮的", example: "Nice to meet you!" },
    { word: "night", syllables: ["night"], phonetic: "/naɪt/", meaning: "n. 夜；夜间", example: "Good night, Mom." },
    { word: "nobody", syllables: ["no","bod","y"], phonetic: "/ˈnoʊbɑːdi/", meaning: "pron. 没有人，谁也不", example: "Nobody knows the answer." },
    { word: "noise", syllables: ["noise"], phonetic: "/nɔɪz/", meaning: "n. 声音；噪声；响声", example: "Don't make so much noise." },
    { word: "noisy", syllables: ["nois","y"], phonetic: "/ˈnɔɪzi/", meaning: "adj. 嘈杂的；喧闹的", example: "The classroom is very noisy." },
    { word: "none", syllables: ["none"], phonetic: "/nʌn/", meaning: "pron. 没有任何东西；没有人", example: "None of them came." },
    { word: "noodle", syllables: ["noo","dle"], phonetic: "/ˈnuːdl/", meaning: "n. 面条", example: "I like eating noodles." },
    { word: "nor", syllables: ["nor"], phonetic: "/nɔːr/", meaning: "conj. 也不", example: "Neither he nor I know the answer." },
    { word: "north", syllables: ["north"], phonetic: "/nɔːrθ/", meaning: "adj. 北的；朝北的；北方的; n. 北；北方；北部", example: "Beijing is in the north of China." },
    { word: "nose", syllables: ["nose"], phonetic: "/noʊz/", meaning: "n. 鼻子", example: "The dog has a good nose." },
    { word: "note", syllables: ["note"], phonetic: "/noʊt/", meaning: "n. 便条，笔记；钞票", example: "She took notes in class." },
    { word: "nothing", syllables: ["noth","ing"], phonetic: "/ˈnʌθɪŋ/", meaning: "pron. 没有东西；没有什么", example: "There is nothing in the box." },
    { word: "notice", syllables: ["no","tice"], phonetic: "/ˈnoʊtɪs/", meaning: "n. 布告；通知；注意; v. 注意，注意到", example: "Did you notice the difference?" },
    { word: "novel", syllables: ["nov","el"], phonetic: "/ˈnɑːvl/", meaning: "n. 小说", example: "She is reading a novel." },
    { word: "now", syllables: ["now"], phonetic: "/naʊ/", meaning: "adv. 现在", example: "What time is it now?" },
    { word: "nowadays", syllables: ["now","a","days"], phonetic: "/ˈnaʊədeɪz/", meaning: "adv. 当今，现在", example: "Nowadays people use smartphones a lot." },
    { word: "nowhere", syllables: ["nowhere"], phonetic: "", meaning: "adv. 任何地方都不", example: "The word 'nowhere' means adv. 任何地方都不." },
    { word: "number", syllables: ["num","ber"], phonetic: "/ˈnʌmbər/", meaning: "n. 数，数字；号码；数量", example: "What is your phone number?" },
    { word: "nurse", syllables: ["nurse"], phonetic: "/nɜːrs/", meaning: "n. 护士；保育员", example: "The nurse took care of the patient." },
    { word: "obey", syllables: ["obey"], phonetic: "", meaning: "v. 服从；顺从；听从", example: "The word 'obey' means v. 服从." },
    { word: "observe", syllables: ["ob","serve"], phonetic: "/əbˈzɜːrv/", meaning: "v. 观察；观测", example: "We observed the stars at night." },
    { word: "occupation", syllables: ["occupation"], phonetic: "", meaning: "n. 职业", example: "The word 'occupation' means n. 职业." },
    { word: "ocean", syllables: ["o","cean"], phonetic: "/ˈoʊʃn/", meaning: "n. 海洋", example: "The Pacific is the largest ocean." },
    { word: "o’clock", syllables: ["o’clock"], phonetic: "", meaning: "adv. ……点钟", example: "The word 'o’clock' means adv. ……点钟." },
    { word: "of", syllables: ["of"], phonetic: "/ʌv/", meaning: "prep. (表示所属，数量，其中等)……的", example: "This is a map of China." },
    { word: "off", syllables: ["off"], phonetic: "/ɔːf/", meaning: "adv. 离开，走开；断掉(水、电等)；完，光; prep. 脱离，(走)开；从……离开", example: "Turn off the light." },
    { word: "offer", syllables: ["of","fer"], phonetic: "/ˈɔːfər/", meaning: "n. & v. 提供", example: "He offered to help me." },
    { word: "office", syllables: ["of","fice"], phonetic: "/ˈɔːfɪs/", meaning: "n. 办公室", example: "She works in an office." },
    { word: "officer", syllables: ["of","fi","cer"], phonetic: "/ˈɔːfɪsər/", meaning: "n. 官员，办事员", example: "The police officer helped us." },
    { word: "official", syllables: ["of","fi","cial"], phonetic: "/əˈfɪʃl/", meaning: "n. (公司、团体或政府的)官员; adj. 官方的，政府的；官员的", example: "This is an official document." },
    { word: "often", syllables: ["of","ten"], phonetic: "/ˈɔːfn/", meaning: "adv. 经常，常常", example: "I often read books." },
    { word: "oil", syllables: ["oil"], phonetic: "/ɔɪl/", meaning: "n. 油；石油", example: "This car needs more oil." },
    { word: "old", syllables: ["old"], phonetic: "/oʊld/", meaning: "adj. 年老的；古老的；旧的", example: "How old are you?" },
    { word: "olympic", syllables: ["O","lym","pic"], phonetic: "/oʊˈlɪmpɪk/", meaning: "adj. 奥林匹克的; n. 奥林匹克(运动会)", example: "The Olympic Games are exciting." },
    { word: "on", syllables: ["on"], phonetic: "/ɑːn/", meaning: "prep. 在……之上；在……时刻；关于; adv. (穿，放……)上；(水、电等)接通；进行下去; adj. 在上映", example: "The book is on the desk." },
    { word: "once", syllables: ["once"], phonetic: "/wʌns/", meaning: "adv. & conj. & n.     一次，一度，从前", example: "I once lived in Shanghai." },
    { word: "one", syllables: ["one"], phonetic: "/wʌn/", meaning: "pron. 一", example: "One plus one is two." },
    { word: "online", syllables: ["on","line"], phonetic: "/ˌɑːnˈlaɪn/", meaning: "adj. 在线的; adv. 在线地", example: "I often shop online." },
    { word: "only", syllables: ["on","ly"], phonetic: "/ˈoʊnli/", meaning: "adv. 只；只是；仅仅; adj. 唯一的，仅有的", example: "I have only one pen." },
    { word: "onto", syllables: ["onto"], phonetic: "", meaning: "prep. 到……上面", example: "The word 'onto' means prep. 到……上面." },
    { word: "open", syllables: ["o","pen"], phonetic: "/ˈoʊpən/", meaning: "v. 打开；张开；开办；开设; adj. 开着的，开口的；敞开的；营业中的", example: "Please open the window." },
    { word: "operate", syllables: ["op","er","ate"], phonetic: "/ˈɑːpəreɪt/", meaning: "v. 动手术，开刀；操作；运转", example: "The doctor operated on him." },
    { word: "operation", syllables: ["op","er","a","tion"], phonetic: "/ˌɑːpəˈreɪʃn/", meaning: "n. 手术", example: "The operation was successful." },
    { word: "opinion", syllables: ["o","pin","ion"], phonetic: "/əˈpɪnjən/", meaning: "n. 看法，观点", example: "What is your opinion?" },
    { word: "opposite", syllables: ["op","po","site"], phonetic: "/ˈɑːpəzət/", meaning: "adj. & prep.        在……对面；相对的；对立的", example: "The bank is opposite the school." },
    { word: "or", syllables: ["or"], phonetic: "", meaning: "conj. 或者；还是；否则", example: "The word 'or' means conj. 或者." }
  ],
  "第9组": [
    { word: "orange", syllables: ["or","ange"], phonetic: "/ˈɔːrɪndʒ/", meaning: "n. 橘子，橙；橙色; adj. 橙色的", example: "I'd like some orange juice." },
    { word: "order", syllables: ["or","der"], phonetic: "/ˈɔːrdər/", meaning: "n. 命令，指示；顺序; v. 命令；定购；点(菜、饮料等)", example: "I'd like to order some food." },
    { word: "ordinary", syllables: ["or","di","nar","y"], phonetic: "/ˈɔːrdneri/", meaning: "adj. 普通的，平常的", example: "He is an ordinary student." },
    { word: "organization", syllables: ["organization"], phonetic: "", meaning: "n. 组织，团体，机构", example: "The word 'organization' means n. 组织." },
    { word: "organize", syllables: ["or","gan","ize"], phonetic: "/ˈɔːrɡənaɪz/", meaning: "v. 组织", example: "They organized a party." },
    { word: "other", syllables: ["oth","er"], phonetic: "/ˈʌðər/", meaning: "adj. 其他的；另外的; pron. 别人；别的东西", example: "Do you have any other questions?" },
    { word: "ought (to) aux .", syllables: ["ought (to) aux ."], phonetic: "", meaning: "v. 应该，应当", example: "The word 'ought (to) aux .' means v. 应该." },
    { word: "out", syllables: ["out"], phonetic: "/aʊt/", meaning: "adv. 向外；在外；离开", example: "Let's go out for a walk." },
    { word: "outdoor", syllables: ["out","door"], phonetic: "/ˈaʊtdɔːr/", meaning: "adj. 室外的", example: "I like outdoor activities." },
    { word: "outside", syllables: ["out","side"], phonetic: "/ˌaʊtˈsaɪd/", meaning: "prep. 在……外; adv. 在外面", example: "It is raining outside." },
    { word: "oven", syllables: ["oven"], phonetic: "", meaning: "n. 炉子；烤箱", example: "The word 'oven' means n. 炉子." },
    { word: "over", syllables: ["o","ver"], phonetic: "/ˈoʊvər/", meaning: "prep. 在……上方；越过；遍及；超过; adv. 结束；越过；翻转", example: "The plane flew over the city." },
    { word: "own", syllables: ["own"], phonetic: "/oʊn/", meaning: "adj. 自己的; v. 拥有", example: "I have my own room." },
    { word: "owner", syllables: ["own","er"], phonetic: "/ˈoʊnər/", meaning: "n. 拥有者；物主", example: "Who is the owner of this dog?" },
    { word: "Pacific", syllables: ["Pacific"], phonetic: "", meaning: "n. 太平洋", example: "The word 'Pacific' means n. 太平洋." },
    { word: "pack", syllables: ["pack"], phonetic: "/pæk/", meaning: "n. 包; v. 打包", example: "Pack your bag before you leave." },
    { word: "page", syllables: ["page"], phonetic: "/peɪdʒ/", meaning: "n. 页；页码", example: "Turn to page ten." },
    { word: "pain", syllables: ["pain"], phonetic: "/peɪn/", meaning: "n. 疼痛，疼", example: "I have a pain in my leg." },
    { word: "paint", syllables: ["paint"], phonetic: "/peɪnt/", meaning: "v. 油漆，粉刷；绘画; n. 油漆；涂料；颜料", example: "She likes to paint flowers." },
    { word: "painting", syllables: ["painting"], phonetic: "", meaning: "n. 画，油画，水彩画", example: "The word 'painting' means n. 画." },
    { word: "pair", syllables: ["pair"], phonetic: "/per/", meaning: "n. 一双；一对", example: "I need a pair of shoes." },
    { word: "palace", syllables: ["pal","ace"], phonetic: "/ˈpælɪs/", meaning: "n. 宫；宫殿", example: "The palace is very beautiful." },
    { word: "pale", syllables: ["pale"], phonetic: "/peɪl/", meaning: "adj. 苍白的，灰白的", example: "She looked pale and tired." },
    { word: "panda", syllables: ["pan","da"], phonetic: "/ˈpændə/", meaning: "n. 熊猫", example: "Pandas live in China." },
    { word: "paper", syllables: ["pa","per"], phonetic: "/ˈpeɪpər/", meaning: "n. (不可数)纸；(可数)报纸；考卷；文件", example: "Please write on the paper." },
    { word: "parent", syllables: ["par","ent"], phonetic: "/ˈperənt/", meaning: "n. 父(母)，(复数)双亲", example: "My parents are teachers." },
    { word: "Paris", syllables: ["Paris"], phonetic: "", meaning: "n. (法国首都)巴黎", example: "The word 'Paris' means n. (法国首都)巴黎." },
    { word: "park", syllables: ["park"], phonetic: "/pɑːrk/", meaning: "n. 公园; v. 停放(车辆等)", example: "Let's go to the park." },
    { word: "part", syllables: ["part"], phonetic: "/pɑːrt/", meaning: "n. 部分；角色；部件；零件", example: "What part of China are you from?" },
    { word: "partner", syllables: ["part","ner"], phonetic: "/ˈpɑːrtnər/", meaning: "n. 搭档，合作者", example: "She is my dancing partner." },
    { word: "party", syllables: ["par","ty"], phonetic: "/ˈpɑːrti/", meaning: "n. 聚会，晚会；政党；党派", example: "We had a birthday party." },
    { word: "pass", syllables: ["pass"], phonetic: "/pæs/", meaning: "v. 传，递；经过，路过；通过", example: "Please pass me the salt." },
    { word: "passage", syllables: ["pas","sage"], phonetic: "/ˈpæsɪdʒ/", meaning: "n. (文章等的)一节，一段；通道", example: "Read the passage and answer." },
    { word: "passenger", syllables: ["pas","sen","ger"], phonetic: "/ˈpæsɪndʒər/", meaning: "n. 乘客；旅客", example: "The passengers got on the bus." },
    { word: "passport", syllables: ["pass","port"], phonetic: "/ˈpæspɔːrt/", meaning: "n. 护照", example: "Don't forget your passport." },
    { word: "past", syllables: ["past"], phonetic: "/pæst/", meaning: "prep. (指时间等)过……；走过某处; n. 过去；昔日；往事", example: "In the past, people walked more." },
    { word: "patient", syllables: ["pa","tient"], phonetic: "/ˈpeɪʃnt/", meaning: "n. 病人", example: "Please be patient." },
    { word: "pay (paid，paid)", syllables: ["pay (paid，paid)"], phonetic: "", meaning: "v. 付钱，给……报酬; n. 工资", example: "The word 'pay (paid，paid)' means v. 付钱." },
    { word: "P.E. 体育", syllables: ["P.E. 体育"], phonetic: "", meaning: "", example: "The word 'P.E. 体育' means ." },
    { word: "peace", syllables: ["peace"], phonetic: "/piːs/", meaning: "n. 和平", example: "We all want peace." },
    { word: "pear", syllables: ["pear"], phonetic: "/per/", meaning: "n. 梨", example: "The pear tastes sweet." },
    { word: "pearl", syllables: ["pearl"], phonetic: "", meaning: "n. 珍珠", example: "The word 'pearl' means n. 珍珠." },
    { word: "pen", syllables: ["pen"], phonetic: "/pen/", meaning: "n. 钢笔；笔", example: "I write with a pen." },
    { word: "pencil", syllables: ["pen","cil"], phonetic: "/ˈpensl/", meaning: "n. 铅笔", example: "May I borrow your pencil?" },
    { word: "people", syllables: ["peo","ple"], phonetic: "/ˈpiːpl/", meaning: "n. 人；人们；人民", example: "Many people like music." },
    { word: "per", syllables: ["per"], phonetic: "", meaning: "prep. 每，每一", example: "The word 'per' means prep. 每." },
    { word: "percent", syllables: ["per","cent"], phonetic: "/pərˈsent/", meaning: "n. 百分比", example: "Fifty percent of students passed." },
    { word: "perfect", syllables: ["per","fect"], phonetic: "/ˈpɜːrfɪkt/", meaning: "adj. 完美的；极好的", example: "The weather is perfect today." },
    { word: "performance", syllables: ["performance"], phonetic: "", meaning: "n. 表演，演出；行动", example: "The word 'performance' means n. 表演." },
    { word: "perhaps", syllables: ["per","haps"], phonetic: "/pərˈhæps/", meaning: "adv. 可能，也许", example: "Perhaps it will rain tomorrow." }
  ]
};