// 中考英语词汇 G-O（按字母分组，每组50词）
const WORDS_ZK_GO = {
  "第12组": [
    { word: "game", syllables: ["game"], phonetic: "/ɡeɪm/", meaning: "n. 游戏；比赛", example: "Let's play a game." },
    { word: "garden", syllables: ["gar","den"], phonetic: "/ˈɡɑːrdn/", meaning: "n. 花园", example: "She is in the garden." },
    { word: "gate", syllables: ["gate"], phonetic: "/ɡeɪt/", meaning: "n. 大门", example: "He stood at the gate." },
    { word: "general", syllables: ["gen","er","al"], phonetic: "/ˈdʒenərəl/", meaning: "adj. 普遍的；一般的", example: "This is a general rule." },
    { word: "gentle", syllables: ["gen","tle"], phonetic: "/ˈdʒentl/", meaning: "adj. 温柔的；轻柔的", example: "She has a gentle voice." },
    { word: "gentleman", syllables: ["gen","tle","man"], phonetic: "/ˈdʒentlmən/", meaning: "n. 绅士；先生", example: "He is a gentleman." },
    { word: "geography", syllables: ["ge","og","ra","phy"], phonetic: "/dʒiˈɑːɡrəfi/", meaning: "n. 地理", example: "I like geography class." },
    { word: "gesture", syllables: ["ges","ture"], phonetic: "/ˈdʒestʃər/", meaning: "n. 手势；姿势", example: "He made a gesture." },
    { word: "get", syllables: ["get"], phonetic: "/ɡet/", meaning: "v. 得到；变得", example: "I get up early every day." },
    { word: "gift", syllables: ["gift"], phonetic: "/ɡɪft/", meaning: "n. 礼物；天赋", example: "This is a birthday gift." },
    { word: "giraffe", syllables: ["gi","raffe"], phonetic: "/dʒɪˈræf/", meaning: "n. 长颈鹿", example: "The giraffe is very tall." },
    { word: "girl", syllables: ["girl"], phonetic: "/ɡɜːrl/", meaning: "n. 女孩", example: "She is a lovely girl." },
    { word: "give", syllables: ["give"], phonetic: "/ɡɪv/", meaning: "v. 给", example: "Please give me the book." },
    { word: "glad", syllables: ["glad"], phonetic: "/ɡlæd/", meaning: "adj. 高兴的", example: "I'm glad to see you." },
    { word: "glass", syllables: ["glass"], phonetic: "/ɡlæs/", meaning: "n. 玻璃；玻璃杯", example: "Give me a glass of water." },
    { word: "glove", syllables: ["glove"], phonetic: "/ɡlʌv/", meaning: "n. 手套", example: "Put on your gloves." },
    { word: "go", syllables: ["go"], phonetic: "/ɡoʊ/", meaning: "v. 去", example: "Let's go to school." },
    { word: "gold", syllables: ["gold"], phonetic: "/ɡoʊld/", meaning: "n. & adj. 黄金(的)", example: "She won a gold medal." },
    { word: "golden", syllables: ["gold","en"], phonetic: "/ˈɡoʊldən/", meaning: "adj. 金色的", example: "She has golden hair." },
    { word: "good", syllables: ["good"], phonetic: "/ɡʊd/", meaning: "adj. 好的", example: "He is a good student." },
    { word: "goodbye", syllables: ["good","bye"], phonetic: "/ɡʊdˈbaɪ/", meaning: "interj. 再见", example: "Goodbye, everyone!" },
    { word: "government", syllables: ["gov","ern","ment"], phonetic: "/ˈɡʌvərnmənt/", meaning: "n. 政府", example: "The government made a new law." },
    { word: "grade", syllables: ["grade"], phonetic: "/ɡreɪd/", meaning: "n. 年级；成绩", example: "She is in Grade 8." },
    { word: "grammar", syllables: ["gram","mar"], phonetic: "/ˈɡræmər/", meaning: "n. 语法", example: "English grammar is not easy." },
    { word: "grandchild", syllables: ["grand","child"], phonetic: "/ˈɡrændtʃaɪld/", meaning: "n. 孙辈", example: "She loves her grandchildren." },
    { word: "granddaughter", syllables: ["grand","daugh","ter"], phonetic: "/ˈɡrændɔːtər/", meaning: "n. 孙女", example: "She is my granddaughter." },
    { word: "grandfather", syllables: ["grand","fa","ther"], phonetic: "/ˈɡrændfɑːðər/", meaning: "n. 祖父；外祖父", example: "My grandfather is 70 years old." },
    { word: "grandmother", syllables: ["grand","mo","ther"], phonetic: "/ˈɡrændmʌðər/", meaning: "n. 祖母；外祖母", example: "My grandmother cooks well." },
    { word: "grandparent", syllables: ["grand","par","ent"], phonetic: "/ˈɡrænperənt/", meaning: "n. 祖父母；外祖父母", example: "I visit my grandparents often." },
    { word: "grandson", syllables: ["grand","son"], phonetic: "/ˈɡrænsʌn/", meaning: "n. 孙子", example: "He is my grandson." },
    { word: "grape", syllables: ["grape"], phonetic: "/ɡreɪp/", meaning: "n. 葡萄", example: "I like eating grapes." },
    { word: "grass", syllables: ["grass"], phonetic: "/ɡræs/", meaning: "n. 草；草地", example: "Don't walk on the grass." },
    { word: "grateful", syllables: ["grate","ful"], phonetic: "/ˈɡreɪtfl/", meaning: "adj. 感激的", example: "I am grateful for your help." },
    { word: "gray", syllables: ["gray"], phonetic: "/ɡreɪ/", meaning: "adj. 灰色的", example: "The sky is gray today." },
    { word: "great", syllables: ["great"], phonetic: "/ɡreɪt/", meaning: "adj. 伟大的；很棒的", example: "That's a great idea!" },
    { word: "green", syllables: ["green"], phonetic: "/ɡriːn/", meaning: "adj. 绿色的", example: "The tree is green." },
    { word: "greet", syllables: ["greet"], phonetic: "/ɡriːt/", meaning: "v. 问候；打招呼", example: "She greeted me with a smile." },
    { word: "greeting", syllables: ["greet","ing"], phonetic: "/ˈɡriːtɪŋ/", meaning: "n. 问候；祝贺", example: "Send my greetings to your family." },
    { word: "ground", syllables: ["ground"], phonetic: "/ɡraʊnd/", meaning: "n. 地面", example: "The ball is on the ground." },
    { word: "group", syllables: ["group"], phonetic: "/ɡruːp/", meaning: "n. 组；群", example: "We work in groups." },
    { word: "grow", syllables: ["grow"], phonetic: "/ɡroʊ/", meaning: "v. 生长；种植", example: "Plants grow in spring." },
    { word: "grow up", syllables: ["grow","up"], phonetic: "/ɡroʊ ʌp/", meaning: "phr. 长大", example: "I want to be a doctor when I grow up." },
    { word: "guard", syllables: ["guard"], phonetic: "/ɡɑːrd/", meaning: "n. & v. 守卫；警卫", example: "The guard stood at the door." },
    { word: "guess", syllables: ["guess"], phonetic: "/ɡes/", meaning: "v. 猜", example: "Can you guess the answer?" },
    { word: "guest", syllables: ["guest"], phonetic: "/ɡest/", meaning: "n. 客人", example: "We have a guest tonight." },
    { word: "guide", syllables: ["guide"], phonetic: "/ɡaɪd/", meaning: "n. 向导 v. 指导", example: "The guide showed us around." },
    { word: "guitar", syllables: ["gui","tar"], phonetic: "/ɡɪˈtɑːr/", meaning: "n. 吉他", example: "He plays the guitar well." },
    { word: "gun", syllables: ["gun"], phonetic: "/ɡʌn/", meaning: "n. 枪", example: "The police carried guns." },
    { word: "guy", syllables: ["guy"], phonetic: "/ɡaɪ/", meaning: "n. 家伙；人", example: "He is a nice guy." },
    { word: "gym", syllables: ["gym"], phonetic: "/dʒɪm/", meaning: "n. 体育馆；健身房", example: "I go to the gym every week." }
  ],
  "第13组": [
    { word: "habit", syllables: ["hab","it"], phonetic: "/ˈhæbɪt/", meaning: "n. 习惯", example: "Reading is a good habit." },
    { word: "hair", syllables: ["hair"], phonetic: "/her/", meaning: "n. 头发", example: "She has long hair." },
    { word: "half", syllables: ["half"], phonetic: "/hæf/", meaning: "n. & adj. 一半(的)", example: "Half of the students are girls." },
    { word: "hall", syllables: ["hall"], phonetic: "/hɔːl/", meaning: "n. 大厅；礼堂", example: "The concert is in the hall." },
    { word: "hamburger", syllables: ["ham","bur","ger"], phonetic: "/ˈhæmbɜːrɡər/", meaning: "n. 汉堡包", example: "I'd like a hamburger." },
    { word: "hammer", syllables: ["ham","mer"], phonetic: "/ˈhæmər/", meaning: "n. 锤子", example: "He hit the nail with a hammer." },
    { word: "hand", syllables: ["hand"], phonetic: "/hænd/", meaning: "n. 手", example: "Raise your hand, please." },
    { word: "handbag", syllables: ["hand","bag"], phonetic: "/ˈhændbæɡ/", meaning: "n. 手提包", example: "She bought a new handbag." },
    { word: "handsome", syllables: ["hand","some"], phonetic: "/ˈhænsəm/", meaning: "adj. 英俊的", example: "He is a handsome boy." },
    { word: "handwriting", syllables: ["hand","writ","ing"], phonetic: "/ˈhændraɪtɪŋ/", meaning: "n. 书法；笔迹", example: "Her handwriting is beautiful." },
    { word: "happen", syllables: ["hap","pen"], phonetic: "/ˈhæpən/", meaning: "v. 发生", example: "What happened to him?" },
    { word: "happy", syllables: ["hap","py"], phonetic: "/ˈhæpi/", meaning: "adj. 高兴的；幸福的", example: "I feel very happy today." },
    { word: "hard", syllables: ["hard"], phonetic: "/hɑːrd/", meaning: "adj. 困难的 adv. 努力地", example: "He studies hard every day." },
    { word: "hardly", syllables: ["hard","ly"], phonetic: "/ˈhɑːrdli/", meaning: "adv. 几乎不", example: "I hardly know her." },
    { word: "hardship", syllables: ["hard","ship"], phonetic: "/ˈhɑːrdʃɪp/", meaning: "n. 困难；苦难", example: "They faced many hardships." },
    { word: "harm", syllables: ["harm"], phonetic: "/hɑːrm/", meaning: "n. & v. 伤害；损害", example: "Smoking does harm to health." },
    { word: "harmful", syllables: ["harm","ful"], phonetic: "/ˈhɑːrmfl/", meaning: "adj. 有害的", example: "Junk food is harmful." },
    { word: "hat", syllables: ["hat"], phonetic: "/hæt/", meaning: "n. 帽子", example: "She is wearing a hat." },
    { word: "hate", syllables: ["hate"], phonetic: "/heɪt/", meaning: "v. 憎恨；讨厌", example: "I hate rainy days." },
    { word: "have", syllables: ["have"], phonetic: "/hæv/", meaning: "v. 有；吃", example: "I have a new book." },
    { word: "he", syllables: ["he"], phonetic: "/hiː/", meaning: "pron. 他", example: "He is my brother." },
    { word: "head", syllables: ["head"], phonetic: "/hed/", meaning: "n. 头；头部", example: "She nodded her head." },
    { word: "headache", syllables: ["head","ache"], phonetic: "/ˈhedeɪk/", meaning: "n. 头痛", example: "I have a headache today." },
    { word: "headline", syllables: ["head","line"], phonetic: "/ˈhedlaɪn/", meaning: "n. 标题", example: "Read the headline of the news." },
    { word: "health", syllables: ["health"], phonetic: "/helθ/", meaning: "n. 健康", example: "Health is very important." },
    { word: "healthy", syllables: ["health","y"], phonetic: "/ˈhelθi/", meaning: "adj. 健康的", example: "We should eat healthy food." },
    { word: "hear", syllables: ["hear"], phonetic: "/hɪr/", meaning: "v. 听见；听到", example: "I can hear the birds singing." },
    { word: "heart", syllables: ["heart"], phonetic: "/hɑːrt/", meaning: "n. 心；心脏", example: "Thank you from the bottom of my heart." },
    { word: "heat", syllables: ["heat"], phonetic: "/hiːt/", meaning: "n. 热 v. 加热", example: "The heat of the sun is strong." },
    { word: "heaven", syllables: ["hea","ven"], phonetic: "/ˈhevn/", meaning: "n. 天堂；天空", example: "The stars are in heaven." },
    { word: "heavy", syllables: ["hea","vy"], phonetic: "/ˈhevi/", meaning: "adj. 重的", example: "This box is too heavy." },
    { word: "height", syllables: ["height"], phonetic: "/haɪt/", meaning: "n. 高度；身高", example: "What is your height?" },
    { word: "helicopter", syllables: ["heli","cop","ter"], phonetic: "/ˈhelɪkɑːptər/", meaning: "n. 直升机", example: "A helicopter flew over us." },
    { word: "hello", syllables: ["hel","lo"], phonetic: "/həˈloʊ/", meaning: "interj. 你好", example: "Hello, how are you?" },
    { word: "help", syllables: ["help"], phonetic: "/help/", meaning: "v. & n. 帮助", example: "Can you help me?" },
    { word: "helpful", syllables: ["help","ful"], phonetic: "/ˈhelpfl/", meaning: "adj. 有帮助的", example: "The book is very helpful." },
    { word: "helpless", syllables: ["help","less"], phonetic: "/ˈhelpləs/", meaning: "adj. 无助的", example: "The baby felt helpless." },
    { word: "her", syllables: ["her"], phonetic: "/hɜːr/", meaning: "pron. 她(宾格)；她的", example: "Give her the pen." },
    { word: "here", syllables: ["here"], phonetic: "/hɪr/", meaning: "adv. 这里", example: "Please come here." },
    { word: "hero", syllables: ["he","ro"], phonetic: "/ˈhɪroʊ/", meaning: "n. 英雄", example: "He is a national hero." },
    { word: "hers", syllables: ["hers"], phonetic: "/hɜːrz/", meaning: "pron. 她的(名词性物主代词)", example: "This book is hers." },
    { word: "herself", syllables: ["her","self"], phonetic: "/hɜːrˈself/", meaning: "pron. 她自己", example: "She did it herself." },
    { word: "hide", syllables: ["hide"], phonetic: "/haɪd/", meaning: "v. 隐藏；躲藏", example: "The cat hid under the bed." },
    { word: "high", syllables: ["high"], phonetic: "/haɪ/", meaning: "adj. 高的 adv. 高", example: "The mountain is very high." },
    { word: "highlight", syllables: ["high","light"], phonetic: "/ˈhaɪlaɪt/", meaning: "v. 强调 n. 亮点", example: "Please highlight the key points." },
    { word: "hill", syllables: ["hill"], phonetic: "/hɪl/", meaning: "n. 小山", example: "We climbed the hill." },
    { word: "him", syllables: ["him"], phonetic: "/hɪm/", meaning: "pron. 他(宾格)", example: "I saw him at school." },
    { word: "himself", syllables: ["him","self"], phonetic: "/hɪmˈself/", meaning: "pron. 他自己", example: "He cooked dinner himself." },
    { word: "his", syllables: ["his"], phonetic: "/hɪz/", meaning: "pron. 他的", example: "This is his book." },
    { word: "hire", syllables: ["hire"], phonetic: "/ˈhaɪər/", meaning: "v. 租用；雇佣", example: "We hired a car for the trip." }
  ],
  "第14组": [
    { word: "history", syllables: ["his","to","ry"], phonetic: "/ˈhɪstri/", meaning: "n. 历史", example: "I like studying history." },
    { word: "hit", syllables: ["hit"], phonetic: "/hɪt/", meaning: "v. 打；击中", example: "He hit the ball hard." },
    { word: "hobby", syllables: ["hob","by"], phonetic: "/ˈhɑːbi/", meaning: "n. 爱好", example: "My hobby is reading." },
    { word: "hold", syllables: ["hold"], phonetic: "/hoʊld/", meaning: "v. 拿；举行", example: "Please hold this for me." },
    { word: "hole", syllables: ["hole"], phonetic: "/hoʊl/", meaning: "n. 洞；孔", example: "There is a hole in the wall." },
    { word: "holiday", syllables: ["hol","i","day"], phonetic: "/ˈhɑːlədeɪ/", meaning: "n. 假日；假期", example: "We went to the beach on holiday." },
    { word: "home", syllables: ["home"], phonetic: "/hoʊm/", meaning: "n. 家 adv. 回家", example: "I go home at five." },
    { word: "hometown", syllables: ["home","town"], phonetic: "/ˈhoʊmtaʊn/", meaning: "n. 家乡", example: "I love my hometown." },
    { word: "homework", syllables: ["home","work"], phonetic: "/ˈhoʊmwɜːrk/", meaning: "n. 家庭作业", example: "I finished my homework." },
    { word: "honest", syllables: ["hon","est"], phonetic: "/ˈɑːnɪst/", meaning: "adj. 诚实的", example: "He is an honest boy." },
    { word: "honor", syllables: ["hon","or"], phonetic: "/ˈɑːnər/", meaning: "n. 荣誉 v. 尊敬", example: "It is an honor to be here." },
    { word: "hook", syllables: ["hook"], phonetic: "/hʊk/", meaning: "n. 钩子 v. 钩住", example: "Hang your coat on the hook." },
    { word: "hope", syllables: ["hope"], phonetic: "/hoʊp/", meaning: "v. & n. 希望", example: "I hope you get well soon." },
    { word: "horrible", syllables: ["hor","ri","ble"], phonetic: "/ˈhɔːrəbl/", meaning: "adj. 可怕的", example: "The weather was horrible." },
    { word: "horse", syllables: ["horse"], phonetic: "/hɔːrs/", meaning: "n. 马", example: "She rides a horse." },
    { word: "hospital", syllables: ["hos","pi","tal"], phonetic: "/ˈhɑːspɪtl/", meaning: "n. 医院", example: "He is in the hospital." },
    { word: "host", syllables: ["host"], phonetic: "/hoʊst/", meaning: "n. 主人；主持人", example: "She is the host of the show." },
    { word: "hot", syllables: ["hot"], phonetic: "/hɑːt/", meaning: "adj. 热的；辣的", example: "It is very hot today." },
    { word: "hot dog", syllables: ["hot","dog"], phonetic: "/ˈhɑːt dɔːɡ/", meaning: "n. 热狗", example: "I want a hot dog." },
    { word: "hotel", syllables: ["ho","tel"], phonetic: "/hoʊˈtel/", meaning: "n. 旅馆；酒店", example: "We stayed at a hotel." },
    { word: "hour", syllables: ["hour"], phonetic: "/ˈaʊər/", meaning: "n. 小时", example: "I waited for two hours." },
    { word: "house", syllables: ["house"], phonetic: "/haʊs/", meaning: "n. 房子", example: "They have a big house." },
    { word: "housework", syllables: ["house","work"], phonetic: "/ˈhaʊswɜːrk/", meaning: "n. 家务", example: "I help with the housework." },
    { word: "how", syllables: ["how"], phonetic: "/haʊ/", meaning: "adv. 怎样；多么", example: "How are you?" },
    { word: "however", syllables: ["how","ev","er"], phonetic: "/haʊˈevər/", meaning: "adv. 然而；不过", example: "However, he didn't agree." },
    { word: "hug", syllables: ["hug"], phonetic: "/hʌɡ/", meaning: "v. & n. 拥抱", example: "She gave her mother a hug." },
    { word: "huge", syllables: ["huge"], phonetic: "/hjuːdʒ/", meaning: "adj. 巨大的", example: "The elephant is huge." },
    { word: "human", syllables: ["hu","man"], phonetic: "/ˈhjuːmən/", meaning: "n. & adj. 人类(的)", example: "Humans need water." },
    { word: "humor", syllables: ["hu","mor"], phonetic: "/ˈhjuːmər/", meaning: "n. 幽默", example: "He has a good sense of humor." },
    { word: "humorous", syllables: ["hu","mor","ous"], phonetic: "/ˈhjuːmərəs/", meaning: "adj. 幽默的", example: "Our teacher is humorous." },
    { word: "hundred", syllables: ["hun","dred"], phonetic: "/ˈhʌndrəd/", meaning: "num. 百", example: "There are a hundred students." },
    { word: "hunger", syllables: ["hun","ger"], phonetic: "/ˈhʌŋɡər/", meaning: "n. 饥饿", example: "Hunger is a big problem." },
    { word: "hungry", syllables: ["hun","gry"], phonetic: "/ˈhʌŋɡri/", meaning: "adj. 饥饿的", example: "I am very hungry now." },
    { word: "hunt", syllables: ["hunt"], phonetic: "/hʌnt/", meaning: "v. 打猎；搜寻", example: "They went hunting." },
    { word: "hurry", syllables: ["hur","ry"], phonetic: "/ˈhɜːri/", meaning: "v. & n. 赶快；匆忙", example: "Hurry up, or we'll be late!" },
    { word: "hurt", syllables: ["hurt"], phonetic: "/hɜːrt/", meaning: "v. 伤害；疼痛", example: "My leg hurts." },
    { word: "husband", syllables: ["hus","band"], phonetic: "/ˈhʌzbənd/", meaning: "n. 丈夫", example: "Her husband is a teacher." },
    { word: "ice", syllables: ["ice"], phonetic: "/aɪs/", meaning: "n. 冰", example: "The lake is covered with ice." },
    { word: "ice cream", syllables: ["ice","cream"], phonetic: "/ˈaɪs kriːm/", meaning: "n. 冰淇淋", example: "I love ice cream." },
    { word: "idea", syllables: ["i","de","a"], phonetic: "/aɪˈdiːə/", meaning: "n. 主意；想法", example: "That's a good idea!" },
    { word: "ideal", syllables: ["i","de","al"], phonetic: "/aɪˈdiːəl/", meaning: "adj. 理想的", example: "This is an ideal place for camping." },
    { word: "if", syllables: ["if"], phonetic: "/ɪf/", meaning: "conj. 如果；是否", example: "If it rains, I will stay home." },
    { word: "ill", syllables: ["ill"], phonetic: "/ɪl/", meaning: "adj. 生病的", example: "She is ill in bed." },
    { word: "illness", syllables: ["ill","ness"], phonetic: "/ˈɪlnəs/", meaning: "n. 疾病", example: "He recovered from his illness." },
    { word: "imagine", syllables: ["i","ma","gine"], phonetic: "/ɪˈmædʒɪn/", meaning: "v. 想象", example: "Imagine you are on the moon." },
    { word: "immediate", syllables: ["im","me","di","ate"], phonetic: "/ɪˈmiːdiət/", meaning: "adj. 立即的", example: "We need immediate action." },
    { word: "import", syllables: ["im","port"], phonetic: "/ɪmˈpɔːrt/", meaning: "v. 进口 n. 进口", example: "We import goods from China." },
    { word: "important", syllables: ["im","por","tant"], phonetic: "/ɪmˈpɔːrtnt/", meaning: "adj. 重要的", example: "Health is very important." },
    { word: "impossible", syllables: ["im","pos","si","ble"], phonetic: "/ɪmˈpɑːsəbl/", meaning: "adj. 不可能的", example: "Nothing is impossible." },
    { word: "impression", syllables: ["im","pres","sion"], phonetic: "/ɪmˈpreʃn/", meaning: "n. 印象", example: "He made a good impression." }
  ],
  "第15组": [
    { word: "improve", syllables: ["im","prove"], phonetic: "/ɪmˈpruːv/", meaning: "v. 改善；提高", example: "I want to improve my English." },
    { word: "in", syllables: ["in"], phonetic: "/ɪn/", meaning: "prep. 在……里面", example: "The book is in the bag." },
    { word: "inch", syllables: ["inch"], phonetic: "/ɪntʃ/", meaning: "n. 英寸", example: "Give him an inch and he'll take a mile." },
    { word: "include", syllables: ["in","clude"], phonetic: "/ɪnˈkluːd/", meaning: "v. 包括", example: "The price includes breakfast." },
    { word: "increase", syllables: ["in","crease"], phonetic: "/ɪnˈkriːs/", meaning: "v. & n. 增加", example: "The population is increasing." },
    { word: "indeed", syllables: ["in","deed"], phonetic: "/ɪnˈdiːd/", meaning: "adv. 确实；真正地", example: "It is indeed a great city." },
    { word: "India", syllables: ["In","dia"], phonetic: "/ˈɪndiə/", meaning: "n. 印度", example: "India is a large country." },
    { word: "Indian", syllables: ["In","dian"], phonetic: "/ˈɪndiən/", meaning: "adj. & n. 印度的；印度人", example: "Indian food is delicious." },
    { word: "industry", syllables: ["in","dus","try"], phonetic: "/ˈɪndəstri/", meaning: "n. 工业；产业", example: "The car industry is growing." },
    { word: "influence", syllables: ["in","flu","ence"], phonetic: "/ˈɪnfluəns/", meaning: "v. & n. 影响", example: "Parents influence their children." },
    { word: "inform", syllables: ["in","form"], phonetic: "/ɪnˈfɔːrm/", meaning: "v. 通知；告知", example: "Please inform me of the result." },
    { word: "information", syllables: ["in","for","ma","tion"], phonetic: "/ˌɪnfərˈmeɪʃn/", meaning: "n. 信息", example: "Can you give me some information?" },
    { word: "ink", syllables: ["ink"], phonetic: "/ɪŋk/", meaning: "n. 墨水", example: "The pen has run out of ink." },
    { word: "inside", syllables: ["in","side"], phonetic: "/ˌɪnˈsaɪd/", meaning: "prep. & adv. 在里面", example: "The cat is inside the box." },
    { word: "insist", syllables: ["in","sist"], phonetic: "/ɪnˈsɪst/", meaning: "v. 坚持", example: "He insisted on going with us." },
    { word: "inspect", syllables: ["in","spect"], phonetic: "/ɪnˈspekt/", meaning: "v. 检查；视察", example: "They will inspect the school." },
    { word: "instead", syllables: ["in","stead"], phonetic: "/ɪnˈsted/", meaning: "adv. 代替；反而", example: "Let's walk instead of driving." },
    { word: "institute", syllables: ["in","sti","tute"], phonetic: "/ˈɪnstɪtuːt/", meaning: "n. 学院；研究所", example: "She works at a research institute." },
    { word: "instruction", syllables: ["in","struc","tion"], phonetic: "/ɪnˈstrʌkʃn/", meaning: "n. 指示；说明", example: "Read the instructions carefully." },
    { word: "instrument", syllables: ["in","stru","ment"], phonetic: "/ˈɪnstrəmənt/", meaning: "n. 乐器；工具", example: "Can you play an instrument?" },
    { word: "insurance", syllables: ["in","sur","ance"], phonetic: "/ɪnˈʃʊrəns/", meaning: "n. 保险", example: "Do you have health insurance?" },
    { word: "intend", syllables: ["in","tend"], phonetic: "/ɪnˈtend/", meaning: "v. 打算", example: "I intend to study abroad." },
    { word: "interest", syllables: ["in","ter","est"], phonetic: "/ˈɪntrəst/", meaning: "n. 兴趣 v. 使感兴趣", example: "I have an interest in music." },
    { word: "interested", syllables: ["in","ter","est","ed"], phonetic: "/ˈɪntrəstɪd/", meaning: "adj. 感兴趣的", example: "I am interested in science." },
    { word: "interesting", syllables: ["in","ter","est","ing"], phonetic: "/ˈɪntrəstɪŋ/", meaning: "adj. 有趣的", example: "The story is very interesting." },
    { word: "international", syllables: ["in","ter","na","tion","al"], phonetic: "/ˌɪntərˈnæʃnəl/", meaning: "adj. 国际的", example: "English is an international language." },
    { word: "Internet", syllables: ["In","ter","net"], phonetic: "/ˈɪntərnet/", meaning: "n. 互联网", example: "I often use the Internet." },
    { word: "interview", syllables: ["in","ter","view"], phonetic: "/ˈɪntərvjuː/", meaning: "n. & v. 采访；面试", example: "I have a job interview tomorrow." },
    { word: "into", syllables: ["in","to"], phonetic: "/ˈɪntuː/", meaning: "prep. 到……里面", example: "Come into the room." },
    { word: "introduce", syllables: ["in","tro","duce"], phonetic: "/ˌɪntrəˈduːs/", meaning: "v. 介绍", example: "Let me introduce myself." },
    { word: "introduction", syllables: ["in","tro","duc","tion"], phonetic: "/ˌɪntrəˈdʌkʃn/", meaning: "n. 介绍；引言", example: "Read the introduction first." },
    { word: "invent", syllables: ["in","vent"], phonetic: "/ɪnˈvent/", meaning: "v. 发明", example: "Who invented the telephone?" },
    { word: "invention", syllables: ["in","ven","tion"], phonetic: "/ɪnˈvenʃn/", meaning: "n. 发明", example: "The computer is a great invention." },
    { word: "invitation", syllables: ["in","vi","ta","tion"], phonetic: "/ˌɪnvɪˈteɪʃn/", meaning: "n. 邀请", example: "I received an invitation to the party." },
    { word: "invite", syllables: ["in","vite"], phonetic: "/ɪnˈvaɪt/", meaning: "v. 邀请", example: "I invited her to dinner." },
    { word: "iron", syllables: ["i","ron"], phonetic: "/ˈaɪərn/", meaning: "n. 铁；熨斗 v. 熨", example: "The gate is made of iron." },
    { word: "island", syllables: ["is","land"], phonetic: "/ˈaɪlənd/", meaning: "n. 岛屿", example: "Taiwan is a beautiful island." },
    { word: "it", syllables: ["it"], phonetic: "/ɪt/", meaning: "pron. 它", example: "It is a cat." },
    { word: "its", syllables: ["its"], phonetic: "/ɪts/", meaning: "pron. 它的", example: "The dog wagged its tail." },
    { word: "itself", syllables: ["it","self"], phonetic: "/ɪtˈself/", meaning: "pron. 它自己", example: "The door opened by itself." },
    { word: "jacket", syllables: ["jack","et"], phonetic: "/ˈdʒækɪt/", meaning: "n. 夹克；短上衣", example: "Put on your jacket." },
    { word: "jam", syllables: ["jam"], phonetic: "/dʒæm/", meaning: "n. 果酱", example: "I like strawberry jam." },
    { word: "January", syllables: ["Jan","u","ar","y"], phonetic: "/ˈdʒænjueri/", meaning: "n. 一月", example: "January is the first month." },
    { word: "Japan", syllables: ["Ja","pan"], phonetic: "/dʒəˈpæn/", meaning: "n. 日本", example: "Japan is near China." },
    { word: "Japanese", syllables: ["Jap","a","nese"], phonetic: "/ˌdʒæpəˈniːz/", meaning: "adj. & n. 日本的；日语；日本人", example: "She is learning Japanese." },
    { word: "jar", syllables: ["jar"], phonetic: "/dʒɑːr/", meaning: "n. 罐子；广口瓶", example: "There is a jar of honey." },
    { word: "jeans", syllables: ["jeans"], phonetic: "/dʒiːnz/", meaning: "n. 牛仔裤", example: "She is wearing jeans." },
    { word: "job", syllables: ["job"], phonetic: "/dʒɑːb/", meaning: "n. 工作", example: "He has a new job." },
    { word: "jog", syllables: ["jog"], phonetic: "/dʒɑːɡ/", meaning: "v. 慢跑", example: "I jog every morning." },
    { word: "jewel", syllables: ["jew","el"], phonetic: "/ˈdʒuːəl/", meaning: "n. 宝石", example: "The jewel was very expensive." }
  ],
  "第16组": [
    { word: "join", syllables: ["join"], phonetic: "/dʒɔɪn/", meaning: "v. 加入；参加", example: "Will you join us?" },
    { word: "joke", syllables: ["joke"], phonetic: "/dʒoʊk/", meaning: "n. 笑话 v. 开玩笑", example: "He told a funny joke." },
    { word: "journal", syllables: ["jour","nal"], phonetic: "/ˈdʒɜːrnl/", meaning: "n. 杂志；日志", example: "She writes in her journal every day." },
    { word: "journey", syllables: ["jour","ney"], phonetic: "/ˈdʒɜːrni/", meaning: "n. 旅行；旅程", example: "Have a good journey!" },
    { word: "joy", syllables: ["joy"], phonetic: "/dʒɔɪ/", meaning: "n. 快乐；喜悦", example: "Children are full of joy." },
    { word: "judge", syllables: ["judge"], phonetic: "/dʒʌdʒ/", meaning: "n. 法官 v. 判断", example: "Don't judge a book by its cover." },
    { word: "juice", syllables: ["juice"], phonetic: "/dʒuːs/", meaning: "n. 果汁", example: "I'd like a glass of orange juice." },
    { word: "July", syllables: ["Ju","ly"], phonetic: "/dʒuˈlaɪ/", meaning: "n. 七月", example: "July is a hot month." },
    { word: "jump", syllables: ["jump"], phonetic: "/dʒʌmp/", meaning: "v. 跳", example: "The cat jumped over the wall." },
    { word: "June", syllables: ["June"], phonetic: "/dʒuːn/", meaning: "n. 六月", example: "June is the sixth month." },
    { word: "junior", syllables: ["jun","ior"], phonetic: "/ˈdʒuːniər/", meaning: "adj. 初级的", example: "He is a junior high school student." },
    { word: "just", syllables: ["just"], phonetic: "/dʒʌst/", meaning: "adv. 刚才；只是；恰好", example: "I just finished my homework." },
    { word: "justice", syllables: ["jus","tice"], phonetic: "/ˈdʒʌstɪs/", meaning: "n. 公正；正义", example: "Everyone should have justice." },
    { word: "keep", syllables: ["keep"], phonetic: "/kiːp/", meaning: "v. 保持；保留", example: "Keep quiet, please." },
    { word: "key", syllables: ["key"], phonetic: "/kiː/", meaning: "n. 钥匙；关键", example: "Where is the key?" },
    { word: "keyboard", syllables: ["key","board"], phonetic: "/ˈkiːbɔːrd/", meaning: "n. 键盘", example: "He typed on the keyboard." },
    { word: "kid", syllables: ["kid"], phonetic: "/kɪd/", meaning: "n. 小孩", example: "The kids are playing outside." },
    { word: "kill", syllables: ["kill"], phonetic: "/kɪl/", meaning: "v. 杀死", example: "The cold weather killed the flowers." },
    { word: "kilo", syllables: ["ki","lo"], phonetic: "/ˈkiːloʊ/", meaning: "n. 千克；公斤", example: "I bought two kilos of apples." },
    { word: "kilometer", syllables: ["ki","lo","me","ter"], phonetic: "/ˈkɪləmiːtər/", meaning: "n. 千米；公里", example: "It is five kilometers away." },
    { word: "kind", syllables: ["kind"], phonetic: "/kaɪnd/", meaning: "adj. 善良的 n. 种类", example: "She is a kind person." },
    { word: "king", syllables: ["king"], phonetic: "/kɪŋ/", meaning: "n. 国王", example: "The king ruled the country." },
    { word: "kiss", syllables: ["kiss"], phonetic: "/kɪs/", meaning: "v. & n. 亲吻", example: "She kissed her mother goodbye." },
    { word: "kitchen", syllables: ["kitch","en"], phonetic: "/ˈkɪtʃɪn/", meaning: "n. 厨房", example: "Mom is cooking in the kitchen." },
    { word: "kite", syllables: ["kite"], phonetic: "/kaɪt/", meaning: "n. 风筝", example: "Let's fly a kite." },
    { word: "knee", syllables: ["knee"], phonetic: "/niː/", meaning: "n. 膝盖", example: "He fell and hurt his knee." },
    { word: "knife", syllables: ["knife"], phonetic: "/naɪf/", meaning: "n. 刀", example: "Please pass me the knife." },
    { word: "knock", syllables: ["knock"], phonetic: "/nɑːk/", meaning: "v. 敲；击", example: "Someone is knocking at the door." },
    { word: "know", syllables: ["know"], phonetic: "/noʊ/", meaning: "v. 知道；认识", example: "I know the answer." },
    { word: "knowledge", syllables: ["knowl","edge"], phonetic: "/ˈnɑːlɪdʒ/", meaning: "n. 知识", example: "Knowledge is power." },
    { word: "lab", syllables: ["lab"], phonetic: "/læb/", meaning: "n. 实验室", example: "We did experiments in the lab." },
    { word: "labor", syllables: ["la","bor"], phonetic: "/ˈleɪbər/", meaning: "n. 劳动", example: "Manual labor is hard work." },
    { word: "lack", syllables: ["lack"], phonetic: "/læk/", meaning: "v. & n. 缺乏", example: "He lacks confidence." },
    { word: "ladder", syllables: ["lad","der"], phonetic: "/ˈlædər/", meaning: "n. 梯子", example: "He climbed up the ladder." },
    { word: "lady", syllables: ["la","dy"], phonetic: "/ˈleɪdi/", meaning: "n. 女士；夫人", example: "The lady is very kind." },
    { word: "lake", syllables: ["lake"], phonetic: "/leɪk/", meaning: "n. 湖", example: "We went swimming in the lake." },
    { word: "lamb", syllables: ["lamb"], phonetic: "/læm/", meaning: "n. 小羊；羔羊", example: "The lamb is very cute." },
    { word: "lamp", syllables: ["lamp"], phonetic: "/læmp/", meaning: "n. 灯", example: "Turn on the lamp, please." },
    { word: "land", syllables: ["land"], phonetic: "/lænd/", meaning: "n. 陆地；土地 v. 着陆", example: "The plane landed safely." },
    { word: "language", syllables: ["lan","guage"], phonetic: "/ˈlæŋɡwɪdʒ/", meaning: "n. 语言", example: "English is a useful language." },
    { word: "large", syllables: ["large"], phonetic: "/lɑːrdʒ/", meaning: "adj. 大的", example: "They live in a large house." },
    { word: "last", syllables: ["last"], phonetic: "/læst/", meaning: "adj. 最后的 v. 持续", example: "What did you do last weekend?" },
    { word: "late", syllables: ["late"], phonetic: "/leɪt/", meaning: "adj. 迟的 adv. 晚地", example: "Don't be late for school." },
    { word: "lately", syllables: ["late","ly"], phonetic: "/ˈleɪtli/", meaning: "adv. 最近", example: "Have you seen him lately?" },
    { word: "later", syllables: ["la","ter"], phonetic: "/ˈleɪtər/", meaning: "adv. 后来", example: "See you later." },
    { word: "laugh", syllables: ["laugh"], phonetic: "/læf/", meaning: "v. & n. 笑", example: "We laughed at the joke." },
    { word: "law", syllables: ["law"], phonetic: "/lɔː/", meaning: "n. 法律", example: "Everyone must obey the law." },
    { word: "lay", syllables: ["lay"], phonetic: "/leɪ/", meaning: "v. 放置；下蛋", example: "She laid the book on the table." },
    { word: "lazy", syllables: ["la","zy"], phonetic: "/ˈleɪzi/", meaning: "adj. 懒惰的", example: "Don't be so lazy." },
    { word: "lead", syllables: ["lead"], phonetic: "/liːd/", meaning: "v. 领导；引导", example: "She led us to the classroom." }
  ],
  "第17组": [
    { word: "leader", syllables: ["lead","er"], phonetic: "/ˈliːdər/", meaning: "n. 领导者", example: "He is a good leader." },
    { word: "leaf", syllables: ["leaf"], phonetic: "/liːf/", meaning: "n. 叶子", example: "The leaf fell from the tree." },
    { word: "lean", syllables: ["lean"], phonetic: "/liːn/", meaning: "v. 倾斜；倚靠", example: "Don't lean against the wall." },
    { word: "learn", syllables: ["learn"], phonetic: "/lɜːrn/", meaning: "v. 学习", example: "I want to learn English." },
    { word: "least", syllables: ["least"], phonetic: "/liːst/", meaning: "adj. 最少的", example: "At least we tried." },
    { word: "leather", syllables: ["leath","er"], phonetic: "/ˈleðər/", meaning: "n. 皮革", example: "This is a leather jacket." },
    { word: "leave", syllables: ["leave"], phonetic: "/liːv/", meaning: "v. 离开；留下", example: "He left home at seven." },
    { word: "lecture", syllables: ["lec","ture"], phonetic: "/ˈlektʃər/", meaning: "n. 演讲；讲座", example: "We attended a lecture." },
    { word: "left", syllables: ["left"], phonetic: "/left/", meaning: "adj. 左边的 n. 左边", example: "Turn left at the corner." },
    { word: "leg", syllables: ["leg"], phonetic: "/leɡ/", meaning: "n. 腿", example: "He broke his leg." },
    { word: "lemon", syllables: ["lem","on"], phonetic: "/ˈlemən/", meaning: "n. 柠檬", example: "I like lemon tea." },
    { word: "lend", syllables: ["lend"], phonetic: "/lend/", meaning: "v. 借给", example: "Can you lend me your pen?" },
    { word: "less", syllables: ["less"], phonetic: "/les/", meaning: "adj. & adv. 更少(的)", example: "Eat less junk food." },
    { word: "lesson", syllables: ["les","son"], phonetic: "/ˈlesn/", meaning: "n. 课；教训", example: "We have six lessons today." },
    { word: "let", syllables: ["let"], phonetic: "/let/", meaning: "v. 让", example: "Let me help you." },
    { word: "letter", syllables: ["let","ter"], phonetic: "/ˈletər/", meaning: "n. 信；字母", example: "I received a letter from my friend." },
    { word: "level", syllables: ["lev","el"], phonetic: "/ˈlevl/", meaning: "n. 水平；等级", example: "The water level is rising." },
    { word: "liberty", syllables: ["lib","er","ty"], phonetic: "/ˈlɪbərti/", meaning: "n. 自由", example: "Everyone should have liberty." },
    { word: "library", syllables: ["li","brar","y"], phonetic: "/ˈlaɪbreri/", meaning: "n. 图书馆", example: "I often go to the library." },
    { word: "license", syllables: ["li","cense"], phonetic: "/ˈlaɪsns/", meaning: "n. 执照；许可证", example: "He got his driver's license." },
    { word: "lid", syllables: ["lid"], phonetic: "/lɪd/", meaning: "n. 盖子", example: "Put the lid on the box." },
    { word: "lie", syllables: ["lie"], phonetic: "/laɪ/", meaning: "v. 躺；说谎 n. 谎言", example: "Don't lie to me." },
    { word: "life", syllables: ["life"], phonetic: "/laɪf/", meaning: "n. 生活；生命", example: "Life is beautiful." },
    { word: "lift", syllables: ["lift"], phonetic: "/lɪft/", meaning: "v. 举起 n. 电梯", example: "Can you lift this box?" },
    { word: "light", syllables: ["light"], phonetic: "/laɪt/", meaning: "n. 光；灯 adj. 轻的", example: "Turn off the light, please." },
    { word: "like", syllables: ["like"], phonetic: "/laɪk/", meaning: "v. 喜欢 prep. 像", example: "I like playing basketball." },
    { word: "likely", syllables: ["like","ly"], phonetic: "/ˈlaɪkli/", meaning: "adj. & adv. 可能的(地)", example: "It is likely to rain." },
    { word: "limit", syllables: ["lim","it"], phonetic: "/ˈlɪmɪt/", meaning: "v. & n. 限制", example: "There is a speed limit here." },
    { word: "line", syllables: ["line"], phonetic: "/laɪn/", meaning: "n. 线；排 v. 排队", example: "Please stand in line." },
    { word: "link", syllables: ["link"], phonetic: "/lɪŋk/", meaning: "v. & n. 连接；联系", example: "The two events are linked." },
    { word: "lion", syllables: ["li","on"], phonetic: "/ˈlaɪən/", meaning: "n. 狮子", example: "The lion is the king of animals." },
    { word: "lip", syllables: ["lip"], phonetic: "/lɪp/", meaning: "n. 嘴唇", example: "She bit her lip." },
    { word: "list", syllables: ["list"], phonetic: "/lɪst/", meaning: "n. 名单；列表 v. 列出", example: "Make a list of things to buy." },
    { word: "listen", syllables: ["lis","ten"], phonetic: "/ˈlɪsn/", meaning: "v. 听", example: "Please listen carefully." },
    { word: "litter", syllables: ["lit","ter"], phonetic: "/ˈlɪtər/", meaning: "v. 乱扔 n. 垃圾", example: "Don't litter in the park." },
    { word: "little", syllables: ["lit","tle"], phonetic: "/ˈlɪtl/", meaning: "adj. 小的；少的", example: "I have a little dog." },
    { word: "live", syllables: ["live"], phonetic: "/lɪv/", meaning: "v. 居住；生活", example: "I live in Beijing." },
    { word: "lively", syllables: ["live","ly"], phonetic: "/ˈlaɪvli/", meaning: "adj. 活泼的；生动的", example: "She is a lively girl." },
    { word: "local", syllables: ["lo","cal"], phonetic: "/ˈloʊkl/", meaning: "adj. 当地的", example: "We eat at a local restaurant." },
    { word: "lock", syllables: ["lock"], phonetic: "/lɑːk/", meaning: "v. 锁 n. 锁", example: "Lock the door when you leave." },
    { word: "log", syllables: ["log"], phonetic: "/lɔːɡ/", meaning: "n. 原木；日志", example: "They sat on a log." },
    { word: "lonely", syllables: ["lone","ly"], phonetic: "/ˈloʊnli/", meaning: "adj. 孤独的", example: "She felt lonely in the new city." },
    { word: "long", syllables: ["long"], phonetic: "/lɔːŋ/", meaning: "adj. 长的 adv. 长久", example: "The river is very long." },
    { word: "look", syllables: ["look"], phonetic: "/lʊk/", meaning: "v. 看 n. 表情", example: "Look at the blackboard." },
    { word: "lose", syllables: ["lose"], phonetic: "/luːz/", meaning: "v. 丢失；输", example: "I lost my keys yesterday." },
    { word: "loss", syllables: ["loss"], phonetic: "/lɔːs/", meaning: "n. 损失", example: "It was a great loss." },
    { word: "lot", syllables: ["lot"], phonetic: "/lɑːt/", meaning: "n. 许多", example: "I have a lot of homework." },
    { word: "loud", syllables: ["loud"], phonetic: "/laʊd/", meaning: "adj. 大声的", example: "The music is too loud." },
    { word: "love", syllables: ["love"], phonetic: "/lʌv/", meaning: "v. & n. 爱", example: "I love my family." },
    { word: "lovely", syllables: ["love","ly"], phonetic: "/ˈlʌvli/", meaning: "adj. 可爱的", example: "What a lovely day!" }
  ],
  "第18组": [
    { word: "low", syllables: ["low"], phonetic: "/loʊ/", meaning: "adj. 低的", example: "The temperature is very low." },
    { word: "luck", syllables: ["luck"], phonetic: "/lʌk/", meaning: "n. 运气", example: "Good luck to you!" },
    { word: "lucky", syllables: ["luck","y"], phonetic: "/ˈlʌki/", meaning: "adj. 幸运的", example: "You are a lucky boy." },
    { word: "lunch", syllables: ["lunch"], phonetic: "/lʌntʃ/", meaning: "n. 午餐", example: "Let's have lunch together." },
    { word: "lung", syllables: ["lung"], phonetic: "/lʌŋ/", meaning: "n. 肺", example: "Smoking is bad for your lungs." },
    { word: "machine", syllables: ["ma","chine"], phonetic: "/məˈʃiːn/", meaning: "n. 机器", example: "This machine is very useful." },
    { word: "mad", syllables: ["mad"], phonetic: "/mæd/", meaning: "adj. 生气的；疯狂的", example: "She was mad at him." },
    { word: "madam", syllables: ["mad","am"], phonetic: "/ˈmædəm/", meaning: "n. 夫人；女士", example: "Can I help you, madam?" },
    { word: "magazine", syllables: ["mag","a","zine"], phonetic: "/ˌmæɡəˈziːn/", meaning: "n. 杂志", example: "I read a magazine every week." },
    { word: "magic", syllables: ["mag","ic"], phonetic: "/ˈmædʒɪk/", meaning: "n. & adj. 魔术(的)", example: "The magic show was amazing." },
    { word: "mail", syllables: ["mail"], phonetic: "/meɪl/", meaning: "n. 邮件 v. 邮寄", example: "I sent the letter by mail." },
    { word: "main", syllables: ["main"], phonetic: "/meɪn/", meaning: "adj. 主要的", example: "What is the main idea?" },
    { word: "major", syllables: ["ma","jor"], phonetic: "/ˈmeɪdʒər/", meaning: "adj. 主要的；重大的", example: "This is a major problem." },
    { word: "make", syllables: ["make"], phonetic: "/meɪk/", meaning: "v. 制作；使", example: "She made a cake." },
    { word: "male", syllables: ["male"], phonetic: "/meɪl/", meaning: "adj. & n. 男性的；男性", example: "A male deer stood there." },
    { word: "man", syllables: ["man"], phonetic: "/mæn/", meaning: "n. 男人", example: "The man is tall." },
    { word: "manage", syllables: ["man","age"], phonetic: "/ˈmænɪdʒ/", meaning: "v. 管理；设法", example: "She manages the company well." },
    { word: "manager", syllables: ["man","ag","er"], phonetic: "/ˈmænɪdʒər/", meaning: "n. 经理", example: "He is the manager of the hotel." },
    { word: "manner", syllables: ["man","ner"], phonetic: "/ˈmænər/", meaning: "n. 方式；礼貌(用复数)", example: "Mind your manners." },
    { word: "map", syllables: ["map"], phonetic: "/mæp/", meaning: "n. 地图", example: "Look at the map of China." },
    { word: "March", syllables: ["March"], phonetic: "/mɑːrtʃ/", meaning: "n. 三月", example: "March is the third month." },
    { word: "mark", syllables: ["mark"], phonetic: "/mɑːrk/", meaning: "n. 分数；标记 v. 标记", example: "He got good marks in the exam." },
    { word: "market", syllables: ["mar","ket"], phonetic: "/ˈmɑːrkɪt/", meaning: "n. 市场", example: "We went to the market to buy fruit." },
    { word: "marry", syllables: ["mar","ry"], phonetic: "/ˈmæri/", meaning: "v. 结婚", example: "They got married last year." },
    { word: "master", syllables: ["mas","ter"], phonetic: "/ˈmæstər/", meaning: "n. 大师；主人 v. 掌握", example: "He is a master of painting." },
    { word: "match", syllables: ["match"], phonetic: "/mætʃ/", meaning: "n. 比赛；火柴 v. 匹配", example: "We watched a football match." },
    { word: "material", syllables: ["ma","te","ri","al"], phonetic: "/məˈtɪriəl/", meaning: "n. 材料；原料", example: "What material is this made of?" },
    { word: "math", syllables: ["math"], phonetic: "/mæθ/", meaning: "n. 数学", example: "I am good at math." },
    { word: "matter", syllables: ["mat","ter"], phonetic: "/ˈmætər/", meaning: "n. 事情；问题 v. 要紧", example: "What's the matter with you?" },
    { word: "May", syllables: ["May"], phonetic: "/meɪ/", meaning: "n. 五月", example: "May is the fifth month." },
    { word: "maybe", syllables: ["may","be"], phonetic: "/ˈmeɪbi/", meaning: "adv. 也许；大概", example: "Maybe it will rain tomorrow." },
    { word: "mayor", syllables: ["may","or"], phonetic: "/ˈmeɪər/", meaning: "n. 市长", example: "The mayor visited our school." },
    { word: "meal", syllables: ["meal"], phonetic: "/miːl/", meaning: "n. 一餐", example: "We have three meals a day." },
    { word: "mean", syllables: ["mean"], phonetic: "/miːn/", meaning: "v. 意思是；意味着", example: "What does this word mean?" },
    { word: "meaning", syllables: ["mean","ing"], phonetic: "/ˈmiːnɪŋ/", meaning: "n. 意思；意义", example: "I don't know the meaning of this word." },
    { word: "measure", syllables: ["meas","ure"], phonetic: "/ˈmeʒər/", meaning: "v. 测量 n. 措施", example: "Please measure the room." },
    { word: "meat", syllables: ["meat"], phonetic: "/miːt/", meaning: "n. 肉", example: "I don't eat much meat." },
    { word: "medal", syllables: ["med","al"], phonetic: "/ˈmedl/", meaning: "n. 奖牌", example: "She won a gold medal." },
    { word: "medical", syllables: ["med","i","cal"], phonetic: "/ˈmedɪkl/", meaning: "adj. 医学的", example: "He needs medical help." },
    { word: "medicine", syllables: ["med","i","cine"], phonetic: "/ˈmedɪsn/", meaning: "n. 药；医学", example: "Take this medicine three times a day." },
    { word: "medium", syllables: ["me","di","um"], phonetic: "/ˈmiːdiəm/", meaning: "adj. 中等的 n. 媒介", example: "I'd like a medium pizza." },
    { word: "meet", syllables: ["meet"], phonetic: "/miːt/", meaning: "v. 遇见；开会", example: "Nice to meet you." },
    { word: "meeting", syllables: ["meet","ing"], phonetic: "/ˈmiːtɪŋ/", meaning: "n. 会议", example: "We have a meeting at ten." },
    { word: "member", syllables: ["mem","ber"], phonetic: "/ˈmembər/", meaning: "n. 成员", example: "She is a member of the club." },
    { word: "memory", syllables: ["mem","o","ry"], phonetic: "/ˈmeməri/", meaning: "n. 记忆；记忆力", example: "She has a good memory." },
    { word: "mend", syllables: ["mend"], phonetic: "/mend/", meaning: "v. 修理", example: "He mended the broken chair." },
    { word: "mention", syllables: ["men","tion"], phonetic: "/ˈmenʃn/", meaning: "v. 提到", example: "He didn't mention it to me." },
    { word: "menu", syllables: ["men","u"], phonetic: "/ˈmenjuː/", meaning: "n. 菜单", example: "May I see the menu, please?" },
    { word: "message", syllables: ["mes","sage"], phonetic: "/ˈmesɪdʒ/", meaning: "n. 消息；信息", example: "Can I leave a message?" },
    { word: "metal", syllables: ["met","al"], phonetic: "/ˈmetl/", meaning: "n. 金属", example: "Gold is a precious metal." }
  ],
  "第19组": [
    { word: "method", syllables: ["meth","od"], phonetic: "/ˈmeθəd/", meaning: "n. 方法", example: "This is a good method." },
    { word: "middle", syllables: ["mid","dle"], phonetic: "/ˈmɪdl/", meaning: "n. & adj. 中间(的)", example: "She sat in the middle." },
    { word: "might", syllables: ["might"], phonetic: "/maɪt/", meaning: "v. 可能；可以", example: "It might rain tomorrow." },
    { word: "mile", syllables: ["mile"], phonetic: "/maɪl/", meaning: "n. 英里", example: "We walked for miles." },
    { word: "milk", syllables: ["milk"], phonetic: "/mɪlk/", meaning: "n. 牛奶 v. 挤奶", example: "I drink milk every morning." },
    { word: "million", syllables: ["mil","lion"], phonetic: "/ˈmɪljən/", meaning: "num. 百万", example: "There are millions of people here." },
    { word: "mind", syllables: ["mind"], phonetic: "/maɪnd/", meaning: "n. 头脑 v. 介意", example: "Do you mind opening the window?" },
    { word: "mine", syllables: ["mine"], phonetic: "/maɪn/", meaning: "pron. 我的(名词性物主代词) n. 矿", example: "This book is mine." },
    { word: "mineral", syllables: ["min","er","al"], phonetic: "/ˈmɪnərəl/", meaning: "n. 矿物 adj. 矿物的", example: "Mineral water is good for health." },
    { word: "minute", syllables: ["min","ute"], phonetic: "/ˈmɪnɪt/", meaning: "n. 分钟", example: "Wait a minute, please." },
    { word: "mirror", syllables: ["mir","ror"], phonetic: "/ˈmɪrər/", meaning: "n. 镜子", example: "She looked in the mirror." },
    { word: "miss", syllables: ["miss"], phonetic: "/mɪs/", meaning: "v. 想念；错过", example: "I miss my old school." },
    { word: "mistake", syllables: ["mis","take"], phonetic: "/mɪˈsteɪk/", meaning: "n. 错误", example: "Everyone makes mistakes." },
    { word: "mix", syllables: ["mix"], phonetic: "/mɪks/", meaning: "v. 混合", example: "Mix the flour and water." },
    { word: "model", syllables: ["mod","el"], phonetic: "/ˈmɑːdl/", meaning: "n. 模型；模特", example: "She made a model plane." },
    { word: "modern", syllables: ["mod","ern"], phonetic: "/ˈmɑːdərn/", meaning: "adj. 现代的", example: "This is a modern city." },
    { word: "moment", syllables: ["mo","ment"], phonetic: "/ˈmoʊmənt/", meaning: "n. 片刻；时刻", example: "Wait a moment, please." },
    { word: "Monday", syllables: ["Mon","day"], phonetic: "/ˈmʌndeɪ/", meaning: "n. 星期一", example: "I have classes on Monday." },
    { word: "money", syllables: ["mon","ey"], phonetic: "/ˈmʌni/", meaning: "n. 钱", example: "I don't have enough money." },
    { word: "monitor", syllables: ["mon","i","tor"], phonetic: "/ˈmɑːnɪtər/", meaning: "n. 班长；显示器", example: "He is our class monitor." },
    { word: "monkey", syllables: ["mon","key"], phonetic: "/ˈmʌŋki/", meaning: "n. 猴子", example: "The monkey is eating a banana." },
    { word: "month", syllables: ["month"], phonetic: "/mʌnθ/", meaning: "n. 月", example: "There are twelve months in a year." },
    { word: "moon", syllables: ["moon"], phonetic: "/muːn/", meaning: "n. 月亮", example: "The moon is bright tonight." },
    { word: "moral", syllables: ["mor","al"], phonetic: "/ˈmɔːrəl/", meaning: "adj. 道德的 n. 寓意", example: "He is a moral person." },
    { word: "more", syllables: ["more"], phonetic: "/mɔːr/", meaning: "adj. & adv. 更多(的)", example: "I need more time." },
    { word: "morning", syllables: ["mor","ning"], phonetic: "/ˈmɔːrnɪŋ/", meaning: "n. 早晨", example: "Good morning, everyone!" },
    { word: "most", syllables: ["most"], phonetic: "/moʊst/", meaning: "adj. & adv. 最多(的)", example: "Most students like English." },
    { word: "mother", syllables: ["moth","er"], phonetic: "/ˈmʌðər/", meaning: "n. 母亲", example: "My mother is a teacher." },
    { word: "motion", syllables: ["mo","tion"], phonetic: "/ˈmoʊʃn/", meaning: "n. 运动；动作", example: "The motion was approved." },
    { word: "motor", syllables: ["mo","tor"], phonetic: "/ˈmoʊtər/", meaning: "n. 发动机；马达", example: "The motor is not working." },
    { word: "mountain", syllables: ["moun","tain"], phonetic: "/ˈmaʊntən/", meaning: "n. 山；山脉", example: "We climbed the mountain." },
    { word: "mouse", syllables: ["mouse"], phonetic: "/maʊs/", meaning: "n. 老鼠；鼠标", example: "A mouse ran across the floor." },
    { word: "mouth", syllables: ["mouth"], phonetic: "/maʊθ/", meaning: "n. 嘴", example: "Open your mouth, please." },
    { word: "move", syllables: ["move"], phonetic: "/muːv/", meaning: "v. 移动；搬家", example: "Please move your car." },
    { word: "movie", syllables: ["mov","ie"], phonetic: "/ˈmuːvi/", meaning: "n. 电影", example: "Let's go to the movies." },
    { word: "Mr", syllables: ["Mr"], phonetic: "/ˈmɪstər/", meaning: "n. 先生", example: "Mr Smith is our teacher." },
    { word: "Mrs", syllables: ["Mrs"], phonetic: "/ˈmɪsɪz/", meaning: "n. 夫人；太太", example: "Mrs Green is very kind." },
    { word: "Ms", syllables: ["Ms"], phonetic: "/mɪz/", meaning: "n. 女士", example: "Ms Wang teaches us English." },
    { word: "much", syllables: ["much"], phonetic: "/mʌtʃ/", meaning: "adj. & adv. 很多(的)", example: "Thank you very much." },
    { word: "mud", syllables: ["mud"], phonetic: "/mʌd/", meaning: "n. 泥", example: "The road was covered in mud." },
    { word: "museum", syllables: ["mu","se","um"], phonetic: "/mjuˈziːəm/", meaning: "n. 博物馆", example: "We visited the museum yesterday." },
    { word: "music", syllables: ["mu","sic"], phonetic: "/ˈmjuːzɪk/", meaning: "n. 音乐", example: "I love listening to music." },
    { word: "musical", syllables: ["mu","si","cal"], phonetic: "/ˈmjuːzɪkl/", meaning: "adj. 音乐的", example: "She has musical talent." },
    { word: "must", syllables: ["must"], phonetic: "/mʌst/", meaning: "v. 必须", example: "You must finish your homework." },
    { word: "my", syllables: ["my"], phonetic: "/maɪ/", meaning: "pron. 我的", example: "This is my book." },
    { word: "myself", syllables: ["my","self"], phonetic: "/maɪˈself/", meaning: "pron. 我自己", example: "I can do it myself." },
    { word: "mystery", syllables: ["mys","ter","y"], phonetic: "/ˈmɪstəri/", meaning: "n. 谜；神秘", example: "It is still a mystery." },
    { word: "nail", syllables: ["nail"], phonetic: "/neɪl/", meaning: "n. 钉子；指甲", example: "She painted her nails." },
    { word: "name", syllables: ["name"], phonetic: "/neɪm/", meaning: "n. 名字 v. 命名", example: "My name is Li Ming." },
    { word: "nation", syllables: ["na","tion"], phonetic: "/ˈneɪʃn/", meaning: "n. 国家；民族", example: "The whole nation celebrated." }
  ],
  "第20组": [
    { word: "national", syllables: ["na","tion","al"], phonetic: "/ˈnæʃnəl/", meaning: "adj. 国家的；民族的", example: "Today is National Day." },
    { word: "native", syllables: ["na","tive"], phonetic: "/ˈneɪtɪv/", meaning: "adj. 本地的；本族的", example: "She is a native speaker." },
    { word: "natural", syllables: ["nat","ur","al"], phonetic: "/ˈnætʃərəl/", meaning: "adj. 自然的", example: "It is a natural phenomenon." },
    { word: "nature", syllables: ["na","ture"], phonetic: "/ˈneɪtʃər/", meaning: "n. 自然；本性", example: "I love the beauty of nature." },
    { word: "near", syllables: ["near"], phonetic: "/nɪr/", meaning: "prep. & adv. 靠近", example: "The school is near my home." },
    { word: "nearly", syllables: ["near","ly"], phonetic: "/ˈnɪrli/", meaning: "adv. 几乎", example: "It is nearly twelve o'clock." },
    { word: "necessary", syllables: ["nec","es","sar","y"], phonetic: "/ˈnesəseri/", meaning: "adj. 必要的", example: "Sleep is necessary for health." },
    { word: "neck", syllables: ["neck"], phonetic: "/nek/", meaning: "n. 脖子", example: "She wore a scarf around her neck." },
    { word: "need", syllables: ["need"], phonetic: "/niːd/", meaning: "v. & n. 需要", example: "I need some help." },
    { word: "neighbor", syllables: ["neigh","bor"], phonetic: "/ˈneɪbər/", meaning: "n. 邻居", example: "Our neighbors are very friendly." },
    { word: "neither", syllables: ["nei","ther"], phonetic: "/ˈniːðər/", meaning: "adj. & pron. 两者都不", example: "Neither answer is correct." },
    { word: "nervous", syllables: ["nerv","ous"], phonetic: "/ˈnɜːrvəs/", meaning: "adj. 紧张的", example: "I felt nervous before the exam." },
    { word: "never", syllables: ["nev","er"], phonetic: "/ˈnevər/", meaning: "adv. 从不", example: "I never get up late." },
    { word: "new", syllables: ["new"], phonetic: "/njuː/", meaning: "adj. 新的", example: "I bought a new bike." },
    { word: "news", syllables: ["news"], phonetic: "/njuːz/", meaning: "n. 新闻；消息", example: "I heard the good news." },
    { word: "newspaper", syllables: ["news","pa","per"], phonetic: "/ˈnjuːzpeɪpər/", meaning: "n. 报纸", example: "He reads the newspaper every day." },
    { word: "next", syllables: ["next"], phonetic: "/nekst/", meaning: "adj. 下一个的 adv. 然后", example: "What will you do next?" },
    { word: "nice", syllables: ["nice"], phonetic: "/naɪs/", meaning: "adj. 好的；令人愉快的", example: "Nice to meet you!" },
    { word: "night", syllables: ["night"], phonetic: "/naɪt/", meaning: "n. 夜晚", example: "Good night, Mom." },
    { word: "nine", syllables: ["nine"], phonetic: "/naɪn/", meaning: "num. 九", example: "There are nine students in the group." },
    { word: "ninety", syllables: ["nine","ty"], phonetic: "/ˈnaɪnti/", meaning: "num. 九十", example: "My grandma is ninety years old." },
    { word: "ninth", syllables: ["ninth"], phonetic: "/naɪnθ/", meaning: "num. 第九", example: "September is the ninth month." },
    { word: "nobody", syllables: ["no","bod","y"], phonetic: "/ˈnoʊbɑːdi/", meaning: "pron. 没有人", example: "Nobody knows the answer." },
    { word: "nod", syllables: ["nod"], phonetic: "/nɑːd/", meaning: "v. 点头", example: "She nodded in agreement." },
    { word: "noise", syllables: ["noise"], phonetic: "/nɔɪz/", meaning: "n. 噪音", example: "Don't make so much noise." },
    { word: "noisy", syllables: ["nois","y"], phonetic: "/ˈnɔɪzi/", meaning: "adj. 吵闹的", example: "The classroom is very noisy." },
    { word: "none", syllables: ["none"], phonetic: "/nʌn/", meaning: "pron. 没有任何东西", example: "None of them came." },
    { word: "noodle", syllables: ["noo","dle"], phonetic: "/ˈnuːdl/", meaning: "n. 面条", example: "I like eating noodles." },
    { word: "noon", syllables: ["noon"], phonetic: "/nuːn/", meaning: "n. 中午", example: "We have lunch at noon." },
    { word: "nor", syllables: ["nor"], phonetic: "/nɔːr/", meaning: "conj. 也不", example: "Neither he nor I know the answer." },
    { word: "normal", syllables: ["nor","mal"], phonetic: "/ˈnɔːrml/", meaning: "adj. 正常的", example: "Everything is normal." },
    { word: "north", syllables: ["north"], phonetic: "/nɔːrθ/", meaning: "n. & adj. 北方(的)", example: "Beijing is in the north of China." },
    { word: "northern", syllables: ["north","ern"], phonetic: "/ˈnɔːrðərn/", meaning: "adj. 北方的", example: "It is cold in northern China." },
    { word: "nose", syllables: ["nose"], phonetic: "/noʊz/", meaning: "n. 鼻子", example: "The dog has a good nose." },
    { word: "note", syllables: ["note"], phonetic: "/noʊt/", meaning: "n. 笔记；便条", example: "She took notes in class." },
    { word: "notebook", syllables: ["note","book"], phonetic: "/ˈnoʊtbʊk/", meaning: "n. 笔记本", example: "Write this in your notebook." },
    { word: "nothing", syllables: ["noth","ing"], phonetic: "/ˈnʌθɪŋ/", meaning: "pron. 没有什么", example: "There is nothing in the box." },
    { word: "notice", syllables: ["no","tice"], phonetic: "/ˈnoʊtɪs/", meaning: "v. & n. 注意；通知", example: "Did you notice the difference?" },
    { word: "novel", syllables: ["nov","el"], phonetic: "/ˈnɑːvl/", meaning: "n. 小说", example: "She is reading a novel." },
    { word: "November", syllables: ["No","vem","ber"], phonetic: "/noʊˈvembər/", meaning: "n. 十一月", example: "November is the eleventh month." },
    { word: "now", syllables: ["now"], phonetic: "/naʊ/", meaning: "adv. 现在", example: "What time is it now?" },
    { word: "nowadays", syllables: ["now","a","days"], phonetic: "/ˈnaʊədeɪz/", meaning: "adv. 如今", example: "Nowadays people use smartphones a lot." },
    { word: "number", syllables: ["num","ber"], phonetic: "/ˈnʌmbər/", meaning: "n. 数字；号码", example: "What is your phone number?" },
    { word: "nurse", syllables: ["nurse"], phonetic: "/nɜːrs/", meaning: "n. 护士", example: "The nurse took care of the patient." },
    { word: "nut", syllables: ["nut"], phonetic: "/nʌt/", meaning: "n. 坚果", example: "Squirrels like to eat nuts." },
    { word: "object", syllables: ["ob","ject"], phonetic: "/ˈɑːbdʒekt/", meaning: "n. 物体 v. 反对", example: "What is that object?" },
    { word: "observe", syllables: ["ob","serve"], phonetic: "/əbˈzɜːrv/", meaning: "v. 观察", example: "We observed the stars at night." },
    { word: "ocean", syllables: ["o","cean"], phonetic: "/ˈoʊʃn/", meaning: "n. 海洋", example: "The Pacific is the largest ocean." },
    { word: "October", syllables: ["Oc","to","ber"], phonetic: "/ɑːkˈtoʊbər/", meaning: "n. 十月", example: "October is the tenth month." },
    { word: "of", syllables: ["of"], phonetic: "/ʌv/", meaning: "prep. ……的", example: "This is a map of China." }
  ],
  "第21组": [
    { word: "off", syllables: ["off"], phonetic: "/ɔːf/", meaning: "adv. 离开；关", example: "Turn off the light." },
    { word: "offer", syllables: ["of","fer"], phonetic: "/ˈɔːfər/", meaning: "v. & n. 提供；提议", example: "He offered to help me." },
    { word: "office", syllables: ["of","fice"], phonetic: "/ˈɔːfɪs/", meaning: "n. 办公室", example: "She works in an office." },
    { word: "officer", syllables: ["of","fi","cer"], phonetic: "/ˈɔːfɪsər/", meaning: "n. 军官；官员", example: "The police officer helped us." },
    { word: "often", syllables: ["of","ten"], phonetic: "/ˈɔːfn/", meaning: "adv. 经常", example: "I often read books." },
    { word: "oil", syllables: ["oil"], phonetic: "/ɔɪl/", meaning: "n. 油", example: "This car needs more oil." },
    { word: "OK", syllables: ["O","K"], phonetic: "/ˌoʊˈkeɪ/", meaning: "adj. & adv. 好的", example: "OK, let's go." },
    { word: "old", syllables: ["old"], phonetic: "/oʊld/", meaning: "adj. 老的；旧的", example: "How old are you?" },
    { word: "Olympics", syllables: ["O","lym","pics"], phonetic: "/oʊˈlɪmpɪks/", meaning: "n. 奥运会", example: "The Olympics are held every four years." },
    { word: "on", syllables: ["on"], phonetic: "/ɑːn/", meaning: "prep. 在……上面", example: "The book is on the desk." },
    { word: "once", syllables: ["once"], phonetic: "/wʌns/", meaning: "adv. 曾经；一次", example: "I once lived in Shanghai." },
    { word: "one", syllables: ["one"], phonetic: "/wʌn/", meaning: "num. 一 pron. 一个人", example: "One plus one is two." },
    { word: "oneself", syllables: ["one","self"], phonetic: "/wʌnˈself/", meaning: "pron. 自己", example: "One should believe in oneself." },
    { word: "onion", syllables: ["on","ion"], phonetic: "/ˈʌnjən/", meaning: "n. 洋葱", example: "She cut the onion." },
    { word: "online", syllables: ["on","line"], phonetic: "/ˌɑːnˈlaɪn/", meaning: "adj. & adv. 在线的(地)", example: "I often shop online." },
    { word: "only", syllables: ["on","ly"], phonetic: "/ˈoʊnli/", meaning: "adv. 只；仅仅", example: "I have only one pen." },
    { word: "open", syllables: ["o","pen"], phonetic: "/ˈoʊpən/", meaning: "v. 打开 adj. 开着的", example: "Please open the window." },
    { word: "opera", syllables: ["op","er","a"], phonetic: "/ˈɑːprə/", meaning: "n. 歌剧", example: "Beijing Opera is famous." },
    { word: "operate", syllables: ["op","er","ate"], phonetic: "/ˈɑːpəreɪt/", meaning: "v. 操作；动手术", example: "The doctor operated on him." },
    { word: "operation", syllables: ["op","er","a","tion"], phonetic: "/ˌɑːpəˈreɪʃn/", meaning: "n. 手术；操作", example: "The operation was successful." },
    { word: "opinion", syllables: ["o","pin","ion"], phonetic: "/əˈpɪnjən/", meaning: "n. 观点；看法", example: "What is your opinion?" },
    { word: "opposite", syllables: ["op","po","site"], phonetic: "/ˈɑːpəzət/", meaning: "adj. 对面的 prep. 在……对面", example: "The bank is opposite the school." },
    { word: "option", syllables: ["op","tion"], phonetic: "/ˈɑːpʃn/", meaning: "n. 选择", example: "You have three options." },
    { word: "orange", syllables: ["or","ange"], phonetic: "/ˈɔːrɪndʒ/", meaning: "n. 橙子 adj. 橙色的", example: "I'd like some orange juice." },
    { word: "order", syllables: ["or","der"], phonetic: "/ˈɔːrdər/", meaning: "n. 顺序 v. 命令；点餐", example: "I'd like to order some food." },
    { word: "ordinary", syllables: ["or","di","nar","y"], phonetic: "/ˈɔːrdneri/", meaning: "adj. 普通的", example: "He is an ordinary student." },
    { word: "organize", syllables: ["or","gan","ize"], phonetic: "/ˈɔːrɡənaɪz/", meaning: "v. 组织", example: "They organized a party." },
    { word: "other", syllables: ["oth","er"], phonetic: "/ˈʌðər/", meaning: "adj. & pron. 其他的", example: "Do you have any other questions?" },
    { word: "otherwise", syllables: ["oth","er","wise"], phonetic: "/ˈʌðərwaɪz/", meaning: "adv. 否则", example: "Hurry up, otherwise you'll be late." },
    { word: "ought", syllables: ["ought"], phonetic: "/ɔːt/", meaning: "v. 应该", example: "You ought to study harder." },
    { word: "our", syllables: ["our"], phonetic: "/ˈaʊər/", meaning: "pron. 我们的", example: "This is our classroom." },
    { word: "ours", syllables: ["ours"], phonetic: "/ˈaʊərz/", meaning: "pron. 我们的(名词性物主代词)", example: "The house is ours." },
    { word: "ourselves", syllables: ["our","selves"], phonetic: "/aʊərˈselvz/", meaning: "pron. 我们自己", example: "We did it ourselves." },
    { word: "out", syllables: ["out"], phonetic: "/aʊt/", meaning: "adv. 出外；在外", example: "Let's go out for a walk." },
    { word: "outcome", syllables: ["out","come"], phonetic: "/ˈaʊtkʌm/", meaning: "n. 结果", example: "What was the outcome?" },
    { word: "outdoor", syllables: ["out","door"], phonetic: "/ˈaʊtdɔːr/", meaning: "adj. 户外的", example: "I like outdoor activities." },
    { word: "outside", syllables: ["out","side"], phonetic: "/ˌaʊtˈsaɪd/", meaning: "adv. & prep. 在外面", example: "It is raining outside." },
    { word: "over", syllables: ["o","ver"], phonetic: "/ˈoʊvər/", meaning: "prep. 在……上方 adv. 结束", example: "The plane flew over the city." },
    { word: "overcome", syllables: ["o","ver","come"], phonetic: "/ˌoʊvərˈkʌm/", meaning: "v. 克服", example: "She overcame many difficulties." },
    { word: "overlook", syllables: ["o","ver","look"], phonetic: "/ˌoʊvərˈlʊk/", meaning: "v. 忽视；俯瞰", example: "Don't overlook this problem." },
    { word: "own", syllables: ["own"], phonetic: "/oʊn/", meaning: "adj. 自己的 v. 拥有", example: "I have my own room." },
    { word: "owner", syllables: ["own","er"], phonetic: "/ˈoʊnər/", meaning: "n. 主人；所有者", example: "Who is the owner of this dog?" },
    { word: "oxygen", syllables: ["ox","y","gen"], phonetic: "/ˈɑːksɪdʒən/", meaning: "n. 氧气", example: "We need oxygen to live." },
    { word: "occur", syllables: ["oc","cur"], phonetic: "/əˈkɜːr/", meaning: "v. 发生", example: "The accident occurred at night." },
    { word: "offend", syllables: ["of","fend"], phonetic: "/əˈfend/", meaning: "v. 冒犯；得罪", example: "I didn't mean to offend you." },
    { word: "official", syllables: ["of","fi","cial"], phonetic: "/əˈfɪʃl/", meaning: "adj. 官方的 n. 官员", example: "This is an official document." },
    { word: "Olympic", syllables: ["O","lym","pic"], phonetic: "/oʊˈlɪmpɪk/", meaning: "adj. 奥林匹克的", example: "The Olympic Games are exciting." },
    { word: "opportunity", syllables: ["op","por","tu","ni","ty"], phonetic: "/ˌɑːpərˈtuːnəti/", meaning: "n. 机会", example: "This is a good opportunity." },
    { word: "oppose", syllables: ["op","pose"], phonetic: "/əˈpoʊz/", meaning: "v. 反对", example: "Many people oppose the plan." },
    { word: "outgoing", syllables: ["out","go","ing"], phonetic: "/ˈaʊtɡoʊɪŋ/", meaning: "adj. 外向的", example: "She is an outgoing girl." }
  ]
};
