const WORDS_ZK_PZ = {
  "第1组": [
    { word: "person", syllables: ["per","son"], phonetic: "/ˈpɜːrsn/", meaning: "n. 人", example: "She is a kind person." },
    { word: "personal", syllables: ["per","son","al"], phonetic: "/ˈpɜːrsənl/", meaning: "adj. 个人的；私人的", example: "This is my personal opinion." },
    { word: "pet", syllables: ["pet"], phonetic: "/pet/", meaning: "n. 宠物", example: "I have a pet dog." },
    { word: "phone (=telephone)", syllables: ["phone (=telephone)"], phonetic: "", meaning: "n. 电话，电话机; v. 打电话", example: "The word 'phone (=telephone)' means n. 电话." },
    { word: "photo (=photograph)", syllables: ["photo (=photograph)"], phonetic: "", meaning: "n. 照片", example: "The word 'photo (=photograph)' means n. 照片." },
    { word: "physical", syllables: ["physical"], phonetic: "", meaning: "adj. 身体的；物理的", example: "The word 'physical' means adj. 身体的." },
    { word: "physics", syllables: ["physics"], phonetic: "", meaning: "n. 物理(学)", example: "The word 'physics' means n. 物理(学)." },
    { word: "piano", syllables: ["pi","an","o"], phonetic: "/piˈænoʊ/", meaning: "n. 钢琴", example: "She plays the piano well." },
    { word: "pick", syllables: ["pick"], phonetic: "/pɪk/", meaning: "v. 拾起；摘；采集；挑选", example: "Pick up the paper, please." },
    { word: "picnic", syllables: ["pic","nic"], phonetic: "/ˈpɪknɪk/", meaning: "n. 野餐", example: "Let's have a picnic." },
    { word: "picture", syllables: ["pic","ture"], phonetic: "/ˈpɪktʃər/", meaning: "n. 图片，画片，照片；影片", example: "Draw a picture of your house." },
    { word: "piece", syllables: ["piece"], phonetic: "/piːs/", meaning: "n. 一块(片，张，件，段……)；碎片；部件", example: "Would you like a piece of cake?" },
    { word: "pig", syllables: ["pig"], phonetic: "/pɪɡ/", meaning: "n. 猪", example: "The pig is pink." },
    { word: "pill", syllables: ["pill"], phonetic: "", meaning: "n. 药丸", example: "The word 'pill' means n. 药丸." },
    { word: "pilot", syllables: ["pi","lot"], phonetic: "/ˈpaɪlət/", meaning: "n. 飞行员", example: "The pilot flies the plane." },
    { word: "pin", syllables: ["pin"], phonetic: "/pɪn/", meaning: "v. 用针别; n. 针", example: "Use a pin to hold it." },
    { word: "pineapple", syllables: ["pineapple"], phonetic: "", meaning: "n. 菠萝", example: "The word 'pineapple' means n. 菠萝." },
    { word: "pink", syllables: ["pink"], phonetic: "/pɪŋk/", meaning: "adj. 粉红色的; n. 粉红", example: "She wore a pink dress." },
    { word: "pioneer", syllables: ["pi","o","neer"], phonetic: "/ˌpaɪəˈnɪr/", meaning: "n. 先锋；开拓者", example: "He is a young pioneer." },
    { word: "pity", syllables: ["pi","ty"], phonetic: "/ˈpɪti/", meaning: "n. 怜悯；同情；可惜", example: "What a pity!" },
    { word: "pizza", syllables: ["pizza"], phonetic: "", meaning: "n. 比萨饼", example: "The word 'pizza' means n. 比萨饼." },
    { word: "place", syllables: ["place"], phonetic: "/pleɪs/", meaning: "n. 地方；处所; v. 放置", example: "This is a nice place." },
    { word: "plan", syllables: ["plan"], phonetic: "/plæn/", meaning: "n. & v. 计划，打算", example: "We plan to go camping." },
    { word: "plane", syllables: ["plane"], phonetic: "/pleɪn/", meaning: "n. 飞机", example: "The plane is taking off." },
    { word: "planet", syllables: ["plan","et"], phonetic: "/ˈplænɪt/", meaning: "n. 行星", example: "Earth is a planet." },
    { word: "plant", syllables: ["plant"], phonetic: "/plænt/", meaning: "v. 种植；播种; n. 植物", example: "They plant trees in spring." },
    { word: "plastic", syllables: ["plas","tic"], phonetic: "/ˈplæstɪk/", meaning: "adj. 塑料的", example: "Don't use too much plastic." },
    { word: "plate", syllables: ["plate"], phonetic: "/pleɪt/", meaning: "n. 盘子；碟子；板；牌", example: "Put the food on the plate." },
    { word: "platform", syllables: ["platform"], phonetic: "", meaning: "n. 讲台；站台", example: "The word 'platform' means n. 讲台." },
    { word: "play", syllables: ["play"], phonetic: "/pleɪ/", meaning: "v. 玩；打(球)；演奏；扮演；播放; n. 玩耍；戏剧；剧本", example: "Let's play basketball." },
    { word: "player", syllables: ["play","er"], phonetic: "/ˈpleɪər/", meaning: "n. 运动员", example: "He is a good soccer player." },
    { word: "playground", syllables: ["play","ground"], phonetic: "/ˈpleɪɡraʊnd/", meaning: "n. 操场，运动场", example: "The children are on the playground." },
    { word: "pleasant", syllables: ["pleas","ant"], phonetic: "/ˈpleznt/", meaning: "adj. 令人愉快的，舒适的", example: "We had a pleasant trip." },
    { word: "please", syllables: ["please"], phonetic: "/pliːz/", meaning: "v. 请", example: "Please sit down." },
    { word: "pleased", syllables: ["pleased"], phonetic: "", meaning: "adj. 感到高兴的；感到满意的", example: "The word 'pleased' means adj. 感到高兴的." },
    { word: "pleasure", syllables: ["pleas","ure"], phonetic: "/ˈpleʒər/", meaning: "n. 高兴；愉快", example: "It's a pleasure to meet you." },
    { word: "plenty", syllables: ["plen","ty"], phonetic: "/ˈplenti/", meaning: "n. 丰富，充足；大量", example: "We have plenty of time." },
    { word: "plus", syllables: ["plus"], phonetic: "", meaning: "prep. 加，加上", example: "The word 'plus' means prep. 加." },
    { word: "P.M. (p.m.) 下午", syllables: ["P.M. (p.m.) 下午"], phonetic: "", meaning: "", example: "The word 'P.M. (p.m.) 下午' means ." },
    { word: "pocket", syllables: ["pock","et"], phonetic: "/ˈpɒkɪt/", meaning: "n. (衣服的)口袋", example: "Put it in your pocket." },
    { word: "poem", syllables: ["po","em"], phonetic: "/ˈpoʊəm/", meaning: "n. 诗", example: "She wrote a beautiful poem." },
    { word: "point", syllables: ["point"], phonetic: "/pɔɪnt/", meaning: "v. 指；指向; n. 点；分数；小数点", example: "He pointed at the map." },
    { word: "pole", syllables: ["pole"], phonetic: "", meaning: "n. 杆；极", example: "The word 'pole' means n. 杆." },
    { word: "policeman (复数 policemen)", syllables: ["policeman (复数 policemen)"], phonetic: "", meaning: "n. 警察", example: "The word 'policeman (复数 policemen)' means n. 警察." },
    { word: "polite", syllables: ["po","lite"], phonetic: "/pəˈlaɪt/", meaning: "adj. 有礼貌的", example: "He is a polite boy." },
    { word: "politely", syllables: ["politely"], phonetic: "", meaning: "adv. 有礼貌地", example: "The word 'politely' means adv. 有礼貌地." },
    { word: "politics", syllables: ["politics"], phonetic: "", meaning: "n. 政治", example: "The word 'politics' means n. 政治." },
    { word: "pollute", syllables: ["pollute"], phonetic: "", meaning: "v. 污染，弄脏", example: "The word 'pollute' means v. 污染." },
    { word: "pollution", syllables: ["pol","lu","tion"], phonetic: "/pəˈluːʃn/", meaning: "n. 污染", example: "Air pollution is a big problem." },
    { word: "pool", syllables: ["pool"], phonetic: "/puːl/", meaning: "n. 水塘，水池", example: "Let's swim in the pool." }
  ],
  "第2组": [
    { word: "poor", syllables: ["poor"], phonetic: "/pʊr/", meaning: "adj. 贫穷的；可怜的；不好的", example: "The poor boy needs help." },
    { word: "popular (=pop)", syllables: ["popular (=pop)"], phonetic: "", meaning: "adj. 流行的；大众的；受欢迎的", example: "The word 'popular (=pop)' means adj. 流行的." },
    { word: "population", syllables: ["pop","u","la","tion"], phonetic: "/ˌpɒpjuˈleɪʃn/", meaning: "n. 人口，人数", example: "China has a large population." },
    { word: "pork", syllables: ["pork"], phonetic: "/pɔːrk/", meaning: "n. 猪肉", example: "I like pork dumplings." },
    { word: "possible", syllables: ["pos","si","ble"], phonetic: "/ˈpɒsəbl/", meaning: "adj. 可能的，也许的", example: "Is it possible to finish today?" },
    { word: "possibly", syllables: ["possibly"], phonetic: "", meaning: "adv. 可能地，也许", example: "The word 'possibly' means adv. 可能地." },
    { word: "post", syllables: ["post"], phonetic: "/poʊst/", meaning: "n. 邮政，邮寄，邮件; v. 投寄； 邮寄", example: "I'll post the letter." },
    { word: "postcard", syllables: ["post","card"], phonetic: "/ˈpoʊstkɑːrd/", meaning: "n. 明信片", example: "She sent me a postcard." },
    { word: "poster", syllables: ["poster"], phonetic: "", meaning: "n. 海报", example: "The word 'poster' means n. 海报." },
    { word: "postman (复数 postmen)", syllables: ["postman (复数 postmen)"], phonetic: "", meaning: "n. 邮递员", example: "The word 'postman (复数 postmen)' means n. 邮递员." },
    { word: "pot", syllables: ["pot"], phonetic: "", meaning: "n. 锅；壶；罐", example: "The word 'pot' means n. 锅." },
    { word: "potato", syllables: ["po","ta","to"], phonetic: "/pəˈteɪtoʊ/", meaning: "n. 土豆，马铃薯", example: "Would you like some potatoes?" },
    { word: "pound", syllables: ["pound"], phonetic: "/paʊnd/", meaning: "n. 磅(重量单位)；英镑", example: "It costs five pounds." },
    { word: "power", syllables: ["power"], phonetic: "", meaning: "n. 电源；能源；动力；电力", example: "The word 'power' means n. 电源." },
    { word: "powerful", syllables: ["powerful"], phonetic: "", meaning: "adj. 强大的", example: "The word 'powerful' means adj. 强大的." },
    { word: "practice", syllables: ["prac","tice"], phonetic: "/ˈpræktɪs/", meaning: "n. 练习；实践; v. (英 practise) 练习；实践", example: "Practice makes perfect." },
    { word: "praise", syllables: ["praise"], phonetic: "/preɪz/", meaning: "n. & v. 赞扬；表扬", example: "The teacher praised him." },
    { word: "precious", syllables: ["precious"], phonetic: "", meaning: "adj. 宝贵的， 珍贵的", example: "The word 'precious' means adj. 宝贵的." },
    { word: "predict", syllables: ["pre","dict"], phonetic: "/prɪˈdɪkt/", meaning: "v. 预言；预料", example: "It's hard to predict the weather." },
    { word: "prefer", syllables: ["pre","fer"], phonetic: "/prɪˈfɜːr/", meaning: "v. 宁愿(选择)，更喜欢", example: "I prefer tea to coffee." },
    { word: "prepare", syllables: ["pre","pare"], phonetic: "/prɪˈper/", meaning: "v. 准备， 预备", example: "We need to prepare for the exam." },
    { word: "present", syllables: ["pres","ent"], phonetic: "/ˈpreznt/", meaning: "n. 礼物；赠品；现在; adj. 出现的，出席的", example: "I got a birthday present." },
    { word: "president", syllables: ["pres","i","dent"], phonetic: "/ˈprezɪdənt/", meaning: "n. 总统；主席", example: "He is the class president." },
    { word: "press", syllables: ["press"], phonetic: "/pres/", meaning: "v. 压，按", example: "Press the button to start." },
    { word: "pretend", syllables: ["pretend"], phonetic: "", meaning: "v. 假装，装作", example: "The word 'pretend' means v. 假装." },
    { word: "pretty", syllables: ["pret","ty"], phonetic: "/ˈprɪti/", meaning: "adj. 漂亮的", example: "She looks pretty today." },
    { word: "prevent", syllables: ["pre","vent"], phonetic: "/prɪˈvent/", meaning: "v. 防止，预防；阻止，阻挡", example: "Wash hands to prevent illness." },
    { word: "price", syllables: ["price"], phonetic: "/praɪs/", meaning: "n. 价格", example: "The price is too high." },
    { word: "primary", syllables: ["pri","ma","ry"], phonetic: "/ˈpraɪmeri/", meaning: "adj. 初等的；初级的", example: "I went to primary school here." },
    { word: "print", syllables: ["print"], phonetic: "/prɪnt/", meaning: "v. 打印，印刷", example: "Can you print this document?" },
    { word: "prison", syllables: ["prison"], phonetic: "", meaning: "n. 监狱", example: "The word 'prison' means n. 监狱." },
    { word: "private", syllables: ["pri","vate"], phonetic: "/ˈpraɪvət/", meaning: "adj. 私人的；私有的", example: "This is a private matter." },
    { word: "prize", syllables: ["prize"], phonetic: "/praɪz/", meaning: "n. 奖赏，奖品", example: "She won first prize." },
    { word: "probably", syllables: ["prob","a","bly"], phonetic: "/ˈprɒbəbli/", meaning: "adv. 很可能地，大概，或许", example: "It will probably rain." },
    { word: "problem", syllables: ["prob","lem"], phonetic: "/ˈprɒbləm/", meaning: "n. 问题，难题，习题", example: "Can you solve this problem?" },
    { word: "process", syllables: ["process"], phonetic: "", meaning: "v. 处理；加工; n. 过程", example: "The word 'process' means v. 处理." },
    { word: "produce", syllables: ["pro","duce"], phonetic: "/prəˈdjuːs/", meaning: "v. 生产；产生；制造", example: "The factory produces cars." },
    { word: "product", syllables: ["prod","uct"], phonetic: "/ˈprɒdʌkt/", meaning: "n. 产品", example: "This product is made in China." },
    { word: "professional", syllables: ["professional"], phonetic: "", meaning: "adj. 职业的；专业的", example: "The word 'professional' means adj. 职业的." },
    { word: "programme (美 program)", syllables: ["programme (美 program)"], phonetic: "", meaning: "n. 节目；项目", example: "The word 'programme (美 program)' means n. 节目." },
    { word: "progress", syllables: ["prog","ress"], phonetic: "/ˈprɒɡres/", meaning: "n. 进步，进展", example: "She has made good progress." },
    { word: "project", syllables: ["proj","ect"], phonetic: "/ˈprɒdʒekt/", meaning: "n. 工程；课程；作业；项目；规划", example: "We're working on a science project." },
    { word: "promise", syllables: ["prom","ise"], phonetic: "/ˈprɒmɪs/", meaning: "n. & v. 答应；承诺", example: "I promise to come on time." },
    { word: "pronounce", syllables: ["pro","nounce"], phonetic: "/prəˈnaʊns/", meaning: "v. 发音", example: "How do you pronounce this word?" },
    { word: "properly", syllables: ["properly"], phonetic: "", meaning: "adv. 恰当地，合适地", example: "The word 'properly' means adv. 恰当地." },
    { word: "protect", syllables: ["pro","tect"], phonetic: "/prəˈtekt/", meaning: "v. 保护", example: "We should protect the earth." },
    { word: "proud", syllables: ["proud"], phonetic: "/praʊd/", meaning: "adj. 自豪的；骄傲的", example: "I'm proud of you." },
    { word: "prove", syllables: ["prove"], phonetic: "/pruːv/", meaning: "v. 证明", example: "You need to prove it." },
    { word: "proverb", syllables: ["proverb"], phonetic: "", meaning: "n. 谚语，格言", example: "The word 'proverb' means n. 谚语." },
    { word: "provide", syllables: ["pro","vide"], phonetic: "/prəˈvaɪd/", meaning: "v. 提供", example: "They provide free food." }
  ],
  "第3组": [
    { word: "public", syllables: ["pub","lic"], phonetic: "/ˈpʌblɪk/", meaning: "adj. 公共的，公众的; n. 公众", example: "Don't smoke in public places." },
    { word: "publish", syllables: ["publish"], phonetic: "", meaning: "v. 出版", example: "The word 'publish' means v. 出版." },
    { word: "pull", syllables: ["pull"], phonetic: "/pʊl/", meaning: "v. 拉；拖；拔", example: "Pull the door open." },
    { word: "purpose", syllables: ["pur","pose"], phonetic: "/ˈpɜːrpəs/", meaning: "n. 目的；用途", example: "What's the purpose of the meeting?" },
    { word: "push", syllables: ["push"], phonetic: "/pʊʃ/", meaning: "n. & v. 推", example: "Push the cart, please." },
    { word: "put (put，put)", syllables: ["put (put，put)"], phonetic: "", meaning: "v. 放；摆", example: "The word 'put (put，put)' means v. 放." },
    { word: "quality", syllables: ["quality"], phonetic: "", meaning: "n. 质量", example: "The word 'quality' means n. 质量." },
    { word: "quarter", syllables: ["quar","ter"], phonetic: "/ˈkwɔːrtər/", meaning: "n. 四分之一；一刻钟", example: "A quarter of the students are girls." },
    { word: "queen", syllables: ["queen"], phonetic: "/kwiːn/", meaning: "n. 皇后，女王", example: "The queen lives in the palace." },
    { word: "question", syllables: ["ques","tion"], phonetic: "/ˈkwestʃən/", meaning: "n. 问题", example: "Can I ask a question?" },
    { word: "quick", syllables: ["quick"], phonetic: "/kwɪk/", meaning: "adj. 快的；敏捷的；迅速的", example: "Be quick! We're late." },
    { word: "quickly", syllables: ["quickly"], phonetic: "", meaning: "adv. 快地；迅速地", example: "The word 'quickly' means adv. 快地." },
    { word: "quiet", syllables: ["qui","et"], phonetic: "/ˈkwaɪət/", meaning: "adj. 安静的", example: "Please keep quiet." },
    { word: "quietly", syllables: ["quietly"], phonetic: "", meaning: "adv. 安静地", example: "The word 'quietly' means adv. 安静地." },
    { word: "quite", syllables: ["quite"], phonetic: "/kwaɪt/", meaning: "adv. 完全；十分；相当", example: "It's quite cold today." },
    { word: "quiz", syllables: ["quiz"], phonetic: "", meaning: "n. 测验", example: "The word 'quiz' means n. 测验." },
    { word: "race", syllables: ["race"], phonetic: "/reɪs/", meaning: "v. 比赛；赛跑; n. 赛跑", example: "He won the race." },
    { word: "radio", syllables: ["ra","di","o"], phonetic: "/ˈreɪdioʊ/", meaning: "n. 无线电；收音机", example: "I listen to the radio every day." },
    { word: "railway", syllables: ["railway"], phonetic: "", meaning: "n. 铁路；铁道", example: "The word 'railway' means n. 铁路." },
    { word: "rain", syllables: ["rain"], phonetic: "/reɪn/", meaning: "n. 雨；雨水; v. 下雨", example: "It's raining outside." },
    { word: "rainy", syllables: ["rain","y"], phonetic: "/ˈreɪni/", meaning: "adj. 有雨的；多雨的", example: "It's a rainy day." },
    { word: "raise", syllables: ["raise"], phonetic: "/reɪz/", meaning: "v. 举起，使升高；饲养，抚养；筹钱", example: "Raise your hand." },
    { word: "rarely", syllables: ["rarely"], phonetic: "", meaning: "adv. 罕有；很少；不常", example: "The word 'rarely' means adv. 罕有." },
    { word: "rather", syllables: ["rather"], phonetic: "", meaning: "adv. 相当，颇；宁可", example: "The word 'rather' means adv. 相当." },
    { word: "reach", syllables: ["reach"], phonetic: "/riːtʃ/", meaning: "v. 到达", example: "Can you reach the top shelf?" },
    { word: "read (read, read)", syllables: ["read (read, read)"], phonetic: "", meaning: "v. 读；朗读", example: "The word 'read (read, read)' means v. 读." },
    { word: "ready", syllables: ["read","y"], phonetic: "/ˈredi/", meaning: "adj. 准备好的；乐于", example: "Are you ready?" },
    { word: "real", syllables: ["real"], phonetic: "/riːl/", meaning: "adj. 真实的，确实的；真正的", example: "Is this real gold?" },
    { word: "realize", syllables: ["re","al","ize"], phonetic: "/ˈriːəlaɪz/", meaning: "v. 认识到；实现", example: "I realized my mistake." },
    { word: "really", syllables: ["real","ly"], phonetic: "/ˈriːəli/", meaning: "adv. 真正地；确实", example: "Do you really like it?" },
    { word: "reason", syllables: ["rea","son"], phonetic: "/ˈriːzn/", meaning: "n. 理由；原因", example: "What's the reason?" },
    { word: "rebuild", syllables: ["rebuild"], phonetic: "", meaning: "v. 重建", example: "The word 'rebuild' means v. 重建." },
    { word: "receive", syllables: ["re","ceive"], phonetic: "/rɪˈsiːv/", meaning: "v. 收到，得到", example: "I received a letter today." },
    { word: "recent", syllables: ["recent"], phonetic: "", meaning: "adj. 近来的，最近的", example: "The word 'recent' means adj. 近来的." },
    { word: "recently", syllables: ["recently"], phonetic: "", meaning: "adv. 最近，近来", example: "The word 'recently' means adv. 最近." },
    { word: "recognize", syllables: ["recognize"], phonetic: "", meaning: "v. 辨认出；认识", example: "The word 'recognize' means v. 辨认出." },
    { word: "record", syllables: ["re","cord"], phonetic: "/ˈrekɔːrd/", meaning: "n. 记录； 唱片; v. 录制，录音；记录", example: "He broke the world record." },
    { word: "recycle", syllables: ["recycle"], phonetic: "", meaning: "v. 回收利用； 使再循环", example: "The word 'recycle' means v. 回收利用." },
    { word: "red", syllables: ["red"], phonetic: "/red/", meaning: "adj. 红色的; n. 红色", example: "She has red hair." },
    { word: "reduce", syllables: ["re","duce"], phonetic: "/rɪˈdjuːs/", meaning: "v. 减少；缩减", example: "We should reduce waste." },
    { word: "reference", syllables: ["reference"], phonetic: "", meaning: "n. 参考", example: "The word 'reference' means n. 参考." },
    { word: "refuse", syllables: ["re","fuse"], phonetic: "/rɪˈfjuːz/", meaning: "v. 拒绝；不愿", example: "He refused to go." },
    { word: "regular", syllables: ["regular"], phonetic: "", meaning: "adj. 规则的，经常", example: "The word 'regular' means adj. 规则的." },
    { word: "relationship", syllables: ["relationship"], phonetic: "", meaning: "n. 关系", example: "The word 'relationship' means n. 关系." },
    { word: "relative", syllables: ["relative"], phonetic: "", meaning: "n. 亲属", example: "The word 'relative' means n. 亲属." },
    { word: "relax", syllables: ["re","lax"], phonetic: "/rɪˈlæks/", meaning: "v. (使)放松，轻松", example: "Let's relax after work." },
    { word: "release", syllables: ["release"], phonetic: "", meaning: "n. & v. 释放，排放；发行，发表", example: "The word 'release' means n. & v. 释放." },
    { word: "rely", syllables: ["rely"], phonetic: "", meaning: "v. 依靠", example: "The word 'rely' means v. 依靠." },
    { word: "remember", syllables: ["re","mem","ber"], phonetic: "/rɪˈmembər/", meaning: "v. 记得；想起", example: "Remember to lock the door." },
    { word: "remind", syllables: ["remind"], phonetic: "", meaning: "v. 提醒", example: "The word 'remind' means v. 提醒." }
  ],
  "第4组": [
    { word: "repair", syllables: ["re","pair"], phonetic: "/rɪˈper/", meaning: "n. & v. 修理", example: "I need to repair my bike." },
    { word: "repeat", syllables: ["re","peat"], phonetic: "/rɪˈpiːt/", meaning: "v. 重复", example: "Please repeat the sentence." },
    { word: "reply", syllables: ["re","ply"], phonetic: "/rɪˈplaɪ/", meaning: "n. & v. 回答，答复", example: "He didn't reply to my email." },
    { word: "report", syllables: ["re","port"], phonetic: "/rɪˈpɔːrt/", meaning: "n. 报道；报告；成绩单; v. 报告；汇报", example: "Write a report about the trip." },
    { word: "reporter", syllables: ["reporter"], phonetic: "", meaning: "n. 记者", example: "The word 'reporter' means n. 记者." },
    { word: "republic", syllables: ["republic"], phonetic: "", meaning: "n. 共和国", example: "The word 'republic' means n. 共和国." },
    { word: "require", syllables: ["re","quire"], phonetic: "/rɪˈkwaɪər/", meaning: "v. 需求；要求", example: "The job requires English skills." },
    { word: "research", syllables: ["re","search"], phonetic: "/rɪˈsɜːrtʃ/", meaning: "n. 研究；调查", example: "She is doing research on animals." },
    { word: "resource", syllables: ["resource"], phonetic: "", meaning: "n. 资源", example: "The word 'resource' means n. 资源." },
    { word: "respect", syllables: ["re","spect"], phonetic: "/rɪˈspekt/", meaning: "n. & v. 尊敬，尊重", example: "We should respect our teachers." },
    { word: "response", syllables: ["response"], phonetic: "", meaning: "n. 响应；反应；作答", example: "The word 'response' means n. 响应." },
    { word: "responsible", syllables: ["responsible"], phonetic: "", meaning: "adj. 负责的；有责任的", example: "The word 'responsible' means adj. 负责的." },
    { word: "responsibility", syllables: ["responsibility"], phonetic: "", meaning: "n. 责任，职责，责任心", example: "The word 'responsibility' means n. 责任." },
    { word: "rest", syllables: ["rest"], phonetic: "/rest/", meaning: "n. 休息；剩余部分，其余的人(物); v. 休息，歇息", example: "Let's take a rest." },
    { word: "restaurant", syllables: ["res","tau","rant"], phonetic: "/ˈrestrɒnt/", meaning: "n. 饭馆； 饭店", example: "Let's eat at a restaurant." },
    { word: "result", syllables: ["re","sult"], phonetic: "/rɪˈzʌlt/", meaning: "n. 结果；成果", example: "The result was surprising." },
    { word: "retired", syllables: ["retired"], phonetic: "", meaning: "adj. 退休的", example: "The word 'retired' means adj. 退休的." },
    { word: "return", syllables: ["re","turn"], phonetic: "/rɪˈtɜːrn/", meaning: "v. 回来；返回；归还；偿还", example: "Return the book tomorrow." },
    { word: "reuse", syllables: ["reuse"], phonetic: "", meaning: "v. 再利用", example: "The word 'reuse' means v. 再利用." },
    { word: "review", syllables: ["re","view"], phonetic: "/rɪˈvjuː/", meaning: "n. & v. 复习；评论", example: "Let's review the lesson." },
    { word: "rice", syllables: ["rice"], phonetic: "/raɪs/", meaning: "n. 稻；米；米饭", example: "We eat rice for lunch." },
    { word: "rich", syllables: ["rich"], phonetic: "/rɪtʃ/", meaning: "adj. 富裕的，有钱的；味道浓的；重油的", example: "He comes from a rich family." },
    { word: "rid", syllables: ["rid"], phonetic: "", meaning: "v. 使摆脱", example: "The word 'rid' means v. 使摆脱." },
    { word: "ride (rode, ridden)", syllables: ["ride (rode, ridden)"], phonetic: "", meaning: "v. 骑(马、自行车等); n. 乘车旅行", example: "The word 'ride (rode, ridden)' means v. 骑(马、自行车等); n. 乘车旅行." },
    { word: "right", syllables: ["right"], phonetic: "/raɪt/", meaning: "adj. 对；正确的；恰当的；右边的; adv. 正确地；恰恰；向右，在右边; n. 右；权利", example: "You are right." },
    { word: "ring (rang, rung)", syllables: ["ring (rang, rung)"], phonetic: "", meaning: "v. (钟、铃等)响；摇铃；打电话; n. 打电话；铃声；环形物", example: "The word 'ring (rang, rung)' means v. (钟、铃等)响." },
    { word: "rise", syllables: ["rise"], phonetic: "/raɪz/", meaning: "v. 上升，上涨；起立", example: "The sun rises in the east." },
    { word: "river", syllables: ["riv","er"], phonetic: "/ˈrɪvər/", meaning: "n. 江；河", example: "The river is very long." },
    { word: "road", syllables: ["road"], phonetic: "/roʊd/", meaning: "n. 路；道路", example: "The road is very busy." },
    { word: "roast", syllables: ["roast"], phonetic: "", meaning: "v. 烤(肉)", example: "The word 'roast' means v. 烤(肉)." },
    { word: "robot", syllables: ["ro","bot"], phonetic: "/ˈroʊbɑːt/", meaning: "n. 机器人", example: "The robot can clean the house." },
    { word: "rock", syllables: ["rock"], phonetic: "/rɒk/", meaning: "n. 岩石", example: "He likes rock music." },
    { word: "rocket", syllables: ["rocket"], phonetic: "", meaning: "n. 火箭", example: "The word 'rocket' means n. 火箭." },
    { word: "role", syllables: ["role"], phonetic: "/roʊl/", meaning: "n. 角色", example: "She played the main role." },
    { word: "room", syllables: ["room"], phonetic: "/ruːm/", meaning: "n. 房间，室；空间；地方", example: "This is my room." },
    { word: "root", syllables: ["root"], phonetic: "", meaning: "n. 根；根源；起源", example: "The word 'root' means n. 根." },
    { word: "rope", syllables: ["rope"], phonetic: "/roʊp/", meaning: "n. 绳子", example: "Tie it with a rope." },
    { word: "rose", syllables: ["rose"], phonetic: "/roʊz/", meaning: "n. 玫瑰花", example: "She received a red rose." },
    { word: "rough", syllables: ["rough"], phonetic: "", meaning: "adj. 粗糙的；不平的；风浪急的", example: "The word 'rough' means adj. 粗糙的." },
    { word: "round", syllables: ["round"], phonetic: "/raʊnd/", meaning: "adj. 圆的；球形的; adv. 环绕地；在周围; prep. 环绕一周，围着", example: "The earth is round." },
    { word: "row", syllables: ["row"], phonetic: "/roʊ/", meaning: "n. (一)排，(一)行", example: "Sit in the first row." },
    { word: "rubbish", syllables: ["rubbish"], phonetic: "", meaning: "n. 垃圾；废物", example: "The word 'rubbish' means n. 垃圾." },
    { word: "rude", syllables: ["rude"], phonetic: "", meaning: "adj. 无理的，粗鲁的", example: "The word 'rude' means adj. 无理的." },
    { word: "rule", syllables: ["rule"], phonetic: "/ruːl/", meaning: "n. 规则；规定; v. 统治", example: "Follow the school rules." },
    { word: "run (ran, run)", syllables: ["run (ran, run)"], phonetic: "", meaning: "v. 跑，奔跑；经营，管理; n. 跑，奔跑", example: "The word 'run (ran, run)' means v. 跑." },
    { word: "rush", syllables: ["rush"], phonetic: "/rʌʃ/", meaning: "v. 冲，奔跑", example: "Don't rush." },
    { word: "sad", syllables: ["sad"], phonetic: "/sæd/", meaning: "adj. 悲伤的", example: "She looks sad." },
    { word: "sadly", syllables: ["sadly"], phonetic: "", meaning: "adv. 悲哀地，忧愁地，令人遗憾地；不幸地", example: "The word 'sadly' means adv. 悲哀地." },
    { word: "safe", syllables: ["safe"], phonetic: "/seɪf/", meaning: "adj. 安全的；平安的; n. 保险柜", example: "Keep your money safe." },
    { word: "safely", syllables: ["safely"], phonetic: "", meaning: "adv. 安全地；平安地", example: "The word 'safely' means adv. 安全地." }
  ],
  "第5组": [
    { word: "safety", syllables: ["safe","ty"], phonetic: "/ˈseɪfti/", meaning: "n. 安全；平安", example: "Safety comes first." },
    { word: "salad", syllables: ["sal","ad"], phonetic: "/ˈsæləd/", meaning: "n. 色拉", example: "I'd like a fruit salad." },
    { word: "salary", syllables: ["salary"], phonetic: "", meaning: "n. 薪金，薪水", example: "The word 'salary' means n. 薪金." },
    { word: "sale", syllables: ["sale"], phonetic: "/seɪl/", meaning: "n. 卖，出售", example: "The shoes are on sale." },
    { word: "salt", syllables: ["salt"], phonetic: "/sɒlt/", meaning: "n. 盐", example: "Add some salt to the soup." },
    { word: "salty", syllables: ["salty"], phonetic: "", meaning: "adj. 咸的；含盐的", example: "The word 'salty' means adj. 咸的." },
    { word: "same", syllables: ["same"], phonetic: "/seɪm/", meaning: "adj. 同样的，同一的; pron. 同样的事", example: "We are in the same class." },
    { word: "sandwich", syllables: ["sand","wich"], phonetic: "/ˈsænwɪtʃ/", meaning: "n. 三明治", example: "I had a sandwich for lunch." },
    { word: "satisfied", syllables: ["satisfied"], phonetic: "", meaning: "adj. 满足的，满意的", example: "The word 'satisfied' means adj. 满足的." },
    { word: "satisfying", syllables: ["satisfying"], phonetic: "", meaning: "adj. 令人满意的，令人满足的", example: "The word 'satisfying' means adj. 令人满意的." },
    { word: "sauce", syllables: ["sauce"], phonetic: "", meaning: "n. 酱汁； 调味汁", example: "The word 'sauce' means n. 酱汁." },
    { word: "save", syllables: ["save"], phonetic: "/seɪv/", meaning: "v. 救，挽救；节省", example: "Save water, please." },
    { word: "say (said, said)", syllables: ["say (said, said)"], phonetic: "", meaning: "v. 说，讲", example: "The word 'say (said, said)' means v. 说." },
    { word: "saying", syllables: ["saying"], phonetic: "", meaning: "n. 谚语，俗语；格言", example: "The word 'saying' means n. 谚语." },
    { word: "schedule", syllables: ["schedule"], phonetic: "", meaning: "n. 时间表", example: "The word 'schedule' means n. 时间表." },
    { word: "school", syllables: ["school"], phonetic: "/skuːl/", meaning: "n. 学校", example: "I go to school at seven." },
    { word: "science", syllables: ["sci","ence"], phonetic: "/ˈsaɪəns/", meaning: "n. 科学，自然科学", example: "I like science class." },
    { word: "scientist", syllables: ["sci","en","tist"], phonetic: "/ˈsaɪəntɪst/", meaning: "n. 科学家", example: "She wants to be a scientist." },
    { word: "score", syllables: ["score"], phonetic: "/skɔːr/", meaning: "n. 得分；分数", example: "What's the score?" },
    { word: "screen", syllables: ["screen"], phonetic: "", meaning: "n. 屏幕；荧光屏", example: "The word 'screen' means n. 屏幕." },
    { word: "sea", syllables: ["sea"], phonetic: "/siː/", meaning: "n. 海，海洋", example: "Let's go to the sea." },
    { word: "seafood", syllables: ["seafood"], phonetic: "", meaning: "n. 海鲜", example: "The word 'seafood' means n. 海鲜." },
    { word: "search", syllables: ["search"], phonetic: "/sɜːrtʃ/", meaning: "n. & v. 搜寻；搜查", example: "Search for information online." },
    { word: "seaside", syllables: ["seaside"], phonetic: "", meaning: "n. 海滨", example: "The word 'seaside' means n. 海滨." },
    { word: "season", syllables: ["sea","son"], phonetic: "/ˈsiːzn/", meaning: "n. 季；季节", example: "Spring is my favorite season." },
    { word: "seat", syllables: ["seat"], phonetic: "/siːt/", meaning: "n. 座位", example: "Take a seat, please." },
    { word: "second", syllables: ["sec","ond"], phonetic: "/ˈsekənd/", meaning: "n. 第二个；秒; adj. 第二位的; adv. 第二位；其次", example: "Wait a second." },
    { word: "secondary", syllables: ["secondary"], phonetic: "", meaning: "adj. 中等的；第二的", example: "The word 'secondary' means adj. 中等的." },
    { word: "secret", syllables: ["se","cret"], phonetic: "/ˈsiːkrɪt/", meaning: "n. 秘密", example: "It's a secret." },
    { word: "secretary", syllables: ["secretary"], phonetic: "", meaning: "n. 秘书", example: "The word 'secretary' means n. 秘书." },
    { word: "section", syllables: ["section"], phonetic: "", meaning: "n. 部分；部门；栏目", example: "The word 'section' means n. 部分." },
    { word: "see (saw, seen)", syllables: ["see (saw, seen)"], phonetic: "", meaning: "v. 看见，看到；领会，理解；拜访，会见", example: "The word 'see (saw, seen)' means v. 看见." },
    { word: "seed", syllables: ["seed"], phonetic: "/siːd/", meaning: "n. 种子", example: "Plant the seeds in spring." },
    { word: "seem", syllables: ["seem"], phonetic: "/siːm/", meaning: "v. 似乎，好像", example: "He seems happy." },
    { word: "seldom", syllables: ["seldom"], phonetic: "", meaning: "adv. 很少，不常", example: "The word 'seldom' means adv. 很少." },
    { word: "select", syllables: ["select"], phonetic: "", meaning: "v. 选择，挑选，选拔", example: "The word 'select' means v. 选择." },
    { word: "sell (sold, sold)", syllables: ["sell (sold, sold)"], phonetic: "", meaning: "v. 卖；销售", example: "The word 'sell (sold, sold)' means v. 卖." },
    { word: "send (sent, sent)", syllables: ["send (sent, sent)"], phonetic: "", meaning: "v. 打发，派遣；送，邮寄", example: "The word 'send (sent, sent)' means v. 打发." },
    { word: "senior", syllables: ["senior"], phonetic: "", meaning: "adj. 年长的；高年级的；高级的", example: "The word 'senior' means adj. 年长的." },
    { word: "sense", syllables: ["sense"], phonetic: "/sens/", meaning: "n. 感觉；意识；感官", example: "A dog has a good sense of smell." },
    { word: "sentence", syllables: ["sen","tence"], phonetic: "/ˈsentəns/", meaning: "n. 句子", example: "Read the first sentence." },
    { word: "serious", syllables: ["se","ri","ous"], phonetic: "/ˈsɪriəs/", meaning: "adj. 严肃的；严重的；认真的", example: "Are you serious?" },
    { word: "seriously", syllables: ["seriously"], phonetic: "", meaning: "adj. 严肃地；严重地；认真地", example: "The word 'seriously' means adj. 严肃地." },
    { word: "serve", syllables: ["serve"], phonetic: "/sɜːrv/", meaning: "v. 招待(顾客等)；为……服务", example: "Breakfast is served at seven." },
    { word: "service", syllables: ["ser","vice"], phonetic: "/ˈsɜːrvɪs/", meaning: "n. 服务；公用事业", example: "The service here is good." },
    { word: "set (set, set)", syllables: ["set (set, set)"], phonetic: "", meaning: "v. 释放，安置；树立(榜样)；创造(纪录)", example: "The word 'set (set, set)' means v. 释放." },
    { word: "settle", syllables: ["settle"], phonetic: "", meaning: "v. 安家，定居；解决", example: "The word 'settle' means v. 安家." },
    { word: "several", syllables: ["sev","er","al"], phonetic: "/ˈsevrəl/", meaning: "adj. 几个，数个", example: "I have several friends here." },
    { word: "shake (shook, shaken)", syllables: ["shake (shook, shaken)"], phonetic: "", meaning: "v. 握(手)，摇(头)；使震动", example: "The word 'shake (shook, shaken)' means v. 握(手)." },
    { word: "shall (should)", syllables: ["shall (should)"], phonetic: "", meaning: "aux. v. (表示将来)将要，会；(表示征求意见)……好吗", example: "The word 'shall (should)' means aux. v. (表示将来)将要." }
  ],
  "第6组": [
    { word: "shame", syllables: ["shame"], phonetic: "", meaning: "n. 遗憾的事；羞愧", example: "The word 'shame' means n. 遗憾的事." },
    { word: "shape", syllables: ["shape"], phonetic: "/ʃeɪp/", meaning: "n. 形状；外形；样子", example: "What shape is it?" },
    { word: "share", syllables: ["share"], phonetic: "/ʃer/", meaning: "v. 分享；共同使用", example: "Let's share the pizza." },
    { word: "sheep (复 sheep)", syllables: ["sheep (复 sheep)"], phonetic: "", meaning: "n. (绵)羊", example: "The word 'sheep (复 sheep)' means n. (绵)羊." },
    { word: "shelf (复 shelves)", syllables: ["shelf (复 shelves)"], phonetic: "", meaning: "n. 架子；搁板", example: "The word 'shelf (复 shelves)' means n. 架子." },
    { word: "shine (shone, shone)", syllables: ["shine (shone, shone)"], phonetic: "", meaning: "v. 发光；照耀；使发光", example: "The word 'shine (shone, shone)' means v. 发光." },
    { word: "ship", syllables: ["ship"], phonetic: "/ʃɪp/", meaning: "n. 船，轮船", example: "The ship sailed away." },
    { word: "shirt", syllables: ["shirt"], phonetic: "/ʃɜːrt/", meaning: "n. 男衬衫", example: "He bought a new shirt." },
    { word: "shoe", syllables: ["shoe"], phonetic: "/ʃuː/", meaning: "n. 鞋", example: "My shoes are too small." },
    { word: "shop", syllables: ["shop"], phonetic: "/ʃɒp/", meaning: "n. 店铺; v. 购物", example: "Let's go shopping." },
    { word: "short", syllables: ["short"], phonetic: "/ʃɔːrt/", meaning: "adj. 短的；矮的；短缺的", example: "The pencil is too short." },
    { word: "should (shall 的过去时态)", syllables: ["should (shall 的过去时态)"], phonetic: "", meaning: "aux. v. 应当，应该，会", example: "The word 'should (shall 的过去时态)' means aux. v. 应当." },
    { word: "shout", syllables: ["shout"], phonetic: "/ʃaʊt/", meaning: "n. & v. 喊；高声呼喊", example: "Don't shout in class." },
    { word: "show (showed, shown)", syllables: ["show (showed, shown)"], phonetic: "", meaning: "v. 给……看；出示；显示；告知；表明; n. 展示；演出；节目；展览会", example: "The word 'show (showed, shown)' means v. 给……看." },
    { word: "shower", syllables: ["show","er"], phonetic: "/ˈʃaʊər/", meaning: "n. 阵雨； 淋浴", example: "I take a shower every morning." },
    { word: "shut (shut, shut)", syllables: ["shut (shut, shut)"], phonetic: "", meaning: "v. 关上，封闭", example: "The word 'shut (shut, shut)' means v. 关上." },
    { word: "shy", syllables: ["shy"], phonetic: "/ʃaɪ/", meaning: "adj. 害羞的", example: "She is shy around strangers." },
    { word: "sick", syllables: ["sick"], phonetic: "/sɪk/", meaning: "adj. 有病的，患病的；(想)呕吐的；恶心的", example: "She is sick today." },
    { word: "side", syllables: ["side"], phonetic: "/saɪd/", meaning: "n. 边，旁边；面，侧面", example: "Sit by my side." },
    { word: "sight", syllables: ["sight"], phonetic: "/saɪt/", meaning: "n. 风景；视力", example: "She has good sight." },
    { word: "sightseeing", syllables: ["sightseeing"], phonetic: "", meaning: "n. 游览，观光", example: "The word 'sightseeing' means n. 游览." },
    { word: "sign", syllables: ["sign"], phonetic: "", meaning: "n. 符号，标记; v. 签名，署名", example: "The word 'sign' means n. 符号." },
    { word: "signal", syllables: ["signal"], phonetic: "", meaning: "n. 信号；手势", example: "The word 'signal' means n. 信号." },
    { word: "silent", syllables: ["si","lent"], phonetic: "/ˈsaɪlənt/", meaning: "adj. 静的，无声的", example: "Please keep silent." },
    { word: "silk", syllables: ["silk"], phonetic: "", meaning: "n. 丝，丝绸", example: "The word 'silk' means n. 丝." },
    { word: "silly", syllables: ["sil","ly"], phonetic: "/ˈsɪli/", meaning: "adj. 傻的，愚蠢的", example: "Don't be silly." },
    { word: "similar", syllables: ["sim","i","lar"], phonetic: "/ˈsɪmələr/", meaning: "adj. 相似的，像", example: "Our ideas are similar." },
    { word: "simple", syllables: ["sim","ple"], phonetic: "/ˈsɪmpl/", meaning: "adj. 简单的，简易的", example: "The answer is simple." },
    { word: "since", syllables: ["since"], phonetic: "/sɪns/", meaning: "prep. 从……以来；自从; conj. 从……以来；由于，既然", example: "I've lived here since 2010." },
    { word: "sing", syllables: ["sing"], phonetic: "/sɪŋ/", meaning: "v. 唱，唱歌", example: "She sings beautifully." },
    { word: "singer", syllables: ["singer"], phonetic: "", meaning: "n. 歌手； 歌唱家", example: "The word 'singer' means n. 歌手." },
    { word: "single", syllables: ["sin","gle"], phonetic: "/ˈsɪŋɡl/", meaning: "adj. 单一的，单个的；单身的", example: "Not a single person came." },
    { word: "sir", syllables: ["sir"], phonetic: "/sɜːr/", meaning: "n. 先生；阁下", example: "Yes, sir." },
    { word: "sister", syllables: ["sis","ter"], phonetic: "/ˈsɪstər/", meaning: "n. 姐；妹", example: "My sister is a doctor." },
    { word: "sit (sat, sat)", syllables: ["sit (sat, sat)"], phonetic: "", meaning: "v. 坐", example: "The word 'sit (sat, sat)' means v. 坐." },
    { word: "situation", syllables: ["sit","u","a","tion"], phonetic: "/ˌsɪtʃuˈeɪʃn/", meaning: "n. 形势，情况；场面", example: "The situation is getting better." },
    { word: "size", syllables: ["size"], phonetic: "/saɪz/", meaning: "n. 尺寸；大小", example: "What size do you need?" },
    { word: "skate", syllables: ["skate"], phonetic: "/skeɪt/", meaning: "v. 溜冰", example: "I like to skate in winter." },
    { word: "skill", syllables: ["skill"], phonetic: "/skɪl/", meaning: "n. 技能，技巧", example: "Reading is an important skill." },
    { word: "skin", syllables: ["skin"], phonetic: "/skɪn/", meaning: "n. 皮肤", example: "She has soft skin." },
    { word: "skirt", syllables: ["skirt"], phonetic: "/skɜːrt/", meaning: "n. 女裙", example: "She bought a new skirt." },
    { word: "sky", syllables: ["sky"], phonetic: "/skaɪ/", meaning: "n. 天空", example: "The sky is blue." },
    { word: "sleep (slept, slept)", syllables: ["sleep (slept, slept)"], phonetic: "", meaning: "v. 睡觉; n. 睡眠", example: "The word 'sleep (slept, slept)' means v. 睡觉; n. 睡眠." },
    { word: "slow", syllables: ["slow"], phonetic: "/sloʊ/", meaning: "adj. 慢慢的，缓慢的", example: "The turtle is very slow." },
    { word: "slowly", syllables: ["slowly"], phonetic: "", meaning: "adv. 慢慢地，缓慢地", example: "The word 'slowly' means adv. 慢慢地." },
    { word: "small", syllables: ["small"], phonetic: "/smɔːl/", meaning: "adj. 小的；少的", example: "The cat is very small." },
    { word: "smart", syllables: ["smart"], phonetic: "/smɑːrt/", meaning: "adj. 灵巧的，聪明的；智能的", example: "She is a smart student." },
    { word: "smell (smelt, smelt)", syllables: ["smell (smelt, smelt)"], phonetic: "", meaning: "v. 嗅；闻到; n. 气味", example: "The word 'smell (smelt, smelt)' means v. 嗅." },
    { word: "smile", syllables: ["smile"], phonetic: "/smaɪl/", meaning: "n. & v. 微笑", example: "She smiled at me." },
    { word: "smoke", syllables: ["smoke"], phonetic: "/smoʊk/", meaning: "n. 烟; v. 冒烟；吸烟", example: "Don't smoke here." }
  ],
  "第7组": [
    { word: "snack", syllables: ["snack"], phonetic: "", meaning: "n. 小吃", example: "The word 'snack' means n. 小吃." },
    { word: "snow", syllables: ["snow"], phonetic: "/snoʊ/", meaning: "n. 雪; v. 下雪", example: "It snowed last night." },
    { word: "snowy", syllables: ["snowy"], phonetic: "", meaning: "adj. 下雪的；多雪的", example: "The word 'snowy' means adj. 下雪的." },
    { word: "so", syllables: ["so"], phonetic: "/soʊ/", meaning: "adv. 如此，这么；也，同样; conj. 因此，所以；为的是，以便", example: "I'm tired, so I'll rest." },
    { word: "society", syllables: ["so","ci","e","ty"], phonetic: "/səˈsaɪəti/", meaning: "n. 社会", example: "We live in a modern society." },
    { word: "soft", syllables: ["soft"], phonetic: "/sɒft/", meaning: "adj. 软的，柔和的", example: "The bed is very soft." },
    { word: "softly", syllables: ["softly"], phonetic: "", meaning: "adv. 温柔地", example: "The word 'softly' means adv. 温柔地." },
    { word: "soldier", syllables: ["soldier"], phonetic: "", meaning: "n. 士兵；战士", example: "The word 'soldier' means n. 士兵." },
    { word: "solution", syllables: ["solution"], phonetic: "", meaning: "n. 解决方法；解答", example: "The word 'solution' means n. 解决方法." },
    { word: "solve", syllables: ["solve"], phonetic: "", meaning: "v. 解决，解答", example: "The word 'solve' means v. 解决." },
    { word: "some", syllables: ["some"], phonetic: "/sʌm/", meaning: "adj. 一些，若干；几个；某一; pron. 若干，一些", example: "I need some water." },
    { word: "somebody/someone", syllables: ["somebody/someone"], phonetic: "", meaning: "pron. 某人；有人", example: "The word 'somebody/someone' means pron. 某人." },
    { word: "something", syllables: ["some","thing"], phonetic: "/ˈsʌmθɪŋ/", meaning: "pron. 某事；某物", example: "I want to tell you something." },
    { word: "sometimes", syllables: ["some","times"], phonetic: "/ˈsʌmtaɪmz/", meaning: "adv. 有时", example: "Sometimes I walk to school." },
    { word: "son", syllables: ["son"], phonetic: "/sʌn/", meaning: "n. 儿子", example: "He has two sons." },
    { word: "song", syllables: ["song"], phonetic: "/sɒŋ/", meaning: "n. 歌唱；歌曲", example: "I like this song." },
    { word: "soon", syllables: ["soon"], phonetic: "/suːn/", meaning: "adv. 不久；很快；一会儿", example: "See you soon." },
    { word: "sorry", syllables: ["sor","ry"], phonetic: "/ˈsɒri/", meaning: "adj. 对不起的；抱歉的；难过的", example: "I'm sorry I'm late." },
    { word: "sound", syllables: ["sound"], phonetic: "/saʊnd/", meaning: "n. 声音; v. 听起来；发出声音", example: "That sounds great." },
    { word: "soup", syllables: ["soup"], phonetic: "", meaning: "n. 汤", example: "The word 'soup' means n. 汤." },
    { word: "south", syllables: ["south"], phonetic: "/saʊθ/", meaning: "n. 南；南方；南部; adj. 南(方)的；向南的", example: "Guangzhou is in the south." },
    { word: "space", syllables: ["space"], phonetic: "/speɪs/", meaning: "n. 空间；太空", example: "The astronaut went into space." },
    { word: "spaceship", syllables: ["spaceship"], phonetic: "", meaning: "n. 宇宙飞船", example: "The word 'spaceship' means n. 宇宙飞船." },
    { word: "spare", syllables: ["spare"], phonetic: "/sper/", meaning: "adj. 空闲的；多余的，剩余的", example: "I have some spare time." },
    { word: "speak (spoke, spoken)", syllables: ["speak (spoke, spoken)"], phonetic: "", meaning: "v. 说，讲；谈话；发言", example: "The word 'speak (spoke, spoken)' means v. 说." },
    { word: "special", syllables: ["spe","cial"], phonetic: "/ˈspeʃl/", meaning: "adj. 特别的，专门的", example: "Today is a special day." },
    { word: "speech", syllables: ["speech"], phonetic: "/spiːtʃ/", meaning: "n. 演讲，说话", example: "He gave a speech." },
    { word: "speed", syllables: ["speed"], phonetic: "/spiːd/", meaning: "n. 速度; v. (使)加速", example: "The car runs at high speed." },
    { word: "spend", syllables: ["spend"], phonetic: "/spend/", meaning: "v. 度过；花费(钱、时间等)", example: "I spend two hours on homework." },
    { word: "spoon", syllables: ["spoon"], phonetic: "/spuːn/", meaning: "n. 调羹", example: "Use a spoon to eat soup." },
    { word: "sport", syllables: ["sport"], phonetic: "/spɔːrt/", meaning: "n. 体育运动；锻炼", example: "I like all kinds of sports." },
    { word: "spread (spread, spread)", syllables: ["spread (spread, spread)"], phonetic: "", meaning: "v. 延伸； 展开", example: "The word 'spread (spread, spread)' means v. 延伸." },
    { word: "spring", syllables: ["spring"], phonetic: "/sprɪŋ/", meaning: "n. 春天，春季", example: "Flowers bloom in spring." },
    { word: "square", syllables: ["square"], phonetic: "/skwer/", meaning: "n. 广场; adj. 平方的；方形的", example: "Meet me at the square." },
    { word: "staff", syllables: ["staff"], phonetic: "", meaning: "n. 全体职员", example: "The word 'staff' means n. 全体职员." },
    { word: "stamp", syllables: ["stamp"], phonetic: "", meaning: "n. 邮票", example: "The word 'stamp' means n. 邮票." },
    { word: "stand (stood, stood)", syllables: ["stand (stood, stood)"], phonetic: "", meaning: "v. 站；起立", example: "The word 'stand (stood, stood)' means v. 站." },
    { word: "star", syllables: ["star"], phonetic: "/stɑːr/", meaning: "n. 星，恒星", example: "Look at the stars." },
    { word: "start", syllables: ["start"], phonetic: "/stɑːrt/", meaning: "v. 开始；着手；出发; n. 开端，开始", example: "School starts at eight." },
    { word: "state", syllables: ["state"], phonetic: "/steɪt/", meaning: "n. 状态； 情形；国家，(美国的)州", example: "What state are you in?" },
    { word: "station", syllables: ["sta","tion"], phonetic: "/ˈsteɪʃn/", meaning: "n. 车站；电台", example: "The train station is near here." },
    { word: "stay", syllables: ["stay"], phonetic: "/steɪ/", meaning: "n. & v. 停留，逗留，呆", example: "Stay here and wait." },
    { word: "steak", syllables: ["steak"], phonetic: "", meaning: "n. 牛排", example: "The word 'steak' means n. 牛排." },
    { word: "steal (stole, stolen)", syllables: ["steal (stole, stolen)"], phonetic: "", meaning: "v. 偷， 窃取", example: "The word 'steal (stole, stolen)' means v. 偷." },
    { word: "steam", syllables: ["steam"], phonetic: "", meaning: "n. 汽；水蒸气", example: "The word 'steam' means n. 汽." },
    { word: "step", syllables: ["step"], phonetic: "/step/", meaning: "n. 脚步，台阶; v. 走； 跨步", example: "Take it step by step." },
    { word: "stick", syllables: ["stick"], phonetic: "/stɪk/", meaning: "n. 木棒(棍)，枝条; v. (stuck, stuck) 粘住，钉住；坚持", example: "Stick the picture on the wall." },
    { word: "still", syllables: ["still"], phonetic: "/stɪl/", meaning: "adv. 仍然，还; adj. 不动的，平静的", example: "He is still sleeping." },
    { word: "stocking", syllables: ["stocking"], phonetic: "", meaning: "n. 长筒袜", example: "The word 'stocking' means n. 长筒袜." },
    { word: "stomachache", syllables: ["stomachache"], phonetic: "", meaning: "n. 胃疼", example: "The word 'stomachache' means n. 胃疼." }
  ],
  "第8组": [
    { word: "stone", syllables: ["stone"], phonetic: "/stoʊn/", meaning: "n. 石头，石料", example: "The wall is made of stone." },
    { word: "stop", syllables: ["stop"], phonetic: "/stɒp/", meaning: "v. 停，停止；阻止; n. 停；(停车)站", example: "Stop talking, please." },
    { word: "store", syllables: ["store"], phonetic: "/stɔːr/", meaning: "n. 商店; v. 储藏，存储", example: "The store is open today." },
    { word: "storm", syllables: ["storm"], phonetic: "/stɔːrm/", meaning: "n. 风暴，暴(风)雨(雪)", example: "A storm is coming." },
    { word: "story", syllables: ["sto","ry"], phonetic: "/ˈstɔːri/", meaning: "n. 故事，小说", example: "Tell me a story." },
    { word: "straight", syllables: ["straight"], phonetic: "/streɪt/", meaning: "adj. 一直的，直的; adv. 一直地，直地", example: "Go straight ahead." },
    { word: "strange", syllables: ["strange"], phonetic: "/streɪndʒ/", meaning: "adj. 奇怪的，奇特的；陌生的", example: "What a strange noise!" },
    { word: "strawberry", syllables: ["straw","ber","ry"], phonetic: "/ˈstrɔːberi/", meaning: "n. 草莓", example: "I love strawberries." },
    { word: "street", syllables: ["street"], phonetic: "/striːt/", meaning: "n. 街；街道", example: "The school is on this street." },
    { word: "stress", syllables: ["stress"], phonetic: "", meaning: "n. 压力；紧张；强调; v. 加压力于；使紧张；强调", example: "The word 'stress' means n. 压力." },
    { word: "strict", syllables: ["strict"], phonetic: "/strɪkt/", meaning: "adj. 严格的；严密的", example: "My teacher is very strict." },
    { word: "strike (struck, struck/stricken)", syllables: ["strike (struck, struck/stricken)"], phonetic: "", meaning: "v. 敲，打击， 侵袭；(钟)鸣", example: "The word 'strike (struck, struck/stricken)' means v. 敲." },
    { word: "strong", syllables: ["strong"], phonetic: "/strɒŋ/", meaning: "adj. 强(壮)的；坚固的；强烈的；坚强的", example: "He is very strong." },
    { word: "stuck", syllables: ["stuck"], phonetic: "", meaning: "v. stick 的过去式及过去分词; adj. 被卡住的，被困住的", example: "The word 'stuck' means v. stick 的过去式及过去分词; adj. 被卡住的." },
    { word: "student", syllables: ["stu","dent"], phonetic: "/ˈstjuːdnt/", meaning: "n. 学生", example: "There are forty students." },
    { word: "study", syllables: ["stud","y"], phonetic: "/ˈstʌdi/", meaning: "v. 学习；研究; n. 学习；研究；书房", example: "I study English every day." },
    { word: "stupid", syllables: ["stupid"], phonetic: "", meaning: "adj. 愚蠢的，笨的", example: "The word 'stupid' means adj. 愚蠢的." },
    { word: "style", syllables: ["style"], phonetic: "/staɪl/", meaning: "n. 风格；方式；类型", example: "I like her style." },
    { word: "subject", syllables: ["sub","ject"], phonetic: "/ˈsʌbdʒɪkt/", meaning: "n. 题目；主题；学科；主语；主体", example: "What's your favorite subject?" },
    { word: "succeed", syllables: ["suc","ceed"], phonetic: "/səkˈsiːd/", meaning: "v. 获得成功，达到目的", example: "If you try hard, you will succeed." },
    { word: "success", syllables: ["suc","cess"], phonetic: "/səkˈses/", meaning: "n. 成功", example: "The project was a success." },
    { word: "successful", syllables: ["suc","cess","ful"], phonetic: "/səkˈsesfl/", meaning: "adj. 成功的", example: "She is a successful writer." },
    { word: "such", syllables: ["such"], phonetic: "/sʌtʃ/", meaning: "adj. 这样的，那样的; pron. (泛指)人，事物", example: "I've never seen such a thing." },
    { word: "suddenly", syllables: ["suddenly"], phonetic: "", meaning: "adv. 突然地", example: "The word 'suddenly' means adv. 突然地." },
    { word: "suffer", syllables: ["suffer"], phonetic: "", meaning: "v. 受苦；遭受", example: "The word 'suffer' means v. 受苦." },
    { word: "sugar", syllables: ["sug","ar"], phonetic: "/ˈʃʊɡər/", meaning: "n. 糖", example: "Don't eat too much sugar." },
    { word: "suggest", syllables: ["sug","gest"], phonetic: "/səˈdʒest/", meaning: "v. 建议；提议", example: "I suggest we go now." },
    { word: "suggestion", syllables: ["suggestion"], phonetic: "", meaning: "n. 建议，提议", example: "The word 'suggestion' means n. 建议." },
    { word: "summer", syllables: ["sum","mer"], phonetic: "/ˈsʌmər/", meaning: "n. 夏天，夏季", example: "Summer is very hot." },
    { word: "sun", syllables: ["sun"], phonetic: "/sʌn/", meaning: "n. 太阳；阳光", example: "The sun is bright." },
    { word: "sunny", syllables: ["sun","ny"], phonetic: "/ˈsʌni/", meaning: "adj. 阳光充足的，晴朗的", example: "It's a sunny day." },
    { word: "super", syllables: ["super"], phonetic: "", meaning: "adj. 超级的；极好的", example: "The word 'super' means adj. 超级的." },
    { word: "supermarket", syllables: ["su","per","mar","ket"], phonetic: "/ˈsuːpərmɑːrkɪt/", meaning: "n. 超级市场", example: "I buy food at the supermarket." },
    { word: "supper", syllables: ["supper"], phonetic: "", meaning: "n. 晚餐，晚饭", example: "The word 'supper' means n. 晚餐." },
    { word: "support", syllables: ["sup","port"], phonetic: "/səˈpɔːrt/", meaning: "vt. & n.      支持；赞助", example: "I support your idea." },
    { word: "suppose", syllables: ["suppose"], phonetic: "", meaning: "v. 猜想，假定，料想", example: "The word 'suppose' means v. 猜想." },
    { word: "sure", syllables: ["sure"], phonetic: "/ʃʊr/", meaning: "adj. 确信的，肯定的，有把握的", example: "Are you sure?" },
    { word: "surface", syllables: ["surface"], phonetic: "", meaning: "n. 表面", example: "The word 'surface' means n. 表面." },
    { word: "surprise", syllables: ["sur","prise"], phonetic: "/sərˈpraɪz/", meaning: "n. 惊奇，诧异", example: "What a nice surprise!" },
    { word: "surprised", syllables: ["surprised"], phonetic: "", meaning: "adj. 感到惊奇的", example: "The word 'surprised' means adj. 感到惊奇的." },
    { word: "survey", syllables: ["sur","vey"], phonetic: "/ˈsɜːrveɪ/", meaning: "n. & v. 调查", example: "We did a survey about food." },
    { word: "survive", syllables: ["survive"], phonetic: "", meaning: "v. 幸存，活下来； 存活；生还", example: "The word 'survive' means v. 幸存." },
    { word: "sweep (swept, swept)", syllables: ["sweep (swept, swept)"], phonetic: "", meaning: "v. 扫除，扫", example: "The word 'sweep (swept, swept)' means v. 扫除." },
    { word: "sweet", syllables: ["sweet"], phonetic: "/swiːt/", meaning: "adj. 甜的；可爱的; n. 甜食；糖果", example: "The cake is very sweet." },
    { word: "swim (swam, swum)", syllables: ["swim (swam, swum)"], phonetic: "", meaning: "v. & n.   游泳", example: "The word 'swim (swam, swum)' means v. & n.   游泳." },
    { word: "system", syllables: ["system"], phonetic: "", meaning: "n. 体系； 系统", example: "The word 'system' means n. 体系." },
    { word: "table", syllables: ["ta","ble"], phonetic: "/ˈteɪbl/", meaning: "n. 桌子；表格", example: "The book is on the table." },
    { word: "take (took，taken)", syllables: ["take (took，taken)"], phonetic: "", meaning: "v. 拿；拿走；做；吃，服用；乘坐(车、船)；", example: "The word 'take (took，taken)' means v. 拿." },
    { word: "talent", syllables: ["talent"], phonetic: "", meaning: "n. 才能；天才", example: "The word 'talent' means n. 才能." },
    { word: "talk", syllables: ["talk"], phonetic: "/tɔːk/", meaning: "n. & v. 谈话，讲话，演讲；交谈", example: "Let's talk about it." }
  ],
  "第9组": [
    { word: "tall", syllables: ["tall"], phonetic: "/tɔːl/", meaning: "adj. 高的", example: "He is very tall." },
    { word: "tap", syllables: ["tap"], phonetic: "", meaning: "n. (自来水、煤气等的)龙头", example: "The word 'tap' means n. (自来水、煤气等的)龙头." },
    { word: "tape", syllables: ["tape"], phonetic: "/teɪp/", meaning: "n. 磁带；录音带", example: "I need some tape." },
    { word: "task", syllables: ["task"], phonetic: "/tæsk/", meaning: "n. 任务， 工作", example: "Finish the task by Friday." },
    { word: "taste", syllables: ["taste"], phonetic: "/teɪst/", meaning: "v. 品尝， 尝味; n. 味道", example: "The soup tastes good." },
    { word: "taxi", syllables: ["tax","i"], phonetic: "/ˈtæksi/", meaning: "n. 出租汽车", example: "Let's take a taxi." },
    { word: "tea", syllables: ["tea"], phonetic: "/tiː/", meaning: "n. 茶；茶叶", example: "Would you like some tea?" },
    { word: "teach (taught, taught)", syllables: ["teach (taught, taught)"], phonetic: "", meaning: "v. 教书，教", example: "The word 'teach (taught, taught)' means v. 教书." },
    { word: "teacher", syllables: ["teach","er"], phonetic: "/ˈtiːtʃər/", meaning: "n. 教师", example: "Our teacher is very kind." },
    { word: "team", syllables: ["team"], phonetic: "/tiːm/", meaning: "n. 队，组", example: "Our team won the game." },
    { word: "tear", syllables: ["tear"], phonetic: "", meaning: "n. 眼泪", example: "The word 'tear' means n. 眼泪." },
    { word: "technology", syllables: ["tech","nol","o","gy"], phonetic: "/tekˈnɒlədʒi/", meaning: "n. 技术", example: "Technology changes our life." },
    { word: "teenager", syllables: ["teenager"], phonetic: "", meaning: "n. (13~19 岁的)青少年，十几岁的少年", example: "The word 'teenager' means n. (13~19 岁的)青少年." },
    { word: "telephone", syllables: ["telephone"], phonetic: "", meaning: "v. 打电话; n. 电话，电话机", example: "The word 'telephone' means v. 打电话; n. 电话." },
    { word: "television (TV)", syllables: ["television (TV)"], phonetic: "", meaning: "n. 电视", example: "The word 'television (TV)' means n. 电视." },
    { word: "tell (told, told)", syllables: ["tell (told, told)"], phonetic: "", meaning: "v. 告诉；讲述；吩咐", example: "The word 'tell (told, told)' means v. 告诉." },
    { word: "temperature", syllables: ["tem","per","a","ture"], phonetic: "/ˈtemprətʃər/", meaning: "n. 温度", example: "The temperature is 30 degrees." },
    { word: "temple", syllables: ["temple"], phonetic: "", meaning: "n. 庙宇，寺院", example: "The word 'temple' means n. 庙宇." },
    { word: "tennis", syllables: ["ten","nis"], phonetic: "/ˈtenɪs/", meaning: "n. 网球", example: "Let's play tennis." },
    { word: "term", syllables: ["term"], phonetic: "/tɜːrm/", meaning: "n. 学期", example: "We have two terms a year." },
    { word: "terrible", syllables: ["ter","ri","ble"], phonetic: "/ˈterəbl/", meaning: "n. 可怕的；糟糕的", example: "The weather was terrible." },
    { word: "test", syllables: ["test"], phonetic: "/test/", meaning: "v. & n.            测试， 考查，试验", example: "We have a math test." },
    { word: "text", syllables: ["text"], phonetic: "/tekst/", meaning: "n. 文本，课文", example: "Read the text carefully." },
    { word: "than", syllables: ["than"], phonetic: "/ðæn/", meaning: "conj. 比", example: "She is taller than me." },
    { word: "thank", syllables: ["thank"], phonetic: "/θæŋk/", meaning: "v. 感谢，致谢，道谢; n. (复)感谢，谢意", example: "Thank you for your help." },
    { word: "thankful", syllables: ["thankful"], phonetic: "", meaning: "adj. 感谢的；感激的", example: "The word 'thankful' means adj. 感谢的." },
    { word: "that", syllables: ["that"], phonetic: "/ðæt/", meaning: "adj. & pron.                那，那个; conj. 引导宾语从句", example: "That is my book." },
    { word: "theatre (美 theater)", syllables: ["theatre (美 theater)"], phonetic: "", meaning: "n. 剧场，戏院", example: "The word 'theatre (美 theater)' means n. 剧场." },
    { word: "then", syllables: ["then"], phonetic: "/ðen/", meaning: "adv. 当时，那时；然后，后来；那么(通常用于句首或句尾)", example: "First wash, then eat." },
    { word: "there", syllables: ["there"], phonetic: "/ðer/", meaning: "adv. 在那里，往那里；(作引导词)表 “存在”", example: "Put it over there." },
    { word: "these", syllables: ["these"], phonetic: "/ðiːz/", meaning: "adj. & pron.           这些", example: "These are my books." },
    { word: "thick", syllables: ["thick"], phonetic: "/θɪk/", meaning: "adj. 厚的，浓的", example: "The book is very thick." },
    { word: "thin", syllables: ["thin"], phonetic: "/θɪn/", meaning: "adj. 薄的；瘦的；细的", example: "The paper is very thin." },
    { word: "thing", syllables: ["thing"], phonetic: "/θɪŋ/", meaning: "n. 东西；事情", example: "What's that thing?" },
    { word: "think (thought, thought)", syllables: ["think (thought, thought)"], phonetic: "", meaning: "v. 想；思考；认为；考虑", example: "The word 'think (thought, thought)' means v. 想." },
    { word: "thirsty", syllables: ["thirs","ty"], phonetic: "/ˈθɜːrsti/", meaning: "adj. 渴", example: "I'm thirsty. Can I have water?" },
    { word: "this", syllables: ["this"], phonetic: "/ðɪs/", meaning: "adj. & pron.                   这；这个", example: "This is my pen." },
    { word: "those", syllables: ["those"], phonetic: "/ðoʊz/", meaning: "adj. & pron.           那些", example: "Those are flowers." },
    { word: "thought", syllables: ["thought"], phonetic: "/θɔːt/", meaning: "n. 思想，想法", example: "What are your thoughts?" },
    { word: "through", syllables: ["through"], phonetic: "/θruː/", meaning: "prep. 穿(通)过；从始至终", example: "Walk through the door." },
    { word: "throughout", syllables: ["throughout"], phonetic: "", meaning: "prep. 遍及；贯穿", example: "The word 'throughout' means prep. 遍及." },
    { word: "throw (threw, thrown)", syllables: ["throw (threw, thrown)"], phonetic: "", meaning: "v. 投，掷，扔", example: "The word 'throw (threw, thrown)' means v. 投." },
    { word: "ticket", syllables: ["tick","et"], phonetic: "/ˈtɪkɪt/", meaning: "n. 票；券", example: "I bought two tickets." },
    { word: "tidy", syllables: ["ti","dy"], phonetic: "/ˈtaɪdi/", meaning: "adj. 整洁的，干净的", example: "Keep your room tidy." },
    { word: "tie", syllables: ["tie"], phonetic: "/taɪ/", meaning: "n. 领带，结; v. (用绳，线)系，拴", example: "Tie your shoes." },
    { word: "tiger", syllables: ["ti","ger"], phonetic: "/ˈtaɪɡər/", meaning: "n. 老虎", example: "The tiger is strong." },
    { word: "till", syllables: ["till"], phonetic: "/tɪl/", meaning: "conj. & prep.                    直到，直到……为止", example: "Wait till I come back." },
    { word: "time", syllables: ["time"], phonetic: "/taɪm/", meaning: "n. 时间；时期；钟点；次，回", example: "What time is it?" },
    { word: "tip", syllables: ["tip"], phonetic: "", meaning: "n. 尖端；提示；小费；小窍门，建议", example: "The word 'tip' means n. 尖端." },
    { word: "tired", syllables: ["tired"], phonetic: "/taɪərd/", meaning: "adj. 疲劳的，累的", example: "I'm very tired today." }
  ],
  "第10组": [
    { word: "title", syllables: ["title"], phonetic: "", meaning: "n. 标题，题目", example: "The word 'title' means n. 标题." },
    { word: "to", syllables: ["to"], phonetic: "/tuː/", meaning: "prep. (表示接受动作的人或物)给……；对……，向……，到……", example: "Let's go to school." },
    { word: "today", syllables: ["to","day"], phonetic: "/təˈdeɪ/", meaning: "adv. & n.                       今天；现在，当前", example: "Today is Monday." },
    { word: "together", syllables: ["to","geth","er"], phonetic: "/təˈɡeðər/", meaning: "adv. 一起，共同", example: "Let's play together." },
    { word: "tomato", syllables: ["to","ma","to"], phonetic: "/təˈmeɪtoʊ/", meaning: "n. 番茄，西红柿", example: "I like tomatoes." },
    { word: "tomorrow", syllables: ["to","mor","row"], phonetic: "/təˈmɒroʊ/", meaning: "adv. & n.      明天", example: "See you tomorrow." },
    { word: "tonight", syllables: ["to","night"], phonetic: "/təˈnaɪt/", meaning: "adv. & n.           今晚，今夜", example: "Let's watch TV tonight." },
    { word: "too", syllables: ["too"], phonetic: "/tuː/", meaning: "adv. 也，还；又；太，过分；很，非常", example: "It's too hot." },
    { word: "tool", syllables: ["tool"], phonetic: "/tuːl/", meaning: "n. 工具", example: "A hammer is a tool." },
    { word: "tooth (复 teeth)", syllables: ["tooth (复 teeth)"], phonetic: "", meaning: "n. 牙齿", example: "The word 'tooth (复 teeth)' means n. 牙齿." },
    { word: "toothache", syllables: ["toothache"], phonetic: "", meaning: "n. 牙痛", example: "The word 'toothache' means n. 牙痛." },
    { word: "top", syllables: ["top"], phonetic: "/tɒp/", meaning: "n. 顶部，(物体的)上面; adj. 最上面的；居首位的", example: "The cat is on top of the box." },
    { word: "topic", syllables: ["topic"], phonetic: "", meaning: "n. 题目，话题", example: "The word 'topic' means n. 题目." },
    { word: "touch", syllables: ["touch"], phonetic: "/tʌtʃ/", meaning: "v. 触摸；接触；感动", example: "Don't touch the painting." },
    { word: "tour", syllables: ["tour"], phonetic: "/tʊr/", meaning: "n. 参观， 观光，旅行", example: "We went on a tour of Beijing." },
    { word: "tourist", syllables: ["tour","ist"], phonetic: "/ˈtʊrɪst/", meaning: "n. 游客，旅客，旅行者", example: "Many tourists visit here." },
    { word: "toward(s)", syllables: ["toward(s)"], phonetic: "", meaning: "prep. 向，朝，对于", example: "The word 'toward(s)' means prep. 向." },
    { word: "tower", syllables: ["tow","er"], phonetic: "/ˈtaʊər/", meaning: "n. 塔", example: "The TV tower is very tall." },
    { word: "town", syllables: ["town"], phonetic: "/taʊn/", meaning: "n. 城镇，城", example: "I live in a small town." },
    { word: "toy", syllables: ["toy"], phonetic: "/tɔɪ/", meaning: "n. 玩具", example: "Children like toys." },
    { word: "tradition", syllables: ["tradition"], phonetic: "", meaning: "n. 传统", example: "The word 'tradition' means n. 传统." },
    { word: "traditional", syllables: ["tra","di","tion","al"], phonetic: "/trəˈdɪʃənl/", meaning: "adj. 传统的", example: "Dumplings are traditional food." },
    { word: "traffic", syllables: ["traf","fic"], phonetic: "/ˈtræfɪk/", meaning: "n. 交通", example: "The traffic is heavy today." },
    { word: "train", syllables: ["train"], phonetic: "/treɪn/", meaning: "n. 火车; v. 培训，训练", example: "I go to school by train." },
    { word: "translate", syllables: ["translate"], phonetic: "", meaning: "v. 翻译", example: "The word 'translate' means v. 翻译." },
    { word: "transport", syllables: ["transport"], phonetic: "", meaning: "v. 运输，运送", example: "The word 'transport' means v. 运输." },
    { word: "travel", syllables: ["trav","el"], phonetic: "/ˈtrævl/", meaning: "n. & v. 旅行", example: "I like to travel." },
    { word: "tree", syllables: ["tree"], phonetic: "/triː/", meaning: "n. 树", example: "The tree is very tall." },
    { word: "trick", syllables: ["trick"], phonetic: "", meaning: "n. 恶作剧；诡计，花招", example: "The word 'trick' means n. 恶作剧." },
    { word: "trip", syllables: ["trip"], phonetic: "/trɪp/", meaning: "n. 旅行，旅程", example: "We had a school trip." },
    { word: "trouble", syllables: ["trou","ble"], phonetic: "/ˈtrʌbl/", meaning: "n. 问题；烦恼；麻烦；困难; v. 使苦恼；使麻烦", example: "What's the trouble?" },
    { word: "trousers", syllables: ["trousers"], phonetic: "", meaning: "n. 裤子，长裤", example: "The word 'trousers' means n. 裤子." },
    { word: "true", syllables: ["true"], phonetic: "/truː/", meaning: "adj. 真的，真实的", example: "Is this story true?" },
    { word: "truck", syllables: ["truck"], phonetic: "/trʌk/", meaning: "n. 卡车；货车", example: "The truck carries goods." },
    { word: "trust", syllables: ["trust"], phonetic: "/trʌst/", meaning: "n. & v. 信任，相信", example: "I trust you." },
    { word: "truth", syllables: ["truth"], phonetic: "/truːθ/", meaning: "n. 真理；真相，实际情况", example: "Tell me the truth." },
    { word: "try", syllables: ["try"], phonetic: "/traɪ/", meaning: "v. 试；试图；努力; n. 试；努力", example: "Try your best." },
    { word: "turkey", syllables: ["turkey"], phonetic: "", meaning: "n. 火鸡", example: "The word 'turkey' means n. 火鸡." },
    { word: "turn", syllables: ["turn"], phonetic: "/tɜːrn/", meaning: "v. 旋转；翻转；转弯；转变；变得; n. (轮流的)顺序", example: "Turn left at the corner." },
    { word: "twice", syllables: ["twice"], phonetic: "/twaɪs/", meaning: "adv. 两次；两倍", example: "I brush my teeth twice a day." },
    { word: "twin", syllables: ["twin"], phonetic: "", meaning: "n. 双胞胎之一", example: "The word 'twin' means n. 双胞胎之一." },
    { word: "type", syllables: ["type"], phonetic: "/taɪp/", meaning: "n. 类型; v. 打字", example: "What type of music is this?" },
    { word: "umbrella", syllables: ["umbrella"], phonetic: "", meaning: "n. 伞", example: "The word 'umbrella' means n. 伞." },
    { word: "uncle", syllables: ["un","cle"], phonetic: "/ˈʌŋkl/", meaning: "n. 叔；伯；舅；姑夫；姨父", example: "My uncle lives in Beijing." },
    { word: "under", syllables: ["un","der"], phonetic: "/ˈʌndər/", meaning: "adv. & prep.     在……下面，向……下面", example: "The cat is under the table." },
    { word: "underground", syllables: ["un","der","ground"], phonetic: "/ˈʌndərɡraʊnd/", meaning: "adj. 地下的; n. (美 subway) 地铁", example: "Take the underground." },
    { word: "underlined", syllables: ["underlined"], phonetic: "", meaning: "adj. 带下划线的", example: "The word 'underlined' means adj. 带下划线的." },
    { word: "understand (understood, understood)", syllables: ["understand (understood, understood)"], phonetic: "", meaning: "v. 明白，懂得；理解", example: "The word 'understand (understood, understood)' means v. 明白." },
    { word: "unfair", syllables: ["unfair"], phonetic: "", meaning: "adj. 不公正的，不公平的；违反规则或准则的", example: "The word 'unfair' means adj. 不公正的." },
    { word: "unforgettable", syllables: ["unforgettable"], phonetic: "", meaning: "adj. 难忘的", example: "The word 'unforgettable' means adj. 难忘的." }
  ],
  "第11组": [
    { word: "unfortunately", syllables: ["unfortunately"], phonetic: "", meaning: "adv. 不幸地，遗憾地", example: "The word 'unfortunately' means adv. 不幸地." },
    { word: "unhappy", syllables: ["unhappy"], phonetic: "", meaning: "adj. 不开心的，不幸福的，难过的", example: "The word 'unhappy' means adj. 不开心的." },
    { word: "unhealthy", syllables: ["unhealthy"], phonetic: "", meaning: "adj. 不健康的", example: "The word 'unhealthy' means adj. 不健康的." },
    { word: "uniform", syllables: ["uniform"], phonetic: "", meaning: "n. 制服", example: "The word 'uniform' means n. 制服." },
    { word: "unit", syllables: ["unit"], phonetic: "", meaning: "n. 单元；单位；部件", example: "The word 'unit' means n. 单元." },
    { word: "united", syllables: ["united"], phonetic: "", meaning: "adj. 联合的；统一的", example: "The word 'united' means adj. 联合的." },
    { word: "university", syllables: ["university"], phonetic: "", meaning: "n. 大学", example: "The word 'university' means n. 大学." },
    { word: "unless", syllables: ["un","less"], phonetic: "/ʌnˈles/", meaning: "conj. 如果不，除非", example: "I won't go unless you come." },
    { word: "until", syllables: ["un","til"], phonetic: "/ʌnˈtɪl/", meaning: "prep. & conj.        直到……为止", example: "Wait until I return." },
    { word: "unusual", syllables: ["unusual"], phonetic: "", meaning: "adj. 不寻常的", example: "The word 'unusual' means adj. 不寻常的." },
    { word: "up", syllables: ["up"], phonetic: "/ʌp/", meaning: "adv. & prep.          向上；在上方；起来", example: "Stand up, please." },
    { word: "upset", syllables: ["up","set"], phonetic: "/ʌpˈset/", meaning: "adj. 心烦的，难过的", example: "Don't be upset." },
    { word: "upstairs", syllables: ["upstairs"], phonetic: "", meaning: "adv. 在楼上；到楼上", example: "The word 'upstairs' means adv. 在楼上." },
    { word: "use", syllables: ["use"], phonetic: "/juːz/", meaning: "v. & n.        利用；使用；应用", example: "Can I use your pen?" },
    { word: "useful", syllables: ["use","ful"], phonetic: "/ˈjuːsfl/", meaning: "adj. 有用的；有益的", example: "This tool is very useful." },
    { word: "useless", syllables: ["useless"], phonetic: "", meaning: "adj. 无用的，废旧的", example: "The word 'useless' means adj. 无用的." },
    { word: "usual", syllables: ["u","su","al"], phonetic: "/ˈjuːʒuəl/", meaning: "adj. 通常的，平常的", example: "He arrived earlier than usual." },
    { word: "usually", syllables: ["u","su","al","ly"], phonetic: "/ˈjuːʒuəli/", meaning: "adv. 通常；经常", example: "I usually get up at seven." },
    { word: "value", syllables: ["val","ue"], phonetic: "/ˈvæljuː/", meaning: "n. 价值；价格；价值观", example: "What's the value of this book?" },
    { word: "variety", syllables: ["variety"], phonetic: "", meaning: "n. 种种，种类", example: "The word 'variety' means n. 种种." },
    { word: "various", syllables: ["various"], phonetic: "", meaning: "adj. 各种各样的，不同的", example: "The word 'various' means adj. 各种各样的." },
    { word: "vegetable", syllables: ["veg","e","ta","ble"], phonetic: "/ˈvedʒtəbl/", meaning: "n. 蔬菜", example: "Eat more vegetables." },
    { word: "very", syllables: ["ver","y"], phonetic: "/ˈveri/", meaning: "adv. 很，非常", example: "It's very cold today." },
    { word: "victory", syllables: ["vic","to","ry"], phonetic: "/ˈvɪktəri/", meaning: "n. 胜利", example: "We celebrated our victory." },
    { word: "video", syllables: ["vid","e","o"], phonetic: "/ˈvɪdioʊ/", meaning: "n. 录像；视频", example: "Let's watch a video." },
    { word: "view", syllables: ["view"], phonetic: "/vjuː/", meaning: "n. 看法，见解；风景，景色；视野", example: "The view from the hill is great." },
    { word: "village", syllables: ["vil","lage"], phonetic: "/ˈvɪlɪdʒ/", meaning: "n. 村庄，乡村", example: "She lives in a small village." },
    { word: "violin", syllables: ["vi","o","lin"], phonetic: "/ˌvaɪəˈlɪn/", meaning: "n. 小提琴", example: "She plays the violin." },
    { word: "visit", syllables: ["vis","it"], phonetic: "/ˈvɪzɪt/", meaning: "n. & v. 参观；访问；拜访", example: "I visited my grandma." },
    { word: "visitor", syllables: ["vis","i","tor"], phonetic: "/ˈvɪzɪtər/", meaning: "n. 参观者；访问者", example: "The museum has many visitors." },
    { word: "voice", syllables: ["voice"], phonetic: "/vɔɪs/", meaning: "n. 嗓音", example: "She has a beautiful voice." },
    { word: "volleyball", syllables: ["volleyball"], phonetic: "", meaning: "n. 排球", example: "The word 'volleyball' means n. 排球." },
    { word: "volunteer", syllables: ["vol","un","teer"], phonetic: "/ˌvɒlənˈtɪr/", meaning: "n. 志愿者; v. 自愿(做)；自愿提供", example: "She works as a volunteer." },
    { word: "wait", syllables: ["wait"], phonetic: "/weɪt/", meaning: "v. 等，等候", example: "Wait for me!" },
    { word: "waiter", syllables: ["waiter"], phonetic: "", meaning: "n. 侍者，服务员", example: "The word 'waiter' means n. 侍者." },
    { word: "waitress", syllables: ["waitress"], phonetic: "", meaning: "n. 女侍者；女服务员", example: "The word 'waitress' means n. 女侍者." },
    { word: "wake (woke, woken)", syllables: ["wake (woke, woken)"], phonetic: "", meaning: "v. 醒来，唤醒", example: "The word 'wake (woke, woken)' means v. 醒来." },
    { word: "walk", syllables: ["walk"], phonetic: "/wɔːk/", meaning: "n. & v. 步行；散步", example: "I walk to school every day." },
    { word: "wall", syllables: ["wall"], phonetic: "/wɔːl/", meaning: "n. 墙", example: "There is a picture on the wall." },
    { word: "want", syllables: ["want"], phonetic: "/wɒnt/", meaning: "v. 要，想要；需要", example: "I want to be a doctor." },
    { word: "war", syllables: ["war"], phonetic: "/wɔːr/", meaning: "n. 战争", example: "Nobody likes war." },
    { word: "warm", syllables: ["warm"], phonetic: "/wɔːrm/", meaning: "adj. 暖和的；热情的", example: "The weather is warm today." },
    { word: "warn", syllables: ["warn"], phonetic: "/wɔːrn/", meaning: "v. 警告；告诫", example: "I warned him not to go." },
    { word: "wash", syllables: ["wash"], phonetic: "/wɒʃ/", meaning: "v. 洗涤；洗", example: "Wash your hands before eating." },
    { word: "waste", syllables: ["waste"], phonetic: "/weɪst/", meaning: "v. 浪费; n. 浪费；废物；垃圾", example: "Don't waste water." },
    { word: "watch", syllables: ["watch"], phonetic: "/wɒtʃ/", meaning: "n. 手表，表; v. 观看，注视；当心", example: "I watch TV every evening." },
    { word: "water", syllables: ["wa","ter"], phonetic: "/ˈwɔːtər/", meaning: "n. 水; v. 浇水", example: "Drink more water." },
    { word: "wave", syllables: ["wave"], phonetic: "/weɪv/", meaning: "n. 波，波浪; v. 挥手，招手；挥动", example: "She waved goodbye." },
    { word: "way", syllables: ["way"], phonetic: "/weɪ/", meaning: "n. 路，路线；路途；方式，手段", example: "Which way should we go?" },
    { word: "weak", syllables: ["weak"], phonetic: "/wiːk/", meaning: "adj. 弱的，差的，淡的", example: "He is weak after the illness." }
  ],
  "第12组": [
    { word: "wealth", syllables: ["wealth"], phonetic: "/welθ/", meaning: "n. 财产，财富", example: "Health is more important than wealth." },
    { word: "wear (wore, worn)", syllables: ["wear (wore, worn)"], phonetic: "", meaning: "v. 穿；戴", example: "The word 'wear (wore, worn)' means v. 穿." },
    { word: "weather", syllables: ["weath","er"], phonetic: "/ˈweðər/", meaning: "n. 天气", example: "The weather is nice today." },
    { word: "web", syllables: ["web"], phonetic: "", meaning: "n. 网，网状物", example: "The word 'web' means n. 网." },
    { word: "website", syllables: ["web","site"], phonetic: "/ˈwebsaɪt/", meaning: "n. 网站", example: "Visit our website." },
    { word: "week", syllables: ["week"], phonetic: "/wiːk/", meaning: "n. 星期", example: "There are seven days in a week." },
    { word: "weekday", syllables: ["week","day"], phonetic: "/ˈwiːkdeɪ/", meaning: "n. 工作日", example: "I'm busy on weekdays." },
    { word: "weekend", syllables: ["week","end"], phonetic: "/ˌwiːkˈend/", meaning: "n. 周末", example: "What do you do on weekends?" },
    { word: "weigh", syllables: ["weigh"], phonetic: "/weɪ/", meaning: "v. 称……的重量；重", example: "How much do you weigh?" },
    { word: "weight", syllables: ["weight"], phonetic: "/weɪt/", meaning: "n. 重量", example: "What's your weight?" },
    { word: "welcome", syllables: ["wel","come"], phonetic: "/ˈwelkəm/", meaning: "n. 欢迎; adj. 受欢迎的; v. 欢迎; int. 欢迎", example: "Welcome to our school." },
    { word: "well (比较级 better，最高级 best)", syllables: ["well (比较级 better，最高级 best)"], phonetic: "", meaning: "adj. 健康的; adv. 好地，令人满意地；完全地; n. 井; int. (表示同意，惊讶等)好；", example: "The word 'well (比较级 better，最高级 best)' means adj. 健康的; adv. 好地." },
    { word: "west", syllables: ["west"], phonetic: "/west/", meaning: "n. 西部；西方; adj. 西方的；向西的", example: "The sun sets in the west." },
    { word: "western", syllables: ["west","ern"], phonetic: "/ˈwestərn/", meaning: "adj. 西方的", example: "I like western music." },
    { word: "wet", syllables: ["wet"], phonetic: "/wet/", meaning: "adj. 湿的，潮的；多雨的", example: "The ground is wet after rain." },
    { word: "what", syllables: ["what"], phonetic: "/wɒt/", meaning: "pron. (表示疑问)什么；(表示建议)怎么样; adv. (表示感叹)多么；(表示疑问)什么; conj. 引导宾语从句", example: "What is your name?" },
    { word: "when", syllables: ["when"], phonetic: "/wen/", meaning: "conj. & adv.            什么时候；当……的时候", example: "When is your birthday?" },
    { word: "where", syllables: ["where"], phonetic: "/wer/", meaning: "adv. 在哪里", example: "Where do you live?" },
    { word: "whether", syllables: ["wheth","er"], phonetic: "/ˈweðər/", meaning: "conj. 是否", example: "I don't know whether he will come." },
    { word: "which", syllables: ["which"], phonetic: "/wɪtʃ/", meaning: "adj. & pron.            那(哪)一个(些)", example: "Which one do you like?" },
    { word: "while", syllables: ["while"], phonetic: "/waɪl/", meaning: "conj. 在……的时候，正当……时; n. 一会儿", example: "I read while he sleeps." },
    { word: "white", syllables: ["white"], phonetic: "/waɪt/", meaning: "adj. 白色的; n. 白色", example: "Snow is white." },
    { word: "who", syllables: ["who"], phonetic: "/huː/", meaning: "pron. 谁", example: "Who is that man?" },
    { word: "whole", syllables: ["whole"], phonetic: "/hoʊl/", meaning: "adj. 整个的", example: "The whole class was quiet." },
    { word: "whom", syllables: ["whom"], phonetic: "/huːm/", meaning: "pron. 谁(who 的宾格)", example: "With whom did you go?" },
    { word: "whose", syllables: ["whose"], phonetic: "/huːz/", meaning: "pron. 谁的", example: "Whose bag is this?" },
    { word: "why", syllables: ["why"], phonetic: "/waɪ/", meaning: "adv. 为什么", example: "Why are you late?" },
    { word: "wide", syllables: ["wide"], phonetic: "/waɪd/", meaning: "adj. 宽的；广泛的", example: "The road is very wide." },
    { word: "widely", syllables: ["widely"], phonetic: "", meaning: "adv. 宽阔地；广泛地", example: "The word 'widely' means adv. 宽阔地." },
    { word: "widen", syllables: ["widen"], phonetic: "", meaning: "v. 拓宽", example: "The word 'widen' means v. 拓宽." },
    { word: "wife", syllables: ["wife"], phonetic: "/waɪf/", meaning: "n. 妻子", example: "His wife is a teacher." },
    { word: "wild", syllables: ["wild"], phonetic: "/waɪld/", meaning: "adj. 野生的；荒凉的", example: "Wild animals live in forests." },
    { word: "will aux .", syllables: ["will aux ."], phonetic: "", meaning: "v. 将，会；愿意；(表示提问)是否愿意；……好吗; n. 意志", example: "The word 'will aux .' means v. 将." },
    { word: "win (won, won)", syllables: ["win (won, won)"], phonetic: "", meaning: "v. 获胜；赢得", example: "The word 'win (won, won)' means v. 获胜." },
    { word: "wind", syllables: ["wind"], phonetic: "/wɪnd/", meaning: "n. 风", example: "The wind is blowing." },
    { word: "window", syllables: ["win","dow"], phonetic: "/ˈwɪndoʊ/", meaning: "n. 窗户；视窗", example: "Open the window, please." },
    { word: "windy", syllables: ["windy"], phonetic: "", meaning: "adj. 有风的，起风的", example: "The word 'windy' means adj. 有风的." },
    { word: "wine", syllables: ["wine"], phonetic: "/waɪn/", meaning: "n. 酒；葡萄酒", example: "He doesn't drink wine." },
    { word: "wing", syllables: ["wing"], phonetic: "/wɪŋ/", meaning: "n. 机翼；翅膀", example: "The bird spread its wings." },
    { word: "winner", syllables: ["win","ner"], phonetic: "/ˈwɪnər/", meaning: "n. 获胜者", example: "She is the winner." },
    { word: "winter", syllables: ["win","ter"], phonetic: "/ˈwɪntər/", meaning: "n. 冬天，冬季", example: "It snows in winter." },
    { word: "wisdom", syllables: ["wisdom"], phonetic: "", meaning: "n. 智慧", example: "The word 'wisdom' means n. 智慧." },
    { word: "wise", syllables: ["wise"], phonetic: "/waɪz/", meaning: "adj. 聪明的，明智的", example: "That's a wise decision." },
    { word: "wish", syllables: ["wish"], phonetic: "/wɪʃ/", meaning: "n. 愿望，祝愿; v. 希望，想要；祝愿", example: "I wish you good luck." },
    { word: "with", syllables: ["with"], phonetic: "/wɪð/", meaning: "prep. 与……一道；跟……一起；带有，具有；", example: "Come with me." },
    { word: "within", syllables: ["within"], phonetic: "", meaning: "prep. 在……范围内", example: "The word 'within' means prep. 在……范围内." },
    { word: "without", syllables: ["with","out"], phonetic: "/wɪˈðaʊt/", meaning: "prep. 没有", example: "I can't do it without you." },
    { word: "wolf", syllables: ["wolf"], phonetic: "", meaning: "n. 狼", example: "The word 'wolf' means n. 狼." },
    { word: "woman (复 women)", syllables: ["woman (复 women)"], phonetic: "", meaning: "n. 妇女，女人", example: "The word 'woman (复 women)' means n. 妇女." },
    { word: "wonder", syllables: ["won","der"], phonetic: "/ˈwʌndər/", meaning: "v. 对……疑惑；想知道; n. 奇迹，奇观", example: "I wonder where he is." }
  ],
  "第13组": [
    { word: "wonderful", syllables: ["won","der","ful"], phonetic: "/ˈwʌndərfl/", meaning: "adj. 美妙的，精彩的；太好了", example: "We had a wonderful time." },
    { word: "wood", syllables: ["wood"], phonetic: "/wʊd/", meaning: "n. 木头，木材；(复)树林", example: "The desk is made of wood." },
    { word: "wooden", syllables: ["wooden"], phonetic: "", meaning: "adj. 木质的", example: "The word 'wooden' means adj. 木质的." },
    { word: "word", syllables: ["word"], phonetic: "/wɜːrd/", meaning: "n. 词，单词；话", example: "Look up the word in the dictionary." },
    { word: "work", syllables: ["work"], phonetic: "/wɜːrk/", meaning: "v. 工作；(机器等)运转，活动; n. 工作，劳动；作品", example: "I work hard every day." },
    { word: "worker", syllables: ["work","er"], phonetic: "/ˈwɜːrkər/", meaning: "n. 工作者；工人", example: "The workers are building a house." },
    { word: "world", syllables: ["world"], phonetic: "/wɜːrld/", meaning: "n. 世界", example: "China is a big country in the world." },
    { word: "worry", syllables: ["wor","ry"], phonetic: "/ˈwʌri/", meaning: "v. 担心；烦恼; n. 烦恼，担忧", example: "Don't worry about it." },
    { word: "worth", syllables: ["worth"], phonetic: "/wɜːrθ/", meaning: "adj. 有……的价值；值得……的", example: "The book is worth reading." },
    { word: "would", syllables: ["would"], phonetic: "/wʊd/", meaning: "aux.      v. 愿意(will 的过去式)", example: "Would you like some tea?" },
    { word: "wound", syllables: ["wound"], phonetic: "/wuːnd/", meaning: "n. 创伤，伤口", example: "The wound is healing." },
    { word: "wounded", syllables: ["wounded"], phonetic: "", meaning: "adj. 受伤的", example: "The word 'wounded' means adj. 受伤的." },
    { word: "write (wrote, written)", syllables: ["write (wrote, written)"], phonetic: "", meaning: "v. 写；写作；写信", example: "The word 'write (wrote, written)' means v. 写." },
    { word: "writer", syllables: ["writer"], phonetic: "", meaning: "n. 作家", example: "The word 'writer' means n. 作家." },
    { word: "wrong", syllables: ["wrong"], phonetic: "/rɒŋ/", meaning: "adj. 错误的；不正常的；有病的", example: "What's wrong with you?" },
    { word: "year", syllables: ["year"], phonetic: "/jɪr/", meaning: "n. 年", example: "I am twelve years old." },
    { word: "yellow", syllables: ["yel","low"], phonetic: "/ˈjeloʊ/", meaning: "adj. 黄色的; n. 黄色", example: "Bananas are yellow." },
    { word: "yesterday", syllables: ["yes","ter","day"], phonetic: "/ˈjestərdeɪ/", meaning: "n. & adv.             昨天", example: "I went shopping yesterday." },
    { word: "yet", syllables: ["yet"], phonetic: "/jet/", meaning: "adv. 尚，还，仍然", example: "I haven't finished yet." },
    { word: "yogurt", syllables: ["yogurt"], phonetic: "", meaning: "n. 酸奶", example: "The word 'yogurt' means n. 酸奶." },
    { word: "young", syllables: ["young"], phonetic: "/jʌŋ/", meaning: "adj. 年轻的", example: "She is very young." },
    { word: "zero", syllables: ["ze","ro"], phonetic: "/ˈzɪroʊ/", meaning: "n. & num. 零；零度；零点", example: "The temperature is zero." },
    { word: "zoo", syllables: ["zoo"], phonetic: "/zuː/", meaning: "n. 动物园", example: "Let's go to the zoo." }
  ]
};