const WORDS_ZK_AF = {
  "第1组": [
    { word: "ability", syllables: ["a","bil","i","ty"], phonetic: "/əˈbɪləti/", meaning: "n. 能力，才能", example: "She has the ability to solve problems." },
    { word: "able", syllables: ["a","ble"], phonetic: "/ˈeɪbl/", meaning: "adj. 能够；有能力的", example: "Are you able to come tomorrow?" },
    { word: "about", syllables: ["a","bout"], phonetic: "/əˈbaʊt/", meaning: "adv. 大约；到处，四处; prep. 关于", example: "Tell me about your family." },
    { word: "above", syllables: ["a","bove"], phonetic: "/əˈbʌv/", meaning: "prep. 在……上面", example: "The picture hangs above the sofa." },
    { word: "abroad", syllables: ["a","broad"], phonetic: "/əˈbrɔːd/", meaning: "adv. 到(在)国外", example: "She went abroad to study English." },
    { word: "accept", syllables: ["ac","cept"], phonetic: "/əkˈsept/", meaning: "v. 接受", example: "Please accept my apology." },
    { word: "accident", syllables: ["ac","ci","dent"], phonetic: "/ˈæksɪdənt/", meaning: "n. 事故，意外的事", example: "There was a car accident on the road." },
    { word: "accurate", syllables: ["accurate"], phonetic: "", meaning: "adj. 准确的", example: "The word 'accurate' means adj. 准确的." },
    { word: "ache", syllables: ["ache"], phonetic: "", meaning: "n. 疼；痛", example: "The word 'ache' means n. 疼." },
    { word: "achieve", syllables: ["a","chieve"], phonetic: "/əˈtʃiːv/", meaning: "v. 达到，获得", example: "Work hard to achieve your dream." },
    { word: "across", syllables: ["a","cross"], phonetic: "/əˈkrɔːs/", meaning: "prep. 横过，穿过", example: "Walk across the bridge." },
    { word: "act", syllables: ["act"], phonetic: "/ækt/", meaning: "v. 表演，扮演(角色)；行动", example: "Think before you act." },
    { word: "active", syllables: ["ac","tive"], phonetic: "/ˈæktɪv/", meaning: "adj. 积极的；活跃的", example: "She is very active in class." },
    { word: "activity", syllables: ["ac","tiv","i","ty"], phonetic: "/ækˈtɪvəti/", meaning: "n. 活动", example: "What activities do you like?" },
    { word: "actor", syllables: ["actor"], phonetic: "", meaning: "n. 男演员", example: "The word 'actor' means n. 男演员." },
    { word: "actress", syllables: ["actress"], phonetic: "", meaning: "n. 女演员", example: "The word 'actress' means n. 女演员." },
    { word: "actually", syllables: ["actually"], phonetic: "", meaning: "adv. 实际上； 现实地", example: "The word 'actually' means adv. 实际上." },
    { word: "add", syllables: ["add"], phonetic: "/æd/", meaning: "v. 添加，增加", example: "Please add some sugar to the coffee." },
    { word: "addition", syllables: ["addition"], phonetic: "", meaning: "n. 增加", example: "The word 'addition' means n. 增加." },
    { word: "address", syllables: ["ad","dress"], phonetic: "/əˈdres/", meaning: "n. 地址", example: "What is your home address?" },
    { word: "adult", syllables: ["a","dult"], phonetic: "/ˈædʌlt/", meaning: "n. & adj. 成年人", example: "This movie is for adults only." },
    { word: "advantage", syllables: ["advantage"], phonetic: "", meaning: "n. 有利条件；优势；优点", example: "The word 'advantage' means n. 有利条件." },
    { word: "adventure", syllables: ["adventure"], phonetic: "", meaning: "n. 冒险；冒险经历；冒险精神", example: "The word 'adventure' means n. 冒险." },
    { word: "advertisement", syllables: ["advertisement"], phonetic: "", meaning: "n. 广告", example: "The word 'advertisement' means n. 广告." },
    { word: "advice", syllables: ["ad","vice"], phonetic: "/ədˈvaɪs/", meaning: "n. 忠告，劝告，建议", example: "Can you give me some advice?" },
    { word: "advise", syllables: ["ad","vise"], phonetic: "/ədˈvaɪz/", meaning: "v. 劝告，建议", example: "I advise you to study harder." },
    { word: "afford", syllables: ["afford"], phonetic: "", meaning: "v. 负担得起，抽得出(时间)", example: "The word 'afford' means v. 负担得起." },
    { word: "afraid", syllables: ["a","fraid"], phonetic: "/əˈfreɪd/", meaning: "adj. 害怕的；担心的", example: "Don't be afraid of the dark." },
    { word: "after", syllables: ["af","ter"], phonetic: "/ˈæftər/", meaning: "prep. 在……之后；在……后面; adv. 在后；后来; conj. 在……以后", example: "We play football after school." },
    { word: "afternoon", syllables: ["af","ter","noon"], phonetic: "/ˌæftərˈnuːn/", meaning: "n. 下午", example: "Good afternoon, everyone!" },
    { word: "again", syllables: ["a","gain"], phonetic: "/əˈɡen/", meaning: "adv. 再一次；再，又", example: "Please say that again." },
    { word: "against", syllables: ["a","gainst"], phonetic: "/əˈɡenst/", meaning: "prep. 对着；反对", example: "Are you for or against the plan?" },
    { word: "age", syllables: ["age"], phonetic: "/eɪdʒ/", meaning: "n. 年龄；时代", example: "What is your age?" },
    { word: "aged", syllables: ["aged"], phonetic: "", meaning: "adj. 有……年岁的；上年龄的", example: "The word 'aged' means adj. 有……年岁的." },
    { word: "ago", syllables: ["a","go"], phonetic: "/əˈɡoʊ/", meaning: "adv. 以前", example: "I lived here five years ago." },
    { word: "agree", syllables: ["a","gree"], phonetic: "/əˈɡriː/", meaning: "v. 同意；应允", example: "I agree with you." },
    { word: "ahead", syllables: ["a","head"], phonetic: "/əˈhed/", meaning: "adv. 在前，向前", example: "Go straight ahead." },
    { word: "aim", syllables: ["aim"], phonetic: "", meaning: "n. 目的；目标; v. 打算；瞄准", example: "The word 'aim' means n. 目的." },
    { word: "air", syllables: ["air"], phonetic: "/er/", meaning: "n. 空气；大气", example: "The air is fresh in the morning." },
    { word: "airline", syllables: ["airline"], phonetic: "", meaning: "n. 航线", example: "The word 'airline' means n. 航线." },
    { word: "airport", syllables: ["air","port"], phonetic: "/ˈerpɔːrt/", meaning: "n. 机场", example: "We arrived at the airport early." },
    { word: "alarm", syllables: ["alarm"], phonetic: "", meaning: "n. 警报", example: "The word 'alarm' means n. 警报." },
    { word: "alive", syllables: ["a","live"], phonetic: "/əˈlaɪv/", meaning: "adj. 活着的，存在的", example: "The fish is still alive." },
    { word: "all", syllables: ["all"], phonetic: "/ɔːl/", meaning: "adj. 全(部)；总；整; adv. 全部地; pron. 全部；全体人员; n. 全部；全体人员", example: "All the students are here." },
    { word: "allow", syllables: ["al","low"], phonetic: "/əˈlaʊ/", meaning: "v. 允许，准许", example: "My parents allow me to watch TV." },
    { word: "almost", syllables: ["al","most"], phonetic: "/ˈɔːlmoʊst/", meaning: "adv. 几乎，差不多", example: "It is almost time to go." },
    { word: "alone", syllables: ["a","lone"], phonetic: "/əˈloʊn/", meaning: "adj. 单独的; adv. 单独地", example: "She lives alone." },
    { word: "along", syllables: ["a","long"], phonetic: "/əˈlɔːŋ/", meaning: "prep. 沿着；顺着", example: "Walk along this road." },
    { word: "already", syllables: ["al","rea","dy"], phonetic: "/ɔːlˈredi/", meaning: "adv. 已经", example: "I have already finished my homework." },
    { word: "also", syllables: ["al","so"], phonetic: "/ˈɔːlsoʊ/", meaning: "adv. 也", example: "She also likes music." }
  ],
  "第2组": [
    { word: "although/though", syllables: ["although/though"], phonetic: "", meaning: "conj. 虽然，尽管", example: "The word 'although/though' means conj. 虽然." },
    { word: "altogether", syllables: ["altogether"], phonetic: "", meaning: "adv. 总共；全部地", example: "The word 'altogether' means adv. 总共." },
    { word: "always", syllables: ["al","ways"], phonetic: "/ˈɔːlweɪz/", meaning: "adv. 总是；一直；永远", example: "She always gets up early." },
    { word: "A.M. (a.m.) 上午", syllables: ["A.M. (a.m.) 上午"], phonetic: "", meaning: "", example: "The word 'A.M. (a.m.) 上午' means ." },
    { word: "amazing", syllables: ["a","ma","zing"], phonetic: "/əˈmeɪzɪŋ/", meaning: "adj. 令人惊讶的；令人赞叹的", example: "The magic show was amazing." },
    { word: "ambition", syllables: ["ambition"], phonetic: "", meaning: "n. 雄心；野心", example: "The word 'ambition' means n. 雄心." },
    { word: "among", syllables: ["a","mong"], phonetic: "/əˈmʌŋ/", meaning: "prep. 在……中间；在(三个以上)之间", example: "She sat among her friends." },
    { word: "amount", syllables: ["amount"], phonetic: "", meaning: "n. 数量，总数", example: "The word 'amount' means n. 数量." },
    { word: "amusement", syllables: ["amusement"], phonetic: "", meaning: "n. 娱乐；消遣；娱乐活动", example: "The word 'amusement' means n. 娱乐." },
    { word: "amusing", syllables: ["amusing"], phonetic: "", meaning: "adj. 引起乐趣的", example: "The word 'amusing' means adj. 引起乐趣的." },
    { word: "ancient", syllables: ["an","cient"], phonetic: "/ˈeɪnʃənt/", meaning: "adj. 古代的，古老的", example: "China has an ancient history." },
    { word: "and", syllables: ["and"], phonetic: "", meaning: "conj. 和；又；而", example: "The word 'and' means conj. 和." },
    { word: "angrily", syllables: ["angrily"], phonetic: "", meaning: "adv. 生气地；愤怒地", example: "The word 'angrily' means adv. 生气地." },
    { word: "angry", syllables: ["an","gry"], phonetic: "/ˈæŋɡri/", meaning: "adj. 生气的，愤怒的", example: "Don't be angry with me." },
    { word: "animal", syllables: ["an","i","mal"], phonetic: "/ˈænɪml/", meaning: "n. 动物", example: "My favorite animal is the panda." },
    { word: "another", syllables: ["a","no","ther"], phonetic: "/əˈnʌðər/", meaning: "adj. 再一；另一；别的；不同的; pron. 另一个", example: "Would you like another cup of tea?" },
    { word: "answer", syllables: ["an","swer"], phonetic: "/ˈænsər/", meaning: "n. 回答；答复；答案；回(信); v. 回答；答复；回(信)", example: "Can you answer the question?" },
    { word: "any", syllables: ["a","ny"], phonetic: "/ˈeni/", meaning: "adj. (用于疑问句、否定句、条件句)一些，什么；任何的，任一的; pron. (无论)哪一个；(无论)哪些", example: "Do you have any questions?" },
    { word: "anybody/anyone", syllables: ["anybody/anyone"], phonetic: "", meaning: "pron. 任何人，无论谁", example: "The word 'anybody/anyone' means pron. 任何人." },
    { word: "anything", syllables: ["any","thing"], phonetic: "/ˈeniθɪŋ/", meaning: "pron. 什么事(物)；任何事(物)", example: "I didn't eat anything this morning." },
    { word: "anywhere", syllables: ["any","where"], phonetic: "/ˈeniwer/", meaning: "adv. 任何地方", example: "I can't find it anywhere." },
    { word: "apologize", syllables: ["apologize"], phonetic: "", meaning: "vi. 道歉", example: "The word 'apologize' means vi. 道歉." },
    { word: "appear", syllables: ["ap","pear"], phonetic: "/əˈpɪr/", meaning: "v. 出现", example: "A rainbow appeared in the sky." },
    { word: "apple", syllables: ["ap","ple"], phonetic: "/ˈæpl/", meaning: "n. 苹果", example: "An apple a day keeps the doctor away." },
    { word: "apply", syllables: ["apply"], phonetic: "", meaning: "v. 申请；应用", example: "The word 'apply' means v. 申请." },
    { word: "area", syllables: ["ar","e","a"], phonetic: "/ˈeriə/", meaning: "n. 面积；范围；地区", example: "This area is very quiet." },
    { word: "argue", syllables: ["argue"], phonetic: "", meaning: "v. 争吵，争论", example: "The word 'argue' means v. 争吵." },
    { word: "arm", syllables: ["arm"], phonetic: "/ɑːrm/", meaning: "n. 手臂", example: "She broke her arm last week." },
    { word: "army", syllables: ["ar","my"], phonetic: "/ˈɑːrmi/", meaning: "n. 军队", example: "He joined the army last year." },
    { word: "around", syllables: ["a","round"], phonetic: "/əˈraʊnd/", meaning: "adv. 在周围；环绕; prep. 在……周围", example: "Look around the room." },
    { word: "arrange", syllables: ["arrange"], phonetic: "", meaning: "v. 安排；布置", example: "The word 'arrange' means v. 安排." },
    { word: "arrival", syllables: ["arrival"], phonetic: "", meaning: "n. 到达", example: "The word 'arrival' means n. 到达." },
    { word: "arrive", syllables: ["ar","rive"], phonetic: "/əˈraɪv/", meaning: "v. 到达；达到", example: "We arrived at the station at eight." },
    { word: "art", syllables: ["art"], phonetic: "/ɑːrt/", meaning: "n. 艺术", example: "She is good at art." },
    { word: "article", syllables: ["ar","ti","cle"], phonetic: "/ˈɑːrtɪkl/", meaning: "n. 文章", example: "I read an interesting article today." },
    { word: "artist", syllables: ["artist"], phonetic: "", meaning: "n. 艺术家；画家", example: "The word 'artist' means n. 艺术家." },
    { word: "as", syllables: ["as"], phonetic: "/æz/", meaning: "conj. 像……一样；如同；因为；当……时; prep. 作为，当作；当……时; adv. 同样地", example: "She works as a teacher." },
    { word: "ask", syllables: ["ask"], phonetic: "/æsk/", meaning: "v. 问，询问；请求，要求", example: "May I ask you a question?" },
    { word: "assistant", syllables: ["assistant"], phonetic: "", meaning: "n. 助手，助理", example: "The word 'assistant' means n. 助手." },
    { word: "at", syllables: ["at"], phonetic: "/æt/", meaning: "prep. 在(几点钟)；在(某处)；(表示动作的目标和方向)", example: "I get up at seven o'clock." },
    { word: "attack", syllables: ["attack"], phonetic: "", meaning: "v. 进攻，袭击", example: "The word 'attack' means v. 进攻." },
    { word: "attend", syllables: ["attend"], phonetic: "", meaning: "v. 出席，参加", example: "The word 'attend' means v. 出席." },
    { word: "attention", syllables: ["at","ten","tion"], phonetic: "/əˈtenʃn/", meaning: "n. 注意，关心", example: "Please pay attention to the teacher." },
    { word: "attitude", syllables: ["attitude"], phonetic: "", meaning: "n. 态度", example: "The word 'attitude' means n. 态度." },
    { word: "attract", syllables: ["attract"], phonetic: "", meaning: "v. 吸引；引起", example: "The word 'attract' means v. 吸引." },
    { word: "attractive", syllables: ["attractive"], phonetic: "", meaning: "adj. 有吸引力的", example: "The word 'attractive' means adj. 有吸引力的." },
    { word: "audience", syllables: ["audience"], phonetic: "", meaning: "n. 观众；听众", example: "The word 'audience' means n. 观众." },
    { word: "aunt", syllables: ["aunt"], phonetic: "/ænt/", meaning: "n. 姑；姨；伯母；舅母；婶", example: "My aunt lives in Beijing." },
    { word: "automatic", syllables: ["automatic"], phonetic: "", meaning: "adj. 自动的", example: "The word 'automatic' means adj. 自动的." },
    { word: "autumn", syllables: ["au","tumn"], phonetic: "/ˈɔːtəm/", meaning: "n. 秋天，秋季", example: "Autumn is a beautiful season." }
  ],
  "第3组": [
    { word: "available", syllables: ["available"], phonetic: "", meaning: "adj. 可用的；可得到的", example: "The word 'available' means adj. 可用的." },
    { word: "average", syllables: ["average"], phonetic: "", meaning: "adj. 平均的；普通的; n. 平均数", example: "The word 'average' means adj. 平均的." },
    { word: "avoid", syllables: ["avoid"], phonetic: "", meaning: "v. 避免；避开", example: "The word 'avoid' means v. 避免." },
    { word: "award", syllables: ["award"], phonetic: "", meaning: "n. 奖品，奖励; v. 授予", example: "The word 'award' means n. 奖品." },
    { word: "away", syllables: ["a","way"], phonetic: "/əˈweɪ/", meaning: "adv. 离开；远离", example: "Please go away." },
    { word: "awful", syllables: ["awful"], phonetic: "", meaning: "adj. 可怕的", example: "The word 'awful' means adj. 可怕的." },
    { word: "baby", syllables: ["ba","by"], phonetic: "/ˈbeɪbi/", meaning: "n. 婴儿", example: "The baby is very cute." },
    { word: "back", syllables: ["back"], phonetic: "/bæk/", meaning: "adv. 回(原处)；向后; n. 背后，后部；背", example: "I will be back soon." },
    { word: "background", syllables: ["background"], phonetic: "", meaning: "n. 背景", example: "The word 'background' means n. 背景." },
    { word: "bad (比较级 worse，最高级 worst)", syllables: ["bad (比较级 worse，最高级 worst)"], phonetic: "", meaning: "adj. 坏的；有害的，不利的；", example: "The word 'bad (比较级 worse，最高级 worst)' means adj. 坏的." },
    { word: "bag", syllables: ["bag"], phonetic: "/bæɡ/", meaning: "n. 书包；提包；袋子", example: "This is my school bag." },
    { word: "bakery", syllables: ["bakery"], phonetic: "", meaning: "n. 面包店", example: "The word 'bakery' means n. 面包店." },
    { word: "balance", syllables: ["balance"], phonetic: "", meaning: "n. 平衡", example: "The word 'balance' means n. 平衡." },
    { word: "ball", syllables: ["ball"], phonetic: "/bɔːl/", meaning: "n. 球", example: "Let's play with the ball." },
    { word: "balloon", syllables: ["balloon"], phonetic: "", meaning: "n. 气球", example: "The word 'balloon' means n. 气球." },
    { word: "banana", syllables: ["ba","na","na"], phonetic: "/bəˈnænə/", meaning: "n. 香蕉", example: "Monkeys like bananas." },
    { word: "bank", syllables: ["bank"], phonetic: "/bæŋk/", meaning: "n. 银行", example: "I need to go to the bank." },
    { word: "bar", syllables: ["bar"], phonetic: "", meaning: "n. 酒吧", example: "The word 'bar' means n. 酒吧." },
    { word: "base", syllables: ["base"], phonetic: "", meaning: "n. 根据地，基地；基础", example: "The word 'base' means n. 根据地." },
    { word: "basic", syllables: ["ba","sic"], phonetic: "/ˈbeɪsɪk/", meaning: "adj. 基本的；基础的", example: "Food is a basic need." },
    { word: "basket", syllables: ["bas","ket"], phonetic: "/ˈbæskɪt/", meaning: "n. 篮子", example: "She carried a basket of flowers." },
    { word: "basketball", syllables: ["bas","ket","ball"], phonetic: "/ˈbæskɪtbɔːl/", meaning: "n. 篮球", example: "He likes playing basketball." },
    { word: "bath", syllables: ["bath"], phonetic: "", meaning: "n. 洗澡", example: "The word 'bath' means n. 洗澡." },
    { word: "bathroom", syllables: ["bathroom"], phonetic: "", meaning: "n. 浴室；盥洗室；厕所", example: "The word 'bathroom' means n. 浴室." },
    { word: "battery", syllables: ["battery"], phonetic: "", meaning: "n. 电池，蓄电池", example: "The word 'battery' means n. 电池." },
    { word: "battle", syllables: ["battle"], phonetic: "", meaning: "n. 战斗；战役", example: "The word 'battle' means n. 战斗." },
    { word: "be", syllables: ["be"], phonetic: "/biː/", meaning: "v. 是；成为(原形，其人称和时态形式有 am, is, are, was, were,", example: "I want to be a doctor." },
    { word: "beach", syllables: ["beach"], phonetic: "/biːtʃ/", meaning: "n. 海滨，海滩", example: "We played on the beach." },
    { word: "bear", syllables: ["bear"], phonetic: "/ber/", meaning: "n. 熊", example: "The bear lives in the forest." },
    { word: "beat (beat, beaten)", syllables: ["beat (beat, beaten)"], phonetic: "", meaning: "v. 敲打；跳动；打赢", example: "The word 'beat (beat, beaten)' means v. 敲打." },
    { word: "beautiful", syllables: ["beau","ti","ful"], phonetic: "/ˈbjuːtɪfl/", meaning: "adj. 美丽的", example: "What a beautiful day!" },
    { word: "beautifully", syllables: ["beautifully"], phonetic: "", meaning: "adv. 优美地", example: "The word 'beautifully' means adv. 优美地." },
    { word: "beauty", syllables: ["beauty"], phonetic: "", meaning: "n. 美", example: "The word 'beauty' means n. 美." },
    { word: "because", syllables: ["be","cause"], phonetic: "/bɪˈkɔːz/", meaning: "conj. 因为", example: "I stayed home because it rained." },
    { word: "become (became, become)", syllables: ["become (became, become)"], phonetic: "", meaning: "v. 变得；成为", example: "The word 'become (became, become)' means v. 变得." },
    { word: "bed", syllables: ["bed"], phonetic: "/bed/", meaning: "n. 床", example: "It is time to go to bed." },
    { word: "bedroom", syllables: ["bed","room"], phonetic: "/ˈbedruːm/", meaning: "n. 卧室", example: "My bedroom is very clean." },
    { word: "beef", syllables: ["beef"], phonetic: "/biːf/", meaning: "n. 牛肉", example: "I had beef for lunch." },
    { word: "before", syllables: ["be","fore"], phonetic: "/bɪˈfɔːr/", meaning: "prep. 在……以前；在……前面; adv. 以前; conj. 在……之前", example: "Wash your hands before eating." },
    { word: "beg", syllables: ["beg"], phonetic: "", meaning: "v. 请求，乞求，乞讨", example: "The word 'beg' means v. 请求." },
    { word: "begin (began, begun)", syllables: ["begin (began, begun)"], phonetic: "", meaning: "v. 开始，着手", example: "The word 'begin (began, begun)' means v. 开始." },
    { word: "beginning", syllables: ["beginning"], phonetic: "", meaning: "n. 开始；开端", example: "The word 'beginning' means n. 开始." },
    { word: "behavior", syllables: ["behavior"], phonetic: "", meaning: "n. 行为，举止", example: "The word 'behavior' means n. 行为." },
    { word: "behind", syllables: ["be","hind"], phonetic: "/bɪˈhaɪnd/", meaning: "prep. 在……后面; adv. 在后面；向后", example: "The park is behind the school." },
    { word: "being", syllables: ["being"], phonetic: "", meaning: "n. 生物；人", example: "The word 'being' means n. 生物." },
    { word: "believe", syllables: ["be","lieve"], phonetic: "/bɪˈliːv/", meaning: "v. 相信，认为", example: "I believe you can do it." },
    { word: "bell", syllables: ["bell"], phonetic: "/bel/", meaning: "n. 钟，铃", example: "The bell is ringing." },
    { word: "belong", syllables: ["belong"], phonetic: "", meaning: "v. 属；附属", example: "The word 'belong' means v. 属." },
    { word: "below", syllables: ["be","low"], phonetic: "/bɪˈloʊ/", meaning: "prep. 在……下面", example: "The temperature is below zero." },
    { word: "belt", syllables: ["belt"], phonetic: "", meaning: "n. (皮)带；带子", example: "The word 'belt' means n. (皮)带." }
  ],
  "第4组": [
    { word: "beside", syllables: ["be","side"], phonetic: "/bɪˈsaɪd/", meaning: "prep. 在……旁边；靠近", example: "Come and sit beside me." },
    { word: "besides", syllables: ["be","sides"], phonetic: "/bɪˈsaɪdz/", meaning: "prep. 除……以外(还有); adv. 还有，此外", example: "Besides English, I study math." },
    { word: "best (good, well 的最高级)", syllables: ["best (good, well 的最高级)"], phonetic: "", meaning: "adj. & adv.                   最好的；最好地，最; n. 最好的(人或物)", example: "The word 'best (good, well 的最高级)' means adj. & adv.                   最好的." },
    { word: "better (good, well 的比较级)", syllables: ["better (good, well 的比较级)"], phonetic: "", meaning: "adj. & adv. 较好的，更好的；更好地; n. 较好的事物；较优者", example: "The word 'better (good, well 的比较级)' means adj. & adv. 较好的." },
    { word: "between", syllables: ["be","tween"], phonetic: "/bɪˈtwiːn/", meaning: "prep. 在(两者)之间；在……中间", example: "Sit between Tom and me." },
    { word: "bicycle/bike", syllables: ["bicycle/bike"], phonetic: "", meaning: "n. 自行车", example: "The word 'bicycle/bike' means n. 自行车." },
    { word: "big", syllables: ["big"], phonetic: "/bɪɡ/", meaning: "adj. 大的", example: "This is a big house." },
    { word: "bill", syllables: ["bill"], phonetic: "/bɪl/", meaning: "n. 账单；钞票，纸币", example: "Let me pay the bill." },
    { word: "bin", syllables: ["bin"], phonetic: "", meaning: "n. 箱子；垃圾箱", example: "The word 'bin' means n. 箱子." },
    { word: "bird", syllables: ["bird"], phonetic: "/bɜːrd/", meaning: "n. 鸟", example: "The bird is singing in the tree." },
    { word: "birthday", syllables: ["birth","day"], phonetic: "/ˈbɜːrθdeɪ/", meaning: "n. 生日", example: "Happy birthday to you!" },
    { word: "biscuit", syllables: ["bis","cuit"], phonetic: "/ˈbɪskɪt/", meaning: "n. 饼干", example: "Would you like a biscuit?" },
    { word: "bit", syllables: ["bit"], phonetic: "/bɪt/", meaning: "n. 一点；一些；少量的", example: "I am a bit tired." },
    { word: "bite (bit, bitten)", syllables: ["bite (bit, bitten)"], phonetic: "", meaning: "v. 咬；叮", example: "The word 'bite (bit, bitten)' means v. 咬." },
    { word: "black", syllables: ["black"], phonetic: "/blæk/", meaning: "n. 黑色; adj. 黑色的", example: "She wears a black dress." },
    { word: "blackboard", syllables: ["blackboard"], phonetic: "", meaning: "n. 黑板", example: "The word 'blackboard' means n. 黑板." },
    { word: "blanket", syllables: ["blanket"], phonetic: "", meaning: "n. 毯子", example: "The word 'blanket' means n. 毯子." },
    { word: "blind", syllables: ["blind"], phonetic: "/blaɪnd/", meaning: "adj. 瞎的; n. 盲人", example: "The old man is blind." },
    { word: "block", syllables: ["block"], phonetic: "/blɑːk/", meaning: "n. 一排房屋；街区(街道中间的区域)；大块; v. 阻止", example: "The school is two blocks away." },
    { word: "blood", syllables: ["blood"], phonetic: "/blʌd/", meaning: "n. 血，血液", example: "He gave blood to help others." },
    { word: "blow (blew, blown)", syllables: ["blow (blew, blown)"], phonetic: "", meaning: "v. 吹；刮风；吹气", example: "The word 'blow (blew, blown)' means v. 吹." },
    { word: "blue", syllables: ["blue"], phonetic: "/bluː/", meaning: "n. 蓝色; adj. 蓝色的", example: "The sky is blue today." },
    { word: "board", syllables: ["board"], phonetic: "/bɔːrd/", meaning: "n. 板；木板；; v. 登，上(船、火车、飞机等)", example: "Please write on the blackboard." },
    { word: "boat", syllables: ["boat"], phonetic: "/boʊt/", meaning: "n. 小船，小舟; v. 划船(游玩)", example: "We went across the river by boat." },
    { word: "body", syllables: ["bo","dy"], phonetic: "/ˈbɑːdi/", meaning: "n. 身体", example: "Exercise is good for your body." },
    { word: "boil", syllables: ["boil"], phonetic: "", meaning: "v. 沸腾；煮", example: "The word 'boil' means v. 沸腾." },
    { word: "book", syllables: ["book"], phonetic: "/bʊk/", meaning: "n. 书；本子; v. 预订，订(房间、车票、座位等)", example: "I am reading a book." },
    { word: "bored", syllables: ["bored"], phonetic: "", meaning: "adj. 感到乏味的；厌倦的", example: "The word 'bored' means adj. 感到乏味的." },
    { word: "boring", syllables: ["bor","ing"], phonetic: "/ˈbɔːrɪŋ/", meaning: "adj. 乏味的；无聊的；令人厌烦的", example: "The movie was boring." },
    { word: "born (动词 bear 的过去分词) 出生", syllables: ["born (动词 bear 的过去分词) 出生"], phonetic: "", meaning: "", example: "The word 'born (动词 bear 的过去分词) 出生' means ." },
    { word: "borrow", syllables: ["bor","row"], phonetic: "/ˈbɑːroʊ/", meaning: "v. (向别人)借用；借", example: "Can I borrow your pen?" },
    { word: "both", syllables: ["both"], phonetic: "/boʊθ/", meaning: "pron. 两者(都)；双方(都); adj. (两)……都；双; adv. 两个都", example: "Both of them are students." },
    { word: "bottle", syllables: ["bot","tle"], phonetic: "/ˈbɑːtl/", meaning: "n. 瓶子", example: "Please buy a bottle of water." },
    { word: "bottom", syllables: ["bot","tom"], phonetic: "/ˈbɑːtəm/", meaning: "n. 底部", example: "The cat is at the bottom of the stairs." },
    { word: "bowl", syllables: ["bowl"], phonetic: "/boʊl/", meaning: "n. 碗", example: "I had a bowl of rice for lunch." },
    { word: "box", syllables: ["box"], phonetic: "/bɑːks/", meaning: "n. 盒子；箱子", example: "The box is very heavy." },
    { word: "boy", syllables: ["boy"], phonetic: "/bɔɪ/", meaning: "n. 男孩", example: "The boy is playing soccer." },
    { word: "brain", syllables: ["brain"], phonetic: "/breɪn/", meaning: "n. 脑", example: "Use your brain to think." },
    { word: "brave", syllables: ["brave"], phonetic: "/breɪv/", meaning: "adj. 勇敢的", example: "The soldier was very brave." },
    { word: "bread", syllables: ["bread"], phonetic: "/bred/", meaning: "n. 面包", example: "I had bread for breakfast." },
    { word: "break (broke, broken)", syllables: ["break (broke, broken)"], phonetic: "", meaning: "v. 打破(断，碎)；损坏; n. 休息；间隙", example: "The word 'break (broke, broken)' means v. 打破(断." },
    { word: "breakfast", syllables: ["break","fast"], phonetic: "/ˈbrekfəst/", meaning: "n. 早餐", example: "I have breakfast at seven." },
    { word: "breath", syllables: ["breath"], phonetic: "/breθ/", meaning: "n. 呼吸， 一口气；气息", example: "Take a deep breath." },
    { word: "breathe", syllables: ["breathe"], phonetic: "/briːð/", meaning: "v. 呼吸", example: "It is hard to breathe in the smoke." },
    { word: "bridge", syllables: ["bridge"], phonetic: "/brɪdʒ/", meaning: "n. 桥", example: "We walked across the bridge." },
    { word: "bright", syllables: ["bright"], phonetic: "/braɪt/", meaning: "adj. 明亮的；聪明的；灿烂的", example: "The room is very bright." },
    { word: "bring (brought, brought)", syllables: ["bring (brought, brought)"], phonetic: "", meaning: "v. 拿来，带来", example: "The word 'bring (brought, brought)' means v. 拿来." },
    { word: "broadcast", syllables: ["broadcast"], phonetic: "", meaning: "n. 广播节目", example: "The word 'broadcast' means n. 广播节目." },
    { word: "brother", syllables: ["bro","ther"], phonetic: "/ˈbrʌðər/", meaning: "n. 兄；弟", example: "My brother is older than me." },
    { word: "brown", syllables: ["brown"], phonetic: "/braʊn/", meaning: "n. 褐色，棕色; adj. 褐色的，棕色的", example: "He has brown hair." }
  ],
  "第5组": [
    { word: "brush", syllables: ["brush"], phonetic: "/brʌʃ/", meaning: "v. 刷；擦; n. 刷子", example: "Brush your teeth every day." },
    { word: "build (built, built)", syllables: ["build (built, built)"], phonetic: "", meaning: "v. 建筑；建造", example: "The word 'build (built, built)' means v. 建筑." },
    { word: "building", syllables: ["buil","ding"], phonetic: "/ˈbɪldɪŋ/", meaning: "n. 建筑物，大楼", example: "That building is very tall." },
    { word: "bund (the Bund)", syllables: ["bund (the Bund)"], phonetic: "", meaning: "n. 外滩", example: "The word 'bund (the Bund)' means n. 外滩." },
    { word: "burn (burned, burned 或 burnt, burnt)", syllables: ["burn (burned, burned 或 burnt, burnt)"], phonetic: "", meaning: "v. 燃烧；着火；使烧焦", example: "The word 'burn (burned, burned 或 burnt, burnt)' means v. 燃烧." },
    { word: "bus", syllables: ["bus"], phonetic: "/bʌs/", meaning: "n. 公共汽车", example: "I go to school by bus." },
    { word: "business", syllables: ["busi","ness"], phonetic: "/ˈbɪznəs/", meaning: "n. 生意；事业；商业", example: "He runs his own business." },
    { word: "businessman", syllables: ["businessman"], phonetic: "", meaning: "n. 商人", example: "The word 'businessman' means n. 商人." },
    { word: "busy", syllables: ["bu","sy"], phonetic: "/ˈbɪzi/", meaning: "adj. 忙(碌)的", example: "I am busy with my homework." },
    { word: "but", syllables: ["but"], phonetic: "/bʌt/", meaning: "conj. 但是", example: "I like it but it is too expensive." },
    { word: "butter", syllables: ["but","ter"], phonetic: "/ˈbʌtər/", meaning: "n. 黄油，奶油", example: "She spread butter on the bread." },
    { word: "butterfly", syllables: ["but","ter","fly"], phonetic: "/ˈbʌtərflaɪ/", meaning: "n. 蝴蝶", example: "A beautiful butterfly flew by." },
    { word: "button", syllables: ["button"], phonetic: "", meaning: "n. 纽扣；(电铃等的)按钮", example: "The word 'button' means n. 纽扣." },
    { word: "buy (bought, bought)", syllables: ["buy (bought, bought)"], phonetic: "", meaning: "v. 买", example: "The word 'buy (bought, bought)' means v. 买." },
    { word: "by", syllables: ["by"], phonetic: "/baɪ/", meaning: "prep. 靠近，在……旁边；在……时间；不迟于；(用于被动语态)被；", example: "I go to school by bus." },
    { word: "bye", syllables: ["bye"], phonetic: "", meaning: "int. 再见", example: "The word 'bye' means int. 再见." },
    { word: "cabbage", syllables: ["cab","bage"], phonetic: "/ˈkæbɪdʒ/", meaning: "n. 卷心菜", example: "My mother cooked cabbage for dinner." },
    { word: "café", syllables: ["café"], phonetic: "", meaning: "n. 咖啡馆", example: "The word 'café' means n. 咖啡馆." },
    { word: "cake", syllables: ["cake"], phonetic: "/keɪk/", meaning: "n. 蛋糕，糕点；饼", example: "She made a birthday cake." },
    { word: "call", syllables: ["call"], phonetic: "/kɔːl/", meaning: "v. 打电话给……；称呼；取名；呼唤；喊；叫; n. 喊；叫；电话；通话", example: "Please call me later." },
    { word: "calm", syllables: ["calm"], phonetic: "/kɑːm/", meaning: "adj. 镇静的；沉着的; v. 使平静，安静", example: "Please stay calm." },
    { word: "camera", syllables: ["cam","er","a"], phonetic: "/ˈkæmərə/", meaning: "n. 照相机", example: "I forgot to bring my camera." },
    { word: "camp", syllables: ["camp"], phonetic: "/kæmp/", meaning: "n. (夏令)营；野营", example: "We went camping last summer." },
    { word: "can (could) can’t = can not", syllables: ["can (could) can’t = can not"], phonetic: "", meaning: "aux. v. 可能；能够；可以；会; n. (美)罐头；罐子", example: "The word 'can (could) can’t = can not' means aux. v. 可能." },
    { word: "cancel", syllables: ["can","cel"], phonetic: "/ˈkænsl/", meaning: "v. 取消", example: "We had to cancel the picnic." },
    { word: "capital", syllables: ["cap","i","tal"], phonetic: "/ˈkæpɪtl/", meaning: "n. 首都", example: "Beijing is the capital of China." },
    { word: "captain", syllables: ["cap","tain"], phonetic: "/ˈkæptɪn/", meaning: "n. 船长，队长", example: "He is the captain of the team." },
    { word: "car", syllables: ["car"], phonetic: "/kɑːr/", meaning: "n. 小汽车", example: "My father has a new car." },
    { word: "card", syllables: ["card"], phonetic: "/kɑːrd/", meaning: "n. 卡片", example: "I sent her a birthday card." },
    { word: "care", syllables: ["care"], phonetic: "/ker/", meaning: "n. 照料，保护；小心; v. 介意；在乎；关心", example: "She cares about the environment." },
    { word: "careful", syllables: ["care","ful"], phonetic: "/ˈkerfl/", meaning: "adj. 小心的；仔细的", example: "Be careful when you cross the road." },
    { word: "carefully", syllables: ["carefully"], phonetic: "", meaning: "adv. 小心地；仔细地", example: "The word 'carefully' means adv. 小心地." },
    { word: "careless", syllables: ["care","less"], phonetic: "/ˈkerləs/", meaning: "adj. 粗心的", example: "He made a careless mistake." },
    { word: "carrot", syllables: ["carrot"], phonetic: "", meaning: "n. 胡萝卜", example: "The word 'carrot' means n. 胡萝卜." },
    { word: "carry", syllables: ["car","ry"], phonetic: "/ˈkæri/", meaning: "v. 拿，搬，提，抬，背，抱，携带，运送等", example: "Let me carry the bag for you." },
    { word: "cartoon", syllables: ["cartoon"], phonetic: "", meaning: "n. 动画片；卡通；漫画", example: "The word 'cartoon' means n. 动画片." },
    { word: "case", syllables: ["case"], phonetic: "/keɪs/", meaning: "n. 情况；案件；箱；盒", example: "In that case, I will go." },
    { word: "cat", syllables: ["cat"], phonetic: "/kæt/", meaning: "n. 猫", example: "The cat is sleeping on the sofa." },
    { word: "catch (caught, caught)", syllables: ["catch (caught, caught)"], phonetic: "", meaning: "v. 接住；捉住；赶上(车辆等)；染上(疾病)；", example: "The word 'catch (caught, caught)' means v. 接住." },
    { word: "cause", syllables: ["cause"], phonetic: "", meaning: "n. 原因，起因; v. 促使，引起，使发生", example: "The word 'cause' means n. 原因." },
    { word: "cave", syllables: ["cave"], phonetic: "", meaning: "n. 洞，穴；地窖", example: "The word 'cave' means n. 洞." },
    { word: "celebrate", syllables: ["cel","e","brate"], phonetic: "/ˈselɪbreɪt/", meaning: "v. 庆祝", example: "We celebrate Spring Festival together." },
    { word: "cent", syllables: ["cent"], phonetic: "", meaning: "n. 美分(100 cents = 1 dollar)", example: "The word 'cent' means n. 美分(100 cents = 1 dollar)." },
    { word: "centre (美 center)", syllables: ["centre (美 center)"], phonetic: "", meaning: "n. 中心，中央", example: "The word 'centre (美 center)' means n. 中心." },
    { word: "century", syllables: ["cen","tu","ry"], phonetic: "/ˈsentʃəri/", meaning: "n. 世纪，百年", example: "This building is from the last century." },
    { word: "certainly", syllables: ["certainly"], phonetic: "", meaning: "adv. 当然，是的；一定，无疑", example: "The word 'certainly' means adv. 当然." },
    { word: "chain", syllables: ["chain"], phonetic: "", meaning: "n. 链；链条，连锁店", example: "The word 'chain' means n. 链." },
    { word: "chair", syllables: ["chair"], phonetic: "/tʃer/", meaning: "n. 椅子", example: "Please take a chair." },
    { word: "challenge", syllables: ["challenge"], phonetic: "", meaning: "n. & v. 挑战, 质疑", example: "The word 'challenge' means n. & v. 挑战, 质疑." },
    { word: "chance", syllables: ["chance"], phonetic: "/tʃæns/", meaning: "n. 机会", example: "This is a good chance to learn." }
  ],
  "第6组": [
    { word: "change", syllables: ["change"], phonetic: "/tʃeɪndʒ/", meaning: "v. 改变，变化； 更换；兑换(零钱); n. 零钱；找头；变化", example: "The weather can change quickly." },
    { word: "changeable", syllables: ["changeable"], phonetic: "", meaning: "adj. 易变的，变化无常的", example: "The word 'changeable' means adj. 易变的." },
    { word: "channel", syllables: ["chan","nel"], phonetic: "/ˈtʃænl/", meaning: "n. (电视)频道", example: "Please turn to Channel 5." },
    { word: "character", syllables: ["character"], phonetic: "", meaning: "n. 性格，特性；特征，特点；角色", example: "The word 'character' means n. 性格." },
    { word: "charge", syllables: ["charge"], phonetic: "", meaning: "n. 主管；掌管", example: "The word 'charge' means n. 主管." },
    { word: "charity", syllables: ["charity"], phonetic: "", meaning: "n. 慈善", example: "The word 'charity' means n. 慈善." },
    { word: "chat n．&", syllables: ["chat n．&"], phonetic: "", meaning: "v. 聊天，闲谈", example: "The word 'chat n．&' means v. 聊天." },
    { word: "cheap", syllables: ["cheap"], phonetic: "/tʃiːp/", meaning: "adj. 便宜的", example: "This shirt is very cheap." },
    { word: "check", syllables: ["check"], phonetic: "/tʃek/", meaning: "n. 检查；批改；支票; v. 核对；检查", example: "Please check your answers." },
    { word: "cheer", syllables: ["cheer"], phonetic: "/tʃɪr/", meaning: "n. & v. 欢呼； 喝彩", example: "The crowd began to cheer." },
    { word: "cheese", syllables: ["cheese"], phonetic: "/tʃiːz/", meaning: "n. 奶酪", example: "Do you like cheese?" },
    { word: "chemical", syllables: ["chemical"], phonetic: "", meaning: "n. 化学品；化学物质; adj. 化学的", example: "The word 'chemical' means n. 化学品." },
    { word: "chemistry", syllables: ["chemistry"], phonetic: "", meaning: "n. 化学", example: "The word 'chemistry' means n. 化学." },
    { word: "chess", syllables: ["chess"], phonetic: "", meaning: "n. 棋", example: "The word 'chess' means n. 棋." },
    { word: "chicken", syllables: ["chick","en"], phonetic: "/ˈtʃɪkɪn/", meaning: "n. 鸡；鸡肉", example: "I like fried chicken." },
    { word: "chief", syllables: ["chief"], phonetic: "", meaning: "adj. 主要的； 首要的; n. 领导，头", example: "The word 'chief' means adj. 主要的." },
    { word: "child (复 children)", syllables: ["child (复 children)"], phonetic: "", meaning: "n. 孩子，儿童", example: "The word 'child (复 children)' means n. 孩子." },
    { word: "childhood", syllables: ["childhood"], phonetic: "", meaning: "n. 幼年时代，童年", example: "The word 'childhood' means n. 幼年时代." },
    { word: "china", syllables: ["Chi","na"], phonetic: "/ˈtʃaɪnə/", meaning: "n. 瓷器", example: "China is a great country." },
    { word: "chocolate", syllables: ["choc","o","late"], phonetic: "/ˈtʃɑːklət/", meaning: "n. 巧克力", example: "She loves chocolate." },
    { word: "choice", syllables: ["choice"], phonetic: "/tʃɔɪs/", meaning: "n. 选择", example: "You have to make a choice." },
    { word: "choose (chose, chosen)", syllables: ["choose (chose, chosen)"], phonetic: "", meaning: "v. 选择", example: "The word 'choose (chose, chosen)' means v. 选择." },
    { word: "chopstick", syllables: ["chopstick"], phonetic: "", meaning: "n. 筷子", example: "The word 'chopstick' means n. 筷子." },
    { word: "Christmas", syllables: ["Christmas"], phonetic: "", meaning: "n. 圣诞节", example: "The word 'Christmas' means n. 圣诞节." },
    { word: "church", syllables: ["church"], phonetic: "/tʃɜːrtʃ/", meaning: "n. 教堂", example: "The old church is very beautiful." },
    { word: "cinema", syllables: ["cin","e","ma"], phonetic: "/ˈsɪnəmə/", meaning: "n. 电影院；电影", example: "Let's go to the cinema tonight." },
    { word: "circle", syllables: ["cir","cle"], phonetic: "/ˈsɜːrkl/", meaning: "n. 圆圈; v. 将……圈起来", example: "Please draw a circle." },
    { word: "citizen", syllables: ["cit","i","zen"], phonetic: "/ˈsɪtɪzn/", meaning: "n. 公民；居民；市民", example: "She is a citizen of China." },
    { word: "city", syllables: ["cit","y"], phonetic: "/ˈsɪti/", meaning: "n. 城市", example: "Beijing is a big city." },
    { word: "class", syllables: ["class"], phonetic: "/klæs/", meaning: "n. (学校里的)班级；课；等级", example: "We have English class today." },
    { word: "classmate", syllables: ["class","mate"], phonetic: "/ˈklæsmeɪt/", meaning: "n. 同班同学", example: "She is my classmate." },
    { word: "classroom", syllables: ["class","room"], phonetic: "/ˈklæsruːm/", meaning: "n. 教室", example: "The classroom is very clean." },
    { word: "clean", syllables: ["clean"], phonetic: "/kliːn/", meaning: "v. 弄干净；打扫; adj. 清洁的，干净的", example: "Please clean the room." },
    { word: "clear", syllables: ["clear"], phonetic: "/klɪr/", meaning: "adj. 清晰的；明亮的；清楚的; v. 清除；清扫", example: "The water is very clear." },
    { word: "clearly", syllables: ["clearly"], phonetic: "", meaning: "adv. 清晰地，明亮地；清楚地", example: "The word 'clearly' means adv. 清晰地." },
    { word: "clerk", syllables: ["clerk"], phonetic: "", meaning: "n. 职员，办事员", example: "The word 'clerk' means n. 职员." },
    { word: "clever", syllables: ["clev","er"], phonetic: "/ˈklevər/", meaning: "adj. 聪明的", example: "The boy is very clever." },
    { word: "click", syllables: ["click"], phonetic: "/klɪk/", meaning: "n. & v. （鼠标）点击", example: "Click the button to start." },
    { word: "climb", syllables: ["climb"], phonetic: "/klaɪm/", meaning: "v. 爬，攀登", example: "We climbed the mountain yesterday." },
    { word: "clinic", syllables: ["clinic"], phonetic: "", meaning: "n. 诊所，医务室", example: "The word 'clinic' means n. 诊所." },
    { word: "clock", syllables: ["clock"], phonetic: "/klɑːk/", meaning: "n. 钟", example: "The clock says it is ten." },
    { word: "close", syllables: ["close"], phonetic: "/kloʊz/", meaning: "v. 关，关闭", example: "Please close the door." },
    { word: "clothes", syllables: ["clothes"], phonetic: "/kloʊðz/", meaning: "n. 衣服", example: "Put on more clothes. It is cold." },
    { word: "cloud", syllables: ["cloud"], phonetic: "/klaʊd/", meaning: "n. 云", example: "There are many clouds in the sky." },
    { word: "cloudy", syllables: ["clou","dy"], phonetic: "/ˈklaʊdi/", meaning: "adj. 多云的；阴天的", example: "It is cloudy today." },
    { word: "club", syllables: ["club"], phonetic: "/klʌb/", meaning: "n. 俱乐部", example: "I joined the English club." },
    { word: "coat", syllables: ["coat"], phonetic: "/koʊt/", meaning: "n. 外套；上衣", example: "Put on your coat. It is cold outside." },
    { word: "coffee", syllables: ["cof","fee"], phonetic: "/ˈkɔːfi/", meaning: "n. 咖啡", example: "Would you like a cup of coffee?" },
    { word: "coin", syllables: ["coin"], phonetic: "/kɔɪn/", meaning: "n. 硬币", example: "He found a coin on the ground." },
    { word: "cold", syllables: ["cold"], phonetic: "/koʊld/", meaning: "adj. 冷的，寒冷的; n. 寒冷；感冒，伤风", example: "It is very cold in winter." }
  ],
  "第7组": [
    { word: "collect", syllables: ["col","lect"], phonetic: "/kəˈlekt/", meaning: "v. 收集，采集", example: "He likes to collect stamps." },
    { word: "collection", syllables: ["collection"], phonetic: "", meaning: "n. 收集", example: "The word 'collection' means n. 收集." },
    { word: "college", syllables: ["col","lege"], phonetic: "/ˈkɑːlɪdʒ/", meaning: "n. 学院", example: "She goes to a medical college." },
    { word: "colour (美 color)", syllables: ["colour (美 color)"], phonetic: "", meaning: "n. 颜色; v. 涂色", example: "The word 'colour (美 color)' means n. 颜色; v. 涂色." },
    { word: "come (came, come)", syllables: ["come (came, come)"], phonetic: "", meaning: "v. 来，来到", example: "The word 'come (came, come)' means v. 来." },
    { word: "comfortable", syllables: ["com","for","ta","ble"], phonetic: "/ˈkʌmftəbl/", meaning: "adj. 舒服的", example: "This sofa is very comfortable." },
    { word: "common", syllables: ["com","mon"], phonetic: "/ˈkɑːmən/", meaning: "adj. 普通的，一般的；共有的", example: "This is a very common mistake." },
    { word: "communicate", syllables: ["com","mu","ni","cate"], phonetic: "/kəˈmjuːnɪkeɪt/", meaning: "v. 交流；交际；传达(感情、信息等)", example: "We communicate by email." },
    { word: "community", syllables: ["com","mu","ni","ty"], phonetic: "/kəˈmjuːnəti/", meaning: "n. 社区", example: "Our community is very friendly." },
    { word: "company", syllables: ["com","pa","ny"], phonetic: "/ˈkʌmpəni/", meaning: "n. 公司", example: "She works for a big company." },
    { word: "compare", syllables: ["com","pare"], phonetic: "/kəmˈper/", meaning: "v. 比较，对照", example: "Compare the two pictures." },
    { word: "competition", syllables: ["com","pe","ti","tion"], phonetic: "/ˌkɑːmpəˈtɪʃn/", meaning: "n. 比赛，竞赛", example: "He won first prize in the competition." },
    { word: "complain", syllables: ["complain"], phonetic: "", meaning: "v. 抱怨；投诉", example: "The word 'complain' means v. 抱怨." },
    { word: "complete", syllables: ["com","plete"], phonetic: "/kəmˈpliːt/", meaning: "adj. 完成的，完整的，完全的; v. 完成，结束", example: "Please complete the form." },
    { word: "completely", syllables: ["completely"], phonetic: "", meaning: "adv. 完全地，完整地", example: "The word 'completely' means adv. 完全地." },
    { word: "computer", syllables: ["com","pu","ter"], phonetic: "/kəmˈpjuːtər/", meaning: "n. 电脑", example: "I use a computer to study." },
    { word: "concert", syllables: ["con","cert"], phonetic: "/ˈkɑːnsərt/", meaning: "n. 音乐会；演奏会", example: "We went to a concert last night." },
    { word: "conclusion", syllables: ["conclusion"], phonetic: "", meaning: "n. 结论；结束，结局", example: "The word 'conclusion' means n. 结论." },
    { word: "conference", syllables: ["con","fer","ence"], phonetic: "/ˈkɑːnfərəns/", meaning: "n. (正式的)会议；讨论会", example: "She attended a conference in Shanghai." },
    { word: "confidence", syllables: ["confidence"], phonetic: "", meaning: "n. 自信心；信任", example: "The word 'confidence' means n. 自信心." },
    { word: "confident", syllables: ["confident"], phonetic: "", meaning: "adj. 自信的", example: "The word 'confident' means adj. 自信的." },
    { word: "confuse", syllables: ["confuse"], phonetic: "", meaning: "v. 使困惑，扰乱；分不清", example: "The word 'confuse' means v. 使困惑." },
    { word: "congratulation", syllables: ["congratulation"], phonetic: "", meaning: "n. 祝贺", example: "The word 'congratulation' means n. 祝贺." },
    { word: "connect", syllables: ["con","nect"], phonetic: "/kəˈnekt/", meaning: "v. 连接，把……联系起来", example: "Please connect to the internet." },
    { word: "consider", syllables: ["con","si","der"], phonetic: "/kənˈsɪdər/", meaning: "v. 考虑", example: "Please consider my suggestion." },
    { word: "consist", syllables: ["consist"], phonetic: "", meaning: "v. 包含；组成，构成", example: "The word 'consist' means v. 包含." },
    { word: "contact", syllables: ["con","tact"], phonetic: "/ˈkɑːntækt/", meaning: "n. 接触；联系; v. 与……来往，联系", example: "Keep in contact with your friends." },
    { word: "contest", syllables: ["contest"], phonetic: "", meaning: "n. 竞赛", example: "The word 'contest' means n. 竞赛." },
    { word: "continue", syllables: ["con","tin","ue"], phonetic: "/kənˈtɪnjuː/", meaning: "v. 继续", example: "Please continue reading." },
    { word: "control", syllables: ["con","trol"], phonetic: "/kənˈtroʊl/", meaning: "v. & n.             控制", example: "Try to control your temper." },
    { word: "convenient", syllables: ["convenient"], phonetic: "", meaning: "adj. 便利的，方便的", example: "The word 'convenient' means adj. 便利的." },
    { word: "conversation", syllables: ["con","ver","sa","tion"], phonetic: "/ˌkɑːnvərˈseɪʃn/", meaning: "n. 会话；谈话", example: "I had a long conversation with her." },
    { word: "cook", syllables: ["cook"], phonetic: "/kʊk/", meaning: "n. 厨师，炊事员; v. 烹调，做饭", example: "My mother cooks delicious food." },
    { word: "cool", syllables: ["cool"], phonetic: "/kuːl/", meaning: "adj. 凉的，凉爽的；酷", example: "It is cool in autumn." },
    { word: "copy", syllables: ["co","py"], phonetic: "/ˈkɑːpi/", meaning: "n. 抄本，副本；一本(份，册……); v. 抄写；复印；(计算机用语)拷(备份)；模仿", example: "Please copy this text." },
    { word: "corner", syllables: ["cor","ner"], phonetic: "/ˈkɔːrnər/", meaning: "n. 角；角落；拐角", example: "The store is on the corner." },
    { word: "correct", syllables: ["cor","rect"], phonetic: "/kəˈrekt/", meaning: "adj. 正确的，对的；恰当的; v. 改正；纠正", example: "Is this answer correct?" },
    { word: "correctly", syllables: ["correctly"], phonetic: "", meaning: "adv. 正确地", example: "The word 'correctly' means adv. 正确地." },
    { word: "cost (cost, cost)", syllables: ["cost (cost, cost)"], phonetic: "", meaning: "v. 值(多少钱)；花费", example: "The word 'cost (cost, cost)' means v. 值(多少钱)." },
    { word: "cotton", syllables: ["cot","ton"], phonetic: "/ˈkɑːtn/", meaning: "n. 棉花", example: "This shirt is made of cotton." },
    { word: "cough", syllables: ["cough"], phonetic: "", meaning: "n. & v. 咳嗽", example: "The word 'cough' means n. & v. 咳嗽." },
    { word: "count", syllables: ["count"], phonetic: "/kaʊnt/", meaning: "v. 数", example: "Can you count from one to ten?" },
    { word: "country", syllables: ["coun","try"], phonetic: "/ˈkʌntri/", meaning: "n. 国家；农村；乡下", example: "China is a large country." },
    { word: "couple", syllables: ["cou","ple"], phonetic: "/ˈkʌpl/", meaning: "n. 夫妇；一对；一双；一副", example: "The couple got married last year." },
    { word: "course", syllables: ["course"], phonetic: "/kɔːrs/", meaning: "n. 过程；经过；课程", example: "Of course I will help you." },
    { word: "cousin", syllables: ["cou","sin"], phonetic: "/ˈkʌzn/", meaning: "n. 堂(表)兄弟，堂(表)姐妹", example: "My cousin lives in Shanghai." },
    { word: "cover", syllables: ["cov","er"], phonetic: "/ˈkʌvər/", meaning: "v. 覆盖；遮盖；掩盖; n. 盖子；罩；封面", example: "Please cover the table with a cloth." },
    { word: "crazy", syllables: ["cra","zy"], phonetic: "/ˈkreɪzi/", meaning: "adj. 疯狂的", example: "She is crazy about music." },
    { word: "cream", syllables: ["cream"], phonetic: "/kriːm/", meaning: "n. 奶油，乳脂", example: "I like ice cream very much." },
    { word: "create", syllables: ["cre","ate"], phonetic: "/kriˈeɪt/", meaning: "v. 创造；造成", example: "He created a beautiful painting." }
  ],
  "第8组": [
    { word: "creative", syllables: ["creative"], phonetic: "", meaning: "adj. 创造性的，有创意的", example: "The word 'creative' means adj. 创造性的." },
    { word: "cross", syllables: ["cross"], phonetic: "/krɔːs/", meaning: "n. 十字形的东西; v. 越过；穿过", example: "Look both ways before you cross the road." },
    { word: "crowd", syllables: ["crowd"], phonetic: "/kraʊd/", meaning: "n. 人群", example: "There was a big crowd at the concert." },
    { word: "crowded", syllables: ["crow","ded"], phonetic: "/ˈkraʊdɪd/", meaning: "adj. 拥挤的", example: "The bus was very crowded." },
    { word: "cry", syllables: ["cry"], phonetic: "/kraɪ/", meaning: "v. 喊叫；哭; n. 叫喊；哭声", example: "The baby began to cry." },
    { word: "culture", syllables: ["cul","ture"], phonetic: "/ˈkʌltʃər/", meaning: "n. 文化", example: "Chinese culture is very rich." },
    { word: "cup", syllables: ["cup"], phonetic: "/kʌp/", meaning: "n. 茶杯，杯子", example: "Would you like a cup of tea?" },
    { word: "custom", syllables: ["custom"], phonetic: "", meaning: "n. 习惯，习俗", example: "The word 'custom' means n. 习惯." },
    { word: "customer", syllables: ["cus","to","mer"], phonetic: "/ˈkʌstəmər/", meaning: "n. 顾客，主顾", example: "The customer is always right." },
    { word: "cut (cut, cut)", syllables: ["cut (cut, cut)"], phonetic: "", meaning: "v. 切；剪；削；割", example: "The word 'cut (cut, cut)' means v. 切." },
    { word: "cute", syllables: ["cute"], phonetic: "", meaning: "adj. 可爱的，漂亮迷人的", example: "The word 'cute' means adj. 可爱的." },
    { word: "cycle", syllables: ["cy","cle"], phonetic: "/ˈsaɪkl/", meaning: "v. 骑(自行)车", example: "I cycle to school every day." },
    { word: "dad", syllables: ["dad"], phonetic: "/dæd/", meaning: "n. (口语)爸爸", example: "My dad is a teacher." },
    { word: "daily", syllables: ["dai","ly"], phonetic: "/ˈdeɪli/", meaning: "adj. 每日的；日常的; adv. 每天; n. 日报", example: "Exercise should be a daily habit." },
    { word: "damage", syllables: ["damage"], phonetic: "", meaning: "n. & v. 破坏，损害", example: "The word 'damage' means n. & v. 破坏." },
    { word: "dance", syllables: ["dance"], phonetic: "/dæns/", meaning: "n. & v. 跳舞", example: "She loves to dance." },
    { word: "dancer", syllables: ["dancer"], phonetic: "", meaning: "n. 跳舞者，舞蹈演员", example: "The word 'dancer' means n. 跳舞者." },
    { word: "danger", syllables: ["dan","ger"], phonetic: "/ˈdeɪndʒər/", meaning: "n. 危险", example: "The children are in danger." },
    { word: "dangerous", syllables: ["dan","ger","ous"], phonetic: "/ˈdeɪndʒərəs/", meaning: "adj. 危险的", example: "It is dangerous to swim here." },
    { word: "dare", syllables: ["dare"], phonetic: "/der/", meaning: "v. (后接不带 to 的不定式主要用于疑问，否定或条件句)敢，敢于", example: "I dare not jump from here." },
    { word: "dark", syllables: ["dark"], phonetic: "/dɑːrk/", meaning: "n. 黑暗；暗处；深色; adj. 黑暗的；暗淡的；深色的", example: "It is getting dark outside." },
    { word: "date", syllables: ["date"], phonetic: "/deɪt/", meaning: "n. 日期；约会", example: "What is the date today?" },
    { word: "daughter", syllables: ["daugh","ter"], phonetic: "/ˈdɔːtər/", meaning: "n. 女儿", example: "She has a lovely daughter." },
    { word: "day", syllables: ["day"], phonetic: "/deɪ/", meaning: "n. (一)天，(一)日；白天", example: "What a beautiful day!" },
    { word: "dead", syllables: ["dead"], phonetic: "/ded/", meaning: "adj. 死的；无生命的", example: "The flowers are dead." },
    { word: "deal (dealt, dealt)", syllables: ["deal (dealt, dealt)"], phonetic: "", meaning: "v. 对付；分配，分给；给予；经营; n. 交易", example: "The word 'deal (dealt, dealt)' means v. 对付." },
    { word: "dear", syllables: ["dear"], phonetic: "/dɪr/", meaning: "adj. 亲爱的；贵的", example: "Dear Mom, I miss you." },
    { word: "death", syllables: ["death"], phonetic: "/deθ/", meaning: "n. 死亡", example: "The death of his dog made him sad." },
    { word: "debate", syllables: ["debate"], phonetic: "", meaning: "v. & n.        争论，辩论；讨论", example: "The word 'debate' means v. & n.        争论." },
    { word: "decide", syllables: ["de","cide"], phonetic: "/dɪˈsaɪd/", meaning: "v. 决定；下决心", example: "I decided to study abroad." },
    { word: "decision", syllables: ["de","ci","sion"], phonetic: "/dɪˈsɪʒn/", meaning: "n. 决定；决心", example: "She made the right decision." },
    { word: "decorate", syllables: ["decorate"], phonetic: "", meaning: "v. 装饰", example: "The word 'decorate' means v. 装饰." },
    { word: "deep", syllables: ["deep"], phonetic: "/diːp/", meaning: "adj. 深", example: "The river is very deep here." },
    { word: "degree", syllables: ["de","gree"], phonetic: "/dɪˈɡriː/", meaning: "n. 程度；度数；学位", example: "She has a master's degree." },
    { word: "delay", syllables: ["delay"], phonetic: "", meaning: "v. & n.                拖延，延误，延期", example: "The word 'delay' means v. & n.                拖延." },
    { word: "delicious", syllables: ["de","li","cious"], phonetic: "/dɪˈlɪʃəs/", meaning: "adj. 美味的，可口的", example: "The food smells delicious." },
    { word: "deliver", syllables: ["de","liv","er"], phonetic: "/dɪˈlɪvər/", meaning: "v. 投递(信件，邮包等)；传送", example: "The postman delivers letters every day." },
    { word: "dentist", syllables: ["den","tist"], phonetic: "/ˈdentɪst/", meaning: "n. 牙科医生", example: "I need to see the dentist." },
    { word: "deny", syllables: ["deny"], phonetic: "", meaning: "v. 否认，否定", example: "The word 'deny' means v. 否认." },
    { word: "departure", syllables: ["departure"], phonetic: "", meaning: "n. 离开", example: "The word 'departure' means n. 离开." },
    { word: "depend", syllables: ["de","pend"], phonetic: "/dɪˈpend/", meaning: "v. 依靠，依赖；取决于", example: "It depends on the weather." },
    { word: "describe", syllables: ["de","scribe"], phonetic: "/dɪˈskraɪb/", meaning: "v. 描写，叙述", example: "Can you describe the person?" },
    { word: "deserve", syllables: ["deserve"], phonetic: "", meaning: "v. 应得，应受", example: "The word 'deserve' means v. 应得." },
    { word: "design", syllables: ["de","sign"], phonetic: "/dɪˈzaɪn/", meaning: "v. 设计，策划", example: "She designed a beautiful dress." },
    { word: "desire", syllables: ["de","sire"], phonetic: "/dɪˈzaɪər/", meaning: "n. 愿望；欲望; v. 渴望；热切希望", example: "He has a strong desire to succeed." },
    { word: "desk", syllables: ["desk"], phonetic: "/desk/", meaning: "n. 书桌，写字台", example: "There is a book on the desk." },
    { word: "destroy", syllables: ["destroy"], phonetic: "", meaning: "v. 破坏，毁坏", example: "The word 'destroy' means v. 破坏." },
    { word: "detail", syllables: ["detail"], phonetic: "", meaning: "n. 细节", example: "The word 'detail' means n. 细节." },
    { word: "detective", syllables: ["detective"], phonetic: "", meaning: "adj. 侦探的; n. 侦探", example: "The word 'detective' means adj. 侦探的; n. 侦探." },
    { word: "develop", syllables: ["de","vel","op"], phonetic: "/dɪˈveləp/", meaning: "v. 发展；开发；培养", example: "The city is developing fast." }
  ],
  "第9组": [
    { word: "development", syllables: ["de","vel","op","ment"], phonetic: "/dɪˈveləpmənt/", meaning: "n. 发展", example: "Economic development is very important." },
    { word: "dial", syllables: ["dial"], phonetic: "", meaning: "v. 拨电话号码", example: "The word 'dial' means v. 拨电话号码." },
    { word: "dialogue (美 dialog)", syllables: ["dialogue (美 dialog)"], phonetic: "", meaning: "n. 对话", example: "The word 'dialogue (美 dialog)' means n. 对话." },
    { word: "diary", syllables: ["diary"], phonetic: "", meaning: "n. 日记；日记簿", example: "The word 'diary' means n. 日记." },
    { word: "dictionary", syllables: ["dic","tion","ar","y"], phonetic: "/ˈdɪkʃəneri/", meaning: "n. 词典，字典", example: "Look it up in the dictionary." },
    { word: "die", syllables: ["die"], phonetic: "/daɪ/", meaning: "v. 死", example: "Plants die without water." },
    { word: "diet", syllables: ["diet"], phonetic: "", meaning: "n. 饮食；食谱；食物", example: "The word 'diet' means n. 饮食." },
    { word: "difference", syllables: ["dif","fer","ence"], phonetic: "/ˈdɪfrəns/", meaning: "n. 不同", example: "Can you tell the difference?" },
    { word: "different", syllables: ["dif","fer","ent"], phonetic: "/ˈdɪfrənt/", meaning: "adj. 不同的，有差异的", example: "We have different opinions." },
    { word: "difficult", syllables: ["dif","fi","cult"], phonetic: "/ˈdɪfɪkʌlt/", meaning: "adj. 困难的，费力的", example: "This question is very difficult." },
    { word: "difficulty", syllables: ["dif","fi","cul","ty"], phonetic: "/ˈdɪfɪkʌlti/", meaning: "n. 困难", example: "He had difficulty finding the place." },
    { word: "dig (dug, dug)", syllables: ["dig (dug, dug)"], phonetic: "", meaning: "v. 挖；掘", example: "The word 'dig (dug, dug)' means v. 挖." },
    { word: "dinner", syllables: ["din","ner"], phonetic: "/ˈdɪnər/", meaning: "n. 正餐", example: "What time is dinner?" },
    { word: "direction", syllables: ["di","rec","tion"], phonetic: "/dɪˈrekʃn/", meaning: "n. 方向；趋势；用法说明", example: "Which direction is the school?" },
    { word: "directly", syllables: ["directly"], phonetic: "", meaning: "adv. 直接地", example: "The word 'directly' means adv. 直接地." },
    { word: "director", syllables: ["di","rec","tor"], phonetic: "/dɪˈrektər/", meaning: "n. 导演", example: "He is the director of the movie." },
    { word: "dirty", syllables: ["dir","ty"], phonetic: "/ˈdɜːrti/", meaning: "adj. 脏的", example: "Your hands are dirty." },
    { word: "disadvantage", syllables: ["disadvantage"], phonetic: "", meaning: "n. 不利，劣势，短处", example: "The word 'disadvantage' means n. 不利." },
    { word: "disappear", syllables: ["disappear"], phonetic: "", meaning: "v. 消失，不见", example: "The word 'disappear' means v. 消失." },
    { word: "disappointed", syllables: ["disappointed"], phonetic: "", meaning: "adj. 失望的，沮丧的", example: "The word 'disappointed' means adj. 失望的." },
    { word: "disaster", syllables: ["disaster"], phonetic: "", meaning: "n. 灾难；灾祸", example: "The word 'disaster' means n. 灾难." },
    { word: "discover", syllables: ["dis","cov","er"], phonetic: "/dɪˈskʌvər/", meaning: "v. 发现；看出", example: "Columbus discovered America." },
    { word: "discuss", syllables: ["dis","cuss"], phonetic: "/dɪˈskʌs/", meaning: "v. 讨论，议论", example: "Let's discuss this problem." },
    { word: "discussion", syllables: ["dis","cus","sion"], phonetic: "/dɪˈskʌʃn/", meaning: "n. 讨论", example: "We had a long discussion." },
    { word: "dish", syllables: ["dish"], phonetic: "/dɪʃ/", meaning: "n. 盘，碟；盘装菜；盘形物", example: "She cooked a delicious dish." },
    { word: "dishonest", syllables: ["dishonest"], phonetic: "", meaning: "adj. 不诚实的，欺骗性的", example: "The word 'dishonest' means adj. 不诚实的." },
    { word: "dislike", syllables: ["dislike"], phonetic: "", meaning: "v. 不喜欢；厌恶", example: "The word 'dislike' means v. 不喜欢." },
    { word: "distance", syllables: ["dis","tance"], phonetic: "/ˈdɪstəns/", meaning: "n. 距离", example: "The school is a short distance away." },
    { word: "disturb", syllables: ["dis","turb"], phonetic: "/dɪˈstɜːrb/", meaning: "v. 扰乱；打扰", example: "Please don't disturb me." },
    { word: "divide", syllables: ["di","vide"], phonetic: "/dɪˈvaɪd/", meaning: "v. 分，划分；(算术用语)除", example: "Divide the cake into four pieces." },
    { word: "do (did，done)", syllables: ["do (did，done)"], phonetic: "", meaning: "v. & aux. 做，干(用以构成疑问句及否定句。第三人", example: "The word 'do (did，done)' means v. & aux. 做." },
    { word: "doctor", syllables: ["doc","tor"], phonetic: "/ˈdɑːktər/", meaning: "n. 医生", example: "You should see a doctor." },
    { word: "dog", syllables: ["dog"], phonetic: "/dɔːɡ/", meaning: "n. 狗", example: "The dog is man's best friend." },
    { word: "dollar", syllables: ["dol","lar"], phonetic: "/ˈdɑːlər/", meaning: "n. 元(美国、加拿大、澳大利亚等国货币单位)", example: "The book costs ten dollars." },
    { word: "door", syllables: ["door"], phonetic: "/dɔːr/", meaning: "n. 门；通道", example: "Please open the door." },
    { word: "double", syllables: ["dou","ble"], phonetic: "/ˈdʌbl/", meaning: "adj. 两倍的；双的", example: "I want a double room." },
    { word: "down", syllables: ["down"], phonetic: "/daʊn/", meaning: "prep. 沿着，沿……而下; adv. 向下", example: "Sit down, please." },
    { word: "download", syllables: ["down","load"], phonetic: "/ˈdaʊnloʊd/", meaning: "v. 下载", example: "You can download the app for free." },
    { word: "downstairs", syllables: ["downstairs"], phonetic: "", meaning: "adv. 在楼下；到楼下", example: "The word 'downstairs' means adv. 在楼下." },
    { word: "draw (drew, drawn)", syllables: ["draw (drew, drawn)"], phonetic: "", meaning: "v. 绘画；绘制；拉，拖", example: "The word 'draw (drew, drawn)' means v. 绘画." },
    { word: "dream (dreamt, dreamt 或 dreamed, dreamed)", syllables: ["dream (dreamt, dreamt 或 dreamed, dreamed)"], phonetic: "", meaning: "n. & v. 梦，梦想", example: "The word 'dream (dreamt, dreamt 或 dreamed, dreamed)' means n. & v. 梦." },
    { word: "dress", syllables: ["dress"], phonetic: "/dres/", meaning: "n. 女服，连衣裙；(统指)服装；童装; v. 穿衣；穿着", example: "She wore a red dress." },
    { word: "drink (drank, drunk)", syllables: ["drink (drank, drunk)"], phonetic: "", meaning: "v. 喝，饮; n. 饮料；喝酒", example: "The word 'drink (drank, drunk)' means v. 喝." },
    { word: "drive (drove, driven)", syllables: ["drive (drove, driven)"], phonetic: "", meaning: "v. 驾驶，开(车)；驱赶", example: "The word 'drive (drove, driven)' means v. 驾驶." },
    { word: "driver", syllables: ["driver"], phonetic: "", meaning: "n. 司机，驾驶员", example: "The word 'driver' means n. 司机." },
    { word: "drop", syllables: ["drop"], phonetic: "/drɑːp/", meaning: "n. 滴; v. 掉下，落下；扔掉；放弃", example: "Be careful not to drop the glass." },
    { word: "dry", syllables: ["dry"], phonetic: "/draɪ/", meaning: "adj. 干的；干燥的", example: "The clothes are dry now." },
    { word: "duck", syllables: ["duck"], phonetic: "/dʌk/", meaning: "n. 鸭子", example: "The duck swims in the pond." },
    { word: "dull", syllables: ["dull"], phonetic: "", meaning: "adj. 单调无味的", example: "The word 'dull' means adj. 单调无味的." },
    { word: "during", syllables: ["dur","ing"], phonetic: "/ˈdʊrɪŋ/", meaning: "prep. 在……期间；在……过程中", example: "I read a lot during the holiday." }
  ],
  "第10组": [
    { word: "duty", syllables: ["du","ty"], phonetic: "/ˈduːti/", meaning: "n. 责任", example: "It is our duty to protect the earth." },
    { word: "each", syllables: ["each"], phonetic: "/iːtʃ/", meaning: "adj. & pron.              每人；每个；每件", example: "Each student has a book." },
    { word: "eager", syllables: ["eager"], phonetic: "", meaning: "adj. 渴望的，热切的", example: "The word 'eager' means adj. 渴望的." },
    { word: "ear", syllables: ["ear"], phonetic: "/ɪr/", meaning: "n. 耳朵", example: "The rabbit has long ears." },
    { word: "early", syllables: ["ear","ly"], phonetic: "/ˈɜːrli/", meaning: "adj. 早的; adv. 早地", example: "I get up early every morning." },
    { word: "earth", syllables: ["earth"], phonetic: "/ɜːrθ/", meaning: "n. 地球；土，泥；大地", example: "The earth goes around the sun." },
    { word: "earthquake", syllables: ["earthquake"], phonetic: "", meaning: "n. 地震", example: "The word 'earthquake' means n. 地震." },
    { word: "easily", syllables: ["easily"], phonetic: "", meaning: "adv. 容易地", example: "The word 'easily' means adv. 容易地." },
    { word: "east", syllables: ["east"], phonetic: "/iːst/", meaning: "adj. 东方的；东部的; n. 东，东方；东部", example: "The sun rises in the east." },
    { word: "easy", syllables: ["ea","sy"], phonetic: "/ˈiːzi/", meaning: "adj. 容易的，不费力的", example: "This question is easy." },
    { word: "eat (ate, eaten)", syllables: ["eat (ate, eaten)"], phonetic: "", meaning: "v. 吃", example: "The word 'eat (ate, eaten)' means v. 吃." },
    { word: "economy", syllables: ["economy"], phonetic: "", meaning: "n. 经济", example: "The word 'economy' means n. 经济." },
    { word: "education", syllables: ["ed","u","ca","tion"], phonetic: "/ˌedʒuˈkeɪʃn/", meaning: "n. 教育", example: "Education is very important." },
    { word: "educational", syllables: ["educational"], phonetic: "", meaning: "adj. 教育的", example: "The word 'educational' means adj. 教育的." },
    { word: "effect", syllables: ["effect"], phonetic: "", meaning: "n. 效果", example: "The word 'effect' means n. 效果." },
    { word: "effort", syllables: ["ef","fort"], phonetic: "/ˈefərt/", meaning: "n. 精力，努力", example: "He made every effort to succeed." },
    { word: "egg", syllables: ["egg"], phonetic: "/eɡ/", meaning: "n. 蛋；卵", example: "I had two eggs for breakfast." },
    { word: "either", syllables: ["ei","ther"], phonetic: "/ˈiːðər/", meaning: "adj. 两方任一方的；二者之一的", example: "You can have either tea or coffee." },
    { word: "elder", syllables: ["el","der"], phonetic: "/ˈeldər/", meaning: "adj. 年龄较大的；前辈的", example: "We should respect our elders." },
    { word: "electric", syllables: ["e","lec","tric"], phonetic: "/ɪˈlektrɪk/", meaning: "adj. 电的", example: "We use electric lights at home." },
    { word: "electricity", syllables: ["electricity"], phonetic: "", meaning: "n. 电", example: "The word 'electricity' means n. 电." },
    { word: "elementary", syllables: ["elementary"], phonetic: "", meaning: "adj. 初级的；基本的", example: "The word 'elementary' means adj. 初级的." },
    { word: "elephant", syllables: ["el","e","phant"], phonetic: "/ˈelɪfənt/", meaning: "n. 大象", example: "The elephant is the largest land animal." },
    { word: "else", syllables: ["else"], phonetic: "/els/", meaning: "adv. 别的；其他的", example: "What else do you want?" },
    { word: "e-mail (email)", syllables: ["e-mail (email)"], phonetic: "", meaning: "n. 电子邮件; v. 发电子邮件", example: "The word 'e-mail (email)' means n. 电子邮件; v. 发电子邮件." },
    { word: "embarrassed", syllables: ["embarrassed"], phonetic: "", meaning: "adj. 局促不安的； 为难的； 尴尬的； 窘迫的", example: "The word 'embarrassed' means adj. 局促不安的." },
    { word: "emergency", syllables: ["emergency"], phonetic: "", meaning: "n. 紧急情况； 突发事件；", example: "The word 'emergency' means n. 紧急情况." },
    { word: "empty", syllables: ["emp","ty"], phonetic: "/ˈempti/", meaning: "adj. 空的", example: "The box is empty." },
    { word: "enable", syllables: ["enable"], phonetic: "", meaning: "v. 使……能够，使……有能力", example: "The word 'enable' means v. 使……能够." },
    { word: "encourage", syllables: ["en","cour","age"], phonetic: "/ɪnˈkɜːrɪdʒ/", meaning: "v. 鼓励", example: "My teacher encouraged me to try again." },
    { word: "end", syllables: ["end"], phonetic: "/end/", meaning: "n. 末尾；终点；结束; v. 结束，终止", example: "The movie ended at ten." },
    { word: "enemy", syllables: ["en","e","my"], phonetic: "/ˈenəmi/", meaning: "n. 敌人；敌军", example: "He has no enemies." },
    { word: "energy", syllables: ["en","er","gy"], phonetic: "/ˈenərdʒi/", meaning: "n. 精力；能量", example: "She is full of energy." },
    { word: "engine", syllables: ["engine"], phonetic: "", meaning: "n. 发动机，引擎", example: "The word 'engine' means n. 发动机." },
    { word: "engineer", syllables: ["en","gi","neer"], phonetic: "/ˌendʒɪˈnɪr/", meaning: "n. 工程师；技师", example: "My father is an engineer." },
    { word: "enjoy", syllables: ["en","joy"], phonetic: "/ɪnˈdʒɔɪ/", meaning: "v. 欣赏；享受；喜欢", example: "I enjoy reading books." },
    { word: "enjoyable", syllables: ["enjoyable"], phonetic: "", meaning: "adj. 使人愉快的；使人欢乐的", example: "The word 'enjoyable' means adj. 使人愉快的." },
    { word: "enough", syllables: ["e","nough"], phonetic: "/ɪˈnʌf/", meaning: "adj. 足够的；充分的; adv. 足够地；充分地; n. 足够；充足", example: "Do you have enough money?" },
    { word: "enrich", syllables: ["enrich"], phonetic: "", meaning: "v. 使……丰富", example: "The word 'enrich' means v. 使……丰富." },
    { word: "enter", syllables: ["en","ter"], phonetic: "/ˈentər/", meaning: "v. 进入；参加", example: "Please enter the room quietly." },
    { word: "entertainment", syllables: ["entertainment"], phonetic: "", meaning: "n. 娱乐；消遣；款待", example: "The word 'entertainment' means n. 娱乐." },
    { word: "entrance", syllables: ["entrance"], phonetic: "", meaning: "n. 入口；入场", example: "The word 'entrance' means n. 入口." },
    { word: "envelope", syllables: ["envelope"], phonetic: "", meaning: "n. 信封", example: "The word 'envelope' means n. 信封." },
    { word: "environment", syllables: ["en","vi","ron","ment"], phonetic: "/ɪnˈvaɪrənmənt/", meaning: "n. 环境", example: "We should protect the environment." },
    { word: "equal", syllables: ["equal"], phonetic: "", meaning: "adj. 平等的; v. 等于", example: "The word 'equal' means adj. 平等的; v. 等于." },
    { word: "escape", syllables: ["escape"], phonetic: "", meaning: "n. & v. 逃跑；逃脱", example: "The word 'escape' means n. & v. 逃跑." },
    { word: "especially", syllables: ["es","pe","cial","ly"], phonetic: "/ɪˈspeʃəli/", meaning: "adv. 特别地，尤其", example: "I like fruit, especially apples." },
    { word: "eve", syllables: ["eve"], phonetic: "", meaning: "n. (节日的)前夜，前夕", example: "The word 'eve' means n. (节日的)前夜." },
    { word: "even", syllables: ["e","ven"], phonetic: "/ˈiːvn/", meaning: "adv. 甚至；连(……都)；更", example: "She can even speak three languages." },
    { word: "evening", syllables: ["eve","ning"], phonetic: "/ˈiːvnɪŋ/", meaning: "n. 傍晚，晚上", example: "I watch TV in the evening." }
  ],
  "第11组": [
    { word: "event", syllables: ["e","vent"], phonetic: "/ɪˈvent/", meaning: "n. 事件，大事；比赛项目", example: "The sports event was exciting." },
    { word: "ever", syllables: ["ev","er"], phonetic: "/ˈevər/", meaning: "adv. 曾经；无论何时", example: "Have you ever been to Beijing?" },
    { word: "every", syllables: ["ev","ery"], phonetic: "/ˈevri/", meaning: "adj. 每一，每个的", example: "Every student must wear a uniform." },
    { word: "everybody/everyone", syllables: ["everybody/everyone"], phonetic: "", meaning: "pron. 每人，人人", example: "The word 'everybody/everyone' means pron. 每人." },
    { word: "everyday", syllables: ["ev","ery","day"], phonetic: "/ˈevrideɪ/", meaning: "adj. 每日的； 日常的", example: "English is an everyday language." },
    { word: "everything", syllables: ["ev","ery","thing"], phonetic: "/ˈevriθɪŋ/", meaning: "pron. 每件事，事事", example: "Everything is ready." },
    { word: "everywhere", syllables: ["ev","ery","where"], phonetic: "/ˈevriwer/", meaning: "adv. 到处", example: "I looked everywhere for my key." },
    { word: "exactly", syllables: ["exactly"], phonetic: "", meaning: "adv. 确切的(表示赞同的回答)；确实如此", example: "The word 'exactly' means adv. 确切的(表示赞同的回答)." },
    { word: "exam=examination", syllables: ["exam=examination"], phonetic: "", meaning: "n. 考试，测试；检查", example: "The word 'exam=examination' means n. 考试." },
    { word: "examine", syllables: ["ex","am","ine"], phonetic: "/ɪɡˈzæmɪn/", meaning: "v. 检查，细查；对……进行考试", example: "The doctor examined the patient." },
    { word: "example", syllables: ["ex","am","ple"], phonetic: "/ɪɡˈzæmpl/", meaning: "n. 例子；榜样", example: "Can you give me an example?" },
    { word: "excellent", syllables: ["ex","cel","lent"], phonetic: "/ˈeksələnt/", meaning: "adj. 极好的，优秀的", example: "She is an excellent student." },
    { word: "except", syllables: ["ex","cept"], phonetic: "/ɪkˈsept/", meaning: "prep. 除……之外", example: "Everyone came except Tom." },
    { word: "exchange", syllables: ["exchange"], phonetic: "", meaning: "n. 交换；交流", example: "The word 'exchange' means n. 交换." },
    { word: "excited", syllables: ["excited"], phonetic: "", meaning: "adj. 兴奋的", example: "The word 'excited' means adj. 兴奋的." },
    { word: "exciting", syllables: ["exciting"], phonetic: "", meaning: "adj. 使人兴奋的", example: "The word 'exciting' means adj. 使人兴奋的." },
    { word: "excuse", syllables: ["ex","cuse"], phonetic: "/ɪkˈskjuːz/", meaning: "v. 原谅；宽恕; n. 借口；辩解", example: "Excuse me, may I ask a question?" },
    { word: "exercise", syllables: ["ex","er","cise"], phonetic: "/ˈeksərsaɪz/", meaning: "n. 锻炼，做操；练习，习题", example: "You should exercise every day." },
    { word: "exhibition", syllables: ["exhibition"], phonetic: "", meaning: "n. 展览；展览会", example: "The word 'exhibition' means n. 展览." },
    { word: "exist", syllables: ["exist"], phonetic: "", meaning: "v. 存在", example: "The word 'exist' means v. 存在." },
    { word: "exit", syllables: ["exit"], phonetic: "", meaning: "n. 出口，通道; v. 离别；退出", example: "The word 'exit' means n. 出口." },
    { word: "expect", syllables: ["ex","pect"], phonetic: "/ɪkˈspekt/", meaning: "v. 预料；期待；认为", example: "I expect to see you soon." },
    { word: "expensive", syllables: ["ex","pen","sive"], phonetic: "/ɪkˈspensɪv/", meaning: "adj. 昂贵的", example: "This car is very expensive." },
    { word: "experience", syllables: ["ex","pe","ri","ence"], phonetic: "/ɪkˈspɪriəns/", meaning: "n. 经验；经历", example: "It was a wonderful experience." },
    { word: "experiment", syllables: ["ex","per","i","ment"], phonetic: "/ɪkˈsperɪmənt/", meaning: "n. 实验", example: "We did an experiment in science class." },
    { word: "explain", syllables: ["ex","plain"], phonetic: "/ɪkˈspleɪn/", meaning: "v. 解释，说明", example: "Can you explain this word to me?" },
    { word: "explore", syllables: ["explore"], phonetic: "", meaning: "v. 探索；探测", example: "The word 'explore' means v. 探索." },
    { word: "express", syllables: ["ex","press"], phonetic: "/ɪkˈspres/", meaning: "v. 表达；表示; n. 快车", example: "Try to express your ideas clearly." },
    { word: "extra", syllables: ["ex","tra"], phonetic: "/ˈekstrə/", meaning: "adv. 特别地，非常；另外; adj. 额外的", example: "Do you need extra help?" },
    { word: "eye", syllables: ["eye"], phonetic: "/aɪ/", meaning: "n. 眼睛", example: "She has beautiful eyes." },
    { word: "fable", syllables: ["fable"], phonetic: "", meaning: "n. 寓言", example: "The word 'fable' means n. 寓言." },
    { word: "face", syllables: ["face"], phonetic: "/feɪs/", meaning: "n. 脸，面孔; v. 面对", example: "Look at my face." },
    { word: "fact", syllables: ["fact"], phonetic: "/fækt/", meaning: "n. 事实，现实；实际", example: "It is a fact that the earth is round." },
    { word: "factory", syllables: ["fac","to","ry"], phonetic: "/ˈfæktəri/", meaning: "n. 工厂", example: "He works in a factory." },
    { word: "fail", syllables: ["fail"], phonetic: "/feɪl/", meaning: "v. 失败；不及格", example: "Don't be afraid to fail." },
    { word: "fair", syllables: ["fair"], phonetic: "/fer/", meaning: "adj. 公平的，合理的；金色的; n. 集市", example: "That is not fair." },
    { word: "fall (fell, fallen)", syllables: ["fall (fell, fallen)"], phonetic: "", meaning: "v. 落下，降落；倒下；跌倒; n. (美)秋季", example: "The word 'fall (fell, fallen)' means v. 落下." },
    { word: "familiar", syllables: ["familiar"], phonetic: "", meaning: "adj. 熟悉的", example: "The word 'familiar' means adj. 熟悉的." },
    { word: "family", syllables: ["fam","i","ly"], phonetic: "/ˈfæməli/", meaning: "n. 家庭；家族；家人", example: "I love my family." },
    { word: "famous", syllables: ["fa","mous"], phonetic: "/ˈfeɪməs/", meaning: "adj. 著名的", example: "She is a famous singer." },
    { word: "fan", syllables: ["fan"], phonetic: "/fæn/", meaning: "n. (电影、运动等的)迷；热心的爱好者(支持者)；扇子", example: "I am a big fan of basketball." },
    { word: "far (比较级 farther， 最高级 farthest 或比较级 further，最高级 furthest)", syllables: ["far (比较级 farther， 最高级 farthest 或比较级 further，最高级 furthest)"], phonetic: "", meaning: "adj. 远的; adv. 远地", example: "The word 'far (比较级 farther， 最高级 farthest 或比较级 further，最高级 furthest)' means adj. 远的; adv. 远地." },
    { word: "fare", syllables: ["fare"], phonetic: "", meaning: "n. 票价；费用", example: "The word 'fare' means n. 票价." },
    { word: "farm", syllables: ["farm"], phonetic: "/fɑːrm/", meaning: "n. 农场；农庄", example: "My uncle lives on a farm." },
    { word: "farmer", syllables: ["farm","er"], phonetic: "/ˈfɑːrmər/", meaning: "n. 农民，农夫", example: "The farmer grows vegetables." },
    { word: "fashion", syllables: ["fashion"], phonetic: "", meaning: "n. 时尚", example: "The word 'fashion' means n. 时尚." },
    { word: "fast", syllables: ["fast"], phonetic: "/fæst/", meaning: "adj. 快的，迅速的; adv. 快地，迅速地", example: "He runs very fast." },
    { word: "fasten", syllables: ["fasten"], phonetic: "", meaning: "v. 系；扎", example: "The word 'fasten' means v. 系." },
    { word: "fat", syllables: ["fat"], phonetic: "/fæt/", meaning: "adj. 胖的；肥的; n. 脂肪", example: "The cat is very fat." },
    { word: "father", syllables: ["fa","ther"], phonetic: "/ˈfɑːðər/", meaning: "n. 父亲", example: "My father is a doctor." }
  ],
  "第12组": [
    { word: "favour (美 favor)", syllables: ["favour (美 favor)"], phonetic: "", meaning: "n. 恩惠；好意；帮助", example: "The word 'favour (美 favor)' means n. 恩惠." },
    { word: "favourite (美 favorite)", syllables: ["favourite (美 favorite)"], phonetic: "", meaning: "adj. 最喜爱的; n. 特别喜爱的人(或物)", example: "The word 'favourite (美 favorite)' means adj. 最喜爱的; n. 特别喜爱的人(或物)." },
    { word: "fear", syllables: ["fear"], phonetic: "/fɪr/", meaning: "n. 害怕；恐惧", example: "She has a fear of spiders." },
    { word: "feed (fed, fed)", syllables: ["feed (fed, fed)"], phonetic: "", meaning: "v. 喂养；饲养", example: "The word 'feed (fed, fed)' means v. 喂养." },
    { word: "feel (felt, felt)", syllables: ["feel (felt, felt)"], phonetic: "", meaning: "v. & link 感觉，觉得；摸，触", example: "The word 'feel (felt, felt)' means v. & link 感觉." },
    { word: "female", syllables: ["female"], phonetic: "", meaning: "adj. 女的；女性的；雌性的", example: "The word 'female' means adj. 女的." },
    { word: "fence", syllables: ["fence"], phonetic: "", meaning: "n. 栅栏；围栏；篱笆", example: "The word 'fence' means n. 栅栏." },
    { word: "ferry", syllables: ["ferry"], phonetic: "", meaning: "n. 渡船", example: "The word 'ferry' means n. 渡船." },
    { word: "festival", syllables: ["fes","ti","val"], phonetic: "/ˈfestɪvl/", meaning: "n. 节日", example: "Spring Festival is the most important festival in China." },
    { word: "fever", syllables: ["fe","ver"], phonetic: "/ˈfiːvər/", meaning: "n. 发烧；发热", example: "She has a high fever." },
    { word: "few", syllables: ["few"], phonetic: "/fjuː/", meaning: "pron. 不多；少数; adj. 不多的；少数的", example: "Few students know the answer." },
    { word: "field", syllables: ["field"], phonetic: "/fiːld/", meaning: "n. 田地；牧场；场地", example: "The children played in the field." },
    { word: "fight (fought, fought)", syllables: ["fight (fought, fought)"], phonetic: "", meaning: "v. & n.   打仗；打架；争论", example: "The word 'fight (fought, fought)' means v. & n.   打仗." },
    { word: "figure", syllables: ["figure"], phonetic: "", meaning: "n. (人的)体型，外形；数字", example: "The word 'figure' means n. (人的)体型." },
    { word: "fill", syllables: ["fill"], phonetic: "/fɪl/", meaning: "v. 填空；装满；充满", example: "Please fill in the form." },
    { word: "film", syllables: ["film"], phonetic: "/fɪlm/", meaning: "n. 电影；影片；胶卷", example: "We went to see a film last night." },
    { word: "final", syllables: ["fi","nal"], phonetic: "/ˈfaɪnl/", meaning: "adj. 最后的；终极的", example: "The final exam is next Monday." },
    { word: "finally", syllables: ["finally"], phonetic: "", meaning: "adv. 最后；最终", example: "The word 'finally' means adv. 最后." },
    { word: "find (found, found)", syllables: ["find (found, found)"], phonetic: "", meaning: "v. 找到；发现；发觉", example: "The word 'find (found, found)' means v. 找到." },
    { word: "fine", syllables: ["fine"], phonetic: "/faɪn/", meaning: "adj. 晴朗的；美好的；(身体)健康的", example: "I am fine, thank you." },
    { word: "finger", syllables: ["fin","ger"], phonetic: "/ˈfɪŋɡər/", meaning: "n. 手指", example: "She pointed her finger at the map." },
    { word: "finish", syllables: ["fin","ish"], phonetic: "/ˈfɪnɪʃ/", meaning: "v. 结束；做完", example: "I finished my homework." },
    { word: "fire", syllables: ["fire"], phonetic: "/faɪər/", meaning: "n. 火；火炉；火灾; v. 开火，开(枪，炮等)，射击", example: "Be careful with fire." },
    { word: "fireman", syllables: ["fireman"], phonetic: "", meaning: "n. 消防队员", example: "The word 'fireman' means n. 消防队员." },
    { word: "firework", syllables: ["firework"], phonetic: "", meaning: "n. 焰火", example: "The word 'firework' means n. 焰火." },
    { word: "first", syllables: ["first"], phonetic: "/fɜːrst/", meaning: "adj. 第一的；最初的; adv. 第一；首先；最初; n. 开始；开端", example: "She was the first to arrive." },
    { word: "fish", syllables: ["fish"], phonetic: "/fɪʃ/", meaning: "n. 鱼；鱼肉; v. 钓鱼；捕鱼", example: "We had fish for dinner." },
    { word: "fisherman", syllables: ["fisherman"], phonetic: "", meaning: "n. 渔夫，渔民", example: "The word 'fisherman' means n. 渔夫." },
    { word: "fit (fit, fit；fitted, fitted)", syllables: ["fit (fit, fit；fitted, fitted)"], phonetic: "", meaning: "v. (使)适合，与……相配; adj. 健康的， 适合的", example: "The word 'fit (fit, fit；fitted, fitted)' means v. (使)适合." },
    { word: "fix", syllables: ["fix"], phonetic: "/fɪks/", meaning: "v. 修理；安装", example: "He fixed the broken chair." },
    { word: "flash", syllables: ["flash"], phonetic: "", meaning: "n. 闪；闪光； 转瞬间", example: "The word 'flash' means n. 闪." },
    { word: "flag", syllables: ["flag"], phonetic: "/flæɡ/", meaning: "n. 旗；旗舰", example: "The national flag is red." },
    { word: "flat", syllables: ["flat"], phonetic: "/flæt/", meaning: "n. 一套房间； 公寓", example: "They live in a flat." },
    { word: "flight", syllables: ["flight"], phonetic: "/flaɪt/", meaning: "n. 航班；飞行", example: "Our flight leaves at ten." },
    { word: "flood", syllables: ["flood"], phonetic: "", meaning: "n. 洪水，水灾", example: "The word 'flood' means n. 洪水." },
    { word: "floor", syllables: ["floor"], phonetic: "/flɔːr/", meaning: "n. 地面，地板；(楼房的)层", example: "Our classroom is on the second floor." },
    { word: "flower", syllables: ["flow","er"], phonetic: "/ˈflaʊər/", meaning: "n. 花", example: "The flowers are beautiful in spring." },
    { word: "flu", syllables: ["flu"], phonetic: "", meaning: "n. 流感", example: "The word 'flu' means n. 流感." },
    { word: "fly (flew, flown)", syllables: ["fly (flew, flown)"], phonetic: "", meaning: "v. 飞；飞行；乘飞机旅行；(旗子等)飘动; v. 放(风筝、飞机模型等); n. 飞行；苍蝇", example: "The word 'fly (flew, flown)' means v. 飞." },
    { word: "focus", syllables: ["focus"], phonetic: "", meaning: "v. 集中", example: "The word 'focus' means v. 集中." },
    { word: "follow", syllables: ["fol","low"], phonetic: "/ˈfɑːloʊ/", meaning: "v. 听从；跟随；仿效；跟得上", example: "Please follow me." },
    { word: "following", syllables: ["following"], phonetic: "", meaning: "adj. 下列的；接着的；以下的", example: "The word 'following' means adj. 下列的." },
    { word: "fond", syllables: ["fond"], phonetic: "", meaning: "adj. 喜爱的", example: "The word 'fond' means adj. 喜爱的." },
    { word: "food", syllables: ["food"], phonetic: "/fuːd/", meaning: "n. 食物，食品", example: "Chinese food is delicious." },
    { word: "fool", syllables: ["fool"], phonetic: "/fuːl/", meaning: "n. 傻子; v. 愚弄，欺骗", example: "Don't be a fool." },
    { word: "foolish", syllables: ["fool","ish"], phonetic: "/ˈfuːlɪʃ/", meaning: "adj. 愚蠢的，傻的", example: "It is foolish to waste time." },
    { word: "foot (复 feet)", syllables: ["foot (复 feet)"], phonetic: "", meaning: "n. 足，脚；英尺", example: "The word 'foot (复 feet)' means n. 足." },
    { word: "football", syllables: ["foot","ball"], phonetic: "/ˈfʊtbɔːl/", meaning: "n. (英式)足球；(美式)橄榄球", example: "He likes playing football." },
    { word: "for", syllables: ["for"], phonetic: "/fɔːr/", meaning: "prep. (表示目的、用途等)为了……；(表示方向)向……；; conj. 因为，由于", example: "This gift is for you." },
    { word: "forecast", syllables: ["forecast"], phonetic: "", meaning: "n. & v. 预告，预报", example: "The word 'forecast' means n. & v. 预告." }
  ],
  "第13组": [
    { word: "foreign", syllables: ["for","eign"], phonetic: "/ˈfɔːrən/", meaning: "adj. 外国的", example: "She speaks three foreign languages." },
    { word: "foreigner", syllables: ["foreigner"], phonetic: "", meaning: "n. 外国人", example: "The word 'foreigner' means n. 外国人." },
    { word: "forest", syllables: ["for","est"], phonetic: "/ˈfɔːrɪst/", meaning: "n. 森林", example: "The forest is full of trees." },
    { word: "forever", syllables: ["for","ev","er"], phonetic: "/fərˈevər/", meaning: "adv. 永远；永恒地", example: "I will remember you forever." },
    { word: "forget (forgot, forgotten)", syllables: ["forget (forgot, forgotten)"], phonetic: "", meaning: "v. 忘记；忘掉", example: "The word 'forget (forgot, forgotten)' means v. 忘记." },
    { word: "forgetful", syllables: ["forgetful"], phonetic: "", meaning: "adj. 健忘的", example: "The word 'forgetful' means adj. 健忘的." },
    { word: "forgive", syllables: ["forgive"], phonetic: "", meaning: "v. 原谅；宽恕", example: "The word 'forgive' means v. 原谅." },
    { word: "fork", syllables: ["fork"], phonetic: "/fɔːrk/", meaning: "n. 叉", example: "Use a fork to eat the cake." },
    { word: "form", syllables: ["form"], phonetic: "/fɔːrm/", meaning: "n. 形式，方式", example: "Please fill in this form." },
    { word: "forward", syllables: ["for","ward"], phonetic: "/ˈfɔːrwərd/", meaning: "adv. 向前，前进；今后", example: "Please step forward." },
    { word: "fountain", syllables: ["fountain"], phonetic: "", meaning: "n. 喷泉", example: "The word 'fountain' means n. 喷泉." },
    { word: "free", syllables: ["free"], phonetic: "/friː/", meaning: "adj. 自由的，空闲的；免费的", example: "The ticket is free for children." },
    { word: "freedom", syllables: ["free","dom"], phonetic: "/ˈfriːdəm/", meaning: "n. 自由", example: "Everyone should have freedom." },
    { word: "freeze (froze, frozen)", syllables: ["freeze (froze, frozen)"], phonetic: "", meaning: "v. 结冰", example: "The word 'freeze (froze, frozen)' means v. 结冰." },
    { word: "freezing", syllables: ["freezing"], phonetic: "", meaning: "adj. 结冰的；极冷的", example: "The word 'freezing' means adj. 结冰的." },
    { word: "fresh", syllables: ["fresh"], phonetic: "/freʃ/", meaning: "adj. 新鲜的", example: "The vegetables are very fresh." },
    { word: "fridge", syllables: ["fridge"], phonetic: "/frɪdʒ/", meaning: "n. 冰箱", example: "Put the milk in the fridge." },
    { word: "fried", syllables: ["fried"], phonetic: "", meaning: "adj. 油煎的", example: "The word 'fried' means adj. 油煎的." },
    { word: "friend", syllables: ["friend"], phonetic: "/frend/", meaning: "n. 朋友", example: "She is my best friend." },
    { word: "friendly", syllables: ["friend","ly"], phonetic: "/ˈfrendli/", meaning: "adj. 朋友般的；友好的", example: "The people here are very friendly." },
    { word: "friendship", syllables: ["friend","ship"], phonetic: "/ˈfrendʃɪp/", meaning: "n. 友谊", example: "Our friendship will last forever." },
    { word: "frighten", syllables: ["frighten"], phonetic: "", meaning: "v. 使害怕", example: "The word 'frighten' means v. 使害怕." },
    { word: "frightened", syllables: ["frightened"], phonetic: "", meaning: "adj. 受惊吓的；吃惊的", example: "The word 'frightened' means adj. 受惊吓的." },
    { word: "frightening", syllables: ["frightening"], phonetic: "", meaning: "adj. 恐怖的", example: "The word 'frightening' means adj. 恐怖的." },
    { word: "from", syllables: ["from"], phonetic: "/frɑːm/", meaning: "prep. (表示起点)从；自；(表示时间)从……开始；", example: "I am from China." },
    { word: "front", syllables: ["front"], phonetic: "/frʌnt/", meaning: "adj. 前面的；前部的; n. 前面；前部；前线", example: "Please sit in the front row." },
    { word: "frozen", syllables: ["fro","zen"], phonetic: "/ˈfroʊzn/", meaning: "adj. 冰冻的", example: "We bought some frozen food." },
    { word: "fruit", syllables: ["fruit"], phonetic: "/fruːt/", meaning: "n. 水果；果实", example: "Eating fruit is good for health." },
    { word: "fuel", syllables: ["fu","el"], phonetic: "/ˈfjuːəl/", meaning: "n. 燃料", example: "The car needs more fuel." },
    { word: "full", syllables: ["full"], phonetic: "/fʊl/", meaning: "adj. 满的，充满的；完全的", example: "The glass is full of water." },
    { word: "fun", syllables: ["fun"], phonetic: "/fʌn/", meaning: "n. 乐趣；有趣的事；娱乐；玩笑", example: "We had a lot of fun." },
    { word: "funny", syllables: ["fun","ny"], phonetic: "/ˈfʌni/", meaning: "adj. 滑稽的，可笑的", example: "The story is very funny." },
    { word: "furniture", syllables: ["fur","ni","ture"], phonetic: "/ˈfɜːrnɪtʃər/", meaning: "n. (总称)家具", example: "We bought new furniture." },
    { word: "future", syllables: ["fu","ture"], phonetic: "/ˈfjuːtʃər/", meaning: "n. 将来，未来", example: "What do you want to be in the future?" },
    { word: "gain", syllables: ["gain"], phonetic: "", meaning: "v. 获得，得到", example: "The word 'gain' means v. 获得." },
    { word: "game", syllables: ["game"], phonetic: "/ɡeɪm/", meaning: "n. 游戏；运动；比赛", example: "Let's play a game." },
    { word: "garden", syllables: ["gar","den"], phonetic: "/ˈɡɑːrdn/", meaning: "n. 花园，果园，菜园", example: "She is in the garden." },
    { word: "gas", syllables: ["gas"], phonetic: "", meaning: "n. 气态；气体；煤气", example: "The word 'gas' means n. 气态." },
    { word: "gate", syllables: ["gate"], phonetic: "/ɡeɪt/", meaning: "n. 大门", example: "He stood at the gate." },
    { word: "general", syllables: ["gen","er","al"], phonetic: "/ˈdʒenərəl/", meaning: "adj. 大体的，笼统的，总的", example: "This is a general rule." },
    { word: "generation", syllables: ["generation"], phonetic: "", meaning: "n. 代，一代", example: "The word 'generation' means n. 代." },
    { word: "generous", syllables: ["generous"], phonetic: "", meaning: "adj. 慷慨的；大方的", example: "The word 'generous' means adj. 慷慨的." },
    { word: "gentle", syllables: ["gen","tle"], phonetic: "/ˈdʒentl/", meaning: "adj. 温柔的，轻轻的", example: "She has a gentle voice." },
    { word: "gentleman", syllables: ["gen","tle","man"], phonetic: "/ˈdʒentlmən/", meaning: "n. 绅士；先生", example: "He is a gentleman." },
    { word: "gently", syllables: ["gently"], phonetic: "", meaning: "adv. 轻柔地", example: "The word 'gently' means adv. 轻柔地." },
    { word: "geography", syllables: ["ge","og","ra","phy"], phonetic: "/dʒiˈɑːɡrəfi/", meaning: "n. 地理", example: "I like geography class." },
    { word: "get (got, got)", syllables: ["get (got, got)"], phonetic: "", meaning: "v. 成为，变得；得到；到达；", example: "The word 'get (got, got)' means v. 成为." },
    { word: "gift", syllables: ["gift"], phonetic: "/ɡɪft/", meaning: "n. 赠品； 礼物", example: "This is a birthday gift." },
    { word: "girl", syllables: ["girl"], phonetic: "/ɡɜːrl/", meaning: "n. 女孩", example: "She is a lovely girl." },
    { word: "give (gave, given)", syllables: ["give (gave, given)"], phonetic: "", meaning: "v. 给；递给；付出；给予", example: "The word 'give (gave, given)' means v. 给." }
  ]
};