const WORDS_ZK_PZ = {
  "第22组": [
    { word: "pace", syllables: ["pace"], phonetic: "/peɪs/", meaning: "n. 步伐；速度", example: "He walked at a fast pace." },
    { word: "pack", syllables: ["pack"], phonetic: "/pæk/", meaning: "v. 打包；n. 包", example: "Pack your bag before you leave." },
    { word: "page", syllables: ["page"], phonetic: "/peɪdʒ/", meaning: "n. 页", example: "Turn to page ten." },
    { word: "pain", syllables: ["pain"], phonetic: "/peɪn/", meaning: "n. 疼痛", example: "I have a pain in my leg." },
    { word: "paint", syllables: ["paint"], phonetic: "/peɪnt/", meaning: "v./n. 画；油漆", example: "She likes to paint flowers." },
    { word: "pair", syllables: ["pair"], phonetic: "/per/", meaning: "n. 一双", example: "I need a pair of shoes." },
    { word: "palace", syllables: ["pal","ace"], phonetic: "/ˈpælɪs/", meaning: "n. 宫殿", example: "The palace is very beautiful." },
    { word: "pale", syllables: ["pale"], phonetic: "/peɪl/", meaning: "adj. 苍白的", example: "She looked pale and tired." },
    { word: "pancake", syllables: ["pan","cake"], phonetic: "/ˈpænkeɪk/", meaning: "n. 煎饼", example: "I had pancakes for breakfast." },
    { word: "panda", syllables: ["pan","da"], phonetic: "/ˈpændə/", meaning: "n. 熊猫", example: "Pandas live in China." },
    { word: "paper", syllables: ["pa","per"], phonetic: "/ˈpeɪpər/", meaning: "n. 纸；论文", example: "Please write on the paper." },
    { word: "pardon", syllables: ["par","don"], phonetic: "/ˈpɑːrdn/", meaning: "v./n. 原谅", example: "Pardon me, could you repeat that?" },
    { word: "parent", syllables: ["par","ent"], phonetic: "/ˈperənt/", meaning: "n. 父母", example: "My parents are teachers." },
    { word: "park", syllables: ["park"], phonetic: "/pɑːrk/", meaning: "n. 公园；v. 停车", example: "Let's go to the park." },
    { word: "part", syllables: ["part"], phonetic: "/pɑːrt/", meaning: "n. 部分", example: "What part of China are you from?" },
    { word: "partner", syllables: ["part","ner"], phonetic: "/ˈpɑːrtnər/", meaning: "n. 搭档", example: "She is my dancing partner." },
    { word: "party", syllables: ["par","ty"], phonetic: "/ˈpɑːrti/", meaning: "n. 聚会", example: "We had a birthday party." },
    { word: "pass", syllables: ["pass"], phonetic: "/pæs/", meaning: "v. 通过；传递", example: "Please pass me the salt." },
    { word: "passage", syllables: ["pas","sage"], phonetic: "/ˈpæsɪdʒ/", meaning: "n. 文章；通道", example: "Read the passage and answer." },
    { word: "passenger", syllables: ["pas","sen","ger"], phonetic: "/ˈpæsɪndʒər/", meaning: "n. 乘客", example: "The passengers got on the bus." },
    { word: "passport", syllables: ["pass","port"], phonetic: "/ˈpæspɔːrt/", meaning: "n. 护照", example: "Don't forget your passport." },
    { word: "past", syllables: ["past"], phonetic: "/pæst/", meaning: "n./adj. 过去", example: "In the past, people walked more." },
    { word: "path", syllables: ["path"], phonetic: "/pæθ/", meaning: "n. 小路", example: "Follow this path to the lake." },
    { word: "patient", syllables: ["pa","tient"], phonetic: "/ˈpeɪʃnt/", meaning: "n. 病人；adj. 耐心的", example: "Please be patient." },
    { word: "pay", syllables: ["pay"], phonetic: "/peɪ/", meaning: "v. 付款", example: "I paid fifty yuan for the book." },
    { word: "peace", syllables: ["peace"], phonetic: "/piːs/", meaning: "n. 和平", example: "We all want peace." },
    { word: "peaceful", syllables: ["peace","ful"], phonetic: "/ˈpiːsfl/", meaning: "adj. 和平的", example: "The village is very peaceful." },
    { word: "pear", syllables: ["pear"], phonetic: "/per/", meaning: "n. 梨", example: "The pear tastes sweet." },
    { word: "pen", syllables: ["pen"], phonetic: "/pen/", meaning: "n. 钢笔", example: "I write with a pen." },
    { word: "pencil", syllables: ["pen","cil"], phonetic: "/ˈpensl/", meaning: "n. 铅笔", example: "May I borrow your pencil?" },
    { word: "penny", syllables: ["pen","ny"], phonetic: "/ˈpeni/", meaning: "n. 便士", example: "It costs one penny." },
    { word: "people", syllables: ["peo","ple"], phonetic: "/ˈpiːpl/", meaning: "n. 人们", example: "Many people like music." },
    { word: "pepper", syllables: ["pep","per"], phonetic: "/ˈpepər/", meaning: "n. 胡椒", example: "Add some pepper to the soup." },
    { word: "percent", syllables: ["per","cent"], phonetic: "/pərˈsent/", meaning: "n. 百分之", example: "Fifty percent of students passed." },
    { word: "perfect", syllables: ["per","fect"], phonetic: "/ˈpɜːrfɪkt/", meaning: "adj. 完美的", example: "The weather is perfect today." },
    { word: "perhaps", syllables: ["per","haps"], phonetic: "/pərˈhæps/", meaning: "adv. 也许", example: "Perhaps it will rain tomorrow." },
    { word: "period", syllables: ["pe","ri","od"], phonetic: "/ˈpɪriəd/", meaning: "n. 时期；一节课", example: "We have six periods today." },
    { word: "person", syllables: ["per","son"], phonetic: "/ˈpɜːrsn/", meaning: "n. 人", example: "She is a kind person." },
    { word: "personal", syllables: ["per","son","al"], phonetic: "/ˈpɜːrsənl/", meaning: "adj. 个人的", example: "This is my personal opinion." },
    { word: "pet", syllables: ["pet"], phonetic: "/pet/", meaning: "n. 宠物", example: "I have a pet dog." },
    { word: "phone", syllables: ["phone"], phonetic: "/foʊn/", meaning: "n. 电话", example: "Call me on the phone." },
    { word: "photo", syllables: ["pho","to"], phonetic: "/ˈfoʊtoʊ/", meaning: "n. 照片", example: "Let's take a photo." },
    { word: "piano", syllables: ["pi","an","o"], phonetic: "/piˈænoʊ/", meaning: "n. 钢琴", example: "She plays the piano well." },
    { word: "pick", syllables: ["pick"], phonetic: "/pɪk/", meaning: "v. 挑选；捡", example: "Pick up the paper, please." },
    { word: "picnic", syllables: ["pic","nic"], phonetic: "/ˈpɪknɪk/", meaning: "n. 野餐", example: "Let's have a picnic." },
    { word: "picture", syllables: ["pic","ture"], phonetic: "/ˈpɪktʃər/", meaning: "n. 图片", example: "Draw a picture of your house." },
    { word: "pie", syllables: ["pie"], phonetic: "/paɪ/", meaning: "n. 馅饼", example: "I like apple pie." },
    { word: "piece", syllables: ["piece"], phonetic: "/piːs/", meaning: "n. 一块；一片", example: "Would you like a piece of cake?" },
    { word: "pig", syllables: ["pig"], phonetic: "/pɪɡ/", meaning: "n. 猪", example: "The pig is pink." },
    { word: "pilot", syllables: ["pi","lot"], phonetic: "/ˈpaɪlət/", meaning: "n. 飞行员", example: "The pilot flies the plane." }
  ],
  "第23组": [
    { word: "pin", syllables: ["pin"], phonetic: "/pɪn/", meaning: "n. 大头针；v. 固定", example: "Use a pin to hold it." },
    { word: "pink", syllables: ["pink"], phonetic: "/pɪŋk/", meaning: "adj. 粉色的", example: "She wore a pink dress." },
    { word: "pioneer", syllables: ["pi","o","neer"], phonetic: "/ˌpaɪəˈnɪr/", meaning: "n. 先锋", example: "He is a young pioneer." },
    { word: "pity", syllables: ["pi","ty"], phonetic: "/ˈpɪti/", meaning: "n. 遗憾", example: "What a pity!" },
    { word: "place", syllables: ["place"], phonetic: "/pleɪs/", meaning: "n. 地方；v. 放置", example: "This is a nice place." },
    { word: "plain", syllables: ["plain"], phonetic: "/pleɪn/", meaning: "adj. 朴素的；n. 平原", example: "She likes plain food." },
    { word: "plan", syllables: ["plan"], phonetic: "/plæn/", meaning: "n./v. 计划", example: "We plan to go camping." },
    { word: "plane", syllables: ["plane"], phonetic: "/pleɪn/", meaning: "n. 飞机", example: "The plane is taking off." },
    { word: "planet", syllables: ["plan","et"], phonetic: "/ˈplænɪt/", meaning: "n. 行星", example: "Earth is a planet." },
    { word: "plant", syllables: ["plant"], phonetic: "/plænt/", meaning: "n. 植物；v. 种植", example: "They plant trees in spring." },
    { word: "plastic", syllables: ["plas","tic"], phonetic: "/ˈplæstɪk/", meaning: "n./adj. 塑料", example: "Don't use too much plastic." },
    { word: "plate", syllables: ["plate"], phonetic: "/pleɪt/", meaning: "n. 盘子", example: "Put the food on the plate." },
    { word: "play", syllables: ["play"], phonetic: "/pleɪ/", meaning: "v. 玩；播放", example: "Let's play basketball." },
    { word: "player", syllables: ["play","er"], phonetic: "/ˈpleɪər/", meaning: "n. 玩家；运动员", example: "He is a good soccer player." },
    { word: "playground", syllables: ["play","ground"], phonetic: "/ˈpleɪɡraʊnd/", meaning: "n. 操场", example: "The children are on the playground." },
    { word: "pleasant", syllables: ["pleas","ant"], phonetic: "/ˈpleznt/", meaning: "adj. 令人愉快的", example: "We had a pleasant trip." },
    { word: "please", syllables: ["please"], phonetic: "/pliːz/", meaning: "adv. 请", example: "Please sit down." },
    { word: "pleasure", syllables: ["pleas","ure"], phonetic: "/ˈpleʒər/", meaning: "n. 快乐", example: "It's a pleasure to meet you." },
    { word: "plenty", syllables: ["plen","ty"], phonetic: "/ˈplenti/", meaning: "pron. 大量", example: "We have plenty of time." },
    { word: "pocket", syllables: ["pock","et"], phonetic: "/ˈpɒkɪt/", meaning: "n. 口袋", example: "Put it in your pocket." },
    { word: "poem", syllables: ["po","em"], phonetic: "/ˈpoʊəm/", meaning: "n. 诗", example: "She wrote a beautiful poem." },
    { word: "poet", syllables: ["po","et"], phonetic: "/ˈpoʊət/", meaning: "n. 诗人", example: "Li Bai was a great poet." },
    { word: "point", syllables: ["point"], phonetic: "/pɔɪnt/", meaning: "n. 点；v. 指", example: "He pointed at the map." },
    { word: "police", syllables: ["po","lice"], phonetic: "/pəˈliːs/", meaning: "n. 警察", example: "Call the police!" },
    { word: "policeman", syllables: ["po","lice","man"], phonetic: "/pəˈliːsmən/", meaning: "n. 警察", example: "The policeman helped me." },
    { word: "polite", syllables: ["po","lite"], phonetic: "/pəˈlaɪt/", meaning: "adj. 有礼貌的", example: "He is a polite boy." },
    { word: "pollution", syllables: ["pol","lu","tion"], phonetic: "/pəˈluːʃn/", meaning: "n. 污染", example: "Air pollution is a big problem." },
    { word: "pool", syllables: ["pool"], phonetic: "/puːl/", meaning: "n. 水池", example: "Let's swim in the pool." },
    { word: "poor", syllables: ["poor"], phonetic: "/pʊr/", meaning: "adj. 贫穷的；可怜的", example: "The poor boy needs help." },
    { word: "popular", syllables: ["pop","u","lar"], phonetic: "/ˈpɒpjələr/", meaning: "adj. 流行的", example: "Soccer is very popular." },
    { word: "population", syllables: ["pop","u","la","tion"], phonetic: "/ˌpɒpjuˈleɪʃn/", meaning: "n. 人口", example: "China has a large population." },
    { word: "pork", syllables: ["pork"], phonetic: "/pɔːrk/", meaning: "n. 猪肉", example: "I like pork dumplings." },
    { word: "possible", syllables: ["pos","si","ble"], phonetic: "/ˈpɒsəbl/", meaning: "adj. 可能的", example: "Is it possible to finish today?" },
    { word: "post", syllables: ["post"], phonetic: "/poʊst/", meaning: "n. 邮政；v. 邮寄", example: "I'll post the letter." },
    { word: "postcard", syllables: ["post","card"], phonetic: "/ˈpoʊstkɑːrd/", meaning: "n. 明信片", example: "She sent me a postcard." },
    { word: "potato", syllables: ["po","ta","to"], phonetic: "/pəˈteɪtoʊ/", meaning: "n. 土豆", example: "Would you like some potatoes?" },
    { word: "pound", syllables: ["pound"], phonetic: "/paʊnd/", meaning: "n. 英镑", example: "It costs five pounds." },
    { word: "pour", syllables: ["pour"], phonetic: "/pɔːr/", meaning: "v. 倒；倾泻", example: "Pour some water into the cup." },
    { word: "practice", syllables: ["prac","tice"], phonetic: "/ˈpræktɪs/", meaning: "n./v. 练习", example: "Practice makes perfect." },
    { word: "praise", syllables: ["praise"], phonetic: "/preɪz/", meaning: "v./n. 表扬", example: "The teacher praised him." },
    { word: "predict", syllables: ["pre","dict"], phonetic: "/prɪˈdɪkt/", meaning: "v. 预测", example: "It's hard to predict the weather." },
    { word: "prefer", syllables: ["pre","fer"], phonetic: "/prɪˈfɜːr/", meaning: "v. 更喜欢", example: "I prefer tea to coffee." },
    { word: "prepare", syllables: ["pre","pare"], phonetic: "/prɪˈper/", meaning: "v. 准备", example: "We need to prepare for the exam." },
    { word: "present", syllables: ["pres","ent"], phonetic: "/ˈpreznt/", meaning: "n. 礼物；adj. 当前的", example: "I got a birthday present." },
    { word: "president", syllables: ["pres","i","dent"], phonetic: "/ˈprezɪdənt/", meaning: "n. 总统；主席", example: "He is the class president." },
    { word: "press", syllables: ["press"], phonetic: "/pres/", meaning: "v. 按；压", example: "Press the button to start." },
    { word: "pretty", syllables: ["pret","ty"], phonetic: "/ˈprɪti/", meaning: "adj. 漂亮的；adv. 相当", example: "She looks pretty today." },
    { word: "prevent", syllables: ["pre","vent"], phonetic: "/prɪˈvent/", meaning: "v. 阻止", example: "Wash hands to prevent illness." },
    { word: "price", syllables: ["price"], phonetic: "/praɪs/", meaning: "n. 价格", example: "The price is too high." }
  ],
  "第24组": [
    { word: "pride", syllables: ["pride"], phonetic: "/praɪd/", meaning: "n. 骄傲；自豪", example: "She takes pride in her work." },
    { word: "primary", syllables: ["pri","ma","ry"], phonetic: "/ˈpraɪmeri/", meaning: "adj. 小学的；主要的", example: "I went to primary school here." },
    { word: "print", syllables: ["print"], phonetic: "/prɪnt/", meaning: "v. 打印", example: "Can you print this document?" },
    { word: "private", syllables: ["pri","vate"], phonetic: "/ˈpraɪvət/", meaning: "adj. 私人的", example: "This is a private matter." },
    { word: "prize", syllables: ["prize"], phonetic: "/praɪz/", meaning: "n. 奖品", example: "She won first prize." },
    { word: "probably", syllables: ["prob","a","bly"], phonetic: "/ˈprɒbəbli/", meaning: "adv. 大概", example: "It will probably rain." },
    { word: "problem", syllables: ["prob","lem"], phonetic: "/ˈprɒbləm/", meaning: "n. 问题", example: "Can you solve this problem?" },
    { word: "produce", syllables: ["pro","duce"], phonetic: "/prəˈdjuːs/", meaning: "v. 生产", example: "The factory produces cars." },
    { word: "product", syllables: ["prod","uct"], phonetic: "/ˈprɒdʌkt/", meaning: "n. 产品", example: "This product is made in China." },
    { word: "program", syllables: ["pro","gram"], phonetic: "/ˈproʊɡræm/", meaning: "n. 节目；程序", example: "I like this TV program." },
    { word: "progress", syllables: ["prog","ress"], phonetic: "/ˈprɒɡres/", meaning: "n. 进步", example: "She has made good progress." },
    { word: "project", syllables: ["proj","ect"], phonetic: "/ˈprɒdʒekt/", meaning: "n. 项目", example: "We're working on a science project." },
    { word: "promise", syllables: ["prom","ise"], phonetic: "/ˈprɒmɪs/", meaning: "v./n. 承诺", example: "I promise to come on time." },
    { word: "pronounce", syllables: ["pro","nounce"], phonetic: "/prəˈnaʊns/", meaning: "v. 发音", example: "How do you pronounce this word?" },
    { word: "proper", syllables: ["prop","er"], phonetic: "/ˈprɒpər/", meaning: "adj. 适当的", example: "That's not the proper way." },
    { word: "protect", syllables: ["pro","tect"], phonetic: "/prəˈtekt/", meaning: "v. 保护", example: "We should protect the earth." },
    { word: "proud", syllables: ["proud"], phonetic: "/praʊd/", meaning: "adj. 自豪的", example: "I'm proud of you." },
    { word: "prove", syllables: ["prove"], phonetic: "/pruːv/", meaning: "v. 证明", example: "You need to prove it." },
    { word: "provide", syllables: ["pro","vide"], phonetic: "/prəˈvaɪd/", meaning: "v. 提供", example: "They provide free food." },
    { word: "public", syllables: ["pub","lic"], phonetic: "/ˈpʌblɪk/", meaning: "adj. 公共的", example: "Don't smoke in public places." },
    { word: "pull", syllables: ["pull"], phonetic: "/pʊl/", meaning: "v. 拉", example: "Pull the door open." },
    { word: "punish", syllables: ["pun","ish"], phonetic: "/ˈpʌnɪʃ/", meaning: "v. 惩罚", example: "Don't punish the child." },
    { word: "pupil", syllables: ["pu","pil"], phonetic: "/ˈpjuːpl/", meaning: "n. 学生", example: "There are thirty pupils in the class." },
    { word: "purple", syllables: ["pur","ple"], phonetic: "/ˈpɜːrpl/", meaning: "adj. 紫色的", example: "She likes purple flowers." },
    { word: "purpose", syllables: ["pur","pose"], phonetic: "/ˈpɜːrpəs/", meaning: "n. 目的", example: "What's the purpose of the meeting?" },
    { word: "push", syllables: ["push"], phonetic: "/pʊʃ/", meaning: "v. 推", example: "Push the cart, please." },
    { word: "put", syllables: ["put"], phonetic: "/pʊt/", meaning: "v. 放", example: "Put the book on the table." },
    { word: "quarter", syllables: ["quar","ter"], phonetic: "/ˈkwɔːrtər/", meaning: "n. 四分之一", example: "A quarter of the students are girls." },
    { word: "queen", syllables: ["queen"], phonetic: "/kwiːn/", meaning: "n. 女王", example: "The queen lives in the palace." },
    { word: "question", syllables: ["ques","tion"], phonetic: "/ˈkwestʃən/", meaning: "n. 问题", example: "Can I ask a question?" },
    { word: "quick", syllables: ["quick"], phonetic: "/kwɪk/", meaning: "adj. 快的", example: "Be quick! We're late." },
    { word: "quiet", syllables: ["qui","et"], phonetic: "/ˈkwaɪət/", meaning: "adj. 安静的", example: "Please keep quiet." },
    { word: "quite", syllables: ["quite"], phonetic: "/kwaɪt/", meaning: "adv. 相当", example: "It's quite cold today." },
    { word: "rabbit", syllables: ["rab","bit"], phonetic: "/ˈræbɪt/", meaning: "n. 兔子", example: "The rabbit is white." },
    { word: "race", syllables: ["race"], phonetic: "/reɪs/", meaning: "n. 赛跑；种族", example: "He won the race." },
    { word: "radio", syllables: ["ra","di","o"], phonetic: "/ˈreɪdioʊ/", meaning: "n. 收音机", example: "I listen to the radio every day." },
    { word: "rain", syllables: ["rain"], phonetic: "/reɪn/", meaning: "n./v. 雨；下雨", example: "It's raining outside." },
    { word: "rainy", syllables: ["rain","y"], phonetic: "/ˈreɪni/", meaning: "adj. 多雨的", example: "It's a rainy day." },
    { word: "raise", syllables: ["raise"], phonetic: "/reɪz/", meaning: "v. 举起；养育", example: "Raise your hand." },
    { word: "rapid", syllables: ["rap","id"], phonetic: "/ˈræpɪd/", meaning: "adj. 快速的", example: "The city has rapid growth." },
    { word: "reach", syllables: ["reach"], phonetic: "/riːtʃ/", meaning: "v. 到达；够到", example: "Can you reach the top shelf?" },
    { word: "read", syllables: ["read"], phonetic: "/riːd/", meaning: "v. 读", example: "I read books every night." },
    { word: "ready", syllables: ["read","y"], phonetic: "/ˈredi/", meaning: "adj. 准备好的", example: "Are you ready?" },
    { word: "real", syllables: ["real"], phonetic: "/riːl/", meaning: "adj. 真的", example: "Is this real gold?" },
    { word: "realize", syllables: ["re","al","ize"], phonetic: "/ˈriːəlaɪz/", meaning: "v. 意识到", example: "I realized my mistake." },
    { word: "really", syllables: ["real","ly"], phonetic: "/ˈriːəli/", meaning: "adv. 真地", example: "Do you really like it?" },
    { word: "reason", syllables: ["rea","son"], phonetic: "/ˈriːzn/", meaning: "n. 原因", example: "What's the reason?" },
    { word: "receive", syllables: ["re","ceive"], phonetic: "/rɪˈsiːv/", meaning: "v. 收到", example: "I received a letter today." },
    { word: "record", syllables: ["re","cord"], phonetic: "/ˈrekɔːrd/", meaning: "n. 记录；v. 录制", example: "He broke the world record." },
    { word: "red", syllables: ["red"], phonetic: "/red/", meaning: "adj. 红色的", example: "She has red hair." }
  ],
  "第25组": [
    { word: "reduce", syllables: ["re","duce"], phonetic: "/rɪˈdjuːs/", meaning: "v. 减少", example: "We should reduce waste." },
    { word: "refuse", syllables: ["re","fuse"], phonetic: "/rɪˈfjuːz/", meaning: "v. 拒绝", example: "He refused to go." },
    { word: "relax", syllables: ["re","lax"], phonetic: "/rɪˈlæks/", meaning: "v. 放松", example: "Let's relax after work." },
    { word: "remain", syllables: ["re","main"], phonetic: "/rɪˈmeɪn/", meaning: "v. 保持；剩下", example: "Please remain seated." },
    { word: "remember", syllables: ["re","mem","ber"], phonetic: "/rɪˈmembər/", meaning: "v. 记住", example: "Remember to lock the door." },
    { word: "repair", syllables: ["re","pair"], phonetic: "/rɪˈper/", meaning: "v. 修理", example: "I need to repair my bike." },
    { word: "repeat", syllables: ["re","peat"], phonetic: "/rɪˈpiːt/", meaning: "v. 重复", example: "Please repeat the sentence." },
    { word: "reply", syllables: ["re","ply"], phonetic: "/rɪˈplaɪ/", meaning: "v./n. 回复", example: "He didn't reply to my email." },
    { word: "report", syllables: ["re","port"], phonetic: "/rɪˈpɔːrt/", meaning: "n./v. 报告", example: "Write a report about the trip." },
    { word: "require", syllables: ["re","quire"], phonetic: "/rɪˈkwaɪər/", meaning: "v. 要求", example: "The job requires English skills." },
    { word: "research", syllables: ["re","search"], phonetic: "/rɪˈsɜːrtʃ/", meaning: "n. 研究", example: "She is doing research on animals." },
    { word: "respect", syllables: ["re","spect"], phonetic: "/rɪˈspekt/", meaning: "v./n. 尊重", example: "We should respect our teachers." },
    { word: "rest", syllables: ["rest"], phonetic: "/rest/", meaning: "n./v. 休息", example: "Let's take a rest." },
    { word: "restaurant", syllables: ["res","tau","rant"], phonetic: "/ˈrestrɒnt/", meaning: "n. 餐厅", example: "Let's eat at a restaurant." },
    { word: "result", syllables: ["re","sult"], phonetic: "/rɪˈzʌlt/", meaning: "n. 结果", example: "The result was surprising." },
    { word: "return", syllables: ["re","turn"], phonetic: "/rɪˈtɜːrn/", meaning: "v. 返回；归还", example: "Return the book tomorrow." },
    { word: "review", syllables: ["re","view"], phonetic: "/rɪˈvjuː/", meaning: "v./n. 复习；评论", example: "Let's review the lesson." },
    { word: "rice", syllables: ["rice"], phonetic: "/raɪs/", meaning: "n. 米饭", example: "We eat rice for lunch." },
    { word: "rich", syllables: ["rich"], phonetic: "/rɪtʃ/", meaning: "adj. 富有的；丰富的", example: "He comes from a rich family." },
    { word: "ride", syllables: ["ride"], phonetic: "/raɪd/", meaning: "v./n. 骑；乘", example: "I ride my bike to school." },
    { word: "right", syllables: ["right"], phonetic: "/raɪt/", meaning: "adj. 正确的；右边的", example: "You are right." },
    { word: "ring", syllables: ["ring"], phonetic: "/rɪŋ/", meaning: "n. 戒指；v. 响铃", example: "The bell is ringing." },
    { word: "rise", syllables: ["rise"], phonetic: "/raɪz/", meaning: "v. 上升", example: "The sun rises in the east." },
    { word: "risk", syllables: ["risk"], phonetic: "/rɪsk/", meaning: "n. 风险", example: "Don't take the risk." },
    { word: "river", syllables: ["riv","er"], phonetic: "/ˈrɪvər/", meaning: "n. 河流", example: "The river is very long." },
    { word: "road", syllables: ["road"], phonetic: "/roʊd/", meaning: "n. 道路", example: "The road is very busy." },
    { word: "robot", syllables: ["ro","bot"], phonetic: "/ˈroʊbɑːt/", meaning: "n. 机器人", example: "The robot can clean the house." },
    { word: "rock", syllables: ["rock"], phonetic: "/rɒk/", meaning: "n. 岩石；摇滚", example: "He likes rock music." },
    { word: "role", syllables: ["role"], phonetic: "/roʊl/", meaning: "n. 角色", example: "She played the main role." },
    { word: "roll", syllables: ["roll"], phonetic: "/roʊl/", meaning: "v. 滚动；卷", example: "The ball rolled down the hill." },
    { word: "roof", syllables: ["roof"], phonetic: "/ruːf/", meaning: "n. 屋顶", example: "The cat is on the roof." },
    { word: "room", syllables: ["room"], phonetic: "/ruːm/", meaning: "n. 房间", example: "This is my room." },
    { word: "rope", syllables: ["rope"], phonetic: "/roʊp/", meaning: "n. 绳子", example: "Tie it with a rope." },
    { word: "rose", syllables: ["rose"], phonetic: "/roʊz/", meaning: "n. 玫瑰", example: "She received a red rose." },
    { word: "round", syllables: ["round"], phonetic: "/raʊnd/", meaning: "adj. 圆的", example: "The earth is round." },
    { word: "row", syllables: ["row"], phonetic: "/roʊ/", meaning: "n. 排；行", example: "Sit in the first row." },
    { word: "rule", syllables: ["rule"], phonetic: "/ruːl/", meaning: "n. 规则；v. 统治", example: "Follow the school rules." },
    { word: "ruler", syllables: ["ru","ler"], phonetic: "/ˈruːlər/", meaning: "n. 尺子", example: "Use a ruler to draw a line." },
    { word: "run", syllables: ["run"], phonetic: "/rʌn/", meaning: "v. 跑", example: "He runs very fast." },
    { word: "rush", syllables: ["rush"], phonetic: "/rʌʃ/", meaning: "v. 冲；匆忙", example: "Don't rush." },
    { word: "sad", syllables: ["sad"], phonetic: "/sæd/", meaning: "adj. 伤心的", example: "She looks sad." },
    { word: "safe", syllables: ["safe"], phonetic: "/seɪf/", meaning: "adj. 安全的", example: "Keep your money safe." },
    { word: "safety", syllables: ["safe","ty"], phonetic: "/ˈseɪfti/", meaning: "n. 安全", example: "Safety comes first." },
    { word: "sail", syllables: ["sail"], phonetic: "/seɪl/", meaning: "v. 航行", example: "They sailed across the sea." },
    { word: "salad", syllables: ["sal","ad"], phonetic: "/ˈsæləd/", meaning: "n. 沙拉", example: "I'd like a fruit salad." },
    { word: "sale", syllables: ["sale"], phonetic: "/seɪl/", meaning: "n. 销售", example: "The shoes are on sale." },
    { word: "salt", syllables: ["salt"], phonetic: "/sɒlt/", meaning: "n. 盐", example: "Add some salt to the soup." },
    { word: "same", syllables: ["same"], phonetic: "/seɪm/", meaning: "adj. 相同的", example: "We are in the same class." },
    { word: "sand", syllables: ["sand"], phonetic: "/sænd/", meaning: "n. 沙子", example: "The children play in the sand." },
    { word: "sandwich", syllables: ["sand","wich"], phonetic: "/ˈsænwɪtʃ/", meaning: "n. 三明治", example: "I had a sandwich for lunch." }
  ],
  "第26组": [
    { word: "satisfy", syllables: ["sat","is","fy"], phonetic: "/ˈsætɪsfaɪ/", meaning: "v. 满足", example: "The answer satisfied me." },
    { word: "Saturday", syllables: ["Sat","ur","day"], phonetic: "/ˈsætərdeɪ/", meaning: "n. 星期六", example: "I play soccer on Saturday." },
    { word: "save", syllables: ["save"], phonetic: "/seɪv/", meaning: "v. 救；节省", example: "Save water, please." },
    { word: "say", syllables: ["say"], phonetic: "/seɪ/", meaning: "v. 说", example: "What did he say?" },
    { word: "school", syllables: ["school"], phonetic: "/skuːl/", meaning: "n. 学校", example: "I go to school at seven." },
    { word: "schoolbag", syllables: ["school","bag"], phonetic: "/ˈskuːlbæɡ/", meaning: "n. 书包", example: "My schoolbag is heavy." },
    { word: "science", syllables: ["sci","ence"], phonetic: "/ˈsaɪəns/", meaning: "n. 科学", example: "I like science class." },
    { word: "scientist", syllables: ["sci","en","tist"], phonetic: "/ˈsaɪəntɪst/", meaning: "n. 科学家", example: "She wants to be a scientist." },
    { word: "score", syllables: ["score"], phonetic: "/skɔːr/", meaning: "n. 分数；v. 得分", example: "What's the score?" },
    { word: "sea", syllables: ["sea"], phonetic: "/siː/", meaning: "n. 海", example: "Let's go to the sea." },
    { word: "search", syllables: ["search"], phonetic: "/sɜːrtʃ/", meaning: "v./n. 搜索", example: "Search for information online." },
    { word: "season", syllables: ["sea","son"], phonetic: "/ˈsiːzn/", meaning: "n. 季节", example: "Spring is my favorite season." },
    { word: "seat", syllables: ["seat"], phonetic: "/siːt/", meaning: "n. 座位", example: "Take a seat, please." },
    { word: "second", syllables: ["sec","ond"], phonetic: "/ˈsekənd/", meaning: "num. 第二；n. 秒", example: "Wait a second." },
    { word: "secret", syllables: ["se","cret"], phonetic: "/ˈsiːkrɪt/", meaning: "n./adj. 秘密", example: "It's a secret." },
    { word: "see", syllables: ["see"], phonetic: "/siː/", meaning: "v. 看见", example: "I can see a bird." },
    { word: "seed", syllables: ["seed"], phonetic: "/siːd/", meaning: "n. 种子", example: "Plant the seeds in spring." },
    { word: "seem", syllables: ["seem"], phonetic: "/siːm/", meaning: "v. 似乎", example: "He seems happy." },
    { word: "sell", syllables: ["sell"], phonetic: "/sel/", meaning: "v. 卖", example: "They sell fruit and vegetables." },
    { word: "send", syllables: ["send"], phonetic: "/send/", meaning: "v. 发送", example: "Please send me an email." },
    { word: "sense", syllables: ["sense"], phonetic: "/sens/", meaning: "n. 感觉；感官", example: "A dog has a good sense of smell." },
    { word: "sentence", syllables: ["sen","tence"], phonetic: "/ˈsentəns/", meaning: "n. 句子", example: "Read the first sentence." },
    { word: "September", syllables: ["Sep","tem","ber"], phonetic: "/sepˈtembər/", meaning: "n. 九月", example: "School starts in September." },
    { word: "serious", syllables: ["se","ri","ous"], phonetic: "/ˈsɪriəs/", meaning: "adj. 严重的；严肃的", example: "Are you serious?" },
    { word: "serve", syllables: ["serve"], phonetic: "/sɜːrv/", meaning: "v. 服务", example: "Breakfast is served at seven." },
    { word: "service", syllables: ["ser","vice"], phonetic: "/ˈsɜːrvɪs/", meaning: "n. 服务", example: "The service here is good." },
    { word: "set", syllables: ["set"], phonetic: "/set/", meaning: "v. 设置；n. 一套", example: "Set the alarm for six." },
    { word: "seven", syllables: ["sev","en"], phonetic: "/ˈsevn/", meaning: "num. 七", example: "I get up at seven." },
    { word: "several", syllables: ["sev","er","al"], phonetic: "/ˈsevrəl/", meaning: "adj. 几个", example: "I have several friends here." },
    { word: "shake", syllables: ["shake"], phonetic: "/ʃeɪk/", meaning: "v. 摇晃", example: "Shake the bottle before use." },
    { word: "shall", syllables: ["shall"], phonetic: "/ʃæl/", meaning: "v. 将要", example: "Shall we go now?" },
    { word: "shape", syllables: ["shape"], phonetic: "/ʃeɪp/", meaning: "n. 形状", example: "What shape is it?" },
    { word: "share", syllables: ["share"], phonetic: "/ʃer/", meaning: "v. 分享", example: "Let's share the pizza." },
    { word: "she", syllables: ["she"], phonetic: "/ʃiː/", meaning: "pron. 她", example: "She is my sister." },
    { word: "sheep", syllables: ["sheep"], phonetic: "/ʃiːp/", meaning: "n. 羊", example: "There are many sheep on the farm." },
    { word: "shelf", syllables: ["shelf"], phonetic: "/ʃelf/", meaning: "n. 架子", example: "Put the book on the shelf." },
    { word: "shine", syllables: ["shine"], phonetic: "/ʃaɪn/", meaning: "v. 照耀", example: "The sun is shining." },
    { word: "ship", syllables: ["ship"], phonetic: "/ʃɪp/", meaning: "n. 船", example: "The ship sailed away." },
    { word: "shirt", syllables: ["shirt"], phonetic: "/ʃɜːrt/", meaning: "n. 衬衫", example: "He bought a new shirt." },
    { word: "shoe", syllables: ["shoe"], phonetic: "/ʃuː/", meaning: "n. 鞋子", example: "My shoes are too small." },
    { word: "shop", syllables: ["shop"], phonetic: "/ʃɒp/", meaning: "n. 商店；v. 购物", example: "Let's go shopping." },
    { word: "short", syllables: ["short"], phonetic: "/ʃɔːrt/", meaning: "adj. 短的；矮的", example: "The pencil is too short." },
    { word: "shorts", syllables: ["shorts"], phonetic: "/ʃɔːrts/", meaning: "n. 短裤", example: "He wears shorts in summer." },
    { word: "should", syllables: ["should"], phonetic: "/ʃʊd/", meaning: "v. 应该", example: "You should study hard." },
    { word: "shoulder", syllables: ["shoul","der"], phonetic: "/ˈʃoʊldər/", meaning: "n. 肩膀", example: "He put his arm on my shoulder." },
    { word: "shout", syllables: ["shout"], phonetic: "/ʃaʊt/", meaning: "v. 喊叫", example: "Don't shout in class." },
    { word: "show", syllables: ["show"], phonetic: "/ʃoʊ/", meaning: "v. 展示；n. 表演", example: "Show me your homework." },
    { word: "shower", syllables: ["show","er"], phonetic: "/ˈʃaʊər/", meaning: "n. 淋浴", example: "I take a shower every morning." },
    { word: "shut", syllables: ["shut"], phonetic: "/ʃʌt/", meaning: "v. 关闭", example: "Shut the door, please." },
    { word: "shy", syllables: ["shy"], phonetic: "/ʃaɪ/", meaning: "adj. 害羞的", example: "She is shy around strangers." }
  ],
  "第27组": [
    { word: "sick", syllables: ["sick"], phonetic: "/sɪk/", meaning: "adj. 生病的", example: "She is sick today." },
    { word: "side", syllables: ["side"], phonetic: "/saɪd/", meaning: "n. 边", example: "Sit by my side." },
    { word: "sight", syllables: ["sight"], phonetic: "/saɪt/", meaning: "n. 视力；风景", example: "She has good sight." },
    { word: "silence", syllables: ["si","lence"], phonetic: "/ˈsaɪləns/", meaning: "n. 安静", example: "There was complete silence." },
    { word: "silent", syllables: ["si","lent"], phonetic: "/ˈsaɪlənt/", meaning: "adj. 沉默的", example: "Please keep silent." },
    { word: "silly", syllables: ["sil","ly"], phonetic: "/ˈsɪli/", meaning: "adj. 愚蠢的", example: "Don't be silly." },
    { word: "silver", syllables: ["sil","ver"], phonetic: "/ˈsɪlvər/", meaning: "n./adj. 银", example: "She wears a silver ring." },
    { word: "similar", syllables: ["sim","i","lar"], phonetic: "/ˈsɪmələr/", meaning: "adj. 相似的", example: "Our ideas are similar." },
    { word: "simple", syllables: ["sim","ple"], phonetic: "/ˈsɪmpl/", meaning: "adj. 简单的", example: "The answer is simple." },
    { word: "since", syllables: ["since"], phonetic: "/sɪns/", meaning: "prep. 自从；conj. 因为", example: "I've lived here since 2010." },
    { word: "sing", syllables: ["sing"], phonetic: "/sɪŋ/", meaning: "v. 唱歌", example: "She sings beautifully." },
    { word: "single", syllables: ["sin","gle"], phonetic: "/ˈsɪŋɡl/", meaning: "adj. 单一的", example: "Not a single person came." },
    { word: "sir", syllables: ["sir"], phonetic: "/sɜːr/", meaning: "n. 先生", example: "Yes, sir." },
    { word: "sister", syllables: ["sis","ter"], phonetic: "/ˈsɪstər/", meaning: "n. 姐妹", example: "My sister is a doctor." },
    { word: "sit", syllables: ["sit"], phonetic: "/sɪt/", meaning: "v. 坐", example: "Please sit down." },
    { word: "situation", syllables: ["sit","u","a","tion"], phonetic: "/ˌsɪtʃuˈeɪʃn/", meaning: "n. 情况", example: "The situation is getting better." },
    { word: "six", syllables: ["six"], phonetic: "/sɪks/", meaning: "num. 六", example: "There are six apples." },
    { word: "size", syllables: ["size"], phonetic: "/saɪz/", meaning: "n. 尺寸", example: "What size do you need?" },
    { word: "skate", syllables: ["skate"], phonetic: "/skeɪt/", meaning: "v. 滑冰", example: "I like to skate in winter." },
    { word: "skill", syllables: ["skill"], phonetic: "/skɪl/", meaning: "n. 技能", example: "Reading is an important skill." },
    { word: "skin", syllables: ["skin"], phonetic: "/skɪn/", meaning: "n. 皮肤", example: "She has soft skin." },
    { word: "skirt", syllables: ["skirt"], phonetic: "/skɜːrt/", meaning: "n. 裙子", example: "She bought a new skirt." },
    { word: "sky", syllables: ["sky"], phonetic: "/skaɪ/", meaning: "n. 天空", example: "The sky is blue." },
    { word: "sleep", syllables: ["sleep"], phonetic: "/sliːp/", meaning: "v./n. 睡觉", example: "I sleep eight hours a day." },
    { word: "slow", syllables: ["slow"], phonetic: "/sloʊ/", meaning: "adj. 慢的", example: "The turtle is very slow." },
    { word: "small", syllables: ["small"], phonetic: "/smɔːl/", meaning: "adj. 小的", example: "The cat is very small." },
    { word: "smart", syllables: ["smart"], phonetic: "/smɑːrt/", meaning: "adj. 聪明的", example: "She is a smart student." },
    { word: "smell", syllables: ["smell"], phonetic: "/smel/", meaning: "v. 闻；n. 气味", example: "The flowers smell good." },
    { word: "smile", syllables: ["smile"], phonetic: "/smaɪl/", meaning: "v./n. 微笑", example: "She smiled at me." },
    { word: "smoke", syllables: ["smoke"], phonetic: "/smoʊk/", meaning: "v. 抽烟；n. 烟", example: "Don't smoke here." },
    { word: "smooth", syllables: ["smooth"], phonetic: "/smuːð/", meaning: "adj. 光滑的", example: "The road is smooth." },
    { word: "snow", syllables: ["snow"], phonetic: "/snoʊ/", meaning: "n./v. 雪；下雪", example: "It snowed last night." },
    { word: "so", syllables: ["so"], phonetic: "/soʊ/", meaning: "adv. 如此；conj. 所以", example: "I'm tired, so I'll rest." },
    { word: "soccer", syllables: ["soc","cer"], phonetic: "/ˈsɒkər/", meaning: "n. 足球", example: "Do you like soccer?" },
    { word: "social", syllables: ["so","cial"], phonetic: "/ˈsoʊʃl/", meaning: "adj. 社会的", example: "She has a good social life." },
    { word: "society", syllables: ["so","ci","e","ty"], phonetic: "/səˈsaɪəti/", meaning: "n. 社会", example: "We live in a modern society." },
    { word: "sock", syllables: ["sock"], phonetic: "/sɒk/", meaning: "n. 袜子", example: "I need a pair of socks." },
    { word: "sofa", syllables: ["so","fa"], phonetic: "/ˈsoʊfə/", meaning: "n. 沙发", example: "Sit on the sofa." },
    { word: "soft", syllables: ["soft"], phonetic: "/sɒft/", meaning: "adj. 柔软的", example: "The bed is very soft." },
    { word: "some", syllables: ["some"], phonetic: "/sʌm/", meaning: "adj. 一些", example: "I need some water." },
    { word: "somebody", syllables: ["some","bod","y"], phonetic: "/ˈsʌmbɑːdi/", meaning: "pron. 某人", example: "Somebody is at the door." },
    { word: "someone", syllables: ["some","one"], phonetic: "/ˈsʌmwʌn/", meaning: "pron. 某人", example: "Someone called you." },
    { word: "something", syllables: ["some","thing"], phonetic: "/ˈsʌmθɪŋ/", meaning: "pron. 某事", example: "I want to tell you something." },
    { word: "sometimes", syllables: ["some","times"], phonetic: "/ˈsʌmtaɪmz/", meaning: "adv. 有时", example: "Sometimes I walk to school." },
    { word: "somewhere", syllables: ["some","where"], phonetic: "/ˈsʌmwer/", meaning: "adv. 某处", example: "Let's go somewhere nice." },
    { word: "son", syllables: ["son"], phonetic: "/sʌn/", meaning: "n. 儿子", example: "He has two sons." },
    { word: "song", syllables: ["song"], phonetic: "/sɒŋ/", meaning: "n. 歌曲", example: "I like this song." },
    { word: "soon", syllables: ["soon"], phonetic: "/suːn/", meaning: "adv. 很快", example: "See you soon." },
    { word: "sorry", syllables: ["sor","ry"], phonetic: "/ˈsɒri/", meaning: "adj. 抱歉的", example: "I'm sorry I'm late." },
    { word: "sort", syllables: ["sort"], phonetic: "/sɔːrt/", meaning: "n. 种类；v. 分类", example: "What sort of music do you like?" }
  ],
  "第28组": [
    { word: "sound", syllables: ["sound"], phonetic: "/saʊnd/", meaning: "n. 声音；v. 听起来", example: "That sounds great." },
    { word: "south", syllables: ["south"], phonetic: "/saʊθ/", meaning: "n./adj. 南方", example: "Guangzhou is in the south." },
    { word: "space", syllables: ["space"], phonetic: "/speɪs/", meaning: "n. 空间；太空", example: "The astronaut went into space." },
    { word: "spare", syllables: ["spare"], phonetic: "/sper/", meaning: "adj. 空闲的；备用的", example: "I have some spare time." },
    { word: "speak", syllables: ["speak"], phonetic: "/spiːk/", meaning: "v. 说（语言）；讲话", example: "Can you speak English?" },
    { word: "speaker", syllables: ["speak","er"], phonetic: "/ˈspiːkər/", meaning: "n. 演讲者；扬声器", example: "She is a good speaker." },
    { word: "special", syllables: ["spe","cial"], phonetic: "/ˈspeʃl/", meaning: "adj. 特别的", example: "Today is a special day." },
    { word: "speech", syllables: ["speech"], phonetic: "/spiːtʃ/", meaning: "n. 演讲", example: "He gave a speech." },
    { word: "speed", syllables: ["speed"], phonetic: "/spiːd/", meaning: "n. 速度", example: "The car runs at high speed." },
    { word: "spend", syllables: ["spend"], phonetic: "/spend/", meaning: "v. 花费；度过", example: "I spend two hours on homework." },
    { word: "spirit", syllables: ["spir","it"], phonetic: "/ˈspɪrɪt/", meaning: "n. 精神", example: "Team spirit is important." },
    { word: "spoon", syllables: ["spoon"], phonetic: "/spuːn/", meaning: "n. 勺子", example: "Use a spoon to eat soup." },
    { word: "sport", syllables: ["sport"], phonetic: "/spɔːrt/", meaning: "n. 运动", example: "I like all kinds of sports." },
    { word: "spread", syllables: ["spread"], phonetic: "/spred/", meaning: "v. 传播", example: "The news spread quickly." },
    { word: "spring", syllables: ["spring"], phonetic: "/sprɪŋ/", meaning: "n. 春天；泉水", example: "Flowers bloom in spring." },
    { word: "square", syllables: ["square"], phonetic: "/skwer/", meaning: "n. 广场；正方形", example: "Meet me at the square." },
    { word: "stage", syllables: ["stage"], phonetic: "/steɪdʒ/", meaning: "n. 舞台；阶段", example: "She is on the stage." },
    { word: "stand", syllables: ["stand"], phonetic: "/stænd/", meaning: "v. 站；忍受", example: "Please stand up." },
    { word: "standard", syllables: ["stan","dard"], phonetic: "/ˈstændərd/", meaning: "n. 标准", example: "The standard is very high." },
    { word: "star", syllables: ["star"], phonetic: "/stɑːr/", meaning: "n. 星星；明星", example: "Look at the stars." },
    { word: "start", syllables: ["start"], phonetic: "/stɑːrt/", meaning: "v./n. 开始", example: "School starts at eight." },
    { word: "state", syllables: ["state"], phonetic: "/steɪt/", meaning: "n. 州；状态", example: "What state are you in?" },
    { word: "station", syllables: ["sta","tion"], phonetic: "/ˈsteɪʃn/", meaning: "n. 车站", example: "The train station is near here." },
    { word: "stay", syllables: ["stay"], phonetic: "/steɪ/", meaning: "v. 停留", example: "Stay here and wait." },
    { word: "steal", syllables: ["steal"], phonetic: "/stiːl/", meaning: "v. 偷", example: "Someone stole my bike." },
    { word: "step", syllables: ["step"], phonetic: "/step/", meaning: "n. 步骤；脚步", example: "Take it step by step." },
    { word: "stick", syllables: ["stick"], phonetic: "/stɪk/", meaning: "n. 棍子；v. 粘贴", example: "Stick the picture on the wall." },
    { word: "still", syllables: ["still"], phonetic: "/stɪl/", meaning: "adv. 仍然", example: "He is still sleeping." },
    { word: "stomach", syllables: ["stom","ach"], phonetic: "/ˈstʌmək/", meaning: "n. 胃；肚子", example: "My stomach hurts." },
    { word: "stone", syllables: ["stone"], phonetic: "/stoʊn/", meaning: "n. 石头", example: "The wall is made of stone." },
    { word: "stop", syllables: ["stop"], phonetic: "/stɒp/", meaning: "v. 停止；n. 车站", example: "Stop talking, please." },
    { word: "store", syllables: ["store"], phonetic: "/stɔːr/", meaning: "n. 商店；v. 储存", example: "The store is open today." },
    { word: "storm", syllables: ["storm"], phonetic: "/stɔːrm/", meaning: "n. 暴风雨", example: "A storm is coming." },
    { word: "story", syllables: ["sto","ry"], phonetic: "/ˈstɔːri/", meaning: "n. 故事", example: "Tell me a story." },
    { word: "straight", syllables: ["straight"], phonetic: "/streɪt/", meaning: "adj./adv. 直的；直接地", example: "Go straight ahead." },
    { word: "strange", syllables: ["strange"], phonetic: "/streɪndʒ/", meaning: "adj. 奇怪的；陌生的", example: "What a strange noise!" },
    { word: "stranger", syllables: ["stran","ger"], phonetic: "/ˈstreɪndʒər/", meaning: "n. 陌生人", example: "Don't talk to strangers." },
    { word: "strawberry", syllables: ["straw","ber","ry"], phonetic: "/ˈstrɔːberi/", meaning: "n. 草莓", example: "I love strawberries." },
    { word: "street", syllables: ["street"], phonetic: "/striːt/", meaning: "n. 街道", example: "The school is on this street." },
    { word: "strict", syllables: ["strict"], phonetic: "/strɪkt/", meaning: "adj. 严格的", example: "My teacher is very strict." },
    { word: "strong", syllables: ["strong"], phonetic: "/strɒŋ/", meaning: "adj. 强壮的", example: "He is very strong." },
    { word: "student", syllables: ["stu","dent"], phonetic: "/ˈstjuːdnt/", meaning: "n. 学生", example: "There are forty students." },
    { word: "study", syllables: ["stud","y"], phonetic: "/ˈstʌdi/", meaning: "v./n. 学习", example: "I study English every day." },
    { word: "style", syllables: ["style"], phonetic: "/staɪl/", meaning: "n. 风格", example: "I like her style." },
    { word: "subject", syllables: ["sub","ject"], phonetic: "/ˈsʌbdʒɪkt/", meaning: "n. 科目；主题", example: "What's your favorite subject?" },
    { word: "succeed", syllables: ["suc","ceed"], phonetic: "/səkˈsiːd/", meaning: "v. 成功", example: "If you try hard, you will succeed." },
    { word: "success", syllables: ["suc","cess"], phonetic: "/səkˈses/", meaning: "n. 成功", example: "The project was a success." },
    { word: "successful", syllables: ["suc","cess","ful"], phonetic: "/səkˈsesfl/", meaning: "adj. 成功的", example: "She is a successful writer." },
    { word: "such", syllables: ["such"], phonetic: "/sʌtʃ/", meaning: "adj. 如此的", example: "I've never seen such a thing." },
    { word: "sudden", syllables: ["sud","den"], phonetic: "/ˈsʌdn/", meaning: "adj. 突然的", example: "There was a sudden noise." }
  ],
  "第29组": [
    { word: "sugar", syllables: ["sug","ar"], phonetic: "/ˈʃʊɡər/", meaning: "n. 糖", example: "Don't eat too much sugar." },
    { word: "suggest", syllables: ["sug","gest"], phonetic: "/səˈdʒest/", meaning: "v. 建议", example: "I suggest we go now." },
    { word: "suit", syllables: ["suit"], phonetic: "/suːt/", meaning: "n. 套装；v. 适合", example: "This suit fits well." },
    { word: "summer", syllables: ["sum","mer"], phonetic: "/ˈsʌmər/", meaning: "n. 夏天", example: "Summer is very hot." },
    { word: "sun", syllables: ["sun"], phonetic: "/sʌn/", meaning: "n. 太阳", example: "The sun is bright." },
    { word: "Sunday", syllables: ["Sun","day"], phonetic: "/ˈsʌndeɪ/", meaning: "n. 星期日", example: "We rest on Sunday." },
    { word: "sunny", syllables: ["sun","ny"], phonetic: "/ˈsʌni/", meaning: "adj. 晴朗的", example: "It's a sunny day." },
    { word: "supermarket", syllables: ["su","per","mar","ket"], phonetic: "/ˈsuːpərmɑːrkɪt/", meaning: "n. 超市", example: "I buy food at the supermarket." },
    { word: "support", syllables: ["sup","port"], phonetic: "/səˈpɔːrt/", meaning: "v./n. 支持", example: "I support your idea." },
    { word: "sure", syllables: ["sure"], phonetic: "/ʃʊr/", meaning: "adj. 确定的", example: "Are you sure?" },
    { word: "surprise", syllables: ["sur","prise"], phonetic: "/sərˈpraɪz/", meaning: "n./v. 惊喜", example: "What a nice surprise!" },
    { word: "survey", syllables: ["sur","vey"], phonetic: "/ˈsɜːrveɪ/", meaning: "n. 调查", example: "We did a survey about food." },
    { word: "sweep", syllables: ["sweep"], phonetic: "/swiːp/", meaning: "v. 扫", example: "Please sweep the floor." },
    { word: "sweet", syllables: ["sweet"], phonetic: "/swiːt/", meaning: "adj. 甜的", example: "The cake is very sweet." },
    { word: "swim", syllables: ["swim"], phonetic: "/swɪm/", meaning: "v. 游泳", example: "I like to swim in summer." },
    { word: "symbol", syllables: ["sym","bol"], phonetic: "/ˈsɪmbl/", meaning: "n. 象征", example: "The dove is a symbol of peace." },
    { word: "table", syllables: ["ta","ble"], phonetic: "/ˈteɪbl/", meaning: "n. 桌子", example: "The book is on the table." },
    { word: "tail", syllables: ["tail"], phonetic: "/teɪl/", meaning: "n. 尾巴", example: "The dog wagged its tail." },
    { word: "take", syllables: ["take"], phonetic: "/teɪk/", meaning: "v. 拿；带", example: "Take your umbrella." },
    { word: "tale", syllables: ["tale"], phonetic: "/teɪl/", meaning: "n. 故事", example: "Tell me a fairy tale." },
    { word: "talk", syllables: ["talk"], phonetic: "/tɔːk/", meaning: "v./n. 谈话", example: "Let's talk about it." },
    { word: "tall", syllables: ["tall"], phonetic: "/tɔːl/", meaning: "adj. 高的", example: "He is very tall." },
    { word: "tape", syllables: ["tape"], phonetic: "/teɪp/", meaning: "n. 磁带；胶带", example: "I need some tape." },
    { word: "task", syllables: ["task"], phonetic: "/tæsk/", meaning: "n. 任务", example: "Finish the task by Friday." },
    { word: "taste", syllables: ["taste"], phonetic: "/teɪst/", meaning: "v. 尝；n. 味道", example: "The soup tastes good." },
    { word: "taxi", syllables: ["tax","i"], phonetic: "/ˈtæksi/", meaning: "n. 出租车", example: "Let's take a taxi." },
    { word: "tea", syllables: ["tea"], phonetic: "/tiː/", meaning: "n. 茶", example: "Would you like some tea?" },
    { word: "teach", syllables: ["teach"], phonetic: "/tiːtʃ/", meaning: "v. 教", example: "She teaches English." },
    { word: "teacher", syllables: ["teach","er"], phonetic: "/ˈtiːtʃər/", meaning: "n. 老师", example: "Our teacher is very kind." },
    { word: "team", syllables: ["team"], phonetic: "/tiːm/", meaning: "n. 团队", example: "Our team won the game." },
    { word: "technology", syllables: ["tech","nol","o","gy"], phonetic: "/tekˈnɒlədʒi/", meaning: "n. 技术", example: "Technology changes our life." },
    { word: "tell", syllables: ["tell"], phonetic: "/tel/", meaning: "v. 告诉", example: "Tell me your name." },
    { word: "temperature", syllables: ["tem","per","a","ture"], phonetic: "/ˈtemprətʃər/", meaning: "n. 温度", example: "The temperature is 30 degrees." },
    { word: "tennis", syllables: ["ten","nis"], phonetic: "/ˈtenɪs/", meaning: "n. 网球", example: "Let's play tennis." },
    { word: "tent", syllables: ["tent"], phonetic: "/tent/", meaning: "n. 帐篷", example: "We put up a tent." },
    { word: "term", syllables: ["term"], phonetic: "/tɜːrm/", meaning: "n. 学期；术语", example: "We have two terms a year." },
    { word: "terrible", syllables: ["ter","ri","ble"], phonetic: "/ˈterəbl/", meaning: "adj. 糟糕的", example: "The weather was terrible." },
    { word: "test", syllables: ["test"], phonetic: "/test/", meaning: "n./v. 测试", example: "We have a math test." },
    { word: "text", syllables: ["text"], phonetic: "/tekst/", meaning: "n. 文本；课文", example: "Read the text carefully." },
    { word: "than", syllables: ["than"], phonetic: "/ðæn/", meaning: "conj. 比", example: "She is taller than me." },
    { word: "thank", syllables: ["thank"], phonetic: "/θæŋk/", meaning: "v. 感谢", example: "Thank you for your help." },
    { word: "that", syllables: ["that"], phonetic: "/ðæt/", meaning: "pron. 那个", example: "That is my book." },
    { word: "the", syllables: ["the"], phonetic: "/ðə/", meaning: "art. 这；那", example: "The sun is bright." },
    { word: "theater", syllables: ["the","a","ter"], phonetic: "/ˈθiːətər/", meaning: "n. 剧院", example: "Let's go to the theater." },
    { word: "their", syllables: ["their"], phonetic: "/ðer/", meaning: "pron. 他们的", example: "Their house is big." },
    { word: "them", syllables: ["them"], phonetic: "/ðem/", meaning: "pron. 他们", example: "I saw them yesterday." },
    { word: "themselves", syllables: ["them","selves"], phonetic: "/ðəmˈselvz/", meaning: "pron. 他们自己", example: "They did it themselves." },
    { word: "then", syllables: ["then"], phonetic: "/ðen/", meaning: "adv. 然后；那时", example: "First wash, then eat." },
    { word: "there", syllables: ["there"], phonetic: "/ðer/", meaning: "adv. 那里", example: "Put it over there." }
  ],
  "第30组": [
    { word: "these", syllables: ["these"], phonetic: "/ðiːz/", meaning: "pron. 这些", example: "These are my books." },
    { word: "they", syllables: ["they"], phonetic: "/ðeɪ/", meaning: "pron. 他们", example: "They are students." },
    { word: "thick", syllables: ["thick"], phonetic: "/θɪk/", meaning: "adj. 厚的；浓的", example: "The book is very thick." },
    { word: "thin", syllables: ["thin"], phonetic: "/θɪn/", meaning: "adj. 薄的；瘦的", example: "The paper is very thin." },
    { word: "thing", syllables: ["thing"], phonetic: "/θɪŋ/", meaning: "n. 东西；事情", example: "What's that thing?" },
    { word: "think", syllables: ["think"], phonetic: "/θɪŋk/", meaning: "v. 想；认为", example: "I think you're right." },
    { word: "thirsty", syllables: ["thirs","ty"], phonetic: "/ˈθɜːrsti/", meaning: "adj. 口渴的", example: "I'm thirsty. Can I have water?" },
    { word: "this", syllables: ["this"], phonetic: "/ðɪs/", meaning: "pron. 这个", example: "This is my pen." },
    { word: "those", syllables: ["those"], phonetic: "/ðoʊz/", meaning: "pron. 那些", example: "Those are flowers." },
    { word: "though", syllables: ["though"], phonetic: "/ðoʊ/", meaning: "conj. 虽然", example: "Though he is young, he is smart." },
    { word: "thought", syllables: ["thought"], phonetic: "/θɔːt/", meaning: "n. 想法", example: "What are your thoughts?" },
    { word: "thousand", syllables: ["thou","sand"], phonetic: "/ˈθaʊznd/", meaning: "num. 千", example: "There are thousands of people." },
    { word: "three", syllables: ["three"], phonetic: "/θriː/", meaning: "num. 三", example: "I have three brothers." },
    { word: "throat", syllables: ["throat"], phonetic: "/θroʊt/", meaning: "n. 喉咙", example: "My throat is sore." },
    { word: "through", syllables: ["through"], phonetic: "/θruː/", meaning: "prep. 通过；穿过", example: "Walk through the door." },
    { word: "throw", syllables: ["throw"], phonetic: "/θroʊ/", meaning: "v. 扔", example: "Don't throw rubbish." },
    { word: "Thursday", syllables: ["Thurs","day"], phonetic: "/ˈθɜːrzdeɪ/", meaning: "n. 星期四", example: "We have PE on Thursday." },
    { word: "ticket", syllables: ["tick","et"], phonetic: "/ˈtɪkɪt/", meaning: "n. 票", example: "I bought two tickets." },
    { word: "tidy", syllables: ["ti","dy"], phonetic: "/ˈtaɪdi/", meaning: "adj. 整洁的", example: "Keep your room tidy." },
    { word: "tie", syllables: ["tie"], phonetic: "/taɪ/", meaning: "v. 系；n. 领带", example: "Tie your shoes." },
    { word: "tiger", syllables: ["ti","ger"], phonetic: "/ˈtaɪɡər/", meaning: "n. 老虎", example: "The tiger is strong." },
    { word: "till", syllables: ["till"], phonetic: "/tɪl/", meaning: "prep./conj. 直到", example: "Wait till I come back." },
    { word: "time", syllables: ["time"], phonetic: "/taɪm/", meaning: "n. 时间", example: "What time is it?" },
    { word: "tiny", syllables: ["ti","ny"], phonetic: "/ˈtaɪni/", meaning: "adj. 极小的", example: "The baby has tiny hands." },
    { word: "tired", syllables: ["tired"], phonetic: "/taɪərd/", meaning: "adj. 疲劳的", example: "I'm very tired today." },
    { word: "to", syllables: ["to"], phonetic: "/tuː/", meaning: "prep. 到；向", example: "Let's go to school." },
    { word: "today", syllables: ["to","day"], phonetic: "/təˈdeɪ/", meaning: "n./adv. 今天", example: "Today is Monday." },
    { word: "together", syllables: ["to","geth","er"], phonetic: "/təˈɡeðər/", meaning: "adv. 一起", example: "Let's play together." },
    { word: "tomato", syllables: ["to","ma","to"], phonetic: "/təˈmeɪtoʊ/", meaning: "n. 西红柿", example: "I like tomatoes." },
    { word: "tomorrow", syllables: ["to","mor","row"], phonetic: "/təˈmɒroʊ/", meaning: "n./adv. 明天", example: "See you tomorrow." },
    { word: "tonight", syllables: ["to","night"], phonetic: "/təˈnaɪt/", meaning: "n./adv. 今晚", example: "Let's watch TV tonight." },
    { word: "too", syllables: ["too"], phonetic: "/tuː/", meaning: "adv. 也；太", example: "It's too hot." },
    { word: "tool", syllables: ["tool"], phonetic: "/tuːl/", meaning: "n. 工具", example: "A hammer is a tool." },
    { word: "tooth", syllables: ["tooth"], phonetic: "/tuːθ/", meaning: "n. 牙齿", example: "Brush your teeth." },
    { word: "top", syllables: ["top"], phonetic: "/tɒp/", meaning: "n. 顶部", example: "The cat is on top of the box." },
    { word: "total", syllables: ["to","tal"], phonetic: "/ˈtoʊtl/", meaning: "adj. 总共的", example: "The total cost is fifty yuan." },
    { word: "touch", syllables: ["touch"], phonetic: "/tʌtʃ/", meaning: "v. 触摸", example: "Don't touch the painting." },
    { word: "tour", syllables: ["tour"], phonetic: "/tʊr/", meaning: "n. 旅行", example: "We went on a tour of Beijing." },
    { word: "tourist", syllables: ["tour","ist"], phonetic: "/ˈtʊrɪst/", meaning: "n. 游客", example: "Many tourists visit here." },
    { word: "toward", syllables: ["to","ward"], phonetic: "/təˈwɔːrd/", meaning: "prep. 朝向", example: "He walked toward the door." },
    { word: "tower", syllables: ["tow","er"], phonetic: "/ˈtaʊər/", meaning: "n. 塔", example: "The TV tower is very tall." },
    { word: "town", syllables: ["town"], phonetic: "/taʊn/", meaning: "n. 城镇", example: "I live in a small town." },
    { word: "toy", syllables: ["toy"], phonetic: "/tɔɪ/", meaning: "n. 玩具", example: "Children like toys." },
    { word: "traditional", syllables: ["tra","di","tion","al"], phonetic: "/trəˈdɪʃənl/", meaning: "adj. 传统的", example: "Dumplings are traditional food." },
    { word: "traffic", syllables: ["traf","fic"], phonetic: "/ˈtræfɪk/", meaning: "n. 交通", example: "The traffic is heavy today." },
    { word: "train", syllables: ["train"], phonetic: "/treɪn/", meaning: "n. 火车；v. 训练", example: "I go to school by train." },
    { word: "travel", syllables: ["trav","el"], phonetic: "/ˈtrævl/", meaning: "v./n. 旅行", example: "I like to travel." },
    { word: "treasure", syllables: ["treas","ure"], phonetic: "/ˈtreʒər/", meaning: "n. 财宝", example: "They found buried treasure." },
    { word: "treat", syllables: ["treat"], phonetic: "/triːt/", meaning: "v. 对待；治疗", example: "Treat others kindly." },
    { word: "tree", syllables: ["tree"], phonetic: "/triː/", meaning: "n. 树", example: "The tree is very tall." }
  ],
  "第31组": [
    { word: "trip", syllables: ["trip"], phonetic: "/trɪp/", meaning: "n. 旅行", example: "We had a school trip." },
    { word: "trouble", syllables: ["trou","ble"], phonetic: "/ˈtrʌbl/", meaning: "n. 麻烦", example: "What's the trouble?" },
    { word: "truck", syllables: ["truck"], phonetic: "/trʌk/", meaning: "n. 卡车", example: "The truck carries goods." },
    { word: "true", syllables: ["true"], phonetic: "/truː/", meaning: "adj. 真实的", example: "Is this story true?" },
    { word: "trust", syllables: ["trust"], phonetic: "/trʌst/", meaning: "v./n. 信任", example: "I trust you." },
    { word: "truth", syllables: ["truth"], phonetic: "/truːθ/", meaning: "n. 真相", example: "Tell me the truth." },
    { word: "try", syllables: ["try"], phonetic: "/traɪ/", meaning: "v. 尝试", example: "Try your best." },
    { word: "turn", syllables: ["turn"], phonetic: "/tɜːrn/", meaning: "v. 转弯；翻转", example: "Turn left at the corner." },
    { word: "twice", syllables: ["twice"], phonetic: "/twaɪs/", meaning: "adv. 两次", example: "I brush my teeth twice a day." },
    { word: "type", syllables: ["type"], phonetic: "/taɪp/", meaning: "n. 类型；v. 打字", example: "What type of music is this?" },
    { word: "ugly", syllables: ["ug","ly"], phonetic: "/ˈʌɡli/", meaning: "adj. 丑陋的", example: "The frog is ugly but useful." },
    { word: "uncle", syllables: ["un","cle"], phonetic: "/ˈʌŋkl/", meaning: "n. 叔叔", example: "My uncle lives in Beijing." },
    { word: "under", syllables: ["un","der"], phonetic: "/ˈʌndər/", meaning: "prep. 在…下面", example: "The cat is under the table." },
    { word: "underground", syllables: ["un","der","ground"], phonetic: "/ˈʌndərɡraʊnd/", meaning: "n. 地铁；adj. 地下的", example: "Take the underground." },
    { word: "understand", syllables: ["un","der","stand"], phonetic: "/ˌʌndərˈstænd/", meaning: "v. 理解", example: "I understand now." },
    { word: "unless", syllables: ["un","less"], phonetic: "/ʌnˈles/", meaning: "conj. 除非", example: "I won't go unless you come." },
    { word: "until", syllables: ["un","til"], phonetic: "/ʌnˈtɪl/", meaning: "prep./conj. 直到", example: "Wait until I return." },
    { word: "up", syllables: ["up"], phonetic: "/ʌp/", meaning: "adv. 向上", example: "Stand up, please." },
    { word: "upon", syllables: ["u","pon"], phonetic: "/əˈpɒn/", meaning: "prep. 在…之上", example: "Once upon a time..." },
    { word: "upset", syllables: ["up","set"], phonetic: "/ʌpˈset/", meaning: "adj. 心烦的", example: "Don't be upset." },
    { word: "us", syllables: ["us"], phonetic: "/ʌs/", meaning: "pron. 我们", example: "Tell us a story." },
    { word: "use", syllables: ["use"], phonetic: "/juːz/", meaning: "v./n. 使用", example: "Can I use your pen?" },
    { word: "used", syllables: ["used"], phonetic: "/juːzd/", meaning: "adj. 习惯的；用过的", example: "I used to walk to school." },
    { word: "useful", syllables: ["use","ful"], phonetic: "/ˈjuːsfl/", meaning: "adj. 有用的", example: "This tool is very useful." },
    { word: "usual", syllables: ["u","su","al"], phonetic: "/ˈjuːʒuəl/", meaning: "adj. 通常的", example: "He arrived earlier than usual." },
    { word: "usually", syllables: ["u","su","al","ly"], phonetic: "/ˈjuːʒuəli/", meaning: "adv. 通常", example: "I usually get up at seven." },
    { word: "vacation", syllables: ["va","ca","tion"], phonetic: "/veɪˈkeɪʃn/", meaning: "n. 假期", example: "We went to the beach on vacation." },
    { word: "valuable", syllables: ["val","u","a","ble"], phonetic: "/ˈvæljuəbl/", meaning: "adj. 有价值的", example: "Time is valuable." },
    { word: "value", syllables: ["val","ue"], phonetic: "/ˈvæljuː/", meaning: "n. 价值", example: "What's the value of this book?" },
    { word: "vegetable", syllables: ["veg","e","ta","ble"], phonetic: "/ˈvedʒtəbl/", meaning: "n. 蔬菜", example: "Eat more vegetables." },
    { word: "very", syllables: ["ver","y"], phonetic: "/ˈveri/", meaning: "adv. 非常", example: "It's very cold today." },
    { word: "victory", syllables: ["vic","to","ry"], phonetic: "/ˈvɪktəri/", meaning: "n. 胜利", example: "We celebrated our victory." },
    { word: "video", syllables: ["vid","e","o"], phonetic: "/ˈvɪdioʊ/", meaning: "n. 视频", example: "Let's watch a video." },
    { word: "view", syllables: ["view"], phonetic: "/vjuː/", meaning: "n. 风景；观点", example: "The view from the hill is great." },
    { word: "village", syllables: ["vil","lage"], phonetic: "/ˈvɪlɪdʒ/", meaning: "n. 村庄", example: "She lives in a small village." },
    { word: "violin", syllables: ["vi","o","lin"], phonetic: "/ˌvaɪəˈlɪn/", meaning: "n. 小提琴", example: "She plays the violin." },
    { word: "visit", syllables: ["vis","it"], phonetic: "/ˈvɪzɪt/", meaning: "v./n. 参观；拜访", example: "I visited my grandma." },
    { word: "visitor", syllables: ["vis","i","tor"], phonetic: "/ˈvɪzɪtər/", meaning: "n. 访客", example: "The museum has many visitors." },
    { word: "voice", syllables: ["voice"], phonetic: "/vɔɪs/", meaning: "n. 声音", example: "She has a beautiful voice." },
    { word: "volunteer", syllables: ["vol","un","teer"], phonetic: "/ˌvɒlənˈtɪr/", meaning: "n. 志愿者", example: "She works as a volunteer." },
    { word: "wait", syllables: ["wait"], phonetic: "/weɪt/", meaning: "v. 等待", example: "Wait for me!" },
    { word: "wake", syllables: ["wake"], phonetic: "/weɪk/", meaning: "v. 醒来", example: "I wake up at six." },
    { word: "walk", syllables: ["walk"], phonetic: "/wɔːk/", meaning: "v./n. 走路", example: "I walk to school every day." },
    { word: "wall", syllables: ["wall"], phonetic: "/wɔːl/", meaning: "n. 墙", example: "There is a picture on the wall." },
    { word: "want", syllables: ["want"], phonetic: "/wɒnt/", meaning: "v. 想要", example: "I want to be a doctor." },
    { word: "war", syllables: ["war"], phonetic: "/wɔːr/", meaning: "n. 战争", example: "Nobody likes war." },
    { word: "warm", syllables: ["warm"], phonetic: "/wɔːrm/", meaning: "adj. 温暖的", example: "The weather is warm today." },
    { word: "warn", syllables: ["warn"], phonetic: "/wɔːrn/", meaning: "v. 警告", example: "I warned him not to go." },
    { word: "wash", syllables: ["wash"], phonetic: "/wɒʃ/", meaning: "v. 洗", example: "Wash your hands before eating." }
  ],
  "第32组": [
    { word: "waste", syllables: ["waste"], phonetic: "/weɪst/", meaning: "v./n. 浪费", example: "Don't waste water." },
    { word: "watch", syllables: ["watch"], phonetic: "/wɒtʃ/", meaning: "v. 观看；n. 手表", example: "I watch TV every evening." },
    { word: "water", syllables: ["wa","ter"], phonetic: "/ˈwɔːtər/", meaning: "n. 水", example: "Drink more water." },
    { word: "watermelon", syllables: ["wa","ter","mel","on"], phonetic: "/ˈwɔːtərmelən/", meaning: "n. 西瓜", example: "I like watermelon." },
    { word: "wave", syllables: ["wave"], phonetic: "/weɪv/", meaning: "n. 波浪；v. 挥手", example: "She waved goodbye." },
    { word: "way", syllables: ["way"], phonetic: "/weɪ/", meaning: "n. 方式；路", example: "Which way should we go?" },
    { word: "we", syllables: ["we"], phonetic: "/wiː/", meaning: "pron. 我们", example: "We are friends." },
    { word: "weak", syllables: ["weak"], phonetic: "/wiːk/", meaning: "adj. 弱的", example: "He is weak after the illness." },
    { word: "wealth", syllables: ["wealth"], phonetic: "/welθ/", meaning: "n. 财富", example: "Health is more important than wealth." },
    { word: "wear", syllables: ["wear"], phonetic: "/wer/", meaning: "v. 穿", example: "She is wearing a red dress." },
    { word: "weather", syllables: ["weath","er"], phonetic: "/ˈweðər/", meaning: "n. 天气", example: "The weather is nice today." },
    { word: "website", syllables: ["web","site"], phonetic: "/ˈwebsaɪt/", meaning: "n. 网站", example: "Visit our website." },
    { word: "Wednesday", syllables: ["Wednes","day"], phonetic: "/ˈwenzdeɪ/", meaning: "n. 星期三", example: "I have English on Wednesday." },
    { word: "week", syllables: ["week"], phonetic: "/wiːk/", meaning: "n. 星期", example: "There are seven days in a week." },
    { word: "weekday", syllables: ["week","day"], phonetic: "/ˈwiːkdeɪ/", meaning: "n. 工作日", example: "I'm busy on weekdays." },
    { word: "weekend", syllables: ["week","end"], phonetic: "/ˌwiːkˈend/", meaning: "n. 周末", example: "What do you do on weekends?" },
    { word: "weigh", syllables: ["weigh"], phonetic: "/weɪ/", meaning: "v. 称重量", example: "How much do you weigh?" },
    { word: "weight", syllables: ["weight"], phonetic: "/weɪt/", meaning: "n. 重量", example: "What's your weight?" },
    { word: "welcome", syllables: ["wel","come"], phonetic: "/ˈwelkəm/", meaning: "v./adj. 欢迎", example: "Welcome to our school." },
    { word: "well", syllables: ["well"], phonetic: "/wel/", meaning: "adv. 好；adj. 健康的", example: "She sings very well." },
    { word: "west", syllables: ["west"], phonetic: "/west/", meaning: "n./adj. 西方", example: "The sun sets in the west." },
    { word: "western", syllables: ["west","ern"], phonetic: "/ˈwestərn/", meaning: "adj. 西方的", example: "I like western music." },
    { word: "wet", syllables: ["wet"], phonetic: "/wet/", meaning: "adj. 湿的", example: "The ground is wet after rain." },
    { word: "what", syllables: ["what"], phonetic: "/wɒt/", meaning: "pron. 什么", example: "What is your name?" },
    { word: "wheat", syllables: ["wheat"], phonetic: "/wiːt/", meaning: "n. 小麦", example: "Bread is made from wheat." },
    { word: "wheel", syllables: ["wheel"], phonetic: "/wiːl/", meaning: "n. 轮子", example: "The car has four wheels." },
    { word: "when", syllables: ["when"], phonetic: "/wen/", meaning: "adv. 什么时候", example: "When is your birthday?" },
    { word: "whenever", syllables: ["when","ev","er"], phonetic: "/wenˈevər/", meaning: "conj. 无论何时", example: "Come whenever you like." },
    { word: "where", syllables: ["where"], phonetic: "/wer/", meaning: "adv. 在哪里", example: "Where do you live?" },
    { word: "whether", syllables: ["wheth","er"], phonetic: "/ˈweðər/", meaning: "conj. 是否", example: "I don't know whether he will come." },
    { word: "which", syllables: ["which"], phonetic: "/wɪtʃ/", meaning: "pron. 哪一个", example: "Which one do you like?" },
    { word: "while", syllables: ["while"], phonetic: "/waɪl/", meaning: "conj. 当…时候", example: "I read while he sleeps." },
    { word: "white", syllables: ["white"], phonetic: "/waɪt/", meaning: "adj. 白色的", example: "Snow is white." },
    { word: "who", syllables: ["who"], phonetic: "/huː/", meaning: "pron. 谁", example: "Who is that man?" },
    { word: "whole", syllables: ["whole"], phonetic: "/hoʊl/", meaning: "adj. 整个的", example: "The whole class was quiet." },
    { word: "whom", syllables: ["whom"], phonetic: "/huːm/", meaning: "pron. 谁（宾格）", example: "With whom did you go?" },
    { word: "whose", syllables: ["whose"], phonetic: "/huːz/", meaning: "pron. 谁的", example: "Whose bag is this?" },
    { word: "why", syllables: ["why"], phonetic: "/waɪ/", meaning: "adv. 为什么", example: "Why are you late?" },
    { word: "wide", syllables: ["wide"], phonetic: "/waɪd/", meaning: "adj. 宽的", example: "The road is very wide." },
    { word: "wife", syllables: ["wife"], phonetic: "/waɪf/", meaning: "n. 妻子", example: "His wife is a teacher." },
    { word: "wild", syllables: ["wild"], phonetic: "/waɪld/", meaning: "adj. 野生的", example: "Wild animals live in forests." },
    { word: "will", syllables: ["will"], phonetic: "/wɪl/", meaning: "v. 将要", example: "I will go tomorrow." },
    { word: "win", syllables: ["win"], phonetic: "/wɪn/", meaning: "v. 赢", example: "We won the game!" },
    { word: "wind", syllables: ["wind"], phonetic: "/wɪnd/", meaning: "n. 风", example: "The wind is blowing." },
    { word: "window", syllables: ["win","dow"], phonetic: "/ˈwɪndoʊ/", meaning: "n. 窗户", example: "Open the window, please." },
    { word: "wine", syllables: ["wine"], phonetic: "/waɪn/", meaning: "n. 葡萄酒", example: "He doesn't drink wine." },
    { word: "wing", syllables: ["wing"], phonetic: "/wɪŋ/", meaning: "n. 翅膀", example: "The bird spread its wings." },
    { word: "winner", syllables: ["win","ner"], phonetic: "/ˈwɪnər/", meaning: "n. 获胜者", example: "She is the winner." },
    { word: "winter", syllables: ["win","ter"], phonetic: "/ˈwɪntər/", meaning: "n. 冬天", example: "It snows in winter." }
  ],
  "第33组": [
    { word: "wise", syllables: ["wise"], phonetic: "/waɪz/", meaning: "adj. 明智的", example: "That's a wise decision." },
    { word: "wish", syllables: ["wish"], phonetic: "/wɪʃ/", meaning: "v./n. 希望", example: "I wish you good luck." },
    { word: "with", syllables: ["with"], phonetic: "/wɪð/", meaning: "prep. 和；用", example: "Come with me." },
    { word: "without", syllables: ["with","out"], phonetic: "/wɪˈðaʊt/", meaning: "prep. 没有", example: "I can't do it without you." },
    { word: "woman", syllables: ["wom","an"], phonetic: "/ˈwʊmən/", meaning: "n. 女人", example: "The woman is my aunt." },
    { word: "wonder", syllables: ["won","der"], phonetic: "/ˈwʌndər/", meaning: "v. 想知道", example: "I wonder where he is." },
    { word: "wonderful", syllables: ["won","der","ful"], phonetic: "/ˈwʌndərfl/", meaning: "adj. 精彩的", example: "We had a wonderful time." },
    { word: "wood", syllables: ["wood"], phonetic: "/wʊd/", meaning: "n. 木头", example: "The desk is made of wood." },
    { word: "word", syllables: ["word"], phonetic: "/wɜːrd/", meaning: "n. 单词；话语", example: "Look up the word in the dictionary." },
    { word: "work", syllables: ["work"], phonetic: "/wɜːrk/", meaning: "v./n. 工作", example: "I work hard every day." },
    { word: "worker", syllables: ["work","er"], phonetic: "/ˈwɜːrkər/", meaning: "n. 工人", example: "The workers are building a house." },
    { word: "world", syllables: ["world"], phonetic: "/wɜːrld/", meaning: "n. 世界", example: "China is a big country in the world." },
    { word: "worry", syllables: ["wor","ry"], phonetic: "/ˈwʌri/", meaning: "v. 担心", example: "Don't worry about it." },
    { word: "worth", syllables: ["worth"], phonetic: "/wɜːrθ/", meaning: "adj. 值得的", example: "The book is worth reading." },
    { word: "would", syllables: ["would"], phonetic: "/wʊd/", meaning: "v. 将；愿意", example: "Would you like some tea?" },
    { word: "wound", syllables: ["wound"], phonetic: "/wuːnd/", meaning: "n. 伤口", example: "The wound is healing." },
    { word: "write", syllables: ["write"], phonetic: "/raɪt/", meaning: "v. 写", example: "Please write your name." },
    { word: "wrong", syllables: ["wrong"], phonetic: "/rɒŋ/", meaning: "adj. 错误的", example: "What's wrong with you?" },
    { word: "yard", syllables: ["yard"], phonetic: "/jɑːrd/", meaning: "n. 院子", example: "The children play in the yard." },
    { word: "year", syllables: ["year"], phonetic: "/jɪr/", meaning: "n. 年", example: "I am twelve years old." },
    { word: "yellow", syllables: ["yel","low"], phonetic: "/ˈjeloʊ/", meaning: "adj. 黄色的", example: "Bananas are yellow." },
    { word: "yes", syllables: ["yes"], phonetic: "/jes/", meaning: "adv. 是的", example: "Yes, I can." },
    { word: "yesterday", syllables: ["yes","ter","day"], phonetic: "/ˈjestərdeɪ/", meaning: "n./adv. 昨天", example: "I went shopping yesterday." },
    { word: "yet", syllables: ["yet"], phonetic: "/jet/", meaning: "adv. 还；已经", example: "I haven't finished yet." },
    { word: "you", syllables: ["you"], phonetic: "/juː/", meaning: "pron. 你；你们", example: "You are my friend." },
    { word: "young", syllables: ["young"], phonetic: "/jʌŋ/", meaning: "adj. 年轻的", example: "She is very young." },
    { word: "your", syllables: ["your"], phonetic: "/jɔːr/", meaning: "pron. 你的", example: "Is this your bag?" },
    { word: "yours", syllables: ["yours"], phonetic: "/jɔːrz/", meaning: "pron. 你的（名词性）", example: "This pen is yours." },
    { word: "yourself", syllables: ["your","self"], phonetic: "/jɔːrˈself/", meaning: "pron. 你自己", example: "Did you do it yourself?" },
    { word: "youth", syllables: ["youth"], phonetic: "/juːθ/", meaning: "n. 青年", example: "The youth are the future." },
    { word: "zero", syllables: ["ze","ro"], phonetic: "/ˈzɪroʊ/", meaning: "num. 零", example: "The temperature is zero." },
    { word: "zoo", syllables: ["zoo"], phonetic: "/zuː/", meaning: "n. 动物园", example: "Let's go to the zoo." }
  ]
};