// 基本要求词汇 — 第三单元、第四单元
const WORDS_JBYQ = {
  "第三单元": [
    { word: "accountant", syllables: ["ac","coun","tant"], phonetic: "/əˈkaʊntənt/", meaning: "n. 会计人员", example: "My father is an accountant. He works in a big company." },
    { word: "admit", syllables: ["ad","mit"], phonetic: "/ədˈmɪt/", meaning: "v. 承认", example: "He finally admitted that he had made a mistake." },
    { word: "adopt", syllables: ["a","dopt"], phonetic: "/əˈdɒpt/", meaning: "v. 收养", example: "The couple decided to adopt an orphan." },
    { word: "agent", syllables: ["a","gent"], phonetic: "/ˈeɪdʒənt/", meaning: "n. 代办；代理人", example: "The agent helped me buy a house." },
    { word: "agriculture", syllables: ["ag","ri","cul","ture"], phonetic: "/ˈæɡrɪkʌltʃə(r)/", meaning: "n. 农业", example: "China is a country with a long history of agriculture." },
    { word: "album", syllables: ["al","bum"], phonetic: "/ˈælbəm/", meaning: "n. 相册；影集；唱片集", example: "She showed me her photo album." },
    { word: "ambulance", syllables: ["am","bu","lance"], phonetic: "/ˈæmbjələns/", meaning: "n. 救护车", example: "The ambulance rushed the injured to the hospital as quickly as possible." },
    { word: "architect", syllables: ["ar","chi","tect"], phonetic: "/ˈɑːkɪtekt/", meaning: "n. 建筑师", example: "My uncle is an architect. He designs many beautiful buildings." },
    { word: "author", syllables: ["au","thor"], phonetic: "/ˈɔːθə(r)/", meaning: "n. 作者", example: "The author of this book is very famous." },
    { word: "badly", syllables: ["bad","ly"], phonetic: "/ˈbædli/", meaning: "adv. 有害地；严重地；非常", example: "He was badly hurt in the accident." },
    { word: "bake", syllables: ["bake"], phonetic: "/beɪk/", meaning: "v. 烘；烤", example: "My mother is baking bread in the kitchen." },
    { word: "balcony", syllables: ["bal","co","ny"], phonetic: "/ˈbælkəni/", meaning: "n. 阳台", example: "There is a flower pot on the balcony." },
    { word: "barbecue", syllables: ["bar","be","cue"], phonetic: "/ˈbɑːbɪkjuː/", meaning: "n. 户外烧烤", example: "We had a barbecue in the park yesterday." },
    { word: "bay", syllables: ["bay"], phonetic: "/beɪ/", meaning: "n. （海或湖的）湾", example: "The ship is sailing in the bay." },
    { word: "beer", syllables: ["beer"], phonetic: "/bɪə(r)/", meaning: "n. 啤酒", example: "He likes to drink beer in summer." },
    { word: "bench", syllables: ["bench"], phonetic: "/bentʃ/", meaning: "n. 长凳", example: "There is an old man sitting on the bench." },
    { word: "blank", syllables: ["blank"], phonetic: "/blæŋk/", meaning: "n. 空白处 adj. 空白的；茫然的", example: "Please fill in the blank with the correct answer." },
    { word: "bone", syllables: ["bone"], phonetic: "/bəʊn/", meaning: "n. 骨头", example: "The dog is gnawing a bone." },
    { word: "boot", syllables: ["boot"], phonetic: "/buːt/", meaning: "n. 靴子", example: "He put on his boots and went out." },
    { word: "cage", syllables: ["cage"], phonetic: "/keɪdʒ/", meaning: "n. 笼子", example: "The little bird is in the cage, longing to fly freely in the sky." },
    { word: "canteen", syllables: ["can","teen"], phonetic: "/kænˈtiːn/", meaning: "n. 食堂；餐厅", example: "We have lunch in the school canteen." },
    { word: "castle", syllables: ["cas","tle"], phonetic: "/ˈkɑːsl/", meaning: "n. 城堡", example: "There is a beautiful castle on the hill." },
    { word: "chase", syllables: ["chase"], phonetic: "/tʃeɪs/", meaning: "v. 追逐", example: "The dog is chasing a cat." },
    { word: "chest", syllables: ["chest"], phonetic: "/tʃest/", meaning: "n. 胸", example: "He has a pain in his chest." },
    { word: "cigarette", syllables: ["cig","a","rette"], phonetic: "/ˌsɪɡəˈret/", meaning: "n. 香烟", example: "Smoking cigarettes is harmful to your health." },
    { word: "clap", syllables: ["clap"], phonetic: "/klæp/", meaning: "v. 拍（手）；鼓掌", example: "Everyone clapped their hands when the performance ended." },
    { word: "cocoa", syllables: ["co","coa"], phonetic: "/ˈkəʊkəʊ/", meaning: "n. 可可", example: "I like to drink cocoa in the morning." },
    { word: "complaint", syllables: ["com","plaint"], phonetic: "/kəmˈpleɪnt/", meaning: "n. 抱怨；埋怨", example: "She made a complaint about the noise." },
    { word: "composition", syllables: ["com","po","si","tion"], phonetic: "/ˌkɒmpəˈzɪʃn/", meaning: "n. 作文", example: "I have to write a composition for my English homework." },
    { word: "consumer", syllables: ["con","su","mer"], phonetic: "/kənˈsjuːmə(r)/", meaning: "n. 消费者", example: "Consumers should be aware of their rights." },
    { word: "continent", syllables: ["con","ti","nent"], phonetic: "/ˈkɒntɪnənt/", meaning: "n. 大陆；洲", example: "Asia is the largest continent in the world." },
    { word: "crop", syllables: ["crop"], phonetic: "/krɒp/", meaning: "n. 庄稼", example: "The farmers are harvesting the crops." },
    { word: "cruel", syllables: ["cru","el"], phonetic: "/ˈkruːəl/", meaning: "adj. 残忍的", example: "It is cruel to treat animals like that." },
    { word: "curtain", syllables: ["cur","tain"], phonetic: "/ˈkɜːtn/", meaning: "n. 窗帘", example: "The curtains in my room are very beautiful." },
    { word: "dairy", syllables: ["dai","ry"], phonetic: "/ˈdeəri/", meaning: "adj. 乳品的，奶制品的", example: "We should drink more dairy products to keep healthy." },
    { word: "department", syllables: ["de","part","ment"], phonetic: "/dɪˈpɑːtmənt/", meaning: "n. 部门", example: "I work in the sales department of the company." },
    { word: "desktop", syllables: ["desk","top"], phonetic: "/ˈdesktɒp/", meaning: "n. 台式计算机", example: "My father bought a new desktop for me." },
    { word: "dessert", syllables: ["des","sert"], phonetic: "/dɪˈzɜːt/", meaning: "n. 甜食", example: "I like to have some dessert after dinner." },
    { word: "dinosaur", syllables: ["di","no","saur"], phonetic: "/ˈdaɪnəsɔː(r)/", meaning: "n. 恐龙", example: "We can see many dinosaur fossils in the museum." },
    { word: "district", syllables: ["dis","trict"], phonetic: "/ˈdɪstrɪkt/", meaning: "n. （行政）区", example: "The Pudong New Area is the largest district in Shanghai." },
    { word: "dive", syllables: ["dive"], phonetic: "/daɪv/", meaning: "v. 跳水；潜水", example: "He likes to dive into the swimming pool." },
    { word: "drawer", syllables: ["draw","er"], phonetic: "/drɔː(r)/", meaning: "n. 抽屉", example: "There are some books in the drawer." },
    { word: "drum", syllables: ["drum"], phonetic: "/drʌm/", meaning: "v. 打鼓 n. 鼓", example: "He likes to drum on the table with his hands when he is thinking." },
    { word: "dusk", syllables: ["dusk"], phonetic: "/dʌsk/", meaning: "n. 黄昏", example: "We went for a walk at dusk." },
    { word: "Easter", syllables: ["Eas","ter"], phonetic: "/ˈiːstə(r)/", meaning: "n. 复活节", example: "We celebrate Easter every year." },
    { word: "editor", syllables: ["ed","i","tor"], phonetic: "/ˈedɪtə(r)/", meaning: "n. 编辑", example: "My sister is an editor in a publishing house." },
    { word: "equipment", syllables: ["e","quip","ment"], phonetic: "/ɪˈkwɪpmənt/", meaning: "n. 装备，设备", example: "The school has bought some new teaching equipment." },
    { word: "estate", syllables: ["es","tate"], phonetic: "/ɪˈsteɪt/", meaning: "n. 地产", example: "He inherited a large estate from his father." },
    { word: "exact", syllables: ["ex","act"], phonetic: "/ɪɡˈzækt/", meaning: "adj. 确切的", example: "Can you tell me the exact time of the meeting?" },
    { word: "feather", syllables: ["feath","er"], phonetic: "/ˈfeðə(r)/", meaning: "n. 羽毛", example: "The peacock's feathers are very beautiful and colourful." },
    { word: "flour", syllables: ["flour"], phonetic: "/ˈflaʊə(r)/", meaning: "n. 面粉", example: "My mother uses flour to make bread." },
    { word: "fry", syllables: ["fry"], phonetic: "/fraɪ/", meaning: "v. 油煎；油炸", example: "She is frying eggs for breakfast." },
    { word: "garage", syllables: ["ga","rage"], phonetic: "/ˈɡærɑːʒ/", meaning: "n. 车库", example: "We park our car in the garage." },
    { word: "garlic", syllables: ["gar","lic"], phonetic: "/ˈɡɑːlɪk/", meaning: "n. 大蒜，蒜头", example: "I don't like the smell of garlic." },
    { word: "golf", syllables: ["golf"], phonetic: "/ɡɒlf/", meaning: "n. 高尔夫球运动", example: "My father likes to play golf on weekends." },
    { word: "goose", syllables: ["goose"], phonetic: "/ɡuːs/", meaning: "n. 鹅（复 geese /ɡiːs/）", example: "There is a group of geese swimming in the pond." },
    { word: "greedy", syllables: ["greed","y"], phonetic: "/ˈɡriːdi/", meaning: "adj. 贪婪的", example: "The greedy boy ate all the cakes." },
    { word: "hammer", syllables: ["ham","mer"], phonetic: "/ˈhæmə(r)/", meaning: "n. 锤子", example: "He used a hammer to fix the table." },
    { word: "helmet", syllables: ["hel","met"], phonetic: "/ˈhelmɪt/", meaning: "n. 头盔；安全帽", example: "You should wear a helmet when you ride a bike." },
    { word: "horror", syllables: ["hor","ror"], phonetic: "/ˈhɒrə(r)/", meaning: "n. 恐惧；令人恐怖的事物", example: "She screamed in horror when she saw the snake." },
    { word: "indeed", syllables: ["in","deed"], phonetic: "/ɪnˈdiːd/", meaning: "adv. 确实；真正地", example: "He is indeed a good student." },
    { word: "India", syllables: ["In","dia"], phonetic: "/ˈɪndiə/", meaning: "n. 印度", example: "India is a country with a large population." },
    { word: "individual", syllables: ["in","di","vid","u","al"], phonetic: "/ˌɪndɪˈvɪdʒuəl/", meaning: "adj. 个人的；个别的 n. 个人", example: "Everyone has their own individual ideas." },
    { word: "jelly", syllables: ["jel","ly"], phonetic: "/ˈdʒeli/", meaning: "n. 果冻", example: "I like to eat jelly very much." },
    { word: "job", syllables: ["job"], phonetic: "/dʒɒb/", meaning: "n. 工作", example: "He has a good job in a big company." },
    { word: "kangaroo", syllables: ["kan","ga","roo"], phonetic: "/ˌkæŋɡəˈruː/", meaning: "n. 袋鼠（产于澳大利亚）", example: "Kangaroos are unique animals with strong hind legs and long tails." },
    { word: "kingdom", syllables: ["king","dom"], phonetic: "/ˈkɪŋdəm/", meaning: "n. 王国", example: "In the fairy tale, the princess lived in a beautiful kingdom." },
    { word: "lamb", syllables: ["lamb"], phonetic: "/læm/", meaning: "n. 羔羊；羊肉", example: "The little lamb is so cute." },
    { word: "laughter", syllables: ["laugh","ter"], phonetic: "/ˈlɑːftə(r)/", meaning: "n. 大笑；笑声", example: "There was a lot of laughter in the classroom." },
    { word: "lip", syllables: ["lip"], phonetic: "/lɪp/", meaning: "n. 嘴唇", example: "Her lips were dry because of the cold weather." },
    { word: "lorry", syllables: ["lor","ry"], phonetic: "/ˈlɒri/", meaning: "n. 卡车", example: "The lorry is carrying a lot of goods." },
    { word: "mask", syllables: ["mask"], phonetic: "/mɑːsk/", meaning: "n. 面具；口罩", example: "People wear masks to protect themselves from the smog." },
    { word: "mate", syllables: ["mate"], phonetic: "/meɪt/", meaning: "n. 伙伴", example: "He is my best mate at school." },
    { word: "melon", syllables: ["mel","on"], phonetic: "/ˈmelən/", meaning: "n. 瓜", example: "Watermelon is a kind of delicious melon." },
    { word: "missing", syllables: ["miss","ing"], phonetic: "/ˈmɪsɪŋ/", meaning: "adj. 失去的；下落不明的", example: "The missing boy was found in the park." },
    { word: "monster", syllables: ["mon","ster"], phonetic: "/ˈmɒnstə(r)/", meaning: "n. 怪物，怪兽", example: "Children are often afraid of monsters in the dark." },
    { word: "motor", syllables: ["mo","tor"], phonetic: "/ˈməʊtə(r)/", meaning: "n. 发动机，马达", example: "The motor of the car is not working well." },
    { word: "musician", syllables: ["mu","si","cian"], phonetic: "/mjuˈzɪʃn/", meaning: "n. 音乐家；作曲家", example: "Beethoven is one of the most famous musicians in the world." },
    { word: "neat", syllables: ["neat"], phonetic: "/niːt/", meaning: "adj. 整齐的", example: "Her room is always neat and tidy." },
    { word: "nursery", syllables: ["nurs","er","y"], phonetic: "/ˈnɜːsəri/", meaning: "n. 托儿所", example: "The children in the nursery are playing happily." },
    { word: "oneself", syllables: ["one","self"], phonetic: "/wʌnˈself/", meaning: "pron. 某人自己", example: "We should take care of ourselves." },
    { word: "opportunity", syllables: ["op","por","tu","ni","ty"], phonetic: "/ˌɒpəˈtjuːnəti/", meaning: "n. 机会", example: "We should seize every opportunity to learn." },
    { word: "oral", syllables: ["o","ral"], phonetic: "/ˈɔːrəl/", meaning: "adj. 口头的", example: "We had an oral test in English class yesterday." },
    { word: "pan", syllables: ["pan"], phonetic: "/pæn/", meaning: "n. 平底锅", example: "She is cooking eggs in a pan." },
    { word: "pants", syllables: ["pants"], phonetic: "/pænts/", meaning: "n. 裤子", example: "These pants are too short for me." },
    { word: "parcel", syllables: ["par","cel"], phonetic: "/ˈpɑːsl/", meaning: "n. 包裹；小包", example: "I received a parcel from my friend." },
    { word: "path", syllables: ["path"], phonetic: "/pɑːθ/", meaning: "n. 路，小路", example: "We walked along the path in the forest." },
    { word: "peach", syllables: ["peach"], phonetic: "/piːtʃ/", meaning: "n. 桃", example: "The peaches are sweet and juicy." },
    { word: "penny", syllables: ["pen","ny"], phonetic: "/ˈpeni/", meaning: "n. 便士（复 pence 或 pennies）", example: "It only cost a few pennies." },
    { word: "phrase", syllables: ["phrase"], phonetic: "/freɪz/", meaning: "n. 短语，词组", example: "We should learn some useful phrases in English." },
    { word: "pillow", syllables: ["pil","low"], phonetic: "/ˈpɪləʊ/", meaning: "n. 枕头", example: "I like soft pillow." },
    { word: "pond", syllables: ["pond"], phonetic: "/pɒnd/", meaning: "n. 池塘", example: "There are some fish in the pond." },
    { word: "professor", syllables: ["pro","fes","sor"], phonetic: "/prəˈfesə(r)/", meaning: "n. 教授", example: "The professor gave us an interesting lecture." },
    { word: "pupil", syllables: ["pu","pil"], phonetic: "/ˈpjuːpl/", meaning: "n. 学生；小学生", example: "The pupils are listening attentively to the teacher in class." },
    { word: "quarrel", syllables: ["quar","rel"], phonetic: "/ˈkwɒrəl/", meaning: "v. & n. 争吵，吵嘴", example: "They quarreled with each other about the small thing." },
    { word: "rail", syllables: ["rail"], phonetic: "/reɪl/", meaning: "n. 铁路，铁轨", example: "The train is running on the rails." },
    { word: "recite", syllables: ["re","cite"], phonetic: "/rɪˈsaɪt/", meaning: "v. 背，背诵", example: "We need to recite some English passages." },
    { word: "retire", syllables: ["re","tire"], phonetic: "/rɪˈtaɪə(r)/", meaning: "v. 退休；退役", example: "My grandfather will retire next year." },
    { word: "riddle", syllables: ["rid","dle"], phonetic: "/ˈrɪdl/", meaning: "n. 谜（语）", example: "Can you guess the riddle?" },
    { word: "rob", syllables: ["rob"], phonetic: "/rɒb/", meaning: "v. 抢夺；抢劫", example: "The thief tried to rob the old woman of her money." },
    { word: "roof", syllables: ["roof"], phonetic: "/ruːf/", meaning: "n. 屋顶；顶部（复 roofs）", example: "There is a cat on the roof." },
    { word: "rubber", syllables: ["rub","ber"], phonetic: "/ˈrʌbə(r)/", meaning: "n. 橡皮", example: "I lost my rubber. Can I borrow yours?" },
    { word: "sail", syllables: ["sail"], phonetic: "/seɪl/", meaning: "v. 航行", example: "They sail across the ocean every year." },
    { word: "sausage", syllables: ["sau","sage"], phonetic: "/ˈsɒsɪdʒ/", meaning: "n. 香肠", example: "I like to eat sausages for breakfast." },
    { word: "servant", syllables: ["ser","vant"], phonetic: "/ˈsɜːvənt/", meaning: "n. 仆人，佣人", example: "In the past, rich families often had many servants." },
    { word: "sex", syllables: ["sex"], phonetic: "/seks/", meaning: "n. 性别", example: "It doesn't matter what sex you are, everyone can succeed." },
    { word: "sharp", syllables: ["sharp"], phonetic: "/ʃɑːp/", meaning: "adj. 尖的；锋利的", example: "Be careful! The knife is very sharp." },
    { word: "skip", syllables: ["skip"], phonetic: "/skɪp/", meaning: "v. 跳绳", example: "The girls are skipping in the playground." },
    { word: "soap", syllables: ["soap"], phonetic: "/səʊp/", meaning: "n. 肥皂", example: "We should wash our hands with soap and water." },
    { word: "soccer", syllables: ["soc","cer"], phonetic: "/ˈsɒkə(r)/", meaning: "n. 足球", example: "He likes to play soccer with his friends on weekends." },
    { word: "solid", syllables: ["sol","id"], phonetic: "/ˈsɒlɪd/", meaning: "n. 固体 adj. 固体的；坚固的；结实的", example: "Ice is a solid, and water is a liquid." },
    { word: "sour", syllables: ["sour"], phonetic: "/ˈsaʊə(r)/", meaning: "adj. 酸的 v. 使变酸；使失望", example: "The lemon tastes sour." },
    { word: "spot", syllables: ["spot"], phonetic: "/spɒt/", meaning: "n. 点；斑点；污渍 v. 发现；注意到", example: "The leopard has black spots." },
    { word: "steel", syllables: ["steel"], phonetic: "/stiːl/", meaning: "n. 钢", example: "The building is made of steel." },
    { word: "stem", syllables: ["stem"], phonetic: "/stem/", meaning: "n. 茎；干", example: "The stem of the flower is very strong." },
    { word: "suburb", syllables: ["sub","urb"], phonetic: "/ˈsʌbɜːb/", meaning: "n. 市郊", example: "Many people live in the suburb and work in the city." },
    { word: "swing", syllables: ["swing"], phonetic: "/swɪŋ/", meaning: "n. 秋千", example: "The children are playing on the swing." },
    { word: "switch", syllables: ["switch"], phonetic: "/swɪtʃ/", meaning: "n. & v. 开关；转换", example: "Please turn on the light switch." },
    { word: "tense", syllables: ["tense"], phonetic: "/tens/", meaning: "n. 时态", example: "We have learned several tenses in English class." },
    { word: "thief", syllables: ["thief"], phonetic: "/θiːf/", meaning: "n. 小偷", example: "The thief was caught by the police last night." },
    { word: "toast", syllables: ["toast"], phonetic: "/təʊst/", meaning: "n. 烤面包（片）；吐司 v. 烤；烘；祝酒", example: "I like to have some butter on my toast." },
    { word: "toe", syllables: ["toe"], phonetic: "/təʊ/", meaning: "n. 脚趾", example: "I hurt my toe when I bumped into the table." },
    { word: "towel", syllables: ["tow","el"], phonetic: "/ˈtaʊəl/", meaning: "n. 毛巾", example: "Dry your hands with the towel." },
    { word: "triangle", syllables: ["tri","an","gle"], phonetic: "/ˈtraɪæŋɡl/", meaning: "n. 三角形", example: "The roof of the house is in the shape of a triangle." },
    { word: "van", syllables: ["van"], phonetic: "/væn/", meaning: "n. 小货车", example: "The delivery man drives a van to send packages." },
    { word: "waist", syllables: ["waist"], phonetic: "/weɪst/", meaning: "n. 腰；腰围", example: "She measures her waist to see if she has lost weight." },
    { word: "wire", syllables: ["wire"], phonetic: "/ˈwaɪə(r)/", meaning: "n. 电线 v. 给……安装电线；发电报", example: "Be careful! The wire is broken." },
    { word: "wool", syllables: ["wool"], phonetic: "/wʊl/", meaning: "n. 羊毛；羊毛制品", example: "This sweater is made of wool." },
    { word: "zebra", syllables: ["ze","bra"], phonetic: "/ˈziːbrə/", meaning: "n. 斑马", example: "We saw a group of zebras in the zoo." }
  ],
  "第四单元": [
    { word: "a few", syllables: ["a","few"], phonetic: "", meaning: "有些，几个（用于可数名词之前）", example: "There are a few apples on the table." },
    { word: "ankle", syllables: ["an","kle"], phonetic: "/ˈæŋkl/", meaning: "n. 踝；踝关节", example: "He hurt his ankle while playing football." },
    { word: "balanced", syllables: ["bal","anced"], phonetic: "/ˈbælənst/", meaning: "adj. 保持（或显示）平衡的", example: "A balanced diet is good for our health." },
    { word: "blog", syllables: ["blog"], phonetic: "/blɒɡ/", meaning: "n. 博客；网志（= weblog）", example: "He writes a blog about his travel experiences." },
    { word: "bravo", syllables: ["bra","vo"], phonetic: "/brɑːˈvəʊ/", meaning: "excl. 好哇！", example: "The audience shouted \"Bravo!\" after the performance." },
    { word: "calf", syllables: ["calf"], phonetic: "/kɑːf/", meaning: "n. 小牛；牛犊", example: "The calf is following its mother." },
    { word: "calligraphy", syllables: ["cal","lig","ra","phy"], phonetic: "/kəˈlɪɡrəfi/", meaning: "n. 书法", example: "She is good at calligraphy." },
    { word: "celebration", syllables: ["cel","e","bra","tion"], phonetic: "/ˌselɪˈbreɪʃn/", meaning: "n. 庆典；庆祝活动", example: "We had a big celebration for his birthday." },
    { word: "comment", syllables: ["com","ment"], phonetic: "/ˈkɒment/", meaning: "n. 议论；评论；解释 v. 表达意见", example: "His comments on the movie were very interesting." },
    { word: "court", syllables: ["court"], phonetic: "/kɔːt/", meaning: "n. 球场", example: "They are playing tennis on the court." },
    { word: "excuse me", syllables: ["ex","cuse","me"], phonetic: "", meaning: "对不起；劳驾", example: "Excuse me, can you tell me the way to the station?" },
    { word: "footprint", syllables: ["foot","print"], phonetic: "/ˈfʊtprɪnt/", meaning: "n. 脚印；足迹", example: "We found some strange footprints in the snow." },
    { word: "Frisbee", syllables: ["Fris","bee"], phonetic: "/ˈfrɪzbi/", meaning: "n. 飞盘", example: "They are playing Frisbee in the park." },
    { word: "gear", syllables: ["gear"], phonetic: "/ɡɪə(r)/", meaning: "n. 设备，用具，衣服", example: "He bought some new fishing gear." },
    { word: "goalkeeper", syllables: ["goal","keep","er"], phonetic: "/ˈɡəʊlkiːpə(r)/", meaning: "n. 守门员", example: "The goalkeeper made a great save." },
    { word: "goat", syllables: ["goat"], phonetic: "/ɡəʊt/", meaning: "n. 山羊", example: "The goat is eating grass." },
    { word: "grain", syllables: ["grain"], phonetic: "/ɡreɪn/", meaning: "n. 谷物；谷粒", example: "Farmers grow different kinds of grains." },
    { word: "herd", syllables: ["herd"], phonetic: "/hɜːd/", meaning: "v. 牧放（牲畜、兽群）", example: "The shepherd is herding the sheep." },
    { word: "high-speed", syllables: ["high","speed"], phonetic: "/haɪ ˈspiːd/", meaning: "adj. 高速的", example: "The high-speed train is very fast." },
    { word: "horseback", syllables: ["horse","back"], phonetic: "/ˈhɔːsbæk/", meaning: "n. 马背", example: "I love exploring the countryside on horseback during my travels." },
    { word: "How come?", syllables: ["How","come"], phonetic: "", meaning: "怎么回事？怎么发生的？", example: "You are late again. How come?" },
    { word: "ICT", syllables: ["ICT"], phonetic: "", meaning: "n. 信息通信技术（课程）", example: "We have an ICT class today." },
    { word: "ingredient", syllables: ["in","gre","di","ent"], phonetic: "/ɪnˈɡriːdiənt/", meaning: "n. 材料；成分", example: "Flour is a main ingredient in making bread." },
    { word: "jump for joy", syllables: ["jump","for","joy"], phonetic: "", meaning: "欢呼雀跃", example: "When she heard the good news, she jumped for joy." },
    { word: "keeper", syllables: ["keep","er"], phonetic: "/ˈkiːpə(r)/", meaning: "n. 饲养员", example: "The zoo keepers take good care of the animals." },
    { word: "living room", syllables: ["liv","ing","room"], phonetic: "/ˈlɪvɪŋ ruːm/", meaning: "n. 客厅；起居室（= sitting room）", example: "We usually watch TV in the living room." },
    { word: "one-way", syllables: ["one","way"], phonetic: "/ˌwʌn ˈweɪ/", meaning: "adj. 单程的", example: "This is a one-way street." },
    { word: "only child", syllables: ["on","ly","child"], phonetic: "", meaning: "独生子（或女）", example: "As an only child, he gets a lot of love from his parents." },
    { word: "peck", syllables: ["peck"], phonetic: "/pek/", meaning: "n. 啄", example: "The bird uses its peck to find food." },
    { word: "pigsty", syllables: ["pig","sty"], phonetic: "/ˈpɪɡstaɪ/", meaning: "n. 猪圈", example: "The pigs are in the pigsty." },
    { word: "recipe", syllables: ["re","ci","pe"], phonetic: "/ˈresəpi/", meaning: "n. 食谱；烹饪法", example: "She found a new recipe for making cakes." },
    { word: "relation", syllables: ["re","la","tion"], phonetic: "/rɪˈleɪʃn/", meaning: "n. 关系；联系", example: "The relation between the two countries is very important." },
    { word: "rock climbing", syllables: ["rock","climb","ing"], phonetic: "", meaning: "攀岩", example: "He likes rock climbing very much." },
    { word: "shh", syllables: ["shh"], phonetic: "/ʃ/", meaning: "excl. 嘘", example: "Shh, the baby is sleeping." },
    { word: "side dish", syllables: ["side","dish"], phonetic: "", meaning: "配菜", example: "The side dish tastes very good." },
    { word: "soy sauce", syllables: ["soy","sauce"], phonetic: "/ˈsɔɪ sɔːs/", meaning: "n. 酱油（= soya sauce）", example: "Add some soy sauce to the dish." },
    { word: "sports ground", syllables: ["sports","ground"], phonetic: "", meaning: "运动场；操场", example: "The students are playing on the sports ground." },
    { word: "super-excited", syllables: ["su","per","ex","cit","ed"], phonetic: "/ˌsuːpər ɪkˈsaɪtɪd/", meaning: "adj. 超级激动的；格外兴奋的", example: "She was super-excited when she got the prize." },
    { word: "tasty", syllables: ["tas","ty"], phonetic: "/ˈteɪsti/", meaning: "adj. 美味的；可口的", example: "The cake is very tasty." },
    { word: "teahouse", syllables: ["tea","house"], phonetic: "/ˈtiːhaʊs/", meaning: "n. 茶馆；茶室", example: "We often go to the teahouse to drink tea." },
    { word: "track", syllables: ["track"], phonetic: "/træk/", meaning: "n. 跑道", example: "The athletes are running on the track." },
    { word: "warm up", syllables: ["warm","up"], phonetic: "", meaning: "热身；准备活动", example: "You should warm up before doing exercise." },
    { word: "warm-up", syllables: ["warm","up"], phonetic: "/ˈwɔːm ʌp/", meaning: "n. 热身；准备活动", example: "Before the basketball game, the players did some warm-up exercises to prevent injuries." },
    { word: "warning", syllables: ["warn","ing"], phonetic: "/ˈwɔːnɪŋ/", meaning: "n. 警告；警示", example: "The sign is a warning of danger." },
    { word: "watch out", syllables: ["watch","out"], phonetic: "", meaning: "小心；留神；注意", example: "Watch out! There is a car coming." },
    { word: "Well done!", syllables: ["Well","done"], phonetic: "", meaning: "做得好！干得好！", example: "You finished the work so quickly. Well done!" },
    { word: "What's the matter?", syllables: ["What's","the","mat","ter"], phonetic: "", meaning: "怎么了？", example: "You look sad. What's the matter?" },
    { word: "announcement", syllables: ["an","nounce","ment"], phonetic: "/əˈnaʊnsmənt/", meaning: "n. 公告；通告", example: "The school made an announcement about the upcoming sports meeting." },
    { word: "beg your pardon", syllables: ["beg","your","par","don"], phonetic: "", meaning: "请原谅；请再说一遍", example: "Beg your pardon, could you repeat what you just said?" },
    { word: "break out", syllables: ["break","out"], phonetic: "", meaning: "突然开始；爆发", example: "A fire broke out in the old building last night." },
    { word: "broken", syllables: ["bro","ken"], phonetic: "/ˈbrəʊkən/", meaning: "adj. 破损的；伤残的", example: "Be careful of the broken glass on the ground." },
    { word: "bulb", syllables: ["bulb"], phonetic: "/bʌlb/", meaning: "n. 电灯泡", example: "The bulb in the ceiling light has burned out." },
    { word: "Celsius", syllables: ["Cel","sius"], phonetic: "/ˈselsiəs/", meaning: "adj. 摄氏的", example: "The temperature today is 25 degrees Celsius." },
    { word: "changer", syllables: ["chang","er"], phonetic: "/ˈtʃeɪndʒə(r)/", meaning: "n. 改变者；改进者", example: "He is a changer in our school, bringing new ideas and methods." },
    { word: "check out", syllables: ["check","out"], phonetic: "", meaning: "察看，观察", example: "Check out the new art exhibition at the museum." },
    { word: "cloth", syllables: ["cloth"], phonetic: "/klɒθ/", meaning: "n. 织物；布料", example: "This cloth feels very soft and comfortable." },
    { word: "coal", syllables: ["coal"], phonetic: "/kəʊl/", meaning: "n. 煤", example: "Coal is still an important energy source in some regions." },
    { word: "colourful", syllables: ["col","our","ful"], phonetic: "/ˈkʌləfl/", meaning: "adj. 颜色鲜艳的；五彩缤纷的", example: "The children drew a very colourful picture of a rainbow." },
    { word: "container", syllables: ["con","tain","er"], phonetic: "/kənˈteɪnə(r)/", meaning: "n. 容器", example: "Put the water into a plastic container." },
    { word: "curly", syllables: ["cur","ly"], phonetic: "/ˈkɜːli/", meaning: "adj. 卷曲状的", example: "She has long curly hair that makes her look very cute." },
    { word: "easy-going", syllables: ["ea","sy","go","ing"], phonetic: "/ˌiːzi ˈɡəʊɪŋ/", meaning: "adj. 随和的", example: "My new neighbour is very easy-going and we get along well." },
    { word: "environmental", syllables: ["en","vi","ron","men","tal"], phonetic: "/ɪnˌvaɪrənˈmentl/", meaning: "adj. 环境的", example: "We should take some environmental protection measures to save our planet." },
    { word: "escalator", syllables: ["es","ca","la","tor"], phonetic: "/ˈeskəleɪtə(r)/", meaning: "n. 自动扶梯", example: "Take the escalator to the second floor, and you can find the clothing store." },
    { word: "excite", syllables: ["ex","cite"], phonetic: "/ɪkˈsaɪt/", meaning: "v. 使激动；使兴奋", example: "The news of the school trip excited all the students." },
    { word: "extreme", syllables: ["ex","treme"], phonetic: "/ɪkˈstriːm/", meaning: "adj. 极度的；极大的", example: "We are facing extreme weather conditions, such as heavy snow and strong winds." },
    { word: "foggy", syllables: ["fog","gy"], phonetic: "/ˈfɒɡi/", meaning: "adj. 有雾的", example: "It was a foggy morning, and the visibility was very low." },
    { word: "gap", syllables: ["gap"], phonetic: "/ɡæp/", meaning: "n. 缺口；间隙", example: "There is a small gap between the two boards." },
    { word: "harvest", syllables: ["har","vest"], phonetic: "/ˈhɑːvɪst/", meaning: "n. 收获；收获季节", example: "The farmers are very happy with the good harvest this year." },
    { word: "heatwave", syllables: ["heat","wave"], phonetic: "/ˈhiːtweɪv/", meaning: "n. 酷热期；热浪", example: "The city was hit by a severe heatwave last summer." },
    { word: "herb", syllables: ["herb"], phonetic: "/hɜːb/", meaning: "n. 药草；香草", example: "Many herbs are used in cooking to add flavour." },
    { word: "hurrah", syllables: ["hur","rah"], phonetic: "/hʊˈrɑː/", meaning: "excl. 万岁；好哇", example: "Hurrah! We won the first prize in the competition!" },
    { word: "indoors", syllables: ["in","doors"], phonetic: "/ɪnˈdɔːz/", meaning: "adv. 在室内", example: "It's too cold outside, so we stay indoors and watch TV." },
    { word: "inexpensive", syllables: ["in","ex","pen","sive"], phonetic: "/ˌɪnɪkˈspensɪv/", meaning: "adj. 廉价的；不昂贵的", example: "You can buy some inexpensive souvenirs at this local market." },
    { word: "lean", syllables: ["lean"], phonetic: "/liːn/", meaning: "v. 倚靠；倾斜", example: "She leaned on her friend's shoulder when she felt sad." },
    { word: "low-energy", syllables: ["low","en","er","gy"], phonetic: "/ˌləʊ ˈenədʒi/", meaning: "adj. 低能耗的", example: "We should use more low-energy appliances to save resources." },
    { word: "lunar calendar", syllables: ["lu","nar","cal","en","dar"], phonetic: "", meaning: "农历", example: "According to the lunar calendar, the Spring Festival is the most important traditional festival in China." },
    { word: "mankind", syllables: ["man","kind"], phonetic: "/mænˈkaɪnd/", meaning: "n. 人类", example: "Mankind has made remarkable progress in science and technology." },
    { word: "midnight", syllables: ["mid","night"], phonetic: "/ˈmɪdnaɪt/", meaning: "n. 午夜", example: "I usually go to bed before midnight to keep a good schedule." },
    { word: "million", syllables: ["mil","lion"], phonetic: "/ˈmɪljən/", meaning: "num. 百万", example: "The company made a profit of three million dollars last year." },
    { word: "millions of", syllables: ["mil","lions","of"], phonetic: "", meaning: "数以百万计的；很多", example: "Millions of people travel abroad every year." },
    { word: "mostly", syllables: ["most","ly"], phonetic: "/ˈməʊstli/", meaning: "adv. 主要地；一般地；通常", example: "The students in this class are mostly from the local area." },
    { word: "musical", syllables: ["mu","si","cal"], phonetic: "/ˈmjuːzɪkl/", meaning: "adj. 音乐的 n. 音乐剧", example: "She has a great musical talent and can play several instruments." },
    { word: "nightingale", syllables: ["night","in","gale"], phonetic: "/ˈnaɪtɪŋɡeɪl/", meaning: "n. 夜莺", example: "The nightingale's song is very beautiful and can be heard in the forest at night." },
    { word: "noticeboard", syllables: ["no","tice","board"], phonetic: "/ˈnəʊtɪsbɔːd/", meaning: "n. 布告栏；告示板", example: "Check the noticeboard regularly, as there are always some important announcements." },
    { word: "nut", syllables: ["nut"], phonetic: "/nʌt/", meaning: "n. 坚果", example: "Nuts are a good source of protein and healthy fats." },
    { word: "pass on", syllables: ["pass","on"], phonetic: "", meaning: "传递；转交", example: "Please pass on this message to your parents when you get home." },
    { word: "pat", syllables: ["pat"], phonetic: "/pæt/", meaning: "v. 轻拍", example: "The mother patted her baby gently on the back to make him stop crying." },
    { word: "peacock", syllables: ["pea","cock"], phonetic: "/ˈpiːkɒk/", meaning: "n. 孔雀", example: "The peacock spread its colorful tail feathers to show off its beauty." },
    { word: "penicillin", syllables: ["pen","i","cil","lin"], phonetic: "/ˌpenɪˈsɪlɪn/", meaning: "n. 青霉素；盘尼西林", example: "Penicillin has saved countless lives since it was discovered." },
    { word: "personality", syllables: ["per","son","al","i","ty"], phonetic: "/ˌpɜːsəˈnæləti/", meaning: "n. 性格；个性", example: "Everyone has a unique personality, which makes them different from others." },
    { word: "power station", syllables: ["pow","er","sta","tion"], phonetic: "", meaning: "发电站；发电厂", example: "The power station provides electricity for the whole city." },
    { word: "regards", syllables: ["re","gards"], phonetic: "/rɪˈɡɑːdz/", meaning: "n. [复] 问候；致意", example: "Please give my regards to your parents when you see them." },
    { word: "reunion", syllables: ["re","un","ion"], phonetic: "/riːˈjuːniən/", meaning: "n. 重逢；团聚", example: "The family reunion during the Spring Festival is a very important event for Chinese people." },
    { word: "reusable", syllables: ["re","us","a","ble"], phonetic: "/ˌriːˈjuːzəbl/", meaning: "adj. 可重复使用的", example: "We should use more reusable bags instead of plastic bags to protect the environment." },
    { word: "runway", syllables: ["run","way"], phonetic: "/ˈrʌnweɪ/", meaning: "n. 飞机跑道", example: "The plane landed safely on the runway after a long flight." },
    { word: "saver", syllables: ["sav","er"], phonetic: "/ˈseɪvə(r)/", meaning: "n. 救助者；救星", example: "The firefighters are the savers in the fire, rescuing people from danger." },
    { word: "sort", syllables: ["sort"], phonetic: "/sɔːt/", meaning: "v. 整理；分类 n. 种类；类别", example: "You should sort your clothes by colour before putting them in the wardrobe." },
    { word: "spring roll", syllables: ["spring","roll"], phonetic: "", meaning: "n. 春卷", example: "Spring roll is a popular snack during the Chinese New Year." },
    { word: "storyteller", syllables: ["sto","ry","tel","ler"], phonetic: "/ˈstɔːritelə(r)/", meaning: "n. 讲故事的人", example: "The storyteller can always attract a lot of children with his interesting stories." },
    { word: "sunshine", syllables: ["sun","shine"], phonetic: "/ˈsʌnʃaɪn/", meaning: "n. 阳光；日光", example: "We sat in the garden, enjoying the warm sunshine." },
    { word: "swan", syllables: ["swan"], phonetic: "/swɒn/", meaning: "n. 天鹅", example: "You swan, he frog has become a popular internet catchphrase." },
    { word: "symphony", syllables: ["sym","pho","ny"], phonetic: "/ˈsɪmfəni/", meaning: "n. 交响乐；交响曲", example: "The symphony performed by the famous orchestra was really amazing." },
    { word: "take turns", syllables: ["take","turns"], phonetic: "", meaning: "轮流；依次", example: "We take turns to clean the classroom." },
    { word: "theory", syllables: ["the","o","ry"], phonetic: "/ˈθɪəri/", meaning: "n. 学说；理论", example: "Einstein's theory of relativity is one of the most important scientific theories in history." },
    { word: "Traditional Chinese Medicine", syllables: ["Tra","di","tion","al","Chi","nese","Med","i","cine"], phonetic: "", meaning: "n. 中医药（TCM）", example: "Traditional Chinese Medicine has a long history and unique treatment methods." },
    { word: "tragedy", syllables: ["trag","e","dy"], phonetic: "/ˈtrædʒədi/", meaning: "n. 悲剧；悲剧作品", example: "Hamlet is one of Shakespeare's most famous tragedies." },
    { word: "unique", syllables: ["u","nique"], phonetic: "/juˈniːk/", meaning: "adj. 唯一的；独一无二的", example: "Each person has a unique fingerprint, which can be used for identification." },
    { word: "alarm clock", syllables: ["alarm","clock"], phonetic: "", meaning: "n. 闹钟", example: "My alarm clock goes off at 6:00 every morning." },
    { word: "dabbawala", syllables: ["dab","ba","wa","la"], phonetic: "/dæbəˈwɑːlə/", meaning: "n. (印度)送饭盒人", example: "The dabbawala in India is very famous for their efficient lunch-delivery service." },
    { word: "health care", syllables: ["health","care"], phonetic: "", meaning: "n. 医疗（服务）", example: "The government is trying to improve the health care system." },
    { word: "heating", syllables: ["heat","ing"], phonetic: "/ˈhiːtɪŋ/", meaning: "n. 供暖；暖气设备", example: "The heating in our house doesn't work well." },
    { word: "keep track of", syllables: ["keep","track","of"], phonetic: "", meaning: "追踪", example: "We should keep track of our expenses." },
    { word: "mode", syllables: ["mode"], phonetic: "/məʊd/", meaning: "n. 模式；方式", example: "The new mode of transportation is very convenient." },
    { word: "speaker", syllables: ["speak","er"], phonetic: "/ˈspiːkə(r)/", meaning: "n. 扬声器；喇叭", example: "The sound from the speaker is too loud." },
    { word: "stranger", syllables: ["stran","ger"], phonetic: "/ˈstreɪndʒə(r)/", meaning: "n. 陌生人", example: "Don't talk to strangers." },
    { word: "text message", syllables: ["text","mes","sage"], phonetic: "", meaning: "n. (手机)短信", example: "I received a text message from my friend." },
    { word: "thermostat", syllables: ["ther","mo","stat"], phonetic: "/ˈθɜːməstæt/", meaning: "n. 温控器", example: "The thermostat in the room keeps the temperature at a comfortable level." },
    { word: "truly", syllables: ["tru","ly"], phonetic: "/ˈtruːli/", meaning: "adv. 确实地；真诚地", example: "I truly believe that he will succeed." },
    { word: "accidentally", syllables: ["ac","ci","den","tal","ly"], phonetic: "/ˌæksɪˈdentəli/", meaning: "adv. 意外地；偶然地", example: "I accidentally met my old friend on the street yesterday." },
    { word: "bait", syllables: ["bait"], phonetic: "/beɪt/", meaning: "n. 鱼饵；诱饵", example: "He put some worms on the hook as bait to catch fish." },
    { word: "bass", syllables: ["bass"], phonetic: "/beɪs/", meaning: "n. 鲈", example: "The bass in this lake are very big, and many fishermen come here to catch them." },
    { word: "cast", syllables: ["cast"], phonetic: "/kɑːst/", meaning: "v. 投(钓线)；掷(钓钩)", example: "He cast the line into the water, hoping for a big catch." },
    { word: "column", syllables: ["col","umn"], phonetic: "/ˈkɒləm/", meaning: "n. 专栏；栏目", example: "I always read the sports column in the newspaper every morning." },
    { word: "even though", syllables: ["e","ven","though"], phonetic: "", meaning: "尽管；虽然", example: "Even though it was raining heavily, he still went to school on time." },
    { word: "handsome", syllables: ["hand","some"], phonetic: "/ˈhændsəm/", meaning: "adj. 英俊的；悦目的", example: "The new building looks very handsome with its modern design." },
    { word: "hook", syllables: ["hook"], phonetic: "/hʊk/", meaning: "n. 钩；钓钩；鱼钩 v. 钩住；挂住", example: "He hung his coat on the hook by the door." },
    { word: "lifetime", syllables: ["life","time"], phonetic: "/ˈlaɪftaɪm/", meaning: "n. 一生；终身；有生之年", example: "She has been passionate about painting all her lifetime." },
    { word: "lower", syllables: ["low","er"], phonetic: "/ˈləʊə(r)/", meaning: "v. 把……放低；使……降低 adj. 下方的；较低的", example: "Please lower your voice. We are in the library." },
    { word: "spill", syllables: ["spill"], phonetic: "/spɪl/", meaning: "v. (使)洒出，溢出，溅出", example: "Be careful not to spill the coffee on the table." },
    { word: "unluckily", syllables: ["un","luck","i","ly"], phonetic: "/ʌnˈlʌkɪli/", meaning: "adv. 不幸地；遗憾地；倒霉地", example: "Unluckily, we arrived at the station just after the last train left." },
    { word: "animated", syllables: ["an","i","mat","ed"], phonetic: "/ˈænɪmeɪtɪd/", meaning: "adj. 动画的；有生气的", example: "The boy was bored with the animated movie because it was too slow." },
    { word: "animation", syllables: ["an","i","ma","tion"], phonetic: "/ˌænɪˈmeɪʃn/", meaning: "n. 动画片（制作）", example: "The animation of Ne Zha 2 is really wonderful." },
    { word: "artistic", syllables: ["ar","tis","tic"], phonetic: "/ɑːˈtɪstɪk/", meaning: "adj. 艺术的", example: "She has a very artistic taste." },
    { word: "attraction", syllables: ["at","trac","tion"], phonetic: "/əˈtrækʃn/", meaning: "n. 向往的地方", example: "The Great Wall is a major tourist attraction in China." },
    { word: "belief", syllables: ["be","lief"], phonetic: "/bɪˈliːf/", meaning: "n. 信念；相信", example: "His belief in hard work led to his success." },
    { word: "career", syllables: ["ca","reer"], phonetic: "/kəˈrɪə(r)/", meaning: "n. 职业；事业", example: "She has a successful career in business." },
    { word: "chant", syllables: ["chant"], phonetic: "/tʃɑːnt/", meaning: "v. 反复呼喊；反复唱", example: "The football fans chanted their team's name." },
    { word: "communication", syllables: ["com","mu","ni","ca","tion"], phonetic: "/kəˌmjuːnɪˈkeɪʃn/", meaning: "n. 交流；交际", example: "Good communication is very important in a relationship." },
    { word: "costume", syllables: ["cos","tume"], phonetic: "/ˈkɒstjuːm/", meaning: "n. 服装；演出服", example: "The actors wore beautiful costumes in the play." },
    { word: "countless", syllables: ["count","less"], phonetic: "/ˈkaʊntləs/", meaning: "adj. 无数的；数不尽的", example: "There are countless stars in the sky." },
    { word: "cruise", syllables: ["cruise"], phonetic: "/kruːz/", meaning: "n. 航行；乘船游览", example: "They went on a cruise in the Mediterranean." },
    { word: "designer", syllables: ["de","sign","er"], phonetic: "/dɪˈzaɪnə(r)/", meaning: "n. 设计师", example: "She is a well-known fashion designer." },
    { word: "deskmate", syllables: ["desk","mate"], phonetic: "/ˈdeskmət/", meaning: "n. 同桌", example: "My deskmate is very helpful." },
    { word: "device", syllables: ["de","vice"], phonetic: "/dɪˈvaɪs/", meaning: "n. 仪器", example: "This is a new device for measuring temperature." },
    { word: "disappointment", syllables: ["dis","ap","point","ment"], phonetic: "/ˌdɪsəˈpɔɪntmənt/", meaning: "n. 失望", example: "To my disappointment, I didn't pass the exam." },
    { word: "element", syllables: ["el","e","ment"], phonetic: "/ˈelɪmənt/", meaning: "n. 要素", example: "Honesty is an important element in a friendship." },
    { word: "enter for", syllables: ["en","ter","for"], phonetic: "", meaning: "报名参加", example: "I decided to enter for the singing competition." },
    { word: "entertain", syllables: ["en","ter","tain"], phonetic: "/ˌentəˈteɪn/", meaning: "v. 使快乐；娱乐", example: "The clown entertained the children with funny tricks." },
    { word: "excitedly", syllables: ["ex","cit","ed","ly"], phonetic: "/ɪkˈsaɪtɪdli/", meaning: "adv. 兴奋地", example: "The children ran out of the classroom excitedly." },
    { word: "firmly", syllables: ["firm","ly"], phonetic: "/ˈfɜːmli/", meaning: "adv. 坚定地；牢固地", example: "He held the rope firmly." },
    { word: "flow", syllables: ["flow"], phonetic: "/fləʊ/", meaning: "v. 流；流动", example: "The river flows through the city." },
    { word: "glow", syllables: ["glow"], phonetic: "/ɡləʊ/", meaning: "v. 发光", example: "The fireflies glow in the dark." },
    { word: "guidance", syllables: ["gui","dance"], phonetic: "/ˈɡaɪdns/", meaning: "n. 指导；引导", example: "The teacher's guidance helped me a lot." },
    { word: "hairdresser", syllables: ["hair","dress","er"], phonetic: "/ˈheədresə(r)/", meaning: "n. 理发师", example: "I have an appointment with my hairdresser tomorrow for a haircut." },
    { word: "handle", syllables: ["han","dle"], phonetic: "/ˈhændl/", meaning: "n. 把手", example: "The handle of the cup is broken." },
    { word: "have...in common", syllables: ["have","in","com","mon"], phonetic: "", meaning: "有相同的特征", example: "We have a lot in common, such as our hobbies." },
    { word: "holder", syllables: ["hold","er"], phonetic: "/ˈhəʊldə(r)/", meaning: "n. 支托（或握持）……之物", example: "This is a pen holder." },
    { word: "hopefully", syllables: ["hope","ful","ly"], phonetic: "/ˈhəʊpfəli/", meaning: "adv. 有希望地", example: "Hopefully, we can finish the work on time." },
    { word: "imagination", syllables: ["i","mag","i","na","tion"], phonetic: "/ɪˌmædʒɪˈneɪʃn/", meaning: "n. 想象；想象力", example: "Children usually have a rich imagination." },
    { word: "impolite", syllables: ["im","po","lite"], phonetic: "/ˌɪmpəˈlaɪt/", meaning: "adj. 不礼貌的", example: "It's impolite to interrupt others when they are talking." },
    { word: "incorrect", syllables: ["in","cor","rect"], phonetic: "/ˌɪnkəˈrekt/", meaning: "adj. 不准确的", example: "Your answer is incorrect." },
    { word: "layer", syllables: ["lay","er"], phonetic: "/ˈleɪə(r)/", meaning: "n. 层；层次", example: "There are several layers of clouds in the sky." },
    { word: "leading", syllables: ["lead","ing"], phonetic: "/ˈliːdɪŋ/", meaning: "adj. 最重要的", example: "He is one of the leading scientists in this field." },
    { word: "lifeblood", syllables: ["life","blood"], phonetic: "/ˈlaɪfblʌd/", meaning: "n. 生命线", example: "Tourism is the lifeblood of this small town." },
    { word: "make-up", syllables: ["make","up"], phonetic: "/ˈmeɪkʌp/", meaning: "n. 化妆品", example: "She spends a lot of time on her make-up." },
    { word: "mascot", syllables: ["mas","cot"], phonetic: "/ˈmæskət/", meaning: "n. 吉祥物", example: "Bing Dwen Dwen is the mascot of the Beijing 2022 Winter Olympics." },
    { word: "meaningful", syllables: ["mean","ing","ful"], phonetic: "/ˈmiːnɪŋfl/", meaning: "adj. 有意义的", example: "This is a meaningful activity." },
    { word: "nurture", syllables: ["nur","ture"], phonetic: "/ˈnɜːtʃə(r)/", meaning: "v. 养育", example: "Parents should nurture their children's interests." },
    { word: "paper cutting", syllables: ["pa","per","cut","ting"], phonetic: "", meaning: "n. 剪纸", example: "Paper cutting is a traditional Chinese art." },
    { word: "photographer", syllables: ["pho","tog","ra","pher"], phonetic: "/fəˈtɒɡrəfə(r)/", meaning: "n. 摄影师", example: "He is a professional photographer." },
    { word: "plot", syllables: ["plot"], phonetic: "/plɒt/", meaning: "n. 故事情节", example: "The fifth book he wrote is my favourite because it has the most exciting plot." },
    { word: "port", syllables: ["port"], phonetic: "/pɔːt/", meaning: "n. 港口", example: "This is a busy port." },
    { word: "poster", syllables: ["post","er"], phonetic: "/ˈpəʊstə(r)/", meaning: "n. 海报", example: "There are many posters on the wall." },
    { word: "practical", syllables: ["prac","ti","cal"], phonetic: "/ˈpræktɪkl/", meaning: "adj. 实际的", example: "This is a very practical tool." },
    { word: "preparation", syllables: ["prep","a","ra","tion"], phonetic: "/ˌprepəˈreɪʃn/", meaning: "n. 准备", example: "We are making preparations for the party." },
    { word: "printing", syllables: ["print","ing"], phonetic: "/ˈprɪntɪŋ/", meaning: "n. 印刷；打印", example: "The printing of this book is very good." },
    { word: "readiness", syllables: ["read","i","ness"], phonetic: "/ˈredinəs/", meaning: "n. 乐意", example: "He showed great readiness to help others." },
    { word: "renewable", syllables: ["re","new","a","ble"], phonetic: "/rɪˈnjuːəbl/", meaning: "adj. 可再生的", example: "Solar energy is a renewable resource." },
    { word: "respond", syllables: ["re","spond"], phonetic: "/rɪˈspɒnd/", meaning: "v. 作出反应；回应", example: "He didn't respond to my question." },
    { word: "riverside", syllables: ["riv","er","side"], phonetic: "/ˈrɪvəsaɪd/", meaning: "n. 河畔；河岸", example: "We had a picnic by the riverside." },
    { word: "scene", syllables: ["scene"], phonetic: "/siːn/", meaning: "n. 现场；场景", example: "The police arrived at the scene of the accident." },
    { word: "sink", syllables: ["sink"], phonetic: "/sɪŋk/", meaning: "v. 下沉，沉没", example: "The ship began to sink." },
    { word: "solar cell", syllables: ["so","lar","cell"], phonetic: "/ˈsəʊlə sel/", meaning: "n. 太阳能电池", example: "Solar cells can convert sunlight into electricity." },
    { word: "solar panel", syllables: ["so","lar","pan","el"], phonetic: "/ˈsəʊlə ˌpænl/", meaning: "n. 太阳能电池板", example: "The house is equipped with solar panels." },
    { word: "special effects", syllables: ["spe","cial","ef","fects"], phonetic: "", meaning: "n. （电影或电视节目的）特技效果", example: "The new cartoon is full of amazing special effects that make it fun to watch." },
    { word: "spider", syllables: ["spi","der"], phonetic: "/ˈspaɪdə(r)/", meaning: "n. 蜘蛛", example: "I saw a spider on the wall." },
    { word: "sticker", syllables: ["stick","er"], phonetic: "/ˈstɪkə(r)/", meaning: "n. 贴纸", example: "The children like to collect stickers." },
    { word: "subtitle", syllables: ["sub","ti","tle"], phonetic: "/ˈsʌbtaɪtl/", meaning: "n. 字幕", example: "I usually watch English movies with Chinese subtitles." },
    { word: "tailor", syllables: ["tai","lor"], phonetic: "/ˈteɪlə(r)/", meaning: "n. 裁缝", example: "The tailor made a beautiful dress for her." },
    { word: "trainer", syllables: ["train","er"], phonetic: "/ˈtreɪnə(r)/", meaning: "n. 教练", example: "The trainer is teaching the athletes some new skills." },
    { word: "troublesome", syllables: ["trou","ble","some"], phonetic: "/ˈtrʌblsəm/", meaning: "adj. 令人烦恼的", example: "This problem is really troublesome. We need to find a way to solve it." },
    { word: "waterfall", syllables: ["wa","ter","fall"], phonetic: "/ˈwɔːtəfɔːl/", meaning: "n. 瀑布", example: "The waterfall looks so magnificent." },
    { word: "windsurf", syllables: ["wind","surf"], phonetic: "/ˈwɪndsɜːf/", meaning: "v. 做帆板运动", example: "He loves to windsurf on the sea during the holidays." },
    { word: "woods", syllables: ["woods"], phonetic: "/wʊdz/", meaning: "n. 树林", example: "We went for a walk in the woods." },
    { word: "wrestle", syllables: ["wres","tle"], phonetic: "/ˈresl/", meaning: "v. 摔跤", example: "The two men were wrestling on the mat." },
    { word: "accent", syllables: ["ac","cent"], phonetic: "/ˈæksent/", meaning: "n. 口音", example: "She has a strong southern accent, which makes her words sound very charming." },
    { word: "analyse", syllables: ["an","a","lyse"], phonetic: "/ˈænəlaɪz/", meaning: "v. 分析", example: "We need to carefully analyse the problem before we find a solution." },
    { word: "application", syllables: ["ap","pli","ca","tion"], phonetic: "/ˌæplɪˈkeɪʃn/", meaning: "n. 申请；请求", example: "I submitted my application for the scholarship last week." },
    { word: "as usual", syllables: ["as","u","su","al"], phonetic: "", meaning: "像往常一样；照例", example: "As usual, he gets up early and goes for a run in the park." },
    { word: "best-known", syllables: ["best","known"], phonetic: "/ˌbest ˈnəʊn/", meaning: "adj. 最知名的", example: "This is one of the best-known museums in the world." },
    { word: "booklet", syllables: ["book","let"], phonetic: "/ˈbʊklət/", meaning: "n. 小册子", example: "The tourist office provides a free booklet about the local attractions." },
    { word: "branch", syllables: ["branch"], phonetic: "/brɑːntʃ/", meaning: "n. 树枝", example: "Some volunteers have removed the broken branches from the road already." },
    { word: "calmly", syllables: ["calm","ly"], phonetic: "/ˈkɑːmli/", meaning: "adv. 沉着地", example: "He calmly faced the challenging situation." },
    { word: "chart", syllables: ["chart"], phonetic: "/tʃɑːt/", meaning: "n. 图表，曲线图", example: "The chart shows the changes in the company's sales over the past year." },
    { word: "check out", syllables: ["check","out"], phonetic: "", meaning: "借阅；借出；查看；结账离开；核实", example: "You can check out three books at a time from the library." },
    { word: "cheer for", syllables: ["cheer","for"], phonetic: "", meaning: "鼓励；支持", example: "All the students cheered for their classmates in the sports meeting." },
    { word: "chorus", syllables: ["cho","rus"], phonetic: "/ˈkɔːrəs/", meaning: "n. 合唱团；歌唱队", example: "The chorus sang a beautiful song at the concert." },
    { word: "classical", syllables: ["clas","si","cal"], phonetic: "/ˈklæsɪkl/", meaning: "adj. 古典的；经典的", example: "Mozart's music is a typical example of classical music." },
    { word: "clothing", syllables: ["cloth","ing"], phonetic: "/ˈkləʊðɪŋ/", meaning: "n. 衣服；服装", example: "We need to donate some warm clothing to the poor in winter." },
    { word: "contain", syllables: ["con","tain"], phonetic: "/kənˈteɪn/", meaning: "v. 包含；含有；容纳", example: "This box contains all my old books." },
    { word: "coverage", syllables: ["cov","er","age"], phonetic: "/ˈkʌvərɪdʒ/", meaning: "n. 覆盖范围", example: "The coverage of this wireless network is very wide, reaching most areas of the city." },
    { word: "cultural", syllables: ["cul","tur","al"], phonetic: "/ˈkʌltʃərəl/", meaning: "adj. 文化的；与文化有关的", example: "We should respect different cultural traditions when traveling abroad." },
    { word: "display", syllables: ["dis","play"], phonetic: "/dɪˈspleɪ/", meaning: "n. 陈列；展示 v. 陈列；展示；表现", example: "The museum has a special display of ancient artifacts." },
    { word: "earn", syllables: ["earn"], phonetic: "/ɜːn/", meaning: "v. 挣；赚得；赚钱", example: "He works hard to earn enough money to support his family." },
    { word: "elderly", syllables: ["el","der","ly"], phonetic: "/ˈeldəli/", meaning: "adj. 上了年纪的", example: "We should take good care of the elderly in our society." },
    { word: "embarrassment", syllables: ["em","bar","rass","ment"], phonetic: "/ɪmˈbærəsmənt/", meaning: "n. 尴尬", example: "He felt a great sense of embarrassment when he forgot his lines on stage." },
    { word: "emoji", syllables: ["emo","ji"], phonetic: "/ɪˈməʊdʒi/", meaning: "n. 表情符号", example: "People often use emojis to express their emotions in online communication." },
    { word: "factory-farmed", syllables: ["fac","to","ry","farmed"], phonetic: "/ˈfæktri fɑːmd/", meaning: "adj. 工厂化养殖的", example: "Factory-farmed chickens are more common in the market these days." },
    { word: "fault", syllables: ["fault"], phonetic: "/fɔːlt/", meaning: "n. 责任；过错", example: "It's not my fault that the plan failed." },
    { word: "fellow", syllables: ["fel","low"], phonetic: "/ˈfeləʊ/", meaning: "adj. 同类的；同伴的 n. 家伙；同伴；同事", example: "We are fellow students, so we should help each other." },
    { word: "flyer", syllables: ["fly","er"], phonetic: "/ˈflaɪə(r)/", meaning: "n. 小(广告)传单", example: "I received a flyer about a new restaurant opening nearby." },
    { word: "freshwater", syllables: ["fresh","wa","ter"], phonetic: "/ˈfreʃwɔːtə(r)/", meaning: "adj. 淡水的", example: "Freshwater fish live in rivers, lakes and ponds." },
    { word: "gesture", syllables: ["ges","ture"], phonetic: "/ˈdʒestʃə(r)/", meaning: "n. 手势；姿势 v. 做手势；用动作示意", example: "He made a gesture of welcome when he saw his friend." },
    { word: "giant", syllables: ["gi","ant"], phonetic: "/ˈdʒaɪənt/", meaning: "adj. 巨大的 n. 巨人；巨兽；大公司", example: "The giant pumpkin at the fall festival weighed over 500 pounds, breaking the previous record." },
    { word: "grateful", syllables: ["grate","ful"], phonetic: "/ˈɡreɪtfl/", meaning: "adj. 感激的；表示感谢的", example: "I'm very grateful to my teacher for her help." },
    { word: "habitat", syllables: ["hab","i","tat"], phonetic: "/ˈhæbɪtæt/", meaning: "n. (动植物的)生活环境，栖息地", example: "The destruction of the forest has greatly affected the habitat of wild animals." },
    { word: "humid", syllables: ["hu","mid"], phonetic: "/ˈhjuːmɪd/", meaning: "adj. 温暖潮湿的", example: "The weather in the south is often humid, especially in summer." },
    { word: "impress", syllables: ["im","press"], phonetic: "/ɪmˈpres/", meaning: "v. 给……留下深刻的好印象", example: "The performance of the young singer impressed the audience deeply." },
    { word: "in person", syllables: ["in","per","son"], phonetic: "", meaning: "亲自；当面", example: "You should go to the office and talk to the manager in person." },
    { word: "jasmine", syllables: ["jas","mine"], phonetic: "/ˈdʒæzmɪn/", meaning: "n. 茉莉", example: "The jasmine in the garden is in full bloom, filling the air with a sweet fragrance." },
    { word: "lead to", syllables: ["lead","to"], phonetic: "", meaning: "导致", example: "Eating too much junk food can lead to health problems." },
    { word: "leaflet", syllables: ["leaf","let"], phonetic: "/ˈliːflət/", meaning: "n. 散页印刷品；传单", example: "The act of distributing leaflets for advertising is outdated." },
    { word: "look through", syllables: ["look","through"], phonetic: "", meaning: "浏览；查看", example: "I like to look through magazines during my break." },
    { word: "lyrics", syllables: ["lyr","ics"], phonetic: "/ˈlɪrɪks/", meaning: "n. (复)歌词", example: "I love the lyrics of this song. They are so meaningful." },
    { word: "melody", syllables: ["mel","o","dy"], phonetic: "/ˈmelədi/", meaning: "n. 旋律；曲调", example: "The melody of this piece of music is very catchy." },
    { word: "melt", syllables: ["melt"], phonetic: "/melt/", meaning: "v. (使)熔化，融化", example: "The ice will melt when the temperature rises." },
    { word: "misunderstand", syllables: ["mis","un","der","stand"], phonetic: "/ˌmɪsʌndəˈstænd/", meaning: "v. 误解；误会", example: "Don't misunderstand me. I didn't mean to hurt your feelings." },
    { word: "nest", syllables: ["nest"], phonetic: "/nest/", meaning: "n. 巢穴；窝", example: "The birds are building a nest in the tree." },
    { word: "not only...but also...", syllables: ["not","on","ly","but","al","so"], phonetic: "", meaning: "不仅……而且……", example: "The toy models at the store are not only for children but also for adults." },
    { word: "operator", syllables: ["op","er","a","tor"], phonetic: "/ˈɒpəreɪtə(r)/", meaning: "n. 电话员；接线员", example: "I called the operator to ask for help." },
    { word: "palm", syllables: ["palm"], phonetic: "/pɑːm/", meaning: "n. 手掌；手心", example: "He held the coin in the palm of his hand." },
    { word: "playlist", syllables: ["play","list"], phonetic: "/ˈpleɪlɪst/", meaning: "n. 音乐播放清单", example: "I created a new playlist with all my favourite songs." },
    { word: "pop", syllables: ["pop"], phonetic: "/pɒp/", meaning: "n. 流行音乐 adj. 流行的；通俗的 v. 突然出现", example: "Pop is very popular among young people." },
    { word: "popularity", syllables: ["pop","u","lar","i","ty"], phonetic: "/ˌpɒpjuˈlærəti/", meaning: "n. 流行", example: "The popularity of smartphones has changed our way of life." },
    { word: "preference", syllables: ["pref","er","ence"], phonetic: "/ˈprefrəns/", meaning: "n. 偏爱；偏好", example: "I have a preference for classical music rather than pop music." },
    { word: "protection", syllables: ["pro","tec","tion"], phonetic: "/prəˈtekʃn/", meaning: "n. 保护", example: "We should take measures for the protection of wild animals." },
    { word: "ranger", syllables: ["rang","er"], phonetic: "/ˈreɪndʒə(r)/", meaning: "n. 护林人", example: "The ranger is responsible for protecting the forest from illegal logging." },
    { word: "recommendation", syllables: ["rec","om","men","da","tion"], phonetic: "/ˌrekəmenˈdeɪʃn/", meaning: "n. 正式建议；提议", example: "On the ninth page of the guide, you'll find recommendations for best restaurants." },
    { word: "request", syllables: ["re","quest"], phonetic: "/rɪˈkwest/", meaning: "n. & v. 要求；请求", example: "I received a request from my boss to finish the report by tomorrow." },
    { word: "rhythm", syllables: ["rhy","thm"], phonetic: "/ˈrɪðəm/", meaning: "n. 节奏；韵律", example: "The rhythm of this dance music is very strong." },
    { word: "second-hand", syllables: ["sec","ond","hand"], phonetic: "/ˌsekənd ˈhænd/", meaning: "adj. 二手的；旧的", example: "I bought a second-hand bike, which is much cheaper than a new one." },
    { word: "smoothly", syllables: ["smooth","ly"], phonetic: "/ˈsmuːðli/", meaning: "adv. 连续而流畅地", example: "The presentation went smoothly, and everyone was satisfied." },
    { word: "social media", syllables: ["so","cial","me","di","a"], phonetic: "", meaning: "n. 社交媒体", example: "Social media helps us get news, but it may also include false information." },
    { word: "solo", syllables: ["so","lo"], phonetic: "/ˈsəʊləʊ/", meaning: "adv. 单独地 n. 独唱；独奏", example: "She performed the dance solo, attracting everyone's attention." },
    { word: "stutter", syllables: ["stut","ter"], phonetic: "/ˈstʌtə(r)/", meaning: "n. & v. 口吃；结巴", example: "He has a stutter, so he is a little shy to speak in public." },
    { word: "suitable", syllables: ["suit","a","ble"], phonetic: "/ˈsuːtəbl/", meaning: "adj. 合适的；适宜的", example: "This book is suitable for children aged 8–12." },
    { word: "sweat", syllables: ["sweat"], phonetic: "/swet/", meaning: "n. 汗 v. 出汗；渗汗", example: "He wiped the sweat from his forehead after running." },
    { word: "theme", syllables: ["theme"], phonetic: "/θiːm/", meaning: "n. (乐曲的)主题，主旋律", example: "The theme of this symphony is about love and hope." },
    { word: "treetop", syllables: ["tree","top"], phonetic: "/ˈtriːtɒp/", meaning: "n. 树梢", example: "The bird is singing happily on the treetop." },
    { word: "trumpet", syllables: ["trum","pet"], phonetic: "/ˈtrʌmpɪt/", meaning: "n. 小号；喇叭", example: "The sound of the trumpet filled the concert hall." },
    { word: "trunk", syllables: ["trunk"], phonetic: "/trʌŋk/", meaning: "n. 象鼻", example: "The elephant used its trunk to pick up the log." },
    { word: "unknown", syllables: ["un","known"], phonetic: "/ʌnˈnəʊn/", meaning: "adj. 不出名的；无名的 n. 未知的事物", example: "He was an unknown writer before his first novel was published." },
    { word: "update", syllables: ["up","date"], phonetic: "/ʌpˈdeɪt/", meaning: "v. 更新；向……提供最新信息 n. 更新；最新消息", example: "We need to update the software to its latest version." },
    { word: "upwards", syllables: ["up","wards"], phonetic: "/ˈʌpwədz/", meaning: "adv. 向上；向高处", example: "The smoke is rising upwards." },
    { word: "vegetarian", syllables: ["veg","e","tar","i","an"], phonetic: "/ˌvedʒəˈteəriən/", meaning: "n. 素食者；吃素的人", example: "She became a vegetarian for health reasons." },
    { word: "warmth", syllables: ["warmth"], phonetic: "/wɔːmθ/", meaning: "n. 温暖；暖和", example: "We sat around the fire to enjoy the warmth." },
    { word: "well-known", syllables: ["well","known"], phonetic: "/ˌwel ˈnəʊn/", meaning: "adj. 众所周知的", example: "He is a well-known scientist in the field of physics." },
    { word: "wilderness", syllables: ["wil","der","ness"], phonetic: "/ˈwɪldənəs/", meaning: "n. 荒野", example: "They went deep into the wilderness to explore the unknown." },
    { word: "wildlife", syllables: ["wild","life"], phonetic: "/ˈwaɪldlaɪf/", meaning: "n. 野生动物；野生生物", example: "We should protect the wildlife and their habitats." }
  ]
};
