const WORDS_7A = {
  "Starter Unit 1": [
    { word: "good", syllables: ["good"], phonetic: "/ɡʊd/", meaning: "adj. 好的", example: "Good morning!" },
    { word: "morning", syllables: ["mor","ning"], phonetic: "/ˈmɔːrnɪŋ/", meaning: "n. 早晨", example: "Good morning, class!" },
    { word: "afternoon", syllables: ["af","ter","noon"], phonetic: "/ˌæftərˈnuːn/", meaning: "n. 下午", example: "Good afternoon!" },
    { word: "evening", syllables: ["eve","ning"], phonetic: "/ˈiːvnɪŋ/", meaning: "n. 晚上", example: "Good evening!" },
    { word: "hello", syllables: ["hel","lo"], phonetic: "/həˈloʊ/", meaning: "interj. 你好", example: "Hello, how are you?" },
    { word: "thank", syllables: ["thank"], phonetic: "/θæŋk/", meaning: "v. 谢谢", example: "Thank you very much." },
    { word: "fine", syllables: ["fine"], phonetic: "/faɪn/", meaning: "adj. 好的", example: "I'm fine, thanks." }
  ],
  "Starter Unit 2": [
    { word: "what", syllables: ["what"], phonetic: "/wɒt/", meaning: "pron. 什么", example: "What is this?" },
    { word: "is", syllables: ["is"], phonetic: "/ɪz/", meaning: "v. 是", example: "This is a map." },
    { word: "this", syllables: ["this"], phonetic: "/ðɪs/", meaning: "pron. 这个", example: "This is my friend." },
    { word: "map", syllables: ["map"], phonetic: "/mæp/", meaning: "n. 地图", example: "It's a map of China." },
    { word: "cup", syllables: ["cup"], phonetic: "/kʌp/", meaning: "n. 杯子", example: "It's a cup." },
    { word: "ruler", syllables: ["ru","ler"], phonetic: "/ˈruːlər/", meaning: "n. 尺子", example: "Is this your ruler?" },
    { word: "pen", syllables: ["pen"], phonetic: "/pen/", meaning: "n. 钢笔", example: "This is my pen." },
    { word: "orange", syllables: ["or","ange"], phonetic: "/ˈɒrɪndʒ/", meaning: "n. 橙子", example: "It's an orange." },
    { word: "jacket", syllables: ["jack","et"], phonetic: "/ˈdʒækɪt/", meaning: "n. 夹克", example: "The jacket is blue." },
    { word: "key", syllables: ["key"], phonetic: "/kiː/", meaning: "n. 钥匙", example: "Is this your key?" },
    { word: "quilt", syllables: ["quilt"], phonetic: "/kwɪlt/", meaning: "n. 被子", example: "It's a quilt." },
    { word: "spell", syllables: ["spell"], phonetic: "/spel/", meaning: "v. 拼写", example: "Can you spell it?" },
    { word: "please", syllables: ["please"], phonetic: "/pliːz/", meaning: "interj. 请", example: "Please sit down." }
  ],
  "Starter Unit 3": [
    { word: "color", syllables: ["co","lor"], phonetic: "/ˈkʌlər/", meaning: "n. 颜色", example: "What color is it?" },
    { word: "red", syllables: ["red"], phonetic: "/red/", meaning: "adj. 红色的", example: "The apple is red." },
    { word: "yellow", syllables: ["yel","low"], phonetic: "/ˈjeloʊ/", meaning: "adj. 黄色的", example: "The banana is yellow." },
    { word: "green", syllables: ["green"], phonetic: "/ɡriːn/", meaning: "adj. 绿色的", example: "The tree is green." },
    { word: "blue", syllables: ["blue"], phonetic: "/bluː/", meaning: "adj. 蓝色的", example: "The sky is blue." },
    { word: "black", syllables: ["black"], phonetic: "/blæk/", meaning: "adj. 黑色的", example: "I have a black pen." },
    { word: "white", syllables: ["white"], phonetic: "/waɪt/", meaning: "adj. 白色的", example: "The cat is white." },
    { word: "purple", syllables: ["pur","ple"], phonetic: "/ˈpɜːrpl/", meaning: "adj. 紫色的", example: "She likes purple." },
    { word: "brown", syllables: ["brown"], phonetic: "/braʊn/", meaning: "adj. 棕色的", example: "The dog is brown." },
    { word: "the", syllables: ["the"], phonetic: "/ðə/", meaning: "art. 这；那", example: "The book is mine." },
    { word: "now", syllables: ["now"], phonetic: "/naʊ/", meaning: "adv. 现在", example: "Now you try." }
  ],
  "Unit 1": [
    { word: "name", syllables: ["name"], phonetic: "/neɪm/", meaning: "n. 名字", example: "My name is Li Ming." },
    { word: "nice", syllables: ["nice"], phonetic: "/naɪs/", meaning: "adj. 令人愉快的", example: "Nice to meet you!" },
    { word: "meet", syllables: ["meet"], phonetic: "/miːt/", meaning: "v. 遇见", example: "Nice to meet you." },
    { word: "too", syllables: ["too"], phonetic: "/tuː/", meaning: "adv. 也", example: "Nice to meet you, too." },
    { word: "friend", syllables: ["friend"], phonetic: "/frend/", meaning: "n. 朋友", example: "She is my friend." },
    { word: "China", syllables: ["Chi","na"], phonetic: "/ˈtʃaɪnə/", meaning: "n. 中国", example: "I'm from China." },
    { word: "phone", syllables: ["phone"], phonetic: "/foʊn/", meaning: "n. 电话", example: "What's your phone number?" },
    { word: "number", syllables: ["num","ber"], phonetic: "/ˈnʌmbər/", meaning: "n. 数字；号码", example: "My phone number is 555-1234." },
    { word: "first", syllables: ["first"], phonetic: "/fɜːrst/", meaning: "adj. 第一的", example: "Her first name is Mary." },
    { word: "last", syllables: ["last"], phonetic: "/læst/", meaning: "adj. 最后的", example: "What's his last name?" },
    { word: "school", syllables: ["school"], phonetic: "/skuːl/", meaning: "n. 学校", example: "I go to school every day." },
    { word: "middle", syllables: ["mid","dle"], phonetic: "/ˈmɪdl/", meaning: "adj. 中间的", example: "I'm in middle school." },
    { word: "your", syllables: ["your"], phonetic: "/jɔːr/", meaning: "pron. 你的", example: "What's your name?" },
    { word: "his", syllables: ["his"], phonetic: "/hɪz/", meaning: "pron. 他的", example: "His name is Tom." },
    { word: "her", syllables: ["her"], phonetic: "/hɜːr/", meaning: "pron. 她的", example: "Her phone is red." }
  ],
  "Unit 2": [
    { word: "sister", syllables: ["sis","ter"], phonetic: "/ˈsɪstər/", meaning: "n. 姐妹", example: "This is my sister." },
    { word: "mother", syllables: ["mo","ther"], phonetic: "/ˈmʌðər/", meaning: "n. 母亲", example: "My mother is a teacher." },
    { word: "father", syllables: ["fa","ther"], phonetic: "/ˈfɑːðər/", meaning: "n. 父亲", example: "My father is a doctor." },
    { word: "parent", syllables: ["pa","rent"], phonetic: "/ˈperənt/", meaning: "n. 父（母）亲", example: "These are my parents." },
    { word: "brother", syllables: ["bro","ther"], phonetic: "/ˈbrʌðər/", meaning: "n. 兄弟", example: "He is my brother." },
    { word: "grandmother", syllables: ["grand","mo","ther"], phonetic: "/ˈɡrændmʌðər/", meaning: "n. 祖母", example: "My grandmother is kind." },
    { word: "grandfather", syllables: ["grand","fa","ther"], phonetic: "/ˈɡrændfɑːðər/", meaning: "n. 祖父", example: "My grandfather is 70." },
    { word: "family", syllables: ["fam","i","ly"], phonetic: "/ˈfæməli/", meaning: "n. 家庭", example: "I love my family." },
    { word: "those", syllables: ["those"], phonetic: "/ðoʊz/", meaning: "pron. 那些", example: "Those are my parents." },
    { word: "these", syllables: ["these"], phonetic: "/ðiːz/", meaning: "pron. 这些", example: "These are my friends." },
    { word: "who", syllables: ["who"], phonetic: "/huː/", meaning: "pron. 谁", example: "Who is she?" },
    { word: "have", syllables: ["have"], phonetic: "/hæv/", meaning: "v. 有", example: "I have a big family." },
    { word: "day", syllables: ["day"], phonetic: "/deɪ/", meaning: "n. 一天", example: "Have a good day!" },
    { word: "daughter", syllables: ["daugh","ter"], phonetic: "/ˈdɔːtər/", meaning: "n. 女儿", example: "She is their daughter." },
    { word: "son", syllables: ["son"], phonetic: "/sʌn/", meaning: "n. 儿子", example: "He is their son." },
    { word: "uncle", syllables: ["un","cle"], phonetic: "/ˈʌŋkl/", meaning: "n. 叔叔", example: "My uncle lives in Beijing." },
    { word: "aunt", syllables: ["aunt"], phonetic: "/ænt/", meaning: "n. 阿姨", example: "My aunt is very nice." },
    { word: "cousin", syllables: ["cou","sin"], phonetic: "/ˈkʌzn/", meaning: "n. 堂（表）兄弟/姐妹", example: "My cousin is a student." },
    { word: "picture", syllables: ["pic","ture"], phonetic: "/ˈpɪktʃər/", meaning: "n. 照片", example: "This is a picture of my family." },
    { word: "girl", syllables: ["girl"], phonetic: "/ɡɜːrl/", meaning: "n. 女孩", example: "The girl is my sister." },
    { word: "dog", syllables: ["dog"], phonetic: "/dɒɡ/", meaning: "n. 狗", example: "The dog is Coco." }
  ],
  "Unit 3": [
    { word: "pencil", syllables: ["pen","cil"], phonetic: "/ˈpensl/", meaning: "n. 铅笔", example: "Is this your pencil?" },
    { word: "book", syllables: ["book"], phonetic: "/bʊk/", meaning: "n. 书", example: "This book is mine." },
    { word: "eraser", syllables: ["e","ra","ser"], phonetic: "/ɪˈreɪsər/", meaning: "n. 橡皮", example: "I need an eraser." },
    { word: "box", syllables: ["box"], phonetic: "/bɒks/", meaning: "n. 箱子", example: "The pencil box is blue." },
    { word: "schoolbag", syllables: ["school","bag"], phonetic: "/ˈskuːlbæɡ/", meaning: "n. 书包", example: "My schoolbag is heavy." },
    { word: "dictionary", syllables: ["dic","tion","a","ry"], phonetic: "/ˈdɪkʃəneri/", meaning: "n. 词典", example: "I look up words in the dictionary." },
    { word: "teacher", syllables: ["teach","er"], phonetic: "/ˈtiːtʃər/", meaning: "n. 老师", example: "The teacher is kind." },
    { word: "classroom", syllables: ["class","room"], phonetic: "/ˈklæsruːm/", meaning: "n. 教室", example: "The classroom is big." },
    { word: "library", syllables: ["li","bra","ry"], phonetic: "/ˈlaɪbreri/", meaning: "n. 图书馆", example: "I read books in the library." },
    { word: "ask", syllables: ["ask"], phonetic: "/æsk/", meaning: "v. 问", example: "You can ask the teacher." },
    { word: "find", syllables: ["find"], phonetic: "/faɪnd/", meaning: "v. 找到", example: "I can't find my pen." },
    { word: "call", syllables: ["call"], phonetic: "/kɔːl/", meaning: "v. 打电话", example: "Please call me." },
    { word: "lost", syllables: ["lost"], phonetic: "/lɒst/", meaning: "adj. 丢失的", example: "I lost my keys." },
    { word: "found", syllables: ["found"], phonetic: "/faʊnd/", meaning: "adj. 找到的", example: "Found: a set of keys." },
    { word: "some", syllables: ["some"], phonetic: "/sʌm/", meaning: "adj. 一些", example: "I need some help." },
    { word: "help", syllables: ["help"], phonetic: "/help/", meaning: "v./n. 帮助", example: "Can you help me?" },
    { word: "notebook", syllables: ["note","book"], phonetic: "/ˈnoʊtbʊk/", meaning: "n. 笔记本", example: "This is my notebook." },
    { word: "mine", syllables: ["mine"], phonetic: "/maɪn/", meaning: "pron. 我的", example: "This book is mine." },
    { word: "yours", syllables: ["yours"], phonetic: "/jɔːrz/", meaning: "pron. 你的", example: "Is this pen yours?" },
    { word: "email", syllables: ["e","mail"], phonetic: "/ˈiːmeɪl/", meaning: "n. 电子邮件", example: "Send me an email." }
  ],
  "Unit 4": [
    { word: "where", syllables: ["where"], phonetic: "/wer/", meaning: "adv. 在哪里", example: "Where is my book?" },
    { word: "table", syllables: ["ta","ble"], phonetic: "/ˈteɪbl/", meaning: "n. 桌子", example: "The keys are on the table." },
    { word: "bed", syllables: ["bed"], phonetic: "/bed/", meaning: "n. 床", example: "The cat is on the bed." },
    { word: "sofa", syllables: ["so","fa"], phonetic: "/ˈsoʊfə/", meaning: "n. 沙发", example: "The dog is on the sofa." },
    { word: "chair", syllables: ["chair"], phonetic: "/tʃer/", meaning: "n. 椅子", example: "Please sit on the chair." },
    { word: "on", syllables: ["on"], phonetic: "/ɒn/", meaning: "prep. 在…上面", example: "The book is on the desk." },
    { word: "under", syllables: ["un","der"], phonetic: "/ˈʌndər/", meaning: "prep. 在…下面", example: "The ball is under the table." },
    { word: "come", syllables: ["come"], phonetic: "/kʌm/", meaning: "v. 来", example: "Come to my room." },
    { word: "desk", syllables: ["desk"], phonetic: "/desk/", meaning: "n. 书桌", example: "My desk is near the window." },
    { word: "think", syllables: ["think"], phonetic: "/θɪŋk/", meaning: "v. 想；认为", example: "I think it's in your bag." },
    { word: "room", syllables: ["room"], phonetic: "/ruːm/", meaning: "n. 房间", example: "My room is clean." },
    { word: "their", syllables: ["their"], phonetic: "/ðer/", meaning: "pron. 他们的", example: "Their house is big." },
    { word: "know", syllables: ["know"], phonetic: "/noʊ/", meaning: "v. 知道", example: "I don't know." },
    { word: "radio", syllables: ["ra","di","o"], phonetic: "/ˈreɪdioʊ/", meaning: "n. 收音机", example: "The radio is on the desk." },
    { word: "clock", syllables: ["clock"], phonetic: "/klɒk/", meaning: "n. 钟表", example: "The clock is on the wall." },
    { word: "tape", syllables: ["tape"], phonetic: "/teɪp/", meaning: "n. 磁带", example: "I have a tape player." },
    { word: "player", syllables: ["play","er"], phonetic: "/ˈpleɪər/", meaning: "n. 播放器", example: "The tape player is old." },
    { word: "model", syllables: ["mod","el"], phonetic: "/ˈmɒdl/", meaning: "n. 模型", example: "I have a model plane." },
    { word: "plane", syllables: ["plane"], phonetic: "/pleɪn/", meaning: "n. 飞机", example: "The model plane is cool." },
    { word: "tidy", syllables: ["ti","dy"], phonetic: "/ˈtaɪdi/", meaning: "adj. 整洁的", example: "Her room is tidy." },
    { word: "but", syllables: ["but"], phonetic: "/bʌt/", meaning: "conj. 但是", example: "I'm tidy, but my brother is not." },
    { word: "our", syllables: ["our"], phonetic: "/aʊr/", meaning: "pron. 我们的", example: "This is our classroom." },
    { word: "everywhere", syllables: ["eve","ry","where"], phonetic: "/ˈevriwer/", meaning: "adv. 到处", example: "My books are everywhere." },
    { word: "always", syllables: ["al","ways"], phonetic: "/ˈɔːlweɪz/", meaning: "adv. 总是", example: "She always helps me." }
  ],
  "Unit 5": [
    { word: "tennis", syllables: ["ten","nis"], phonetic: "/ˈtenɪs/", meaning: "n. 网球", example: "Let's play tennis." },
    { word: "ball", syllables: ["ball"], phonetic: "/bɔːl/", meaning: "n. 球", example: "I have a soccer ball." },
    { word: "soccer", syllables: ["soc","cer"], phonetic: "/ˈsɒkər/", meaning: "n. 足球", example: "Do you like soccer?" },
    { word: "volleyball", syllables: ["vol","ley","ball"], phonetic: "/ˈvɒlibɔːl/", meaning: "n. 排球", example: "She plays volleyball." },
    { word: "basketball", syllables: ["bas","ket","ball"], phonetic: "/ˈbæskɪtbɔːl/", meaning: "n. 篮球", example: "He likes basketball." },
    { word: "let", syllables: ["let"], phonetic: "/let/", meaning: "v. 允许", example: "Let's go!" },
    { word: "play", syllables: ["play"], phonetic: "/pleɪ/", meaning: "v. 玩；播放", example: "Let's play soccer." },
    { word: "sound", syllables: ["sound"], phonetic: "/saʊnd/", meaning: "v. 听起来", example: "That sounds good." },
    { word: "sport", syllables: ["sport"], phonetic: "/spɔːrt/", meaning: "n. 运动", example: "I like sports." },
    { word: "we", syllables: ["we"], phonetic: "/wiː/", meaning: "pron. 我们", example: "We play soccer after school." },
    { word: "many", syllables: ["ma","ny"], phonetic: "/ˈmeni/", meaning: "adj. 许多", example: "I have many balls." },
    { word: "class", syllables: ["class"], phonetic: "/klæs/", meaning: "n. 班级；课", example: "We have English class." },
    { word: "classmate", syllables: ["class","mate"], phonetic: "/ˈklæsmeɪt/", meaning: "n. 同学", example: "She is my classmate." },
    { word: "same", syllables: ["same"], phonetic: "/seɪm/", meaning: "adj. 相同的", example: "We are in the same class." },
    { word: "love", syllables: ["love"], phonetic: "/lʌv/", meaning: "v./n. 爱", example: "I love sports." },
    { word: "with", syllables: ["with"], phonetic: "/wɪð/", meaning: "prep. 和…一起", example: "I play with my friends." },
    { word: "them", syllables: ["them"], phonetic: "/ðem/", meaning: "pron. 他们", example: "I play with them." },
    { word: "only", syllables: ["on","ly"], phonetic: "/ˈoʊnli/", meaning: "adv. 只；仅", example: "I only watch them on TV." },
    { word: "easy", syllables: ["ea","sy"], phonetic: "/ˈiːzi/", meaning: "adj. 容易的", example: "It's easy for me." },
    { word: "difficult", syllables: ["dif","fi","cult"], phonetic: "/ˈdɪfɪkʌlt/", meaning: "adj. 困难的", example: "It's difficult for me." },
    { word: "interesting", syllables: ["in","ter","est","ing"], phonetic: "/ˈɪntrəstɪŋ/", meaning: "adj. 有趣的", example: "The game is interesting." },
    { word: "boring", syllables: ["bor","ing"], phonetic: "/ˈbɔːrɪŋ/", meaning: "adj. 无聊的", example: "The movie is boring." },
    { word: "relaxing", syllables: ["re","lax","ing"], phonetic: "/rɪˈlæksɪŋ/", meaning: "adj. 令人放松的", example: "It's a relaxing sport." },
    { word: "fun", syllables: ["fun"], phonetic: "/fʌn/", meaning: "adj. 有趣的", example: "That sounds fun." },
    { word: "watch", syllables: ["watch"], phonetic: "/wɒtʃ/", meaning: "v. 观看", example: "I watch TV every day." },
    { word: "television", syllables: ["tel","e","vi","sion"], phonetic: "/ˈtelɪvɪʒn/", meaning: "n. 电视", example: "I watch sports on television." }
  ],
  "Unit 6": [
    { word: "banana", syllables: ["ba","na","na"], phonetic: "/bəˈnænə/", meaning: "n. 香蕉", example: "I like bananas." },
    { word: "apple", syllables: ["ap","ple"], phonetic: "/ˈæpl/", meaning: "n. 苹果", example: "Do you like apples?" },
    { word: "hamburger", syllables: ["ham","bur","ger"], phonetic: "/ˈhæmbɜːrɡər/", meaning: "n. 汉堡包", example: "I like hamburgers." },
    { word: "tomato", syllables: ["to","ma","to"], phonetic: "/təˈmeɪtoʊ/", meaning: "n. 西红柿", example: "I don't like tomatoes." },
    { word: "ice", syllables: ["ice"], phonetic: "/aɪs/", meaning: "n. 冰", example: "I like ice-cream." },
    { word: "cream", syllables: ["cream"], phonetic: "/kriːm/", meaning: "n. 奶油", example: "Ice-cream is sweet." },
    { word: "salad", syllables: ["sal","ad"], phonetic: "/ˈsæləd/", meaning: "n. 沙拉", example: "She likes salad." },
    { word: "strawberry", syllables: ["straw","ber","ry"], phonetic: "/ˈstrɔːberi/", meaning: "n. 草莓", example: "Strawberries are delicious." },
    { word: "pear", syllables: ["pear"], phonetic: "/per/", meaning: "n. 梨", example: "The pear is sweet." },
    { word: "milk", syllables: ["milk"], phonetic: "/mɪlk/", meaning: "n. 牛奶", example: "I drink milk every morning." },
    { word: "bread", syllables: ["bread"], phonetic: "/bred/", meaning: "n. 面包", example: "I have bread for breakfast." },
    { word: "food", syllables: ["food"], phonetic: "/fuːd/", meaning: "n. 食物", example: "What food do you like?" },
    { word: "chicken", syllables: ["chick","en"], phonetic: "/ˈtʃɪkɪn/", meaning: "n. 鸡肉", example: "I like chicken." },
    { word: "rice", syllables: ["rice"], phonetic: "/raɪs/", meaning: "n. 米饭", example: "We eat rice for lunch." },
    { word: "carrot", syllables: ["car","rot"], phonetic: "/ˈkærət/", meaning: "n. 胡萝卜", example: "Rabbits like carrots." },
    { word: "eat", syllables: ["eat"], phonetic: "/iːt/", meaning: "v. 吃", example: "I eat breakfast at seven." },
    { word: "well", syllables: ["well"], phonetic: "/wel/", meaning: "adv. 好", example: "She eats well." },
    { word: "really", syllables: ["real","ly"], phonetic: "/ˈriːəli/", meaning: "adv. 真正地", example: "Do you really like it?" },
    { word: "healthy", syllables: ["health","y"], phonetic: "/ˈhelθi/", meaning: "adj. 健康的", example: "Vegetables are healthy." },
    { word: "habit", syllables: ["hab","it"], phonetic: "/ˈhæbɪt/", meaning: "n. 习惯", example: "Eating fruit is a good habit." },
    { word: "breakfast", syllables: ["break","fast"], phonetic: "/ˈbrekfəst/", meaning: "n. 早餐", example: "I have breakfast at 7:00." },
    { word: "lunch", syllables: ["lunch"], phonetic: "/lʌntʃ/", meaning: "n. 午餐", example: "We have lunch at school." },
    { word: "dinner", syllables: ["din","ner"], phonetic: "/ˈdɪnər/", meaning: "n. 晚餐", example: "Dinner is at 6:00." },
    { word: "fruit", syllables: ["fruit"], phonetic: "/fruːt/", meaning: "n. 水果", example: "I like fruit." },
    { word: "vegetable", syllables: ["veg","e","ta","ble"], phonetic: "/ˈvedʒtəbl/", meaning: "n. 蔬菜", example: "Eat more vegetables." },
    { word: "star", syllables: ["star"], phonetic: "/stɑːr/", meaning: "n. 明星", example: "She is a sports star." },
    { word: "question", syllables: ["ques","tion"], phonetic: "/ˈkwestʃən/", meaning: "n. 问题", example: "Can I ask a question?" },
    { word: "fat", syllables: ["fat"], phonetic: "/fæt/", meaning: "adj. 胖的", example: "I don't want to be fat." }
  ],
  "Unit 7": [
    { word: "much", syllables: ["much"], phonetic: "/mʌtʃ/", meaning: "adv. 多少", example: "How much is it?" },
    { word: "sock", syllables: ["sock"], phonetic: "/sɒk/", meaning: "n. 袜子", example: "I need a pair of socks." },
    { word: "T-shirt", syllables: ["T-","shirt"], phonetic: "/ˈtiːʃɜːrt/", meaning: "n. T恤衫", example: "This T-shirt is nice." },
    { word: "shorts", syllables: ["shorts"], phonetic: "/ʃɔːrts/", meaning: "n. 短裤", example: "I like these shorts." },
    { word: "sweater", syllables: ["sweat","er"], phonetic: "/ˈswetər/", meaning: "n. 毛衣", example: "The sweater is warm." },
    { word: "trousers", syllables: ["trou","sers"], phonetic: "/ˈtraʊzərz/", meaning: "n. 裤子", example: "These trousers are long." },
    { word: "shoe", syllables: ["shoe"], phonetic: "/ʃuː/", meaning: "n. 鞋子", example: "These shoes are comfortable." },
    { word: "skirt", syllables: ["skirt"], phonetic: "/skɜːrt/", meaning: "n. 裙子", example: "She wears a skirt." },
    { word: "dollar", syllables: ["dol","lar"], phonetic: "/ˈdɒlər/", meaning: "n. 美元", example: "It's ten dollars." },
    { word: "price", syllables: ["price"], phonetic: "/praɪs/", meaning: "n. 价格", example: "The price is good." },
    { word: "buy", syllables: ["buy"], phonetic: "/baɪ/", meaning: "v. 买", example: "I want to buy a shirt." },
    { word: "sale", syllables: ["sale"], phonetic: "/seɪl/", meaning: "n. 特价销售", example: "We have a big sale." },
    { word: "sell", syllables: ["sell"], phonetic: "/sel/", meaning: "v. 卖", example: "We sell all our clothes." },
    { word: "store", syllables: ["store"], phonetic: "/stɔːr/", meaning: "n. 商店", example: "Let's go to the store." },
    { word: "clothes", syllables: ["clothes"], phonetic: "/kloʊðz/", meaning: "n. 衣服", example: "I need new clothes." },
    { word: "small", syllables: ["small"], phonetic: "/smɔːl/", meaning: "adj. 小的", example: "This is too small." },
    { word: "big", syllables: ["big"], phonetic: "/bɪɡ/", meaning: "adj. 大的", example: "I need a big one." },
    { word: "long", syllables: ["long"], phonetic: "/lɒŋ/", meaning: "adj. 长的", example: "The pants are too long." },
    { word: "short", syllables: ["short"], phonetic: "/ʃɔːrt/", meaning: "adj. 短的", example: "Her hair is short." },
    { word: "woman", syllables: ["wom","an"], phonetic: "/ˈwʊmən/", meaning: "n. 女人", example: "The woman is my teacher." },
    { word: "need", syllables: ["need"], phonetic: "/niːd/", meaning: "v. 需要", example: "I need a new bag." },
    { word: "look", syllables: ["look"], phonetic: "/lʊk/", meaning: "v. 看", example: "Look at this shirt." },
    { word: "pair", syllables: ["pair"], phonetic: "/per/", meaning: "n. 一双", example: "I need a pair of shoes." },
    { word: "take", syllables: ["take"], phonetic: "/teɪk/", meaning: "v. 拿走；买下", example: "I'll take it." },
    { word: "eleven", syllables: ["e","lev","en"], phonetic: "/ɪˈlevn/", meaning: "num. 十一", example: "It's eleven dollars." },
    { word: "twelve", syllables: ["twelve"], phonetic: "/twelv/", meaning: "num. 十二", example: "She is twelve years old." },
    { word: "thirteen", syllables: ["thir","teen"], phonetic: "/θɜːrˈtiːn/", meaning: "num. 十三", example: "The hat is thirteen dollars." },
    { word: "fifteen", syllables: ["fif","teen"], phonetic: "/fɪfˈtiːn/", meaning: "num. 十五", example: "It's fifteen yuan." },
    { word: "eighteen", syllables: ["eigh","teen"], phonetic: "/eɪˈtiːn/", meaning: "num. 十八", example: "He is eighteen." },
    { word: "twenty", syllables: ["twen","ty"], phonetic: "/ˈtwenti/", meaning: "num. 二十", example: "It's twenty dollars." },
    { word: "thirty", syllables: ["thir","ty"], phonetic: "/ˈθɜːrti/", meaning: "num. 三十", example: "The shoes are thirty dollars." }
  ],
  "Unit 8": [
    { word: "month", syllables: ["month"], phonetic: "/mʌnθ/", meaning: "n. 月", example: "Which month do you like?" },
    { word: "January", syllables: ["Jan","u","a","ry"], phonetic: "/ˈdʒænjueri/", meaning: "n. 一月", example: "January is the first month." },
    { word: "February", syllables: ["Feb","ru","a","ry"], phonetic: "/ˈfebrueri/", meaning: "n. 二月", example: "February is short." },
    { word: "March", syllables: ["March"], phonetic: "/mɑːrtʃ/", meaning: "n. 三月", example: "My birthday is in March." },
    { word: "April", syllables: ["A","pril"], phonetic: "/ˈeɪprəl/", meaning: "n. 四月", example: "April 1st is April Fool's Day." },
    { word: "May", syllables: ["May"], phonetic: "/meɪ/", meaning: "n. 五月", example: "May is a beautiful month." },
    { word: "June", syllables: ["June"], phonetic: "/dʒuːn/", meaning: "n. 六月", example: "Children's Day is in June." },
    { word: "July", syllables: ["Ju","ly"], phonetic: "/dʒuˈlaɪ/", meaning: "n. 七月", example: "July is very hot." },
    { word: "August", syllables: ["Au","gust"], phonetic: "/ˈɔːɡəst/", meaning: "n. 八月", example: "We have vacation in August." },
    { word: "September", syllables: ["Sep","tem","ber"], phonetic: "/sepˈtembər/", meaning: "n. 九月", example: "School starts in September." },
    { word: "October", syllables: ["Oc","to","ber"], phonetic: "/ɒkˈtoʊbər/", meaning: "n. 十月", example: "October is my favorite month." },
    { word: "November", syllables: ["No","vem","ber"], phonetic: "/noʊˈvembər/", meaning: "n. 十一月", example: "Thanksgiving is in November." },
    { word: "December", syllables: ["De","cem","ber"], phonetic: "/dɪˈsembər/", meaning: "n. 十二月", example: "Christmas is in December." },
    { word: "happy", syllables: ["hap","py"], phonetic: "/ˈhæpi/", meaning: "adj. 高兴的", example: "Happy birthday!" },
    { word: "birthday", syllables: ["birth","day"], phonetic: "/ˈbɜːrθdeɪ/", meaning: "n. 生日", example: "When is your birthday?" },
    { word: "party", syllables: ["par","ty"], phonetic: "/ˈpɑːrti/", meaning: "n. 聚会", example: "We have a birthday party." },
    { word: "age", syllables: ["age"], phonetic: "/eɪdʒ/", meaning: "n. 年龄", example: "What's your age?" },
    { word: "old", syllables: ["old"], phonetic: "/oʊld/", meaning: "adj. 老的；旧的", example: "How old are you?" },
    { word: "test", syllables: ["test"], phonetic: "/test/", meaning: "n. 测试", example: "We have a math test." },
    { word: "trip", syllables: ["trip"], phonetic: "/trɪp/", meaning: "n. 旅行", example: "We have a school trip." },
    { word: "art", syllables: ["art"], phonetic: "/ɑːrt/", meaning: "n. 艺术", example: "I like art class." },
    { word: "festival", syllables: ["fes","ti","val"], phonetic: "/ˈfestɪvl/", meaning: "n. 节日", example: "We have an art festival." },
    { word: "dear", syllables: ["dear"], phonetic: "/dɪr/", meaning: "adj. 亲爱的", example: "Dear students," },
    { word: "student", syllables: ["stu","dent"], phonetic: "/ˈstjuːdnt/", meaning: "n. 学生", example: "I am a student." },
    { word: "thing", syllables: ["thing"], phonetic: "/θɪŋ/", meaning: "n. 东西", example: "I have many things." },
    { word: "term", syllables: ["term"], phonetic: "/tɜːrm/", meaning: "n. 学期", example: "We have a busy term." },
    { word: "busy", syllables: ["bu","sy"], phonetic: "/ˈbɪzi/", meaning: "adj. 忙碌的", example: "I'm very busy this term." },
    { word: "time", syllables: ["time"], phonetic: "/taɪm/", meaning: "n. 时间", example: "What time is it?" }
  ],
  "Unit 9": [
    { word: "favorite", syllables: ["fa","vor","ite"], phonetic: "/ˈfeɪvərɪt/", meaning: "adj. 最喜爱的", example: "What's your favorite subject?" },
    { word: "subject", syllables: ["sub","ject"], phonetic: "/ˈsʌbdʒɪkt/", meaning: "n. 科目", example: "My favorite subject is English." },
    { word: "science", syllables: ["sci","ence"], phonetic: "/ˈsaɪəns/", meaning: "n. 科学", example: "I like science class." },
    { word: "music", syllables: ["mu","sic"], phonetic: "/ˈmjuːzɪk/", meaning: "n. 音乐", example: "She likes music." },
    { word: "math", syllables: ["math"], phonetic: "/mæθ/", meaning: "n. 数学", example: "Math is interesting." },
    { word: "Chinese", syllables: ["Chi","nese"], phonetic: "/tʃaɪˈniːz/", meaning: "n./adj. 中文；中国的", example: "I study Chinese." },
    { word: "geography", syllables: ["ge","og","ra","phy"], phonetic: "/dʒiˈɒɡrəfi/", meaning: "n. 地理", example: "Geography is fun." },
    { word: "history", syllables: ["his","to","ry"], phonetic: "/ˈhɪstri/", meaning: "n. 历史", example: "We learn about history." },
    { word: "boring", syllables: ["bor","ing"], phonetic: "/ˈbɔːrɪŋ/", meaning: "adj. 无聊的", example: "The class is boring." },
    { word: "useful", syllables: ["use","ful"], phonetic: "/ˈjuːsfl/", meaning: "adj. 有用的", example: "English is useful." },
    { word: "cool", syllables: ["cool"], phonetic: "/kuːl/", meaning: "adj. 酷的", example: "That's cool!" },
    { word: "Monday", syllables: ["Mon","day"], phonetic: "/ˈmʌndeɪ/", meaning: "n. 星期一", example: "I have math on Monday." },
    { word: "Tuesday", syllables: ["Tues","day"], phonetic: "/ˈtuːzdeɪ/", meaning: "n. 星期二", example: "Tuesday is busy." },
    { word: "Wednesday", syllables: ["Wednes","day"], phonetic: "/ˈwenzdeɪ/", meaning: "n. 星期三", example: "We have art on Wednesday." },
    { word: "Thursday", syllables: ["Thurs","day"], phonetic: "/ˈθɜːrzdeɪ/", meaning: "n. 星期四", example: "Thursday is my favorite day." },
    { word: "Friday", syllables: ["Fri","day"], phonetic: "/ˈfraɪdeɪ/", meaning: "n. 星期五", example: "Friday is fun." },
    { word: "Saturday", syllables: ["Sat","ur","day"], phonetic: "/ˈsætərdeɪ/", meaning: "n. 星期六", example: "I play on Saturday." },
    { word: "Sunday", syllables: ["Sun","day"], phonetic: "/ˈsʌndeɪ/", meaning: "n. 星期日", example: "We rest on Sunday." },
    { word: "free", syllables: ["free"], phonetic: "/friː/", meaning: "adj. 空闲的", example: "Are you free today?" },
    { word: "lesson", syllables: ["les","son"], phonetic: "/ˈlesn/", meaning: "n. 课", example: "We have six lessons today." },
    { word: "hour", syllables: ["hour"], phonetic: "/aʊr/", meaning: "n. 小时", example: "We have two hours of English." },
    { word: "finish", syllables: ["fin","ish"], phonetic: "/ˈfɪnɪʃ/", meaning: "v. 完成", example: "Classes finish at 4:00." },
    { word: "from", syllables: ["from"], phonetic: "/frɒm/", meaning: "prep. 从", example: "I'm from China." },
    { word: "why", syllables: ["why"], phonetic: "/waɪ/", meaning: "adv. 为什么", example: "Why do you like it?" },
    { word: "because", syllables: ["be","cause"], phonetic: "/bɪˈkɒz/", meaning: "conj. 因为", example: "Because it's fun." },
    { word: "teacher", syllables: ["teach","er"], phonetic: "/ˈtiːtʃər/", meaning: "n. 老师", example: "Our teacher is great." }
  ]
};