const WORDS_ZK_AF = {
  "第1组": [
    { word: "a", syllables: ["a"], phonetic: "/ə/", meaning: "art. 一个", example: "I have a book." },
    { word: "ability", syllables: ["a","bil","i","ty"], phonetic: "/əˈbɪləti/", meaning: "n. 能力", example: "She has the ability to solve problems." },
    { word: "able", syllables: ["a","ble"], phonetic: "/ˈeɪbl/", meaning: "adj. 能够的", example: "Are you able to come tomorrow?" },
    { word: "about", syllables: ["a","bout"], phonetic: "/əˈbaʊt/", meaning: "prep./adv. 关于；大约", example: "Tell me about your family." },
    { word: "above", syllables: ["a","bove"], phonetic: "/əˈbʌv/", meaning: "prep./adv. 在……上面", example: "The picture hangs above the sofa." },
    { word: "abroad", syllables: ["a","broad"], phonetic: "/əˈbrɔːd/", meaning: "adv. 在国外", example: "She went abroad to study English." },
    { word: "absent", syllables: ["ab","sent"], phonetic: "/ˈæbsənt/", meaning: "adj. 缺席的", example: "He was absent from school yesterday." },
    { word: "accept", syllables: ["ac","cept"], phonetic: "/əkˈsept/", meaning: "v. 接受", example: "Please accept my apology." },
    { word: "accident", syllables: ["ac","ci","dent"], phonetic: "/ˈæksɪdənt/", meaning: "n. 事故；意外", example: "There was a car accident on the road." },
    { word: "according", syllables: ["ac","cor","ding"], phonetic: "/əˈkɔːrdɪŋ/", meaning: "adv. 根据", example: "According to the map, we are here." },
    { word: "achieve", syllables: ["a","chieve"], phonetic: "/əˈtʃiːv/", meaning: "v. 达到；实现", example: "Work hard to achieve your dream." },
    { word: "across", syllables: ["a","cross"], phonetic: "/əˈkrɔːs/", meaning: "prep./adv. 穿过", example: "Walk across the bridge." },
    { word: "act", syllables: ["act"], phonetic: "/ækt/", meaning: "v./n. 行动；表演", example: "Think before you act." },
    { word: "action", syllables: ["ac","tion"], phonetic: "/ˈækʃn/", meaning: "n. 行动", example: "Actions speak louder than words." },
    { word: "active", syllables: ["ac","tive"], phonetic: "/ˈæktɪv/", meaning: "adj. 积极的；活跃的", example: "She is very active in class." },
    { word: "activity", syllables: ["ac","tiv","i","ty"], phonetic: "/ækˈtɪvəti/", meaning: "n. 活动", example: "What activities do you like?" },
    { word: "actual", syllables: ["ac","tu","al"], phonetic: "/ˈæktʃuəl/", meaning: "adj. 实际的", example: "What is the actual price?" },
    { word: "add", syllables: ["add"], phonetic: "/æd/", meaning: "v. 添加；加", example: "Please add some sugar to the coffee." },
    { word: "address", syllables: ["ad","dress"], phonetic: "/əˈdres/", meaning: "n. 地址", example: "What is your home address?" },
    { word: "admire", syllables: ["ad","mire"], phonetic: "/ədˈmaɪər/", meaning: "v. 钦佩；赞赏", example: "I admire her courage." },
    { word: "adult", syllables: ["a","dult"], phonetic: "/ˈædʌlt/", meaning: "n./adj. 成年人；成年的", example: "This movie is for adults only." },
    { word: "advice", syllables: ["ad","vice"], phonetic: "/ədˈvaɪs/", meaning: "n. 建议", example: "Can you give me some advice?" },
    { word: "advise", syllables: ["ad","vise"], phonetic: "/ədˈvaɪz/", meaning: "v. 建议", example: "I advise you to study harder." },
    { word: "afraid", syllables: ["a","fraid"], phonetic: "/əˈfreɪd/", meaning: "adj. 害怕的", example: "Don't be afraid of the dark." },
    { word: "after", syllables: ["af","ter"], phonetic: "/ˈæftər/", meaning: "prep./conj. 在……之后", example: "We play football after school." },
    { word: "afternoon", syllables: ["af","ter","noon"], phonetic: "/ˌæftərˈnuːn/", meaning: "n. 下午", example: "Good afternoon, everyone!" },
    { word: "again", syllables: ["a","gain"], phonetic: "/əˈɡen/", meaning: "adv. 再次；又", example: "Please say that again." },
    { word: "against", syllables: ["a","gainst"], phonetic: "/əˈɡenst/", meaning: "prep. 反对；对着", example: "Are you for or against the plan?" },
    { word: "age", syllables: ["age"], phonetic: "/eɪdʒ/", meaning: "n. 年龄", example: "What is your age?" },
    { word: "ago", syllables: ["a","go"], phonetic: "/əˈɡoʊ/", meaning: "adv. 以前", example: "I lived here five years ago." },
    { word: "agree", syllables: ["a","gree"], phonetic: "/əˈɡriː/", meaning: "v. 同意", example: "I agree with you." },
    { word: "ahead", syllables: ["a","head"], phonetic: "/əˈhed/", meaning: "adv. 在前面；向前", example: "Go straight ahead." },
    { word: "air", syllables: ["air"], phonetic: "/er/", meaning: "n. 空气", example: "The air is fresh in the morning." },
    { word: "airport", syllables: ["air","port"], phonetic: "/ˈerpɔːrt/", meaning: "n. 机场", example: "We arrived at the airport early." },
    { word: "alive", syllables: ["a","live"], phonetic: "/əˈlaɪv/", meaning: "adj. 活着的", example: "The fish is still alive." },
    { word: "all", syllables: ["all"], phonetic: "/ɔːl/", meaning: "adj./pron. 全部；所有", example: "All the students are here." },
    { word: "allow", syllables: ["al","low"], phonetic: "/əˈlaʊ/", meaning: "v. 允许", example: "My parents allow me to watch TV." },
    { word: "almost", syllables: ["al","most"], phonetic: "/ˈɔːlmoʊst/", meaning: "adv. 几乎", example: "It is almost time to go." },
    { word: "alone", syllables: ["a","lone"], phonetic: "/əˈloʊn/", meaning: "adj./adv. 单独的；独自地", example: "She lives alone." },
    { word: "along", syllables: ["a","long"], phonetic: "/əˈlɔːŋ/", meaning: "prep./adv. 沿着；一起", example: "Walk along this road." },
    { word: "already", syllables: ["al","rea","dy"], phonetic: "/ɔːlˈredi/", meaning: "adv. 已经", example: "I have already finished my homework." },
    { word: "also", syllables: ["al","so"], phonetic: "/ˈɔːlsoʊ/", meaning: "adv. 也；而且", example: "She also likes music." },
    { word: "although", syllables: ["al","though"], phonetic: "/ɔːlˈðoʊ/", meaning: "conj. 尽管；虽然", example: "Although it rained, we had fun." },
    { word: "always", syllables: ["al","ways"], phonetic: "/ˈɔːlweɪz/", meaning: "adv. 总是", example: "She always gets up early." },
    { word: "amazing", syllables: ["a","ma","zing"], phonetic: "/əˈmeɪzɪŋ/", meaning: "adj. 令人惊奇的", example: "The magic show was amazing." },
    { word: "among", syllables: ["a","mong"], phonetic: "/əˈmʌŋ/", meaning: "prep. 在……之中", example: "She sat among her friends." },
    { word: "ancient", syllables: ["an","cient"], phonetic: "/ˈeɪnʃənt/", meaning: "adj. 古代的；古老的", example: "China has an ancient history." },
    { word: "angry", syllables: ["an","gry"], phonetic: "/ˈæŋɡri/", meaning: "adj. 生气的", example: "Don't be angry with me." },
    { word: "animal", syllables: ["an","i","mal"], phonetic: "/ˈænɪml/", meaning: "n. 动物", example: "My favorite animal is the panda." },
    { word: "another", syllables: ["a","no","ther"], phonetic: "/əˈnʌðər/", meaning: "adj./pron. 另一个", example: "Would you like another cup of tea?" }
  ],
  "第2组": [
    { word: "answer", syllables: ["an","swer"], phonetic: "/ˈænsər/", meaning: "n./v. 回答；答案", example: "Can you answer the question?" },
    { word: "ant", syllables: ["ant"], phonetic: "/ænt/", meaning: "n. 蚂蚁", example: "An ant can carry heavy things." },
    { word: "anxious", syllables: ["anx","ious"], phonetic: "/ˈæŋkʃəs/", meaning: "adj. 焦虑的；担忧的", example: "She felt anxious before the exam." },
    { word: "any", syllables: ["a","ny"], phonetic: "/ˈeni/", meaning: "adj./pron. 任何的", example: "Do you have any questions?" },
    { word: "anybody", syllables: ["any","bo","dy"], phonetic: "/ˈenibɑːdi/", meaning: "pron. 任何人", example: "Is anybody here?" },
    { word: "anyone", syllables: ["any","one"], phonetic: "/ˈeniwʌn/", meaning: "pron. 任何人", example: "Can anyone help me?" },
    { word: "anything", syllables: ["any","thing"], phonetic: "/ˈeniθɪŋ/", meaning: "pron. 任何事物", example: "I didn't eat anything this morning." },
    { word: "anywhere", syllables: ["any","where"], phonetic: "/ˈeniwer/", meaning: "adv. 任何地方", example: "I can't find it anywhere." },
    { word: "appear", syllables: ["ap","pear"], phonetic: "/əˈpɪr/", meaning: "v. 出现；似乎", example: "A rainbow appeared in the sky." },
    { word: "apple", syllables: ["ap","ple"], phonetic: "/ˈæpl/", meaning: "n. 苹果", example: "An apple a day keeps the doctor away." },
    { word: "area", syllables: ["ar","e","a"], phonetic: "/ˈeriə/", meaning: "n. 地区；区域", example: "This area is very quiet." },
    { word: "arm", syllables: ["arm"], phonetic: "/ɑːrm/", meaning: "n. 手臂", example: "She broke her arm last week." },
    { word: "army", syllables: ["ar","my"], phonetic: "/ˈɑːrmi/", meaning: "n. 军队", example: "He joined the army last year." },
    { word: "around", syllables: ["a","round"], phonetic: "/əˈraʊnd/", meaning: "prep./adv. 在周围；大约", example: "Look around the room." },
    { word: "arrive", syllables: ["ar","rive"], phonetic: "/əˈraɪv/", meaning: "v. 到达", example: "We arrived at the station at eight." },
    { word: "art", syllables: ["art"], phonetic: "/ɑːrt/", meaning: "n. 艺术；美术", example: "She is good at art." },
    { word: "article", syllables: ["ar","ti","cle"], phonetic: "/ˈɑːrtɪkl/", meaning: "n. 文章", example: "I read an interesting article today." },
    { word: "as", syllables: ["as"], phonetic: "/æz/", meaning: "conj./prep. 作为；如同", example: "She works as a teacher." },
    { word: "ask", syllables: ["ask"], phonetic: "/æsk/", meaning: "v. 问；请求", example: "May I ask you a question?" },
    { word: "asleep", syllables: ["a","sleep"], phonetic: "/əˈsliːp/", meaning: "adj./adv. 睡着的", example: "The baby fell asleep quickly." },
    { word: "at", syllables: ["at"], phonetic: "/æt/", meaning: "prep. 在", example: "I get up at seven o'clock." },
    { word: "attention", syllables: ["at","ten","tion"], phonetic: "/əˈtenʃn/", meaning: "n. 注意", example: "Please pay attention to the teacher." },
    { word: "aunt", syllables: ["aunt"], phonetic: "/ænt/", meaning: "n. 阿姨；姑母", example: "My aunt lives in Beijing." },
    { word: "autumn", syllables: ["au","tumn"], phonetic: "/ˈɔːtəm/", meaning: "n. 秋天", example: "Autumn is a beautiful season." },
    { word: "awake", syllables: ["a","wake"], phonetic: "/əˈweɪk/", meaning: "adj. 醒着的", example: "The baby is awake now." },
    { word: "away", syllables: ["a","way"], phonetic: "/əˈweɪ/", meaning: "adv. 离开；远离", example: "Please go away." },
    { word: "baby", syllables: ["ba","by"], phonetic: "/ˈbeɪbi/", meaning: "n. 婴儿", example: "The baby is very cute." },
    { word: "back", syllables: ["back"], phonetic: "/bæk/", meaning: "n./adv. 背部；回来", example: "I will be back soon." },
    { word: "bad", syllables: ["bad"], phonetic: "/bæd/", meaning: "adj. 坏的；糟糕的", example: "The weather was bad yesterday." },
    { word: "bag", syllables: ["bag"], phonetic: "/bæɡ/", meaning: "n. 包；袋子", example: "This is my school bag." },
    { word: "ball", syllables: ["ball"], phonetic: "/bɔːl/", meaning: "n. 球", example: "Let's play with the ball." },
    { word: "banana", syllables: ["ba","na","na"], phonetic: "/bəˈnænə/", meaning: "n. 香蕉", example: "Monkeys like bananas." },
    { word: "bank", syllables: ["bank"], phonetic: "/bæŋk/", meaning: "n. 银行；河岸", example: "I need to go to the bank." },
    { word: "basic", syllables: ["ba","sic"], phonetic: "/ˈbeɪsɪk/", meaning: "adj. 基本的", example: "Food is a basic need." },
    { word: "basket", syllables: ["bas","ket"], phonetic: "/ˈbæskɪt/", meaning: "n. 篮子", example: "She carried a basket of flowers." },
    { word: "basketball", syllables: ["bas","ket","ball"], phonetic: "/ˈbæskɪtbɔːl/", meaning: "n. 篮球", example: "He likes playing basketball." },
    { word: "be", syllables: ["be"], phonetic: "/biː/", meaning: "v. 是；存在", example: "I want to be a doctor." },
    { word: "beach", syllables: ["beach"], phonetic: "/biːtʃ/", meaning: "n. 海滩", example: "We played on the beach." },
    { word: "bear", syllables: ["bear"], phonetic: "/ber/", meaning: "n. 熊", example: "The bear lives in the forest." },
    { word: "beat", syllables: ["beat"], phonetic: "/biːt/", meaning: "v. 打败；敲打", example: "Our team beat them in the game." },
    { word: "beautiful", syllables: ["beau","ti","ful"], phonetic: "/ˈbjuːtɪfl/", meaning: "adj. 美丽的", example: "What a beautiful day!" },
    { word: "because", syllables: ["be","cause"], phonetic: "/bɪˈkɔːz/", meaning: "conj. 因为", example: "I stayed home because it rained." },
    { word: "become", syllables: ["be","come"], phonetic: "/bɪˈkʌm/", meaning: "v. 变成；成为", example: "He wants to become a pilot." },
    { word: "bed", syllables: ["bed"], phonetic: "/bed/", meaning: "n. 床", example: "It is time to go to bed." },
    { word: "bedroom", syllables: ["bed","room"], phonetic: "/ˈbedruːm/", meaning: "n. 卧室", example: "My bedroom is very clean." },
    { word: "beef", syllables: ["beef"], phonetic: "/biːf/", meaning: "n. 牛肉", example: "I had beef for lunch." },
    { word: "before", syllables: ["be","fore"], phonetic: "/bɪˈfɔːr/", meaning: "prep./conj. 在……之前", example: "Wash your hands before eating." },
    { word: "begin", syllables: ["be","gin"], phonetic: "/bɪˈɡɪn/", meaning: "v. 开始", example: "The class begins at eight." },
    { word: "behind", syllables: ["be","hind"], phonetic: "/bɪˈhaɪnd/", meaning: "prep./adv. 在……后面", example: "The park is behind the school." },
    { word: "believe", syllables: ["be","lieve"], phonetic: "/bɪˈliːv/", meaning: "v. 相信", example: "I believe you can do it." }
  ],
  "第3组": [
    { word: "bell", syllables: ["bell"], phonetic: "/bel/", meaning: "n. 钟；铃", example: "The bell is ringing." },
    { word: "below", syllables: ["be","low"], phonetic: "/bɪˈloʊ/", meaning: "prep./adv. 在……下面", example: "The temperature is below zero." },
    { word: "beside", syllables: ["be","side"], phonetic: "/bɪˈsaɪd/", meaning: "prep. 在……旁边", example: "Come and sit beside me." },
    { word: "besides", syllables: ["be","sides"], phonetic: "/bɪˈsaɪdz/", meaning: "prep./adv. 除了；此外", example: "Besides English, I study math." },
    { word: "best", syllables: ["best"], phonetic: "/best/", meaning: "adj./adv. 最好的", example: "She is my best friend." },
    { word: "better", syllables: ["bet","ter"], phonetic: "/ˈbetər/", meaning: "adj./adv. 更好的", example: "This one is better than that one." },
    { word: "between", syllables: ["be","tween"], phonetic: "/bɪˈtwiːn/", meaning: "prep. 在……之间", example: "Sit between Tom and me." },
    { word: "big", syllables: ["big"], phonetic: "/bɪɡ/", meaning: "adj. 大的", example: "This is a big house." },
    { word: "bike", syllables: ["bike"], phonetic: "/baɪk/", meaning: "n. 自行车", example: "I ride my bike to school." },
    { word: "bill", syllables: ["bill"], phonetic: "/bɪl/", meaning: "n. 账单", example: "Let me pay the bill." },
    { word: "bird", syllables: ["bird"], phonetic: "/bɜːrd/", meaning: "n. 鸟", example: "The bird is singing in the tree." },
    { word: "birthday", syllables: ["birth","day"], phonetic: "/ˈbɜːrθdeɪ/", meaning: "n. 生日", example: "Happy birthday to you!" },
    { word: "biscuit", syllables: ["bis","cuit"], phonetic: "/ˈbɪskɪt/", meaning: "n. 饼干", example: "Would you like a biscuit?" },
    { word: "bit", syllables: ["bit"], phonetic: "/bɪt/", meaning: "n. 一小块；一点", example: "I am a bit tired." },
    { word: "bite", syllables: ["bite"], phonetic: "/baɪt/", meaning: "v./n. 咬", example: "The dog tried to bite me." },
    { word: "black", syllables: ["black"], phonetic: "/blæk/", meaning: "adj./n. 黑色的；黑色", example: "She wears a black dress." },
    { word: "blind", syllables: ["blind"], phonetic: "/blaɪnd/", meaning: "adj. 瞎的；盲的", example: "The old man is blind." },
    { word: "block", syllables: ["block"], phonetic: "/blɑːk/", meaning: "n./v. 街区；阻挡", example: "The school is two blocks away." },
    { word: "blood", syllables: ["blood"], phonetic: "/blʌd/", meaning: "n. 血", example: "He gave blood to help others." },
    { word: "blow", syllables: ["blow"], phonetic: "/bloʊ/", meaning: "v. 吹", example: "The wind began to blow." },
    { word: "blue", syllables: ["blue"], phonetic: "/bluː/", meaning: "adj./n. 蓝色的；蓝色", example: "The sky is blue today." },
    { word: "board", syllables: ["board"], phonetic: "/bɔːrd/", meaning: "n. 板；董事会", example: "Please write on the blackboard." },
    { word: "boat", syllables: ["boat"], phonetic: "/boʊt/", meaning: "n. 船", example: "We went across the river by boat." },
    { word: "body", syllables: ["bo","dy"], phonetic: "/ˈbɑːdi/", meaning: "n. 身体", example: "Exercise is good for your body." },
    { word: "bone", syllables: ["bone"], phonetic: "/boʊn/", meaning: "n. 骨头", example: "The dog is chewing a bone." },
    { word: "book", syllables: ["book"], phonetic: "/bʊk/", meaning: "n. 书", example: "I am reading a book." },
    { word: "boring", syllables: ["bor","ing"], phonetic: "/ˈbɔːrɪŋ/", meaning: "adj. 无聊的", example: "The movie was boring." },
    { word: "born", syllables: ["born"], phonetic: "/bɔːrn/", meaning: "adj. 出生的", example: "I was born in Beijing." },
    { word: "borrow", syllables: ["bor","row"], phonetic: "/ˈbɑːroʊ/", meaning: "v. 借入", example: "Can I borrow your pen?" },
    { word: "both", syllables: ["both"], phonetic: "/boʊθ/", meaning: "adj./pron. 两个都", example: "Both of them are students." },
    { word: "bottle", syllables: ["bot","tle"], phonetic: "/ˈbɑːtl/", meaning: "n. 瓶子", example: "Please buy a bottle of water." },
    { word: "bottom", syllables: ["bot","tom"], phonetic: "/ˈbɑːtəm/", meaning: "n. 底部", example: "The cat is at the bottom of the stairs." },
    { word: "bowl", syllables: ["bowl"], phonetic: "/boʊl/", meaning: "n. 碗", example: "I had a bowl of rice for lunch." },
    { word: "box", syllables: ["box"], phonetic: "/bɑːks/", meaning: "n. 盒子；箱子", example: "The box is very heavy." },
    { word: "boy", syllables: ["boy"], phonetic: "/bɔɪ/", meaning: "n. 男孩", example: "The boy is playing soccer." },
    { word: "brain", syllables: ["brain"], phonetic: "/breɪn/", meaning: "n. 大脑", example: "Use your brain to think." },
    { word: "brave", syllables: ["brave"], phonetic: "/breɪv/", meaning: "adj. 勇敢的", example: "The soldier was very brave." },
    { word: "bread", syllables: ["bread"], phonetic: "/bred/", meaning: "n. 面包", example: "I had bread for breakfast." },
    { word: "break", syllables: ["break"], phonetic: "/breɪk/", meaning: "v./n. 打破；休息", example: "Don't break the window." },
    { word: "breakfast", syllables: ["break","fast"], phonetic: "/ˈbrekfəst/", meaning: "n. 早餐", example: "I have breakfast at seven." },
    { word: "breath", syllables: ["breath"], phonetic: "/breθ/", meaning: "n. 呼吸", example: "Take a deep breath." },
    { word: "breathe", syllables: ["breathe"], phonetic: "/briːð/", meaning: "v. 呼吸", example: "It is hard to breathe in the smoke." },
    { word: "bridge", syllables: ["bridge"], phonetic: "/brɪdʒ/", meaning: "n. 桥", example: "We walked across the bridge." },
    { word: "bright", syllables: ["bright"], phonetic: "/braɪt/", meaning: "adj. 明亮的；聪明的", example: "The room is very bright." },
    { word: "bring", syllables: ["bring"], phonetic: "/brɪŋ/", meaning: "v. 带来", example: "Please bring your book tomorrow." },
    { word: "broad", syllables: ["broad"], phonetic: "/brɔːd/", meaning: "adj. 宽的；广阔的", example: "The river is very broad here." },
    { word: "broken", syllables: ["bro","ken"], phonetic: "/ˈbroʊkən/", meaning: "adj. 破碎的", example: "The window is broken." },
    { word: "brother", syllables: ["bro","ther"], phonetic: "/ˈbrʌðər/", meaning: "n. 兄弟", example: "My brother is older than me." },
    { word: "brown", syllables: ["brown"], phonetic: "/braʊn/", meaning: "adj./n. 棕色的；棕色", example: "He has brown hair." },
    { word: "brush", syllables: ["brush"], phonetic: "/brʌʃ/", meaning: "n./v. 刷子；刷", example: "Brush your teeth every day." }
  ],
  "第4组": [
    { word: "build", syllables: ["build"], phonetic: "/bɪld/", meaning: "v. 建造", example: "They plan to build a new school." },
    { word: "building", syllables: ["buil","ding"], phonetic: "/ˈbɪldɪŋ/", meaning: "n. 建筑物", example: "That building is very tall." },
    { word: "burn", syllables: ["burn"], phonetic: "/bɜːrn/", meaning: "v. 燃烧；烧", example: "Be careful not to burn yourself." },
    { word: "bus", syllables: ["bus"], phonetic: "/bʌs/", meaning: "n. 公共汽车", example: "I go to school by bus." },
    { word: "business", syllables: ["busi","ness"], phonetic: "/ˈbɪznəs/", meaning: "n. 商业；生意", example: "He runs his own business." },
    { word: "busy", syllables: ["bu","sy"], phonetic: "/ˈbɪzi/", meaning: "adj. 忙碌的", example: "I am busy with my homework." },
    { word: "but", syllables: ["but"], phonetic: "/bʌt/", meaning: "conj. 但是", example: "I like it but it is too expensive." },
    { word: "butter", syllables: ["but","ter"], phonetic: "/ˈbʌtər/", meaning: "n. 黄油", example: "She spread butter on the bread." },
    { word: "butterfly", syllables: ["but","ter","fly"], phonetic: "/ˈbʌtərflaɪ/", meaning: "n. 蝴蝶", example: "A beautiful butterfly flew by." },
    { word: "buy", syllables: ["buy"], phonetic: "/baɪ/", meaning: "v. 买", example: "I want to buy a new book." },
    { word: "by", syllables: ["by"], phonetic: "/baɪ/", meaning: "prep. 通过；被；在……旁", example: "I go to school by bus." },
    { word: "cabbage", syllables: ["cab","bage"], phonetic: "/ˈkæbɪdʒ/", meaning: "n. 卷心菜", example: "My mother cooked cabbage for dinner." },
    { word: "cake", syllables: ["cake"], phonetic: "/keɪk/", meaning: "n. 蛋糕", example: "She made a birthday cake." },
    { word: "call", syllables: ["call"], phonetic: "/kɔːl/", meaning: "v./n. 打电话；叫", example: "Please call me later." },
    { word: "calm", syllables: ["calm"], phonetic: "/kɑːm/", meaning: "adj./v. 平静的；使平静", example: "Please stay calm." },
    { word: "came", syllables: ["came"], phonetic: "/keɪm/", meaning: "v. 来（come的过去式）", example: "She came to school early." },
    { word: "camera", syllables: ["cam","er","a"], phonetic: "/ˈkæmərə/", meaning: "n. 照相机", example: "I forgot to bring my camera." },
    { word: "camp", syllables: ["camp"], phonetic: "/kæmp/", meaning: "n./v. 营地；露营", example: "We went camping last summer." },
    { word: "can", syllables: ["can"], phonetic: "/kæn/", meaning: "v. 能；会", example: "I can speak English." },
    { word: "cancel", syllables: ["can","cel"], phonetic: "/ˈkænsl/", meaning: "v. 取消", example: "We had to cancel the picnic." },
    { word: "candle", syllables: ["can","dle"], phonetic: "/ˈkændl/", meaning: "n. 蜡烛", example: "She blew out the candles." },
    { word: "cap", syllables: ["cap"], phonetic: "/kæp/", meaning: "n. 帽子", example: "He wore a baseball cap." },
    { word: "capital", syllables: ["cap","i","tal"], phonetic: "/ˈkæpɪtl/", meaning: "n. 首都；资本", example: "Beijing is the capital of China." },
    { word: "captain", syllables: ["cap","tain"], phonetic: "/ˈkæptɪn/", meaning: "n. 队长；船长", example: "He is the captain of the team." },
    { word: "car", syllables: ["car"], phonetic: "/kɑːr/", meaning: "n. 汽车", example: "My father has a new car." },
    { word: "card", syllables: ["card"], phonetic: "/kɑːrd/", meaning: "n. 卡片；纸牌", example: "I sent her a birthday card." },
    { word: "care", syllables: ["care"], phonetic: "/ker/", meaning: "v./n. 关心；照顾", example: "She cares about the environment." },
    { word: "careful", syllables: ["care","ful"], phonetic: "/ˈkerfl/", meaning: "adj. 小心的；仔细的", example: "Be careful when you cross the road." },
    { word: "careless", syllables: ["care","less"], phonetic: "/ˈkerləs/", meaning: "adj. 粗心的", example: "He made a careless mistake." },
    { word: "carry", syllables: ["car","ry"], phonetic: "/ˈkæri/", meaning: "v. 携带；搬运", example: "Let me carry the bag for you." },
    { word: "case", syllables: ["case"], phonetic: "/keɪs/", meaning: "n. 情况；箱子", example: "In that case, I will go." },
    { word: "cash", syllables: ["cash"], phonetic: "/kæʃ/", meaning: "n. 现金", example: "I don't have enough cash." },
    { word: "cat", syllables: ["cat"], phonetic: "/kæt/", meaning: "n. 猫", example: "The cat is sleeping on the sofa." },
    { word: "catch", syllables: ["catch"], phonetic: "/kætʃ/", meaning: "v. 接住；赶上", example: "Can you catch the ball?" },
    { word: "celebrate", syllables: ["cel","e","brate"], phonetic: "/ˈselɪbreɪt/", meaning: "v. 庆祝", example: "We celebrate Spring Festival together." },
    { word: "center", syllables: ["cen","ter"], phonetic: "/ˈsentər/", meaning: "n. 中心", example: "The park is in the center of the city." },
    { word: "central", syllables: ["cen","tral"], phonetic: "/ˈsentrəl/", meaning: "adj. 中心的；中央的", example: "The school is in a central location." },
    { word: "century", syllables: ["cen","tu","ry"], phonetic: "/ˈsentʃəri/", meaning: "n. 世纪；百年", example: "This building is from the last century." },
    { word: "certain", syllables: ["cer","tain"], phonetic: "/ˈsɜːrtn/", meaning: "adj. 确定的；某些", example: "I am certain he will come." },
    { word: "chair", syllables: ["chair"], phonetic: "/tʃer/", meaning: "n. 椅子", example: "Please take a chair." },
    { word: "chairman", syllables: ["chair","man"], phonetic: "/ˈtʃermən/", meaning: "n. 主席；会长", example: "He is the chairman of the club." },
    { word: "chance", syllables: ["chance"], phonetic: "/tʃæns/", meaning: "n. 机会", example: "This is a good chance to learn." },
    { word: "change", syllables: ["change"], phonetic: "/tʃeɪndʒ/", meaning: "v./n. 改变；变化", example: "The weather can change quickly." },
    { word: "channel", syllables: ["chan","nel"], phonetic: "/ˈtʃænl/", meaning: "n. 频道；渠道", example: "Please turn to Channel 5." },
    { word: "cheap", syllables: ["cheap"], phonetic: "/tʃiːp/", meaning: "adj. 便宜的", example: "This shirt is very cheap." },
    { word: "cheat", syllables: ["cheat"], phonetic: "/tʃiːt/", meaning: "v. 欺骗；作弊", example: "Never cheat in exams." },
    { word: "check", syllables: ["check"], phonetic: "/tʃek/", meaning: "v./n. 检查", example: "Please check your answers." },
    { word: "cheer", syllables: ["cheer"], phonetic: "/tʃɪr/", meaning: "v./n. 欢呼；喝彩", example: "The crowd began to cheer." },
    { word: "cheese", syllables: ["cheese"], phonetic: "/tʃiːz/", meaning: "n. 奶酪", example: "Do you like cheese?" },
    { word: "chicken", syllables: ["chick","en"], phonetic: "/ˈtʃɪkɪn/", meaning: "n. 鸡；鸡肉", example: "I like fried chicken." }
  ],
  "第5组": [
    { word: "child", syllables: ["child"], phonetic: "/tʃaɪld/", meaning: "n. 孩子", example: "The child is playing in the park." },
    { word: "China", syllables: ["Chi","na"], phonetic: "/ˈtʃaɪnə/", meaning: "n. 中国", example: "China is a great country." },
    { word: "Chinese", syllables: ["Chi","nese"], phonetic: "/tʃaɪˈniːz/", meaning: "adj./n. 中国的；中国人；中文", example: "I am learning Chinese." },
    { word: "chocolate", syllables: ["choc","o","late"], phonetic: "/ˈtʃɑːklət/", meaning: "n. 巧克力", example: "She loves chocolate." },
    { word: "choice", syllables: ["choice"], phonetic: "/tʃɔɪs/", meaning: "n. 选择", example: "You have to make a choice." },
    { word: "choose", syllables: ["choose"], phonetic: "/tʃuːz/", meaning: "v. 选择", example: "Please choose one from these." },
    { word: "church", syllables: ["church"], phonetic: "/tʃɜːrtʃ/", meaning: "n. 教堂", example: "The old church is very beautiful." },
    { word: "cinema", syllables: ["cin","e","ma"], phonetic: "/ˈsɪnəmə/", meaning: "n. 电影院", example: "Let's go to the cinema tonight." },
    { word: "circle", syllables: ["cir","cle"], phonetic: "/ˈsɜːrkl/", meaning: "n./v. 圆；圈出", example: "Please draw a circle." },
    { word: "citizen", syllables: ["cit","i","zen"], phonetic: "/ˈsɪtɪzn/", meaning: "n. 公民；市民", example: "She is a citizen of China." },
    { word: "city", syllables: ["cit","y"], phonetic: "/ˈsɪti/", meaning: "n. 城市", example: "Beijing is a big city." },
    { word: "class", syllables: ["class"], phonetic: "/klæs/", meaning: "n. 班级；课", example: "We have English class today." },
    { word: "classmate", syllables: ["class","mate"], phonetic: "/ˈklæsmeɪt/", meaning: "n. 同学", example: "She is my classmate." },
    { word: "classroom", syllables: ["class","room"], phonetic: "/ˈklæsruːm/", meaning: "n. 教室", example: "The classroom is very clean." },
    { word: "clean", syllables: ["clean"], phonetic: "/kliːn/", meaning: "adj./v. 干净的；打扫", example: "Please clean the room." },
    { word: "clear", syllables: ["clear"], phonetic: "/klɪr/", meaning: "adj. 清楚的；晴朗的", example: "The water is very clear." },
    { word: "clever", syllables: ["clev","er"], phonetic: "/ˈklevər/", meaning: "adj. 聪明的", example: "The boy is very clever." },
    { word: "click", syllables: ["click"], phonetic: "/klɪk/", meaning: "v./n. 点击", example: "Click the button to start." },
    { word: "climb", syllables: ["climb"], phonetic: "/klaɪm/", meaning: "v. 攀爬", example: "We climbed the mountain yesterday." },
    { word: "clock", syllables: ["clock"], phonetic: "/klɑːk/", meaning: "n. 钟", example: "The clock says it is ten." },
    { word: "close", syllables: ["close"], phonetic: "/kloʊz/", meaning: "v./adj. 关闭；近的", example: "Please close the door." },
    { word: "cloth", syllables: ["cloth"], phonetic: "/klɔːθ/", meaning: "n. 布；布料", example: "She bought some cloth to make a dress." },
    { word: "clothes", syllables: ["clothes"], phonetic: "/kloʊðz/", meaning: "n. 衣服", example: "Put on more clothes. It is cold." },
    { word: "cloud", syllables: ["cloud"], phonetic: "/klaʊd/", meaning: "n. 云", example: "There are many clouds in the sky." },
    { word: "cloudy", syllables: ["clou","dy"], phonetic: "/ˈklaʊdi/", meaning: "adj. 多云的", example: "It is cloudy today." },
    { word: "club", syllables: ["club"], phonetic: "/klʌb/", meaning: "n. 俱乐部", example: "I joined the English club." },
    { word: "coach", syllables: ["coach"], phonetic: "/koʊtʃ/", meaning: "n. 教练", example: "Our coach is very strict." },
    { word: "coast", syllables: ["coast"], phonetic: "/koʊst/", meaning: "n. 海岸", example: "We walked along the coast." },
    { word: "coat", syllables: ["coat"], phonetic: "/koʊt/", meaning: "n. 外套", example: "Put on your coat. It is cold outside." },
    { word: "coffee", syllables: ["cof","fee"], phonetic: "/ˈkɔːfi/", meaning: "n. 咖啡", example: "Would you like a cup of coffee?" },
    { word: "coin", syllables: ["coin"], phonetic: "/kɔɪn/", meaning: "n. 硬币", example: "He found a coin on the ground." },
    { word: "cold", syllables: ["cold"], phonetic: "/koʊld/", meaning: "adj./n. 冷的；感冒", example: "It is very cold in winter." },
    { word: "collect", syllables: ["col","lect"], phonetic: "/kəˈlekt/", meaning: "v. 收集", example: "He likes to collect stamps." },
    { word: "college", syllables: ["col","lege"], phonetic: "/ˈkɑːlɪdʒ/", meaning: "n. 学院；大学", example: "She goes to a medical college." },
    { word: "color", syllables: ["co","lor"], phonetic: "/ˈkʌlər/", meaning: "n. 颜色", example: "What is your favorite color?" },
    { word: "come", syllables: ["come"], phonetic: "/kʌm/", meaning: "v. 来", example: "Please come here." },
    { word: "comfortable", syllables: ["com","for","ta","ble"], phonetic: "/ˈkʌmftəbl/", meaning: "adj. 舒适的", example: "This sofa is very comfortable." },
    { word: "common", syllables: ["com","mon"], phonetic: "/ˈkɑːmən/", meaning: "adj. 普通的；常见的", example: "This is a very common mistake." },
    { word: "communicate", syllables: ["com","mu","ni","cate"], phonetic: "/kəˈmjuːnɪkeɪt/", meaning: "v. 交流；沟通", example: "We communicate by email." },
    { word: "community", syllables: ["com","mu","ni","ty"], phonetic: "/kəˈmjuːnəti/", meaning: "n. 社区", example: "Our community is very friendly." },
    { word: "company", syllables: ["com","pa","ny"], phonetic: "/ˈkʌmpəni/", meaning: "n. 公司", example: "She works for a big company." },
    { word: "compare", syllables: ["com","pare"], phonetic: "/kəmˈper/", meaning: "v. 比较", example: "Compare the two pictures." },
    { word: "competition", syllables: ["com","pe","ti","tion"], phonetic: "/ˌkɑːmpəˈtɪʃn/", meaning: "n. 比赛；竞争", example: "He won first prize in the competition." },
    { word: "complete", syllables: ["com","plete"], phonetic: "/kəmˈpliːt/", meaning: "v./adj. 完成；完整的", example: "Please complete the form." },
    { word: "computer", syllables: ["com","pu","ter"], phonetic: "/kəmˈpjuːtər/", meaning: "n. 计算机", example: "I use a computer to study." },
    { word: "concert", syllables: ["con","cert"], phonetic: "/ˈkɑːnsərt/", meaning: "n. 音乐会", example: "We went to a concert last night." },
    { word: "condition", syllables: ["con","di","tion"], phonetic: "/kənˈdɪʃn/", meaning: "n. 条件；状况", example: "The road is in good condition." },
    { word: "conference", syllables: ["con","fer","ence"], phonetic: "/ˈkɑːnfərəns/", meaning: "n. 会议", example: "She attended a conference in Shanghai." },
    { word: "connect", syllables: ["con","nect"], phonetic: "/kəˈnekt/", meaning: "v. 连接", example: "Please connect to the internet." },
    { word: "consider", syllables: ["con","si","der"], phonetic: "/kənˈsɪdər/", meaning: "v. 考虑", example: "Please consider my suggestion." }
  ],
  "第6组": [
    { word: "contact", syllables: ["con","tact"], phonetic: "/ˈkɑːntækt/", meaning: "n./v. 联系", example: "Keep in contact with your friends." },
    { word: "continue", syllables: ["con","tin","ue"], phonetic: "/kənˈtɪnjuː/", meaning: "v. 继续", example: "Please continue reading." },
    { word: "control", syllables: ["con","trol"], phonetic: "/kənˈtroʊl/", meaning: "v./n. 控制", example: "Try to control your temper." },
    { word: "conversation", syllables: ["con","ver","sa","tion"], phonetic: "/ˌkɑːnvərˈseɪʃn/", meaning: "n. 对话；会话", example: "I had a long conversation with her." },
    { word: "cook", syllables: ["cook"], phonetic: "/kʊk/", meaning: "v./n. 烹饪；厨师", example: "My mother cooks delicious food." },
    { word: "cool", syllables: ["cool"], phonetic: "/kuːl/", meaning: "adj. 凉爽的；酷的", example: "It is cool in autumn." },
    { word: "copy", syllables: ["co","py"], phonetic: "/ˈkɑːpi/", meaning: "n./v. 复制；抄写", example: "Please copy this text." },
    { word: "corner", syllables: ["cor","ner"], phonetic: "/ˈkɔːrnər/", meaning: "n. 角落；拐角", example: "The store is on the corner." },
    { word: "correct", syllables: ["cor","rect"], phonetic: "/kəˈrekt/", meaning: "adj./v. 正确的；纠正", example: "Is this answer correct?" },
    { word: "cost", syllables: ["cost"], phonetic: "/kɔːst/", meaning: "v./n. 花费；成本", example: "How much does it cost?" },
    { word: "cotton", syllables: ["cot","ton"], phonetic: "/ˈkɑːtn/", meaning: "n. 棉花", example: "This shirt is made of cotton." },
    { word: "could", syllables: ["could"], phonetic: "/kʊd/", meaning: "v. 能（can的过去式）", example: "Could you help me, please?" },
    { word: "count", syllables: ["count"], phonetic: "/kaʊnt/", meaning: "v. 数；计算", example: "Can you count from one to ten?" },
    { word: "country", syllables: ["coun","try"], phonetic: "/ˈkʌntri/", meaning: "n. 国家；农村", example: "China is a large country." },
    { word: "countryside", syllables: ["coun","try","side"], phonetic: "/ˈkʌntrisaɪd/", meaning: "n. 乡下；农村", example: "I love the fresh air in the countryside." },
    { word: "couple", syllables: ["cou","ple"], phonetic: "/ˈkʌpl/", meaning: "n. 一对；夫妇", example: "The couple got married last year." },
    { word: "courage", syllables: ["cour","age"], phonetic: "/ˈkɜːrɪdʒ/", meaning: "n. 勇气", example: "She showed great courage." },
    { word: "course", syllables: ["course"], phonetic: "/kɔːrs/", meaning: "n. 课程；过程", example: "Of course I will help you." },
    { word: "cousin", syllables: ["cou","sin"], phonetic: "/ˈkʌzn/", meaning: "n. 表（堂）兄弟姐妹", example: "My cousin lives in Shanghai." },
    { word: "cover", syllables: ["cov","er"], phonetic: "/ˈkʌvər/", meaning: "v./n. 覆盖；封面", example: "Please cover the table with a cloth." },
    { word: "cow", syllables: ["cow"], phonetic: "/kaʊ/", meaning: "n. 奶牛", example: "The cow gives us milk." },
    { word: "crazy", syllables: ["cra","zy"], phonetic: "/ˈkreɪzi/", meaning: "adj. 疯狂的；着迷的", example: "She is crazy about music." },
    { word: "cream", syllables: ["cream"], phonetic: "/kriːm/", meaning: "n. 奶油；霜", example: "I like ice cream very much." },
    { word: "create", syllables: ["cre","ate"], phonetic: "/kriˈeɪt/", meaning: "v. 创造；创建", example: "He created a beautiful painting." },
    { word: "cross", syllables: ["cross"], phonetic: "/krɔːs/", meaning: "v./n. 穿过；十字", example: "Look both ways before you cross the road." },
    { word: "crowd", syllables: ["crowd"], phonetic: "/kraʊd/", meaning: "n. 人群", example: "There was a big crowd at the concert." },
    { word: "crowded", syllables: ["crow","ded"], phonetic: "/ˈkraʊdɪd/", meaning: "adj. 拥挤的", example: "The bus was very crowded." },
    { word: "cruel", syllables: ["cru","el"], phonetic: "/ˈkruːəl/", meaning: "adj. 残忍的", example: "It is cruel to hurt animals." },
    { word: "cry", syllables: ["cry"], phonetic: "/kraɪ/", meaning: "v./n. 哭；叫喊", example: "The baby began to cry." },
    { word: "culture", syllables: ["cul","ture"], phonetic: "/ˈkʌltʃər/", meaning: "n. 文化", example: "Chinese culture is very rich." },
    { word: "cup", syllables: ["cup"], phonetic: "/kʌp/", meaning: "n. 杯子", example: "Would you like a cup of tea?" },
    { word: "customer", syllables: ["cus","to","mer"], phonetic: "/ˈkʌstəmər/", meaning: "n. 顾客", example: "The customer is always right." },
    { word: "cut", syllables: ["cut"], phonetic: "/kʌt/", meaning: "v. 切；剪", example: "Please cut the cake into pieces." },
    { word: "cycle", syllables: ["cy","cle"], phonetic: "/ˈsaɪkl/", meaning: "n./v. 循环；骑自行车", example: "I cycle to school every day." },
    { word: "dad", syllables: ["dad"], phonetic: "/dæd/", meaning: "n. 爸爸", example: "My dad is a teacher." },
    { word: "daily", syllables: ["dai","ly"], phonetic: "/ˈdeɪli/", meaning: "adj./adv. 每日的", example: "Exercise should be a daily habit." },
    { word: "dance", syllables: ["dance"], phonetic: "/dæns/", meaning: "v./n. 跳舞", example: "She loves to dance." },
    { word: "danger", syllables: ["dan","ger"], phonetic: "/ˈdeɪndʒər/", meaning: "n. 危险", example: "The children are in danger." },
    { word: "dangerous", syllables: ["dan","ger","ous"], phonetic: "/ˈdeɪndʒərəs/", meaning: "adj. 危险的", example: "It is dangerous to swim here." },
    { word: "dare", syllables: ["dare"], phonetic: "/der/", meaning: "v. 敢；敢于", example: "I dare not jump from here." },
    { word: "dark", syllables: ["dark"], phonetic: "/dɑːrk/", meaning: "adj. 黑暗的；深色的", example: "It is getting dark outside." },
    { word: "date", syllables: ["date"], phonetic: "/deɪt/", meaning: "n. 日期；约会", example: "What is the date today?" },
    { word: "daughter", syllables: ["daugh","ter"], phonetic: "/ˈdɔːtər/", meaning: "n. 女儿", example: "She has a lovely daughter." },
    { word: "day", syllables: ["day"], phonetic: "/deɪ/", meaning: "n. 天；白天", example: "What a beautiful day!" },
    { word: "dead", syllables: ["dead"], phonetic: "/ded/", meaning: "adj. 死的", example: "The flowers are dead." },
    { word: "deaf", syllables: ["deaf"], phonetic: "/def/", meaning: "adj. 聋的", example: "The old man is deaf in one ear." },
    { word: "deal", syllables: ["deal"], phonetic: "/diːl/", meaning: "v./n. 处理；交易", example: "How do you deal with this problem?" },
    { word: "dear", syllables: ["dear"], phonetic: "/dɪr/", meaning: "adj. 亲爱的", example: "Dear Mom, I miss you." },
    { word: "death", syllables: ["death"], phonetic: "/deθ/", meaning: "n. 死亡", example: "The death of his dog made him sad." },
    { word: "December", syllables: ["De","cem","ber"], phonetic: "/dɪˈsembər/", meaning: "n. 十二月", example: "Christmas is in December." }
  ],
  "第7组": [
    { word: "decide", syllables: ["de","cide"], phonetic: "/dɪˈsaɪd/", meaning: "v. 决定", example: "I decided to study abroad." },
    { word: "decision", syllables: ["de","ci","sion"], phonetic: "/dɪˈsɪʒn/", meaning: "n. 决定", example: "She made the right decision." },
    { word: "deep", syllables: ["deep"], phonetic: "/diːp/", meaning: "adj./adv. 深的", example: "The river is very deep here." },
    { word: "deer", syllables: ["deer"], phonetic: "/dɪr/", meaning: "n. 鹿", example: "We saw a deer in the forest." },
    { word: "defeat", syllables: ["de","feat"], phonetic: "/dɪˈfiːt/", meaning: "v./n. 打败；击败", example: "We defeated the other team." },
    { word: "degree", syllables: ["de","gree"], phonetic: "/dɪˈɡriː/", meaning: "n. 度；学位", example: "She has a master's degree." },
    { word: "delicious", syllables: ["de","li","cious"], phonetic: "/dɪˈlɪʃəs/", meaning: "adj. 美味的", example: "The food smells delicious." },
    { word: "delight", syllables: ["de","light"], phonetic: "/dɪˈlaɪt/", meaning: "n./v. 高兴；使高兴", example: "The news filled us with delight." },
    { word: "deliver", syllables: ["de","liv","er"], phonetic: "/dɪˈlɪvər/", meaning: "v. 递送；发表", example: "The postman delivers letters every day." },
    { word: "demand", syllables: ["de","mand"], phonetic: "/dɪˈmænd/", meaning: "v./n. 要求；需求", example: "The demand for water is increasing." },
    { word: "dentist", syllables: ["den","tist"], phonetic: "/ˈdentɪst/", meaning: "n. 牙医", example: "I need to see the dentist." },
    { word: "depend", syllables: ["de","pend"], phonetic: "/dɪˈpend/", meaning: "v. 依赖；取决于", example: "It depends on the weather." },
    { word: "describe", syllables: ["de","scribe"], phonetic: "/dɪˈskraɪb/", meaning: "v. 描述", example: "Can you describe the person?" },
    { word: "desert", syllables: ["des","ert"], phonetic: "/ˈdezərt/", meaning: "n. 沙漠", example: "The Sahara is the largest desert." },
    { word: "design", syllables: ["de","sign"], phonetic: "/dɪˈzaɪn/", meaning: "v./n. 设计", example: "She designed a beautiful dress." },
    { word: "desire", syllables: ["de","sire"], phonetic: "/dɪˈzaɪər/", meaning: "n./v. 渴望", example: "He has a strong desire to succeed." },
    { word: "desk", syllables: ["desk"], phonetic: "/desk/", meaning: "n. 书桌", example: "There is a book on the desk." },
    { word: "develop", syllables: ["de","vel","op"], phonetic: "/dɪˈveləp/", meaning: "v. 发展；开发", example: "The city is developing fast." },
    { word: "development", syllables: ["de","vel","op","ment"], phonetic: "/dɪˈveləpmənt/", meaning: "n. 发展", example: "Economic development is very important." },
    { word: "dictionary", syllables: ["dic","tion","ar","y"], phonetic: "/ˈdɪkʃəneri/", meaning: "n. 字典", example: "Look it up in the dictionary." },
    { word: "die", syllables: ["die"], phonetic: "/daɪ/", meaning: "v. 死", example: "Plants die without water." },
    { word: "difference", syllables: ["dif","fer","ence"], phonetic: "/ˈdɪfrəns/", meaning: "n. 不同；差异", example: "Can you tell the difference?" },
    { word: "different", syllables: ["dif","fer","ent"], phonetic: "/ˈdɪfrənt/", meaning: "adj. 不同的", example: "We have different opinions." },
    { word: "difficult", syllables: ["dif","fi","cult"], phonetic: "/ˈdɪfɪkʌlt/", meaning: "adj. 困难的", example: "This question is very difficult." },
    { word: "difficulty", syllables: ["dif","fi","cul","ty"], phonetic: "/ˈdɪfɪkʌlti/", meaning: "n. 困难", example: "He had difficulty finding the place." },
    { word: "dig", syllables: ["dig"], phonetic: "/dɪɡ/", meaning: "v. 挖", example: "They are digging a hole." },
    { word: "dinner", syllables: ["din","ner"], phonetic: "/ˈdɪnər/", meaning: "n. 正餐；晚餐", example: "What time is dinner?" },
    { word: "direct", syllables: ["di","rect"], phonetic: "/dɪˈrekt/", meaning: "adj./v. 直接的；指导", example: "What is the direct way to the station?" },
    { word: "direction", syllables: ["di","rec","tion"], phonetic: "/dɪˈrekʃn/", meaning: "n. 方向", example: "Which direction is the school?" },
    { word: "director", syllables: ["di","rec","tor"], phonetic: "/dɪˈrektər/", meaning: "n. 导演；主任", example: "He is the director of the movie." },
    { word: "dirty", syllables: ["dir","ty"], phonetic: "/ˈdɜːrti/", meaning: "adj. 脏的", example: "Your hands are dirty." },
    { word: "disappoint", syllables: ["dis","ap","point"], phonetic: "/ˌdɪsəˈpɔɪnt/", meaning: "v. 使失望", example: "Don't disappoint your parents." },
    { word: "discover", syllables: ["dis","cov","er"], phonetic: "/dɪˈskʌvər/", meaning: "v. 发现", example: "Columbus discovered America." },
    { word: "discovery", syllables: ["dis","cov","er","y"], phonetic: "/dɪˈskʌvəri/", meaning: "n. 发现", example: "It was a great discovery." },
    { word: "discuss", syllables: ["dis","cuss"], phonetic: "/dɪˈskʌs/", meaning: "v. 讨论", example: "Let's discuss this problem." },
    { word: "discussion", syllables: ["dis","cus","sion"], phonetic: "/dɪˈskʌʃn/", meaning: "n. 讨论", example: "We had a long discussion." },
    { word: "disease", syllables: ["dis","ease"], phonetic: "/dɪˈziːz/", meaning: "n. 疾病", example: "The disease spread quickly." },
    { word: "dish", syllables: ["dish"], phonetic: "/dɪʃ/", meaning: "n. 盘子；菜肴", example: "She cooked a delicious dish." },
    { word: "dismiss", syllables: ["dis","miss"], phonetic: "/dɪsˈmɪs/", meaning: "v. 解散；解雇", example: "The teacher dismissed the class." },
    { word: "display", syllables: ["dis","play"], phonetic: "/dɪˈspleɪ/", meaning: "v./n. 展示；展览", example: "The store displays new products." },
    { word: "distance", syllables: ["dis","tance"], phonetic: "/ˈdɪstəns/", meaning: "n. 距离", example: "The school is a short distance away." },
    { word: "disturb", syllables: ["dis","turb"], phonetic: "/dɪˈstɜːrb/", meaning: "v. 打扰", example: "Please don't disturb me." },
    { word: "divide", syllables: ["di","vide"], phonetic: "/dɪˈvaɪd/", meaning: "v. 分；划分", example: "Divide the cake into four pieces." },
    { word: "do", syllables: ["do"], phonetic: "/duː/", meaning: "v. 做", example: "What do you want to do?" },
    { word: "doctor", syllables: ["doc","tor"], phonetic: "/ˈdɑːktər/", meaning: "n. 医生", example: "You should see a doctor." },
    { word: "dog", syllables: ["dog"], phonetic: "/dɔːɡ/", meaning: "n. 狗", example: "The dog is man's best friend." },
    { word: "dollar", syllables: ["dol","lar"], phonetic: "/ˈdɑːlər/", meaning: "n. 美元", example: "The book costs ten dollars." },
    { word: "door", syllables: ["door"], phonetic: "/dɔːr/", meaning: "n. 门", example: "Please open the door." },
    { word: "double", syllables: ["dou","ble"], phonetic: "/ˈdʌbl/", meaning: "adj./v. 双倍的；加倍", example: "I want a double room." },
    { word: "doubt", syllables: ["doubt"], phonetic: "/daʊt/", meaning: "v./n. 怀疑", example: "I doubt if he will come." }
  ],
  "第8组": [
    { word: "down", syllables: ["down"], phonetic: "/daʊn/", meaning: "adv./prep. 向下", example: "Sit down, please." },
    { word: "download", syllables: ["down","load"], phonetic: "/ˈdaʊnloʊd/", meaning: "v./n. 下载", example: "You can download the app for free." },
    { word: "downtown", syllables: ["down","town"], phonetic: "/ˈdaʊntaʊn/", meaning: "n./adv. 市中心", example: "We went shopping downtown." },
    { word: "draw", syllables: ["draw"], phonetic: "/drɔː/", meaning: "v. 画；拉", example: "She likes to draw pictures." },
    { word: "dream", syllables: ["dream"], phonetic: "/driːm/", meaning: "n./v. 梦想；做梦", example: "I had a strange dream last night." },
    { word: "dress", syllables: ["dress"], phonetic: "/dres/", meaning: "n./v. 连衣裙；穿衣", example: "She wore a red dress." },
    { word: "drink", syllables: ["drink"], phonetic: "/drɪŋk/", meaning: "v./n. 喝；饮料", example: "Would you like something to drink?" },
    { word: "drive", syllables: ["drive"], phonetic: "/draɪv/", meaning: "v. 开车", example: "My father drives to work every day." },
    { word: "drop", syllables: ["drop"], phonetic: "/drɑːp/", meaning: "v./n. 掉落；滴", example: "Be careful not to drop the glass." },
    { word: "drug", syllables: ["drug"], phonetic: "/drʌɡ/", meaning: "n. 药；毒品", example: "The doctor gave him some drugs." },
    { word: "drum", syllables: ["drum"], phonetic: "/drʌm/", meaning: "n. 鼓", example: "He plays the drum in the band." },
    { word: "dry", syllables: ["dry"], phonetic: "/draɪ/", meaning: "adj./v. 干的；弄干", example: "The clothes are dry now." },
    { word: "duck", syllables: ["duck"], phonetic: "/dʌk/", meaning: "n. 鸭子", example: "The duck swims in the pond." },
    { word: "dumpling", syllables: ["dump","ling"], phonetic: "/ˈdʌmplɪŋ/", meaning: "n. 饺子", example: "We eat dumplings on Spring Festival." },
    { word: "during", syllables: ["dur","ing"], phonetic: "/ˈdʊrɪŋ/", meaning: "prep. 在……期间", example: "I read a lot during the holiday." },
    { word: "dust", syllables: ["dust"], phonetic: "/dʌst/", meaning: "n. 灰尘", example: "There is a lot of dust on the table." },
    { word: "duty", syllables: ["du","ty"], phonetic: "/ˈduːti/", meaning: "n. 责任；义务", example: "It is our duty to protect the earth." },
    { word: "each", syllables: ["each"], phonetic: "/iːtʃ/", meaning: "adj./pron. 每个的", example: "Each student has a book." },
    { word: "ear", syllables: ["ear"], phonetic: "/ɪr/", meaning: "n. 耳朵", example: "The rabbit has long ears." },
    { word: "early", syllables: ["ear","ly"], phonetic: "/ˈɜːrli/", meaning: "adj./adv. 早的", example: "I get up early every morning." },
    { word: "earth", syllables: ["earth"], phonetic: "/ɜːrθ/", meaning: "n. 地球；泥土", example: "The earth goes around the sun." },
    { word: "east", syllables: ["east"], phonetic: "/iːst/", meaning: "n./adj. 东方", example: "The sun rises in the east." },
    { word: "eastern", syllables: ["east","ern"], phonetic: "/ˈiːstərn/", meaning: "adj. 东方的", example: "Eastern culture is fascinating." },
    { word: "easy", syllables: ["ea","sy"], phonetic: "/ˈiːzi/", meaning: "adj. 容易的", example: "This question is easy." },
    { word: "eat", syllables: ["eat"], phonetic: "/iːt/", meaning: "v. 吃", example: "Let's eat lunch together." },
    { word: "education", syllables: ["ed","u","ca","tion"], phonetic: "/ˌedʒuˈkeɪʃn/", meaning: "n. 教育", example: "Education is very important." },
    { word: "effort", syllables: ["ef","fort"], phonetic: "/ˈefərt/", meaning: "n. 努力", example: "He made every effort to succeed." },
    { word: "egg", syllables: ["egg"], phonetic: "/eɡ/", meaning: "n. 鸡蛋", example: "I had two eggs for breakfast." },
    { word: "eight", syllables: ["eight"], phonetic: "/eɪt/", meaning: "num. 八", example: "There are eight students in the group." },
    { word: "either", syllables: ["ei","ther"], phonetic: "/ˈiːðər/", meaning: "adj./conj. 任一的；要么", example: "You can have either tea or coffee." },
    { word: "elder", syllables: ["el","der"], phonetic: "/ˈeldər/", meaning: "adj./n. 年长的；长辈", example: "We should respect our elders." },
    { word: "electric", syllables: ["e","lec","tric"], phonetic: "/ɪˈlektrɪk/", meaning: "adj. 电的", example: "We use electric lights at home." },
    { word: "elephant", syllables: ["el","e","phant"], phonetic: "/ˈelɪfənt/", meaning: "n. 大象", example: "The elephant is the largest land animal." },
    { word: "else", syllables: ["else"], phonetic: "/els/", meaning: "adj./adv. 其他的；另外", example: "What else do you want?" },
    { word: "email", syllables: ["e","mail"], phonetic: "/ˈiːmeɪl/", meaning: "n./v. 电子邮件", example: "I will send you an email." },
    { word: "empty", syllables: ["emp","ty"], phonetic: "/ˈempti/", meaning: "adj. 空的", example: "The box is empty." },
    { word: "encourage", syllables: ["en","cour","age"], phonetic: "/ɪnˈkɜːrɪdʒ/", meaning: "v. 鼓励", example: "My teacher encouraged me to try again." },
    { word: "end", syllables: ["end"], phonetic: "/end/", meaning: "n./v. 结束；尽头", example: "The movie ended at ten." },
    { word: "enemy", syllables: ["en","e","my"], phonetic: "/ˈenəmi/", meaning: "n. 敌人", example: "He has no enemies." },
    { word: "energy", syllables: ["en","er","gy"], phonetic: "/ˈenərdʒi/", meaning: "n. 能量；精力", example: "She is full of energy." },
    { word: "engineer", syllables: ["en","gi","neer"], phonetic: "/ˌendʒɪˈnɪr/", meaning: "n. 工程师", example: "My father is an engineer." },
    { word: "England", syllables: ["Eng","land"], phonetic: "/ˈɪŋɡlənd/", meaning: "n. 英格兰", example: "He went to England to study." },
    { word: "English", syllables: ["Eng","lish"], phonetic: "/ˈɪŋɡlɪʃ/", meaning: "n./adj. 英语；英国的", example: "I study English every day." },
    { word: "enjoy", syllables: ["en","joy"], phonetic: "/ɪnˈdʒɔɪ/", meaning: "v. 享受；喜欢", example: "I enjoy reading books." },
    { word: "enough", syllables: ["e","nough"], phonetic: "/ɪˈnʌf/", meaning: "adj./adv. 足够的", example: "Do you have enough money?" },
    { word: "enter", syllables: ["en","ter"], phonetic: "/ˈentər/", meaning: "v. 进入", example: "Please enter the room quietly." },
    { word: "environment", syllables: ["en","vi","ron","ment"], phonetic: "/ɪnˈvaɪrənmənt/", meaning: "n. 环境", example: "We should protect the environment." },
    { word: "eraser", syllables: ["e","ras","er"], phonetic: "/ɪˈreɪsər/", meaning: "n. 橡皮", example: "May I borrow your eraser?" },
    { word: "especially", syllables: ["es","pe","cial","ly"], phonetic: "/ɪˈspeʃəli/", meaning: "adv. 尤其；特别", example: "I like fruit, especially apples." },
    { word: "Europe", syllables: ["Eu","rope"], phonetic: "/ˈjʊrəp/", meaning: "n. 欧洲", example: "She traveled around Europe last year." }
  ],
  "第9组": [
    { word: "European", syllables: ["Eu","ro","pe","an"], phonetic: "/ˌjʊrəˈpiːən/", meaning: "adj./n. 欧洲的；欧洲人", example: "He likes European food." },
    { word: "even", syllables: ["e","ven"], phonetic: "/ˈiːvn/", meaning: "adv. 甚至；即使", example: "She can even speak three languages." },
    { word: "evening", syllables: ["eve","ning"], phonetic: "/ˈiːvnɪŋ/", meaning: "n. 晚上", example: "I watch TV in the evening." },
    { word: "event", syllables: ["e","vent"], phonetic: "/ɪˈvent/", meaning: "n. 事件；活动", example: "The sports event was exciting." },
    { word: "ever", syllables: ["ev","er"], phonetic: "/ˈevər/", meaning: "adv. 曾经；究竟", example: "Have you ever been to Beijing?" },
    { word: "every", syllables: ["ev","ery"], phonetic: "/ˈevri/", meaning: "adj. 每一的", example: "Every student must wear a uniform." },
    { word: "everybody", syllables: ["ev","ery","bo","dy"], phonetic: "/ˈevribɑːdi/", meaning: "pron. 每个人", example: "Everybody likes her." },
    { word: "everyday", syllables: ["ev","ery","day"], phonetic: "/ˈevrideɪ/", meaning: "adj. 每天的", example: "English is an everyday language." },
    { word: "everyone", syllables: ["ev","ery","one"], phonetic: "/ˈevriwʌn/", meaning: "pron. 每个人", example: "Everyone is here today." },
    { word: "everything", syllables: ["ev","ery","thing"], phonetic: "/ˈevriθɪŋ/", meaning: "pron. 一切", example: "Everything is ready." },
    { word: "everywhere", syllables: ["ev","ery","where"], phonetic: "/ˈevriwer/", meaning: "adv. 到处", example: "I looked everywhere for my key." },
    { word: "exam", syllables: ["ex","am"], phonetic: "/ɪɡˈzæm/", meaning: "n. 考试", example: "The final exam is next week." },
    { word: "examine", syllables: ["ex","am","ine"], phonetic: "/ɪɡˈzæmɪn/", meaning: "v. 检查；考试", example: "The doctor examined the patient." },
    { word: "example", syllables: ["ex","am","ple"], phonetic: "/ɪɡˈzæmpl/", meaning: "n. 例子", example: "Can you give me an example?" },
    { word: "excellent", syllables: ["ex","cel","lent"], phonetic: "/ˈeksələnt/", meaning: "adj. 优秀的", example: "She is an excellent student." },
    { word: "except", syllables: ["ex","cept"], phonetic: "/ɪkˈsept/", meaning: "prep. 除了", example: "Everyone came except Tom." },
    { word: "excite", syllables: ["ex","cite"], phonetic: "/ɪkˈsaɪt/", meaning: "v. 使兴奋", example: "The news excited everyone." },
    { word: "excuse", syllables: ["ex","cuse"], phonetic: "/ɪkˈskjuːz/", meaning: "v./n. 原谅；借口", example: "Excuse me, may I ask a question?" },
    { word: "exercise", syllables: ["ex","er","cise"], phonetic: "/ˈeksərsaɪz/", meaning: "n./v. 练习；锻炼", example: "You should exercise every day." },
    { word: "expect", syllables: ["ex","pect"], phonetic: "/ɪkˈspekt/", meaning: "v. 期望；预料", example: "I expect to see you soon." },
    { word: "expensive", syllables: ["ex","pen","sive"], phonetic: "/ɪkˈspensɪv/", meaning: "adj. 昂贵的", example: "This car is very expensive." },
    { word: "experience", syllables: ["ex","pe","ri","ence"], phonetic: "/ɪkˈspɪriəns/", meaning: "n. 经验；经历", example: "It was a wonderful experience." },
    { word: "experiment", syllables: ["ex","per","i","ment"], phonetic: "/ɪkˈsperɪmənt/", meaning: "n. 实验", example: "We did an experiment in science class." },
    { word: "expert", syllables: ["ex","pert"], phonetic: "/ˈekspɜːrt/", meaning: "n. 专家", example: "She is an expert in this field." },
    { word: "explain", syllables: ["ex","plain"], phonetic: "/ɪkˈspleɪn/", meaning: "v. 解释", example: "Can you explain this word to me?" },
    { word: "express", syllables: ["ex","press"], phonetic: "/ɪkˈspres/", meaning: "v./adj. 表达；快速的", example: "Try to express your ideas clearly." },
    { word: "extra", syllables: ["ex","tra"], phonetic: "/ˈekstrə/", meaning: "adj./adv. 额外的", example: "Do you need extra help?" },
    { word: "eye", syllables: ["eye"], phonetic: "/aɪ/", meaning: "n. 眼睛", example: "She has beautiful eyes." },
    { word: "face", syllables: ["face"], phonetic: "/feɪs/", meaning: "n./v. 脸；面对", example: "Look at my face." },
    { word: "fact", syllables: ["fact"], phonetic: "/fækt/", meaning: "n. 事实", example: "It is a fact that the earth is round." },
    { word: "factory", syllables: ["fac","to","ry"], phonetic: "/ˈfæktəri/", meaning: "n. 工厂", example: "He works in a factory." },
    { word: "fail", syllables: ["fail"], phonetic: "/feɪl/", meaning: "v. 失败；不及格", example: "Don't be afraid to fail." },
    { word: "fair", syllables: ["fair"], phonetic: "/fer/", meaning: "adj. 公平的；金发的", example: "That is not fair." },
    { word: "fall", syllables: ["fall"], phonetic: "/fɔːl/", meaning: "v./n. 落下；秋天", example: "Leaves fall in autumn." },
    { word: "family", syllables: ["fam","i","ly"], phonetic: "/ˈfæməli/", meaning: "n. 家庭", example: "I love my family." },
    { word: "famous", syllables: ["fa","mous"], phonetic: "/ˈfeɪməs/", meaning: "adj. 著名的", example: "She is a famous singer." },
    { word: "fan", syllables: ["fan"], phonetic: "/fæn/", meaning: "n. 迷；风扇", example: "I am a big fan of basketball." },
    { word: "fantastic", syllables: ["fan","tas","tic"], phonetic: "/fænˈtæstɪk/", meaning: "adj. 极好的", example: "You did a fantastic job." },
    { word: "far", syllables: ["far"], phonetic: "/fɑːr/", meaning: "adj./adv. 远的", example: "The school is not far from here." },
    { word: "farm", syllables: ["farm"], phonetic: "/fɑːrm/", meaning: "n. 农场", example: "My uncle lives on a farm." },
    { word: "farmer", syllables: ["farm","er"], phonetic: "/ˈfɑːrmər/", meaning: "n. 农民", example: "The farmer grows vegetables." },
    { word: "fast", syllables: ["fast"], phonetic: "/fæst/", meaning: "adj./adv. 快的", example: "He runs very fast." },
    { word: "fat", syllables: ["fat"], phonetic: "/fæt/", meaning: "adj. 胖的", example: "The cat is very fat." },
    { word: "father", syllables: ["fa","ther"], phonetic: "/ˈfɑːðər/", meaning: "n. 父亲", example: "My father is a doctor." },
    { word: "favorite", syllables: ["fa","vor","ite"], phonetic: "/ˈfeɪvərɪt/", meaning: "adj./n. 最喜欢的", example: "What is your favorite color?" },
    { word: "fear", syllables: ["fear"], phonetic: "/fɪr/", meaning: "n./v. 害怕", example: "She has a fear of spiders." },
    { word: "February", syllables: ["Feb","ru","ar","y"], phonetic: "/ˈfebrueri/", meaning: "n. 二月", example: "Spring Festival is usually in February." },
    { word: "feed", syllables: ["feed"], phonetic: "/fiːd/", meaning: "v. 喂养", example: "She feeds the cat every day." },
    { word: "feel", syllables: ["feel"], phonetic: "/fiːl/", meaning: "v. 感觉", example: "I feel happy today." },
    { word: "festival", syllables: ["fes","ti","val"], phonetic: "/ˈfestɪvl/", meaning: "n. 节日", example: "Spring Festival is the most important festival in China." }
  ],
  "第10组": [
    { word: "fetch", syllables: ["fetch"], phonetic: "/fetʃ/", meaning: "v. 取来；接来", example: "Please fetch me a glass of water." },
    { word: "fever", syllables: ["fe","ver"], phonetic: "/ˈfiːvər/", meaning: "n. 发烧", example: "She has a high fever." },
    { word: "few", syllables: ["few"], phonetic: "/fjuː/", meaning: "adj./pron. 很少的", example: "Few students know the answer." },
    { word: "field", syllables: ["field"], phonetic: "/fiːld/", meaning: "n. 田地；领域", example: "The children played in the field." },
    { word: "fifteen", syllables: ["fif","teen"], phonetic: "/ˌfɪfˈtiːn/", meaning: "num. 十五", example: "There are fifteen students in the group." },
    { word: "fifth", syllables: ["fifth"], phonetic: "/fɪfθ/", meaning: "num. 第五", example: "May is the fifth month of the year." },
    { word: "fifty", syllables: ["fif","ty"], phonetic: "/ˈfɪfti/", meaning: "num. 五十", example: "There are fifty states in the USA." },
    { word: "fight", syllables: ["fight"], phonetic: "/faɪt/", meaning: "v./n. 打架；战斗", example: "Don't fight with your brother." },
    { word: "fill", syllables: ["fill"], phonetic: "/fɪl/", meaning: "v. 填满", example: "Please fill in the form." },
    { word: "film", syllables: ["film"], phonetic: "/fɪlm/", meaning: "n. 电影；胶卷", example: "We went to see a film last night." },
    { word: "final", syllables: ["fi","nal"], phonetic: "/ˈfaɪnl/", meaning: "adj. 最后的；最终的", example: "The final exam is next Monday." },
    { word: "find", syllables: ["find"], phonetic: "/faɪnd/", meaning: "v. 找到；发现", example: "I can't find my pen." },
    { word: "fine", syllables: ["fine"], phonetic: "/faɪn/", meaning: "adj. 好的；细的", example: "I am fine, thank you." },
    { word: "finger", syllables: ["fin","ger"], phonetic: "/ˈfɪŋɡər/", meaning: "n. 手指", example: "She pointed her finger at the map." },
    { word: "finish", syllables: ["fin","ish"], phonetic: "/ˈfɪnɪʃ/", meaning: "v. 完成", example: "I finished my homework." },
    { word: "fire", syllables: ["fire"], phonetic: "/faɪər/", meaning: "n. 火", example: "Be careful with fire." },
    { word: "firm", syllables: ["firm"], phonetic: "/fɜːrm/", meaning: "adj./n. 坚定的；公司", example: "She spoke in a firm voice." },
    { word: "first", syllables: ["first"], phonetic: "/fɜːrst/", meaning: "adj./adv. 第一的", example: "She was the first to arrive." },
    { word: "fish", syllables: ["fish"], phonetic: "/fɪʃ/", meaning: "n./v. 鱼；钓鱼", example: "We had fish for dinner." },
    { word: "fit", syllables: ["fit"], phonetic: "/fɪt/", meaning: "v./adj. 适合；健康的", example: "This shirt doesn't fit me." },
    { word: "five", syllables: ["five"], phonetic: "/faɪv/", meaning: "num. 五", example: "There are five people in my family." },
    { word: "fix", syllables: ["fix"], phonetic: "/fɪks/", meaning: "v. 修理；固定", example: "He fixed the broken chair." },
    { word: "flag", syllables: ["flag"], phonetic: "/flæɡ/", meaning: "n. 旗帜", example: "The national flag is red." },
    { word: "flat", syllables: ["flat"], phonetic: "/flæt/", meaning: "adj./n. 平的；公寓", example: "They live in a flat." },
    { word: "flight", syllables: ["flight"], phonetic: "/flaɪt/", meaning: "n. 航班；飞行", example: "Our flight leaves at ten." },
    { word: "floor", syllables: ["floor"], phonetic: "/flɔːr/", meaning: "n. 地板；楼层", example: "Our classroom is on the second floor." },
    { word: "flower", syllables: ["flow","er"], phonetic: "/ˈflaʊər/", meaning: "n. 花", example: "The flowers are beautiful in spring." },
    { word: "fly", syllables: ["fly"], phonetic: "/flaɪ/", meaning: "v./n. 飞；苍蝇", example: "Birds can fly high in the sky." },
    { word: "follow", syllables: ["fol","low"], phonetic: "/ˈfɑːloʊ/", meaning: "v. 跟随；遵循", example: "Please follow me." },
    { word: "food", syllables: ["food"], phonetic: "/fuːd/", meaning: "n. 食物", example: "Chinese food is delicious." },
    { word: "fool", syllables: ["fool"], phonetic: "/fuːl/", meaning: "n./v. 傻瓜；欺骗", example: "Don't be a fool." },
    { word: "foolish", syllables: ["fool","ish"], phonetic: "/ˈfuːlɪʃ/", meaning: "adj. 愚蠢的", example: "It is foolish to waste time." },
    { word: "foot", syllables: ["foot"], phonetic: "/fʊt/", meaning: "n. 脚；英尺", example: "He hurt his foot." },
    { word: "football", syllables: ["foot","ball"], phonetic: "/ˈfʊtbɔːl/", meaning: "n. 足球", example: "He likes playing football." },
    { word: "for", syllables: ["for"], phonetic: "/fɔːr/", meaning: "prep. 为了；因为", example: "This gift is for you." },
    { word: "force", syllables: ["force"], phonetic: "/fɔːrs/", meaning: "v./n. 强迫；力量", example: "Don't force him to go." },
    { word: "foreign", syllables: ["for","eign"], phonetic: "/ˈfɔːrən/", meaning: "adj. 外国的", example: "She speaks three foreign languages." },
    { word: "forest", syllables: ["for","est"], phonetic: "/ˈfɔːrɪst/", meaning: "n. 森林", example: "The forest is full of trees." },
    { word: "forever", syllables: ["for","ev","er"], phonetic: "/fərˈevər/", meaning: "adv. 永远", example: "I will remember you forever." },
    { word: "forget", syllables: ["for","get"], phonetic: "/fərˈɡet/", meaning: "v. 忘记", example: "Don't forget to bring your homework." },
    { word: "fork", syllables: ["fork"], phonetic: "/fɔːrk/", meaning: "n. 叉子", example: "Use a fork to eat the cake." },
    { word: "form", syllables: ["form"], phonetic: "/fɔːrm/", meaning: "n./v. 形式；形成", example: "Please fill in this form." },
    { word: "fort", syllables: ["fort"], phonetic: "/fɔːrt/", meaning: "n. 堡垒", example: "The old fort is now a museum." },
    { word: "fortunate", syllables: ["for","tu","nate"], phonetic: "/ˈfɔːrtʃənət/", meaning: "adj. 幸运的", example: "We are fortunate to have good friends." },
    { word: "forty", syllables: ["for","ty"], phonetic: "/ˈfɔːrti/", meaning: "num. 四十", example: "There are forty students in the class." },
    { word: "forward", syllables: ["for","ward"], phonetic: "/ˈfɔːrwərd/", meaning: "adv./adj. 向前", example: "Please step forward." },
    { word: "found", syllables: ["found"], phonetic: "/faʊnd/", meaning: "v. 建立（find的过去式/建立）", example: "The school was founded in 1950." },
    { word: "four", syllables: ["four"], phonetic: "/fɔːr/", meaning: "num. 四", example: "There are four seasons in a year." },
    { word: "fourteen", syllables: ["four","teen"], phonetic: "/ˌfɔːrˈtiːn/", meaning: "num. 十四", example: "She is fourteen years old." },
    { word: "fourth", syllables: ["fourth"], phonetic: "/fɔːrθ/", meaning: "num. 第四", example: "Thursday is the fourth day of the week." }
  ],
  "第11组": [
    { word: "fox", syllables: ["fox"], phonetic: "/fɑːks/", meaning: "n. 狐狸", example: "The fox is a clever animal." },
    { word: "free", syllables: ["free"], phonetic: "/friː/", meaning: "adj. 自由的；免费的", example: "The ticket is free for children." },
    { word: "freedom", syllables: ["free","dom"], phonetic: "/ˈfriːdəm/", meaning: "n. 自由", example: "Everyone should have freedom." },
    { word: "freeze", syllables: ["freeze"], phonetic: "/friːz/", meaning: "v. 结冰；冻结", example: "Water freezes at zero degrees." },
    { word: "French", syllables: ["French"], phonetic: "/frentʃ/", meaning: "adj./n. 法国的；法语", example: "She is learning French." },
    { word: "fresh", syllables: ["fresh"], phonetic: "/freʃ/", meaning: "adj. 新鲜的", example: "The vegetables are very fresh." },
    { word: "Friday", syllables: ["Fri","day"], phonetic: "/ˈfraɪdeɪ/", meaning: "n. 星期五", example: "We have a party on Friday." },
    { word: "fridge", syllables: ["fridge"], phonetic: "/frɪdʒ/", meaning: "n. 冰箱", example: "Put the milk in the fridge." },
    { word: "friend", syllables: ["friend"], phonetic: "/frend/", meaning: "n. 朋友", example: "She is my best friend." },
    { word: "friendly", syllables: ["friend","ly"], phonetic: "/ˈfrendli/", meaning: "adj. 友好的", example: "The people here are very friendly." },
    { word: "friendship", syllables: ["friend","ship"], phonetic: "/ˈfrendʃɪp/", meaning: "n. 友谊", example: "Our friendship will last forever." },
    { word: "frog", syllables: ["frog"], phonetic: "/frɔːɡ/", meaning: "n. 青蛙", example: "The frog jumped into the water." },
    { word: "from", syllables: ["from"], phonetic: "/frɑːm/", meaning: "prep. 从；来自", example: "I am from China." },
    { word: "front", syllables: ["front"], phonetic: "/frʌnt/", meaning: "n./adj. 前面", example: "Please sit in the front row." },
    { word: "frozen", syllables: ["fro","zen"], phonetic: "/ˈfroʊzn/", meaning: "adj. 冷冻的；冻结的", example: "We bought some frozen food." },
    { word: "fruit", syllables: ["fruit"], phonetic: "/fruːt/", meaning: "n. 水果", example: "Eating fruit is good for health." },
    { word: "fuel", syllables: ["fu","el"], phonetic: "/ˈfjuːəl/", meaning: "n. 燃料", example: "The car needs more fuel." },
    { word: "full", syllables: ["full"], phonetic: "/fʊl/", meaning: "adj. 满的；饱的", example: "The glass is full of water." },
    { word: "fun", syllables: ["fun"], phonetic: "/fʌn/", meaning: "n./adj. 乐趣；有趣的", example: "We had a lot of fun." },
    { word: "funny", syllables: ["fun","ny"], phonetic: "/ˈfʌni/", meaning: "adj. 有趣的；滑稽的", example: "The story is very funny." },
    { word: "furniture", syllables: ["fur","ni","ture"], phonetic: "/ˈfɜːrnɪtʃər/", meaning: "n. 家具", example: "We bought new furniture." },
    { word: "future", syllables: ["fu","ture"], phonetic: "/ˈfjuːtʃər/", meaning: "n./adj. 未来", example: "What do you want to be in the future?" }
  ]
};